# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# The toolchain the rust-code-model skill pins for ra_ap_* 0.0.352 (its PROVENANCE.json).
[toolchain]
channel = "nightly-2026-09-13"
profile = "minimal"
