# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Rust-owned boundary documents as frozen msgspec types (ADR-0116 Outcome 7).

Generated from the documents' JSON Schemas in `docs/generated/schema/`; the Rust serde
types are the authority. Every enumeration is a registry vocabulary.
"""

from __future__ import annotations

from typing import Annotated, Literal

import msgspec

from pse.contracts import enums

FiniteBound = float

Fraction = Annotated[float, msgspec.Meta(le=1.0, gt=0.0)]

OptionValue = bool | int | float | str

PositiveCount = Annotated[int, msgspec.Meta(ge=1)]

Tolerance = Annotated[float, msgspec.Meta(gt=0.0)]


class AuthoredNumericalRequirementsRow(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """A row or nested value projected from the registry declaration."""

    #: absolute_tolerance
    absolute_tolerance: float | None = None
    #: The case declaration the requirement belongs to: the solved root when it is a case or a test, otherwise absent.
    case_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")] | None = None
    #: coordinates
    coordinates: enums.NumericalCoordinates
    #: The fit whose parameter requirement this is; absent otherwise.
    fit_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")] | None = None
    #: The instance whose preparation declared the requirement: the solved root instance (a fit experiment's own instance), or the implicit block whose trial hints declared it. Absent for a fit's parameter requirements and a generated rate system's.
    instance_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")] | None = None
    #: The specialized definition the requirement belongs to: the root declaration of the model it is declared for. A modeling preparation's requirements name its root, an implicit block's trial hints their enclosing model's; a fit's parameter requirements name the one definition all its experiments specialize, and none when they specialize different ones.
    model_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")] | None = None
    #: nominal
    nominal: float | None = None
    #: priority
    priority: int
    #: provenance
    provenance: str
    #: relative_tolerance
    relative_tolerance: float | None = None
    #: required
    required: bool
    #: requirement_id
    requirement_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")]
    #: scaling_factor
    scaling_factor: float | None = None
    #: target_id
    target_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")]
    #: target_kind
    target_kind: enums.NumericalTarget
    #: unit_id
    unit_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")] | None = None


class ClarabelSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="backend", tag="clarabel"):
    """The pse-owned Clarabel settings: mode and every admitted native control."""

    #: Compact the decomposed problem.
    chordal_decomposition_compact: bool = True
    #: Complete the dual of decomposed PSD cones.
    chordal_decomposition_complete_dual: bool = True
    #: Chordal decomposition of PSD cones; `ReusableData` disables it. Without the SDP
    #: profile only the chordal defaults are admitted.
    chordal_decomposition_enable: bool = True
    #: Clique merging.
    chordal_decomposition_merge_method: enums.ClarabelMergeMethod = enums.ClarabelMergeMethod.CLIQUE_GRAPH
    #: Dynamic regularization shift.
    dynamic_regularization_delta: float = 2e-7
    #: Dynamic KKT regularization.
    dynamic_regularization_enable: bool = True
    #: Dynamic regularization threshold.
    dynamic_regularization_eps: float = 1e-13
    #: Equilibration iterations.
    equilibrate_max_iter: Annotated[int, msgspec.Meta(ge=0)] = 10
    #: Maximum equilibration scaling.
    equilibrate_max_scaling: float = 10000.0
    #: Minimum equilibration scaling.
    equilibrate_min_scaling: float = 0.0001
    #: Drop explicit input zeros; `ReusableData` disables it.
    input_sparse_dropzeros: bool = False
    #: Refinement absolute tolerance.
    iterative_refinement_abstol: float = 1e-12
    #: KKT iterative refinement.
    iterative_refinement_enable: bool = True
    #: Refinement iterations.
    iterative_refinement_max_iter: Annotated[int, msgspec.Meta(ge=0)] = 10
    #: Refinement relative tolerance.
    iterative_refinement_reltol: float = 1e-13
    #: Refinement stall ratio.
    iterative_refinement_stop_ratio: float = 5.0
    #: Line-search backtracking factor.
    linesearch_backtrack_step: float = 0.8
    #: Maximum interior step fraction.
    max_step_fraction: float = 0.99
    #: Minimum step length before switching to symmetric scaling.
    min_switch_step_length: float = 0.1
    #: Minimum step length before termination.
    min_terminate_step_length: float = 0.0001
    #: Preprocessing or data-update mode.
    mode: enums.ClarabelMode = enums.ClarabelMode.SINGLE_SOLVE
    #: Native presolve; `ReusableData` disables it.
    presolve_enable: bool = True
    #: Reduced absolute infeasibility tolerance.
    reduced_tol_infeas_abs: float = 5e-12
    #: Reduced relative infeasibility tolerance.
    reduced_tol_infeas_rel: float = 0.00005
    #: Reduced KKT ratio tolerance.
    reduced_tol_ktratio: float = 0.0001
    #: Constant static regularization.
    static_regularization_constant: float = 1e-8
    #: Static KKT regularization.
    static_regularization_enable: bool = True
    #: Proportional static regularization.
    static_regularization_proportional: float = 4.930380657631324e-32
    #: Absolute infeasibility tolerance.
    tol_infeas_abs: float = 1e-8
    #: Relative infeasibility tolerance.
    tol_infeas_rel: float = 1e-8
    #: KKT ratio tolerance.
    tol_ktratio: float = 1e-6


class DiffsolSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Typed Diffsol-only method controls, a versioned boundary document (ADR-0116 Outcome 6):
    the version is required, and absent fields take these defaults.
    """

    #: Document version.
    version: Literal[1] = 1
    #: Newton linear solver of the implicit schemes.
    linear: enums.DiffsolLinear = enums.DiffsolLinear.FAER_LU
    #: Time-stepping scheme.
    method: enums.DiffsolMethod = enums.DiffsolMethod.BDF


class FeralSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """The `FeralSettings` document type."""

    cascade_break: bool | None = None
    fma: bool = False
    increase_quality: bool = True
    inertia_pivot_floor: float | None = None
    min_par_flops: Annotated[int, msgspec.Meta(ge=0)] | None = None
    ordering: enums.FeralOrdering = enums.FeralOrdering.AUTO
    parallel: bool | None = None
    pivtol: float = 1e-8
    refine: bool = True
    refine_max_steps: Annotated[int, msgspec.Meta(ge=0)] = 10
    refine_target: float = 0.0
    scaling: enums.FeralScaling = enums.FeralScaling.AUTO
    singular_pivot_floor: float = 1e-20
    static_pivoting: bool | None = None


class HighsDiagnostics(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Requested native diagnostic work, bounded by the original attempt's deadline."""

    #: Rows of the basis inverse `B⁻¹` at these basis positions, with the basic variables,
    #: for an optimal continuous LP with a valid basis.
    basis_inverse: tuple[Annotated[int, msgspec.Meta(ge=0)], ...] | None = None
    #: The MIP solver's cut pool after root cut generation (callback kind 7).
    cut_pool: bool = False
    #: Duals of the MIP's LP with its discrete columns fixed at the solution
    #: (`Highs_getFixedLp`), conditional on that commitment.
    fixed_lp: bool = False
    #: Native irreducible infeasible subsystem; MIP scope is its LP relaxation.
    iis: bool = False
    #: Native presolve of a copied model: the presolved LP and, for a continuous LP, the
    #: postsolved solution of that LP.
    presolve: bool = False
    #: Basis sensitivity ranges for an optimal continuous LP with a valid basis.
    ranging: bool = False
    #: Native primal/dual rays when available for the continuous model.
    rays: bool = False
    #: Separate feasibility-relaxation solve on a copied LP/MIP. Negative penalties
    #: forbid violation, as in the native API; no penalty is inferred from units.
    relaxation: HighsPenalties | None = None


class HighsPenalties(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Complete physical penalty declarations for native feasibility relaxation."""

    #: Global lower-bound, upper-bound and constraint penalties.
    global_: tuple[FiniteBound, FiniteBound, FiniteBound] = msgspec.field(name="global")
    #: Optional per-variable lower-bound penalties.
    lower: tuple[float, ...] | None = None
    #: Optional per-row penalties.
    rows: tuple[float, ...] | None = None
    #: Optional per-variable upper-bound penalties.
    upper: tuple[float, ...] | None = None


class HighsSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="backend", tag="highs"):
    """HiGHS method, opt-in diagnostics and partial MIP start."""

    #: Opt-in native work, separate from the original candidate.
    diagnostics: HighsDiagnostics = msgspec.field(default_factory=lambda: msgspec.convert({"basis_inverse": None, "cut_pool": False, "fixed_lp": False, "iis": False, "presolve": False, "ranging": False, "rays": False, "relaxation": None}, type=HighsDiagnostics))
    #: Eligible LP algorithm; mixed models retain native class routing.
    method: enums.HighsMethod = enums.HighsMethod.CHOOSE
    #: MIP node budget, separate from the iteration budget (F10). `None` leaves the native
    #: default (no node limit), so the time limit alone bounds the search.
    nodes: Annotated[int, msgspec.Meta(ge=0)] | None = None
    #: Partial source-attributed MIP start, with unspecified coordinates absent.
    sparse_start: dict[Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")], float] | None = None


class IdasLinearKlu(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="klu"):
    """SuiteSparse KLU over the compiled analytic Jacobian."""


class IdasLinearSpfgmr(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="spfgmr"):
    """Matrix-free flexible GMRES over analytic Jacobian-vector products."""

    #: Maximum Krylov subspace dimension.
    dimension: PositiveCount
    #: Left preconditioner built from the compiled Jacobian; none when absent.
    preconditioner: enums.Preconditioner = enums.Preconditioner.NONE


class IdasLinearSpgmr(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="spgmr"):
    """Matrix-free GMRES over analytic Jacobian-vector products."""

    #: Maximum Krylov subspace dimension.
    dimension: PositiveCount
    #: Left preconditioner built from the compiled Jacobian; none when absent.
    preconditioner: enums.Preconditioner = enums.Preconditioner.NONE


class IdasSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Typed IDAS-only method controls (ADR-0110 item 1), a versioned boundary document
    (ADR-0116 Outcome 6): the version is required, and absent fields take these defaults.
    """

    #: Document version.
    version: Literal[1] = 1
    #: Empty, or one declared sign per state in state order.
    constraints: tuple[enums.StateSign, ...] = msgspec.field(default_factory=tuple)
    #: Consistent initialization at the start of the horizon; scheduled changes and resets
    #: always keep their differential states.
    initialization: enums.IdasInitialization = enums.IdasInitialization.ALGEBRAIC_AND_RATES
    #: Newton linear solver.
    linear: IdasLinear = msgspec.field(default_factory=lambda: msgspec.convert({"kind": "klu"}, type=IdasLinear))
    #: Forward-sensitivity corrector.
    sensitivity: enums.SensitivityCorrector = enums.SensitivityCorrector.SIMULTANEOUS


class IpoptLinearMumps(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="mumps"):
    """Sequential MUMPS 5.9 (`linear_solver = mumps`)."""

    #: Fill-reducing ordering (`mumps_pivot_order`, MUMPS ICNTL(7)).
    ordering: enums.MumpsOrdering


class IpoptLinearPardisomkl(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="pardisomkl"):
    """oneMKL Pardiso on MKL threads (`linear_solver = pardisomkl`), under the pinned CBWR
    branch.
    """

    #: Symmetric weighted matching (`pardisomkl_matching_strategy`).
    matching: enums.PardisoMatching
    #: Fill-reducing ordering (`pardisomkl_order`).
    ordering: enums.PardisoOrdering


class IpoptLinearSpral(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="spral"):
    """SPRAL SSIDS on OpenMP threads (`linear_solver = spral`)."""

    #: Elimination ordering (`spral_order`).
    ordering: enums.SpralOrdering
    #: A posteriori pivoting strategy (`spral_pivot_method`).
    pivot: enums.SpralPivot
    #: Matrix scaling (`spral_scaling`).
    scaling: enums.SpralScaling


class IpoptSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="backend", tag="ipopt"):
    """Ipopt linear solver with its parameters, barrier strategy and initial-point push."""

    #: Minimum relative distance of a cold initial point from its bounds (`bound_frac`);
    #: admission refuses more than one half, Ipopt's registered range.
    bound_frac: Fraction = 0.01
    #: Minimum absolute distance of a cold initial point from its bounds (`bound_push`).
    bound_push: Tolerance = 0.01
    #: Symmetric-indefinite factorization of the KKT systems.
    linear: IpoptLinear = msgspec.field(default_factory=lambda: msgspec.convert({"kind": "mumps", "ordering": "metis"}, type=IpoptLinear))
    #: Barrier-parameter update strategy (`mu_strategy`).
    mu_strategy: enums.MuStrategy = enums.MuStrategy.MONOTONE
    #: Restart of a submitted primal-dual seed: barrier and pushes (L-N3).
    restart: WarmRestart = msgspec.field(default_factory=lambda: msgspec.convert({"barrier": {"kind": "seed"}, "bound_frac": 1e-9, "bound_push": 1e-9, "mult_bound_push": 1e-9, "slack_bound_frac": 1e-9, "slack_bound_push": 1e-9}, type=WarmRestart))


class JobPayload(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Version 3 of a durable job's payload: the one task a job runs. Unknown fields, tasks
    and versions are refused.
    """

    #: Document version.
    version: Literal[3] = 3
    #: The task.
    task: JobTask


class JobStartFresh(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="fresh"):
    """From the case's authored starts."""


class JobStartResumeFromParent(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="resume_from_parent"):
    """From the latest incumbent in the parent attempt chain (Plan 22 G8)."""


class JobStartStoredSolution(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="stored_solution"):
    """From one stored solution (Plan 22 G8)."""

    #: The stored solution.
    solution: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")]


class JobTaskModeling(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="modeling"):
    """Solve one authored case once, possibly as one point of a study."""

    #: The authored case to solve.
    case: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")]
    #: The source bundles of the modeling package closure, in load order.
    modeling: tuple[Annotated[str, msgspec.Meta(pattern="^blake3:[0-9a-fA-F]{64}$")], ...]
    #: The source bundle of the physical package.
    physical: Annotated[str, msgspec.Meta(pattern="^blake3:[0-9a-fA-F]{64}$")]
    #: Its analysis route.
    route: enums.ModelingAnalysisRoute
    #: The solve settings.
    settings: SolveSettings
    #: How the solve starts. A study point with a predecessor starts from the
    #: predecessor's stored solution instead.
    start: JobStart = msgspec.field(default_factory=lambda: msgspec.convert({"kind": "fresh"}, type=JobStart))
    #: The study point this job runs (Plan 22 O7).
    study: StudyPointBinding | None = None


class JobTaskStudyFinalization(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="study_finalization"):
    """Publish a concluded study: its summary and every completed point's result members,
    as the study's one publication (Plan 22 O7).
    """

    #: The study to publish.
    study_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")]


class KinsolEtaChoice1(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="choice1"):
    """Eisenstat-Walker choice 1, KINSOL's default."""


class KinsolEtaChoice2(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="choice2"):
    """Eisenstat-Walker choice 2 (`KINSetEtaParams`)."""

    #: Power in (1, 2].
    alpha: float
    #: Safeguard factor in (0, 1].
    gamma: Fraction


class KinsolEtaConstant(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="constant"):
    """A constant forcing term in (0, 1] (`KINSetEtaConstValue`)."""

    #: The forcing term.
    value: Fraction


class KinsolLinearDense(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="dense"):
    """Serial dense factorization for explicitly small systems."""

    #: Maximum admitted dimension.
    limit: PositiveCount


class KinsolLinearKlu(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="klu"):
    """Vendored SuiteSparse KLU with analytic CSC Jacobian."""


class KinsolLinearSpbcgs(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="spbcgs"):
    """Matrix-free native BiCGStab."""

    #: Maximum Krylov subspace dimension.
    dimension: PositiveCount


class KinsolLinearSpfgmr(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="spfgmr"):
    """Matrix-free native flexible GMRES."""

    #: Maximum Krylov subspace dimension.
    dimension: PositiveCount


class KinsolLinearSpgmr(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="spgmr"):
    """Matrix-free native GMRES."""

    #: Maximum Krylov subspace dimension.
    dimension: PositiveCount


class KinsolLinearSptfqmr(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="sptfqmr"):
    """Matrix-free native transpose-free QMR."""

    #: Maximum Krylov subspace dimension.
    dimension: PositiveCount


class KinsolSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="backend", tag="kinsol"):
    """KINSOL method controls; scales and the step tolerance derive from policy."""

    #: Native Anderson history; zero disables acceleration.
    anderson: Annotated[int, msgspec.Meta(ge=0)] = 0
    #: Iterations before Anderson acceleration starts (`KINSetDelayAA`); Anderson only.
    anderson_delay: Annotated[int, msgspec.Meta(ge=0)] = 0
    #: Damping in (0,1].
    damping: Fraction = 1.0
    #: Inexact-Newton forcing term; Krylov routes only.
    eta: KinsolEta = msgspec.field(default_factory=lambda: msgspec.convert({"kind": "choice1"}, type=KinsolEta))
    #: Native linear solver for equation profiles.
    linear: KinsolLinear = msgspec.field(default_factory=lambda: msgspec.convert({"kind": "klu"}, type=KinsolLinear))
    #: Maximum scaled Newton step (`KINSetMaxNewtonStep`), at least one scaled unit
    #: because KINSOL raises a smaller cap to one; `None` keeps KINSOL's
    #: `1000 * ||D_u u_0||`.
    max_newton_step: float | None = None
    #: Anderson QR orthogonalization; Anderson acceleration only.
    orthogonalization: enums.KinsolOrthogonalization = enums.KinsolOrthogonalization.MODIFIED_GRAM_SCHMIDT
    #: Krylov preconditioner from the analytic Jacobian (`KINSetPreconditioner`);
    #: KINSOL preconditions on the right.
    preconditioner: enums.Preconditioner = enums.Preconditioner.NONE
    #: Maximum nonlinear iterations between linear setups.
    setup_interval: Annotated[int, msgspec.Meta(ge=0)] = 10
    #: Nonlinear strategy.
    strategy: enums.KinsolStrategy = enums.KinsolStrategy.LINE_SEARCH


class KktTolerances(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Distinct normalized optimality requirements; no scalar means every stopping test."""

    #: Normalized complementarity budget.
    complementarity: float
    #: Normalized stationarity budget.
    stationarity: float


class NumericalPolicy(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Shared semantic controls resolved before invoking any native adapter."""

    #: Optional separately qualified acceptable-termination budgets.
    acceptable: KktTolerances | None = None
    #: Physical acceptance, separate from native termination.
    closure: enums.ClosurePolicy = enums.ClosurePolicy.REQUIRE_CLOSED
    #: Absolute continuous optimality gap in normalized objective coordinates.
    gap_absolute: float = 1e-8
    #: Dimensionless relative continuous optimality gap.
    gap_relative: float = 1e-8
    #: Integer-lattice violation budget in original variable coordinates.
    integrality: float = 1e-8
    #: Independent KKT budgets.
    kkt: KktTolerances = msgspec.field(default_factory=lambda: msgspec.convert({"complementarity": 1e-8, "stationarity": 1e-8}, type=KktTolerances))
    #: Absolute gap in normalized objective coordinates.
    mip_absolute_gap: float = 1e-6
    #: Dimensionless relative MIP gap.
    mip_relative_gap: float = 0.0001
    #: Permit native algorithmic scaling after model normalization.
    native_scaling: bool = True
    #: ID-keyed analysis overrides, using the same declaration as model/case sources.
    requirements: tuple[AuthoredNumericalRequirementsRow, ...] = msgspec.field(default_factory=tuple)
    #: Refuse canonical-unit fallback where no authored or quantity nominal is known.
    strict_nominals: bool = False


class PointOverlay(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Values a study point replaces in its authored case, composed over the original for the
    point only.
    """

    #: Declared parameters by identity.
    parameters: dict[Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")], float] = msgspec.field(default_factory=dict)
    #: Case values by path.
    values: dict[str, float] = msgspec.field(default_factory=dict)


class PounceSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="backend", tag="pounce"):
    """POUNCE method and complete native FERAL configuration."""

    #: Native linear settings.
    linear: FeralSettings = msgspec.field(default_factory=lambda: msgspec.convert({"cascade_break": None, "fma": False, "increase_quality": True, "inertia_pivot_floor": None, "min_par_flops": None, "ordering": "auto", "parallel": None, "pivtol": 1e-8, "refine": True, "refine_max_steps": 10, "refine_target": 0.0, "scaling": "auto", "singular_pivot_floor": 1e-20, "static_pivoting": None}, type=FeralSettings))
    #: NLP method.
    method: enums.PounceMethod = enums.PounceMethod.INTERIOR_POINT
    #: Interior-point restart of a submitted primal-dual seed (L-N3).
    restart: WarmRestart = msgspec.field(default_factory=lambda: msgspec.convert({"barrier": {"kind": "seed"}, "bound_frac": 1e-9, "bound_push": 1e-9, "mult_bound_push": 1e-9, "slack_bound_frac": 1e-9, "slack_bound_push": 1e-9}, type=WarmRestart))


class RestartBarrierSeed(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="seed"):
    """The final barrier value the producing interior-point solve recorded with the seed. A
    seed without one (an authored seed) leaves the native default in force, and the
    receipt says so.
    """


class RestartBarrierValue(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="value"):
    """A stated positive value."""

    #: The initial barrier parameter.
    value: Tolerance


class ScipSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="backend", tag="scip"):
    """SCIP's nested Ipopt linear solver, seed and node budget."""

    #: Exact rational MILP (`SCIPenableExactSolving`); admitted for linear programs
    #: without native forms, and never with reoptimization or concurrency.
    exact: bool = False
    #: After a proof of infeasibility, compute an irreducible infeasible subsystem of the
    #: true exported program (`SCIPgenerateIIS`).
    iis: bool = False
    #: Linear solver of the nested Ipopt (`nlpi/ipopt/linear_solver`): the image's one
    #: Ipopt, so the same type the Ipopt adapter's settings select.
    nlp_linear_solver: enums.IpoptLinearSolver = enums.IpoptLinearSolver.MUMPS
    #: Total branch-and-bound node budget including restarts (`limits/totalnodes`);
    #: absent leaves the deadline as the only budget.
    nodes: Annotated[int, msgspec.Meta(ge=0)] | None = None
    #: Number of ranked stored solutions reported beside the candidate (0: none).
    pool: Annotated[int, msgspec.Meta(ge=0, le=65535)] = 0
    #: Retain the native search tree across a finite MIP sequence whose constraint system
    #: is unchanged and whose linear objective changes (`SCIPenableReoptimization`).
    reoptimize: bool = False
    #: Random seed shift (`randomization/randomseedshift`), recorded with the result.
    seed: Annotated[int, msgspec.Meta(ge=0, le=65535)] = 0


class SolveControls(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Finite shared attempt controls chosen by the caller; solver-specific settings remain
    native typed values. Accuracy is not among them: it is resolved from the numerical
    policy ([`ResolvedAccuracy`]). A document states the time limit in seconds; absent
    fields take these defaults and unknown fields are refused.
    """

    #: Hessian representation for compatible NLP methods.
    hessian: enums.HessianMode = enums.HessianMode.EXACT
    #: Bounded retained progress and failure events.
    history: Annotated[int, msgspec.Meta(ge=0)] = 256
    #: Positive native iteration limit.
    iterations: Annotated[int, msgspec.Meta(ge=0)] = 3000
    #: Additional native options, admitted by the selected adapter.
    options: dict[str, OptionValue] = msgspec.field(default_factory=dict)
    #: Native allocation/data reuse policy.
    reuse: enums.ReusePolicy = enums.ReusePolicy.FRESH
    #: Numerical start policy, independent of native allocation reuse.
    start: enums.NativeStartPolicy = enums.NativeStartPolicy.NO_PRIOR_START
    #: Explicit admitted native thread count.
    threads: Annotated[int, msgspec.Meta(ge=0)] = 1
    #: Positive wall-clock allowance, including callbacks, in seconds.
    time_limit: Tolerance = 300.0


class SolveSettings(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """The settings of one solve. The version is required; every other field takes the
    default of [`SolverProfile::default`] when absent.
    """

    #: Document version.
    version: Literal[1] = 1
    #: An explicitly selected eligible backend; absent is deterministic routing.
    backend: enums.NativeBackend | None = None
    #: Shared finite attempt controls.
    controls: SolveControls = msgspec.field(default_factory=lambda: msgspec.convert({"hessian": "exact", "history": 256, "iterations": 3000, "options": {}, "reuse": "fresh", "start": "no_prior_start", "threads": 1, "time_limit": 300.0}, type=SolveControls))
    #: Absolute eigenvalue budget of a numerical convexity assessment; with the relative
    #: budget, it permits numerical assessment, and absent both, only exact certification.
    convexity_absolute: float | None = None
    #: Relative eigenvalue budget of a numerical convexity assessment.
    convexity_relative: float | None = None
    #: Mathematical purpose.
    intent: enums.NativeSolveIntent = enums.NativeSolveIntent.OPTIMIZE
    #: ID-keyed numerical requirements and acceptance budgets.
    numerics: NumericalPolicy = msgspec.field(default_factory=lambda: msgspec.convert({"acceptable": None, "closure": "require_closed", "gap_absolute": 1e-8, "gap_relative": 1e-8, "integrality": 1e-8, "kkt": {"complementarity": 1e-8, "stationarity": 1e-8}, "mip_absolute_gap": 1e-6, "mip_relative_gap": 0.0001, "native_scaling": True, "requirements": [], "strict_nominals": False}, type=NumericalPolicy))
    #: Library presolve policy.
    presolve: enums.PresolvePolicyKind = enums.PresolvePolicyKind.AUTO
    #: Native presolve options; an explicit policy only.
    presolve_options: dict[str, OptionValue] = msgspec.field(default_factory=dict)
    #: Passes that may not silently become unavailable; an explicit policy only.
    required_passes: tuple[enums.PresolvePass, ...] = msgspec.field(default_factory=tuple)
    #: Typed settings of one backend; absent is the routed backend's native defaults.
    settings: BackendSettings | None = None


class SourceManifest(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Version 1 of a source bundle's manifest: the path of every document, in order."""

    #: Document version.
    version: Literal[1] = 1
    #: The document paths, relative to the package root.
    paths: tuple[str, ...]


class StudyDefinition(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Version 1 of a study's definition: the store's `definition` document and the content of
    the study's request identity.
    """

    #: Document version.
    version: Literal[1] = 1
    #: The source bundles of the modeling package closure, in load order.
    modeling: tuple[Annotated[str, msgspec.Meta(pattern="^blake3:[0-9a-fA-F]{64}$")], ...]
    #: The source bundle of the physical package.
    physical: Annotated[str, msgspec.Meta(pattern="^blake3:[0-9a-fA-F]{64}$")]
    #: The points, in index order.
    points: tuple[StudyPointDefinition, ...]
    #: The analysis route of every point.
    route: enums.ModelingAnalysisRoute
    #: The solve settings of every point.
    settings: SolveSettings


class StudyPointBinding(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """The binding of one study point (Plan 22 O7): which point of which study the job runs,
    its value bindings and the earlier point that seeds it.
    """

    #: The hash of the point's value bindings: its case, route and overlay.
    binding_hash: Annotated[str, msgspec.Meta(pattern="^blake3:[0-9a-fA-F]{64}$")]
    #: The values the point replaces in its case.
    overlay: PointOverlay = msgspec.field(default_factory=lambda: msgspec.convert({"parameters": {}, "values": {}}, type=PointOverlay))
    #: The point's index in the study.
    point_index: Annotated[int, msgspec.Meta(ge=0)]
    #: The earlier point whose stored solution this one starts from; the point runs only
    #: once that point completed.
    predecessor: Annotated[int, msgspec.Meta(ge=0)] | None = None
    #: The study.
    study_id: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")]


class StudyPointDefinition(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """One point of a study's definition."""

    #: The hash of the point's value bindings.
    binding_hash: Annotated[str, msgspec.Meta(pattern="^blake3:[0-9a-fA-F]{64}$")]
    #: The authored case.
    case: Annotated[str, msgspec.Meta(pattern="^[0-9a-fA-F]{32}$")]
    #: The values the point replaces in its case.
    overlay: PointOverlay = msgspec.field(default_factory=lambda: msgspec.convert({"parameters": {}, "values": {}}, type=PointOverlay))
    #: The earlier point that seeds it.
    predecessor: Annotated[int, msgspec.Meta(ge=0)] | None = None


class TerminationCauseAssessment(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="assessment"):
    """The joined run was assessed."""

    #: The use of each requested candidate, in request order.
    candidate_use: tuple[enums.CandidateUse, ...]
    #: Every requested candidate is a result.
    usable: bool


class TerminationCauseError(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="error"):
    """The run failed with an error, or cancellation stopped it."""

    #: The error's message.
    message: str
    #: The violated named contract the error reports.
    rule: str


class TerminationCauseInfrastructure(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field="kind", tag="infrastructure"):
    """Infrastructure failed the try; it is retried under the job's policy."""

    #: The error's message.
    message: str


class TerminationDetail(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Version 1 of the typed detail of an attempt's termination, stored as the attempt's
    termination-detail document (ADR-0116 Outcome 6): the typed values that explain why the
    try ended as it did.
    """

    #: Document version.
    version: Literal[1] = 1
    #: Why the try ended.
    cause: TerminationCause


class WarmRestart(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """How an interior-point method re-centres a complete primal-dual seed (L-N3). With the
    cold-start defaults a seeded restart is pushed back towards the analytic centre and loses
    most of its benefit, so a restart states its barrier and its pushes. Absent fields take
    these defaults across the Python boundary (ADR-0113).
    """

    #: Initial barrier parameter of the restart (`mu_init`).
    barrier: RestartBarrier = msgspec.field(default_factory=lambda: msgspec.convert({"kind": "seed"}, type=RestartBarrier))
    #: Relative push of the primal seed from its bounds (`warm_start_bound_frac`); at most
    #: one half.
    bound_frac: Fraction = 1e-9
    #: Absolute push of the primal seed from its bounds (`warm_start_bound_push`).
    bound_push: Tolerance = 1e-9
    #: Push of the bound multipliers from zero (`warm_start_mult_bound_push`).
    mult_bound_push: Tolerance = 1e-9
    #: Relative push of the slack seed from its bounds (`warm_start_slack_bound_frac`); at
    #: most one half.
    slack_bound_frac: Fraction = 1e-9
    #: Absolute push of the slack seed from its bounds (`warm_start_slack_bound_push`).
    slack_bound_push: Tolerance = 1e-9


BackendSettings = IpoptSettings | PounceSettings | KinsolSettings | HighsSettings | ClarabelSettings | ScipSettings

IdasLinear = IdasLinearKlu | IdasLinearSpgmr | IdasLinearSpfgmr

IpoptLinear = IpoptLinearMumps | IpoptLinearSpral | IpoptLinearPardisomkl

JobStart = JobStartFresh | JobStartResumeFromParent | JobStartStoredSolution

JobTask = JobTaskModeling | JobTaskStudyFinalization

KinsolEta = KinsolEtaChoice1 | KinsolEtaChoice2 | KinsolEtaConstant

KinsolLinear = KinsolLinearKlu | KinsolLinearDense | KinsolLinearSpgmr | KinsolLinearSpfgmr | KinsolLinearSpbcgs | KinsolLinearSptfqmr

RestartBarrier = RestartBarrierSeed | RestartBarrierValue

TerminationCause = TerminationCauseError | TerminationCauseInfrastructure | TerminationCauseAssessment

__all__ = [
    "AuthoredNumericalRequirementsRow",
    "BackendSettings",
    "ClarabelSettings",
    "DiffsolSettings",
    "FeralSettings",
    "FiniteBound",
    "Fraction",
    "HighsDiagnostics",
    "HighsPenalties",
    "HighsSettings",
    "IdasLinear",
    "IdasLinearKlu",
    "IdasLinearSpfgmr",
    "IdasLinearSpgmr",
    "IdasSettings",
    "IpoptLinear",
    "IpoptLinearMumps",
    "IpoptLinearPardisomkl",
    "IpoptLinearSpral",
    "IpoptSettings",
    "JobPayload",
    "JobStart",
    "JobStartFresh",
    "JobStartResumeFromParent",
    "JobStartStoredSolution",
    "JobTask",
    "JobTaskModeling",
    "JobTaskStudyFinalization",
    "KinsolEta",
    "KinsolEtaChoice1",
    "KinsolEtaChoice2",
    "KinsolEtaConstant",
    "KinsolLinear",
    "KinsolLinearDense",
    "KinsolLinearKlu",
    "KinsolLinearSpbcgs",
    "KinsolLinearSpfgmr",
    "KinsolLinearSpgmr",
    "KinsolLinearSptfqmr",
    "KinsolSettings",
    "KktTolerances",
    "NumericalPolicy",
    "OptionValue",
    "PointOverlay",
    "PositiveCount",
    "PounceSettings",
    "RestartBarrier",
    "RestartBarrierSeed",
    "RestartBarrierValue",
    "ScipSettings",
    "SolveControls",
    "SolveSettings",
    "SourceManifest",
    "StudyDefinition",
    "StudyPointBinding",
    "StudyPointDefinition",
    "TerminationCause",
    "TerminationCauseAssessment",
    "TerminationCauseError",
    "TerminationCauseInfrastructure",
    "TerminationDetail",
    "Tolerance",
    "WarmRestart",
]
