// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Deterministic C interface generation from the selected solver's actual headers.
use anyhow::{Context, Result, bail};
use sha2::{Digest, Sha256};
use std::fmt::Write as _;
use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

const HEADERS: [&str; 5] = [
    "IpStdCInterface.h",
    "IpTypes.h",
    "IpoptConfig.h",
    "IpReturnCodes.h",
    "IpReturnCodes_inc.h",
];

pub(super) fn run(root: &Path, check: bool) -> Result<()> {
    let scratch = tempfile::tempdir().context("creating Ipopt generation directory")?;
    let headers = if let Some(prefix) = std::env::var_os("IPOPT_DIR") {
        PathBuf::from(prefix).join("include/coin-or")
    } else {
        extract_headers(root, scratch.path())?;
        scratch.path().to_owned()
    };
    let text = generate(&headers)?;
    let output = root.join(super::BINDINGS);
    if check {
        if fs::read_to_string(&output).context("reading committed Ipopt bindings")? != text {
            bail!(
                "Ipopt bindings differ from actual regenerated headers; run just codegen --only bindgen"
            );
        }
        super::untracked_check(root, &[PathBuf::from(super::BINDINGS)])?;
    } else {
        fs::write(output, text).context("writing generated Ipopt bindings")?;
    }
    println!(
        "codegen: Ipopt bindings {}",
        if check {
            "regeneration matches"
        } else {
            "generated"
        }
    );
    Ok(())
}

fn generate(headers: &Path) -> Result<String> {
    let mut hash = Sha256::new();
    for name in HEADERS {
        hash.update(name.as_bytes());
        hash.update([0]);
        hash.update(
            fs::read(headers.join(name)).with_context(|| format!("reading Ipopt header {name}"))?,
        );
    }
    let bindings = bindgen::Builder::default()
        .header_contents("pse-ipopt.h", "#include \"IpStdCInterface.h\"\n")
        .clang_arg(format!("-I{}", headers.display()))
        .allowlist_function(".*Ipopt.*|SetIntermediateCallback")
        .allowlist_var("IPOPT_VERSION.*")
        .allowlist_type("ApplicationReturnStatus|AlgorithmMode")
        .generate_comments(false)
        .layout_tests(false)
        .merge_extern_blocks(true)
        .rust_target(bindgen::RustTarget::stable(85, 0).map_err(|e| anyhow::anyhow!("{e}"))?)
        .rust_edition(bindgen::RustEdition::Edition2024)
        .formatter(bindgen::Formatter::Prettyplease)
        .generate()
        .context("generating actual Ipopt C API bindings")?;
    let mut digest = String::new();
    for byte in hash.finalize() {
        write!(digest, "{byte:02x}")?;
    }
    Ok(format!(
        "// @generated by cargo xtask codegen --only bindgen; do not edit\n// SPDX-License-Identifier: MIT OR Apache-2.0\n// Copyright (c) 2026 Paul Heyse\n// C interface headers SHA256: {digest}\n\n{bindings}"
    ))
}

fn extract_headers(root: &Path, destination: &Path) -> Result<()> {
    let pins: serde_json::Value =
        serde_json::from_slice(&fs::read(root.join(".github/setup/solver-images.json"))?)?;
    let image = pins["ci"].as_str().context("pinned solver image absent")?;
    let archive = Command::new("docker")
        .args([
            "run",
            "--rm",
            "--entrypoint",
            "tar",
            image,
            "-C",
            "/opt/pse-solvers/include/coin-or",
            "-cf",
            "-",
        ])
        .args(HEADERS)
        .output()
        .context("extracting headers from the pinned solver image; alternatively set IPOPT_DIR")?;
    if !archive.status.success() {
        bail!(
            "pinned solver header extraction failed: {}",
            String::from_utf8_lossy(&archive.stderr)
        );
    }
    let mut tar = Command::new("tar")
        .args(["--no-same-owner", "-xf", "-", "-C"])
        .arg(destination)
        .stdin(Stdio::piped())
        .spawn()
        .context("extracting pinned Ipopt headers")?;
    tar.stdin
        .take()
        .context("tar input absent")?
        .write_all(&archive.stdout)?;
    if !tar.wait()?.success() {
        bail!("pinned Ipopt header extraction failed");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn missing_headers_cannot_certify_a_placeholder() {
        let scratch = tempfile::tempdir().unwrap();
        assert!(generate(scratch.path()).is_err());
    }
}
