// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! The operational store's statements, compiled by Cornucopia into the generated crate
//! `crates/pse-operations-queries` (ADR-0114 Outcome 24; Plan 22 X6).
//!
//! Cornucopia 1.0.1 runs as a library under the workspace lockfile. It prepares every
//! statement of `crates/pse-operations/queries/*.sql` against a temporary database created
//! from the freshly generated `schema.sql` and the hand-written `physical.sql`, so a
//! misspelled column, a misspelled ENUM literal or a mistyped parameter fails generation.
//! Its output is then normalized: the manifest is rendered here with workspace inheritance
//! (Cornucopia's own manifest is only an inventory), `src/lib.rs` is written here with a
//! reasoned crate-level `allow`, and every other source is re-printed with prettyplease so
//! the committed bytes never depend on a `$PATH` rustfmt.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{Context, Result, anyhow, bail, ensure};
use pse_codegen::codegen::GeneratedTree;
use pse_codegen::codegen::postgres;

/// The generated crate, relative to the workspace.
pub(super) const ROOT: &str = "crates/pse-operations-queries";

/// The statements, relative to the workspace.
pub(super) const QUERIES: &str = "crates/pse-operations/queries";

/// The generated package's name.
const PACKAGE: &str = "pse-operations-queries";

/// The environment variable naming the server generation prepares statements on.
const URL_ENV: &str = "PSE_DATABASE_URL";

/// Where the store's development default URL is declared, once.
const STORE_SOURCE: &str = "crates/pse-operations/src/store.rs";

/// How long the reachability probe waits for the server.
const PROBE: Duration = Duration::from_secs(2);

const RUST_HEADER: &str = "// SPDX-License-Identifier: MIT OR Apache-2.0\n// Copyright (c) 2026 Paul Heyse\n// @generated by cargo xtask codegen (Cornucopia 1.0.1) from crates/pse-operations/queries; do not edit\n\n";

/// Dependencies Cornucopia may declare; anything else fails generation.
const KNOWN_DEPENDENCIES: [&str; 10] = [
    "chrono",
    "deadpool-postgres",
    "futures",
    "postgres",
    "postgres-protocol",
    "postgres-types",
    "serde",
    "serde_json",
    "tokio-postgres",
    "uuid",
];

/// The server to prepare statements on: `PSE_DATABASE_URL`, else the store's development
/// default as `pse-operations` declares it.
pub(super) fn database_url(root: &Path) -> Result<String> {
    if let Some(url) = std::env::var(URL_ENV).ok().filter(|url| !url.is_empty()) {
        return Ok(url);
    }
    let source = fs::read_to_string(root.join(STORE_SOURCE))
        .with_context(|| format!("reading {STORE_SOURCE}"))?;
    let marker = "pub const DEFAULT_DATABASE_URL: &str = \"";
    let start = source
        .find(marker)
        .map(|at| at + marker.len())
        .with_context(|| format!("{STORE_SOURCE} declares no DEFAULT_DATABASE_URL"))?;
    let end = source[start..]
        .find('"')
        .context("unterminated DEFAULT_DATABASE_URL")?;
    Ok(source[start..start + end].to_owned())
}

/// Generate the query crate from the fresh PostgreSQL tree (never the committed one).
pub(super) fn generate(root: &Path, schema: &GeneratedTree, check: bool) -> Result<GeneratedTree> {
    let url = database_url(root)?;
    generate_from(root, schema, &root.join(QUERIES), &url, check)
}

fn generate_from(
    root: &Path,
    schema: &GeneratedTree,
    queries: &Path,
    url: &str,
    check: bool,
) -> Result<GeneratedTree> {
    // (1) The freshly rendered schema and mapping, in scratch space.
    let rendered = tempfile::tempdir().context("creating the schema scratch directory")?;
    for name in ["schema.sql", "cornucopia.toml"] {
        let bytes = schema
            .files
            .get(&Path::new(postgres::ROOT).join(name))
            .with_context(|| format!("the PostgreSQL generator rendered no {name}"))?;
        fs::write(rendered.path().join(name), bytes)?;
    }
    // (2) The statements.
    let statements = tempfile::tempdir().context("creating the statement scratch directory")?;
    let mut count = 0;
    for path in sql_files(queries)? {
        let name = path.file_name().context("statement file without a name")?;
        fs::copy(&path, statements.path().join(name))
            .with_context(|| format!("copying {}", path.display()))?;
        count += 1;
    }
    ensure!(count > 0, "{} holds no statement files", queries.display());
    // (3) A reachable server.
    reachable(url, check)?;
    // (4) Cornucopia against a temporary database.
    let output = tempfile::tempdir().context("creating the Cornucopia output directory")?;
    let destination = output.path().join("crate");
    let config =
        cornucopia::config::Config::builder_from_file(rendered.path().join("cornucopia.toml"))
            .map_err(|error| anyhow!("reading the generated Cornucopia mapping: {error}"))?
            .queries(statements.path())
            .destination(&destination)
            .r#async(true)
            .sync(false)
            .params_only(true)
            .name(PACKAGE)
            .build();
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|elapsed| elapsed.subsec_nanos())
        .unwrap_or_default();
    let database = format!("pse_codegen_{}_{nanos}", std::process::id());
    cornucopia::gen_fresh(
        url,
        &database,
        &[
            rendered.path().join("schema.sql"),
            root.join(postgres::PHYSICAL_SQL),
        ],
        None,
        false,
        config,
    )
    .map_err(|error| anyhow!("{:?}", miette::Report::new(error)))
    .context("Cornucopia refused the store statements")?;
    // (5) Normalize into the committed shape.
    normalize(&destination)
}

/// The `.sql` files of a directory, in name order.
fn sql_files(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    for entry in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "sql") {
            files.push(path);
        }
    }
    files.sort();
    Ok(files)
}

/// Connect once with a short timeout, naming the target (never its password) on failure.
fn reachable(url: &str, check: bool) -> Result<()> {
    let config: tokio_postgres::Config = url
        .parse()
        .map_err(|error| anyhow!("{URL_ENV} is not a PostgreSQL URL: {error}"))?;
    let target = describe(&config);
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("starting the reachability probe")?;
    let connected = runtime.block_on(async {
        let connect = tokio::time::timeout(PROBE, config.connect(tokio_postgres::NoTls)).await;
        match connect {
            Ok(Ok((client, connection))) => {
                drop(client);
                // Close the probe's connection before Cornucopia connects.
                let _ = connection.await;
                Ok(())
            }
            Ok(Err(error)) => Err(error.to_string()),
            Err(_) => Err(format!("no answer within {PROBE:?}")),
        }
    });
    if let Err(reason) = connected {
        let verb = if check { "checked" } else { "generated" };
        bail!(
            "store queries not {verb}: PostgreSQL unreachable at {target} ({reason}); see `just db-status`"
        );
    }
    Ok(())
}

/// A connection target without credentials.
fn describe(config: &tokio_postgres::Config) -> String {
    let hosts = config
        .get_hosts()
        .iter()
        .map(|host| match host {
            tokio_postgres::config::Host::Tcp(name) => name.clone(),
            #[cfg(unix)]
            tokio_postgres::config::Host::Unix(path) => path.display().to_string(),
        })
        .collect::<Vec<_>>()
        .join(",");
    let port = config
        .get_ports()
        .first()
        .map_or_else(|| "5432".to_owned(), u16::to_string);
    let database = config.get_dbname().unwrap_or("<default>");
    format!("postgres {hosts}:{port}/{database}")
}

/// What Cornucopia's `src/lib.rs` declares: modules with their visibility, and re-exports.
#[derive(Debug, Default)]
struct LibInventory {
    json: bool,
}

const MODULES: [(&str, bool); 7] = [
    ("array_iterator", false),
    ("client", true),
    ("domain", false),
    ("queries", true),
    ("type_traits", false),
    ("types", true),
    ("utils", false),
];

const REEXPORTS: [&str; 10] = [
    "array_iterator :: ArrayIterator",
    "deadpool_postgres",
    "domain :: { Domain , DomainArray }",
    "postgres",
    "postgres :: fallible_iterator",
    "tokio_postgres",
    "tokio_postgres :: fallible_iterator",
    "type_traits :: JsonSql",
    "type_traits :: { ArraySql , BytesSql , IterSql , StringSql }",
    "utils :: slice_iter",
];

/// Read Cornucopia's `lib.rs` as an inventory: exactly the known modules and re-exports.
fn lib_inventory(source: &str) -> Result<LibInventory> {
    use quote::ToTokens as _;
    let file = syn::parse_file(source).context("parsing Cornucopia's lib.rs")?;
    let mut modules = BTreeMap::new();
    let mut inventory = LibInventory::default();
    for item in &file.items {
        match item {
            syn::Item::Mod(module) if module.content.is_none() => {
                let public = matches!(module.vis, syn::Visibility::Public(_));
                modules.insert(module.ident.to_string(), public);
            }
            syn::Item::Use(import) => {
                let path = import.tree.to_token_stream().to_string();
                ensure!(
                    REEXPORTS.contains(&path.as_str()),
                    "Cornucopia's lib.rs re-exports an unexpected `{path}`"
                );
                inventory.json |= path == "type_traits :: JsonSql";
            }
            other => bail!(
                "Cornucopia's lib.rs declares an unexpected item: {}",
                other.to_token_stream()
            ),
        }
    }
    let expected: BTreeMap<String, bool> = MODULES
        .iter()
        .map(|(name, public)| ((*name).to_owned(), *public))
        .collect();
    ensure!(
        modules == expected,
        "Cornucopia's lib.rs declares modules {modules:?}; expected {expected:?}"
    );
    Ok(inventory)
}

/// The crate root: modules skipped by rustfmt, one reasoned crate-level `allow`, and the
/// async client surface only (no sync `postgres`, no wasm branches).
fn render_lib(inventory: &LibInventory) -> String {
    let mut lib = String::from(RUST_HEADER);
    lib.push_str(concat!(
        "//! The operational store's statements, compiled by Cornucopia 1.0.1 from\n",
        "//! `crates/pse-operations/queries/*.sql` against the registry-generated schema\n",
        "//! (ADR-0114 Outcome 24). `pse-operations` is its only consumer; `just codegen`\n",
        "//! regenerates it and `just codegen-queries-check` compares a fresh generation.\n",
        "\n",
        "#![allow(\n",
        "    missing_docs,\n",
        "    unreachable_pub,\n",
        "    missing_debug_implementations,\n",
        "    unused_qualifications,\n",
        "    trivial_casts,\n",
        "    rust_2018_idioms,\n",
        "    dead_code,\n",
        "    unused_imports,\n",
        "    unused_variables,\n",
        "    clippy::all,\n",
        "    clippy::unwrap_used,\n",
        "    clippy::expect_used,\n",
        "    clippy::panic,\n",
        "    clippy::allow_attributes_without_reason,\n",
        "    rustdoc::broken_intra_doc_links,\n",
        "    rustdoc::bare_urls,\n",
        "    reason = \"Cornucopia-generated statement code; statements are checked at generation and by store tests\"\n",
        ")]\n",
        "\n",
    ));
    for (name, public) in MODULES {
        lib.push_str("#[rustfmt::skip]\n");
        if public {
            lib.push_str("pub ");
        }
        lib.push_str("mod ");
        lib.push_str(name);
        lib.push_str(";\n");
    }
    lib.push_str(concat!(
        "\n",
        "pub use array_iterator::ArrayIterator;\n",
        "#[cfg(feature = \"deadpool\")]\n",
        "pub use deadpool_postgres;\n",
        "pub use domain::{Domain, DomainArray};\n",
        "pub use tokio_postgres;\n",
        "pub use tokio_postgres::fallible_iterator;\n",
    ));
    if inventory.json {
        lib.push_str("pub use type_traits::JsonSql;\n");
    }
    lib.push_str(concat!(
        "pub use type_traits::{ArraySql, BytesSql, IterSql, StringSql};\n",
        "pub(crate) use utils::slice_iter;\n",
    ));
    lib
}

/// The dependency names Cornucopia's manifest declares, refusing any it should not.
fn dependency_inventory(manifest: &str) -> Result<BTreeSet<String>> {
    let table: toml::Table = toml::from_str(manifest).context("parsing Cornucopia's manifest")?;
    let dependencies = table
        .get("dependencies")
        .and_then(toml::Value::as_table)
        .context("Cornucopia's manifest declares no dependencies")?;
    let mut names = BTreeSet::new();
    for name in dependencies.keys() {
        ensure!(
            KNOWN_DEPENDENCIES.contains(&name.as_str()),
            "Cornucopia's manifest declares an unexpected dependency `{name}`"
        );
        names.insert(name.clone());
    }
    Ok(names)
}

/// The generated manifest: workspace-inherited package metadata, lints and dependencies.
/// A dependency Cornucopia declares is kept when the crate needs it structurally or its
/// sources name it; the synchronous `postgres` client is never kept.
fn render_manifest(inventory: &BTreeSet<String>, sources: &str) -> Result<String> {
    for structural in [
        "deadpool-postgres",
        "futures",
        "postgres-protocol",
        "postgres-types",
        "tokio-postgres",
    ] {
        ensure!(
            inventory.contains(structural),
            "Cornucopia's manifest lacks `{structural}`; the async client needs it"
        );
    }
    let named = |name: &str| sources.contains(&format!("{}::", name.replace('-', "_")));
    let mut dependencies = vec![
        "pse-ids = { workspace = true, features = [\"postgres\"] }".to_owned(),
        "pse-model = { workspace = true, features = [\"postgres\"] }".to_owned(),
    ];
    for name in inventory {
        let line = match name.as_str() {
            "postgres" => continue,
            "deadpool-postgres" => {
                "deadpool-postgres = { workspace = true, optional = true }".to_owned()
            }
            "serde_json" if named(name) => {
                "serde_json = { workspace = true, features = [\"raw_value\"] }".to_owned()
            }
            "futures" | "postgres-protocol" | "postgres-types" | "tokio-postgres" => {
                format!("{name}.workspace = true")
            }
            _ if named(name) => format!("{name}.workspace = true"),
            _ => continue,
        };
        dependencies.push(line);
    }
    Ok(format!(
        concat!(
            // REUSE-IgnoreStart
            "# SPDX-License-Identifier: MIT OR Apache-2.0\n",
            "# Copyright (c) 2026 Paul Heyse\n",
            // REUSE-IgnoreEnd
            "# @generated by cargo xtask codegen (Cornucopia 1.0.1) from crates/pse-operations/queries; do not edit\n",
            "\n",
            "[package]\n",
            "name = \"{package}\"\n",
            "description = \"The operational store's statements, compiled by Cornucopia from crates/pse-operations/queries against the registry-generated schema (ADR-0114 Outcome 24).\"\n",
            "version.workspace = true\n",
            "edition.workspace = true\n",
            "rust-version.workspace = true\n",
            "license.workspace = true\n",
            "repository.workspace = true\n",
            "homepage.workspace = true\n",
            "authors.workspace = true\n",
            "publish.workspace = true\n",
            "\n",
            "[lints]\n",
            "workspace = true\n",
            "\n",
            "[features]\n",
            "default = [\"deadpool\"]\n",
            "deadpool = [\"dep:deadpool-postgres\"]\n",
            "\n",
            "[dependencies]\n",
            "{dependencies}\n",
        ),
        package = PACKAGE,
        dependencies = dependencies.join("\n"),
    ))
}

/// Cornucopia's output in the committed shape.
fn normalize(generated: &Path) -> Result<GeneratedTree> {
    let manifest = fs::read_to_string(generated.join("Cargo.toml"))
        .context("reading Cornucopia's manifest")?;
    let inventory = dependency_inventory(&manifest)?;
    let mut files = BTreeMap::new();
    let mut sources = String::new();
    let mut lib = None;
    let mut found = BTreeSet::new();
    super::collect_files(generated, Path::new(""), &mut found)?;
    for relative in found {
        if relative == Path::new("Cargo.toml") {
            continue;
        }
        ensure!(
            relative.starts_with("src") && relative.extension().is_some_and(|ext| ext == "rs"),
            "Cornucopia wrote an unexpected file: {}",
            relative.display()
        );
        let text = fs::read_to_string(generated.join(&relative))
            .with_context(|| format!("reading {}", relative.display()))?;
        if relative == Path::new("src/lib.rs") {
            lib = Some(lib_inventory(&text)?);
            continue;
        }
        let syntax = syn::parse_file(&text)
            .with_context(|| format!("parsing generated {}", relative.display()))?;
        if relative == Path::new("src/types.rs") {
            ensure!(
                syntax.items.is_empty(),
                "Cornucopia generated types in src/types.rs: every store ENUM, domain and \
                 composite must be mapped by the generated cornucopia.toml"
            );
        }
        let printed = format!("{RUST_HEADER}{}", prettyplease::unparse(&syntax));
        sources.push_str(&printed);
        files.insert(Path::new(ROOT).join(&relative), printed.into_bytes());
    }
    let lib = lib.context("Cornucopia wrote no src/lib.rs")?;
    files.insert(
        Path::new(ROOT).join("src/lib.rs"),
        render_lib(&lib).into_bytes(),
    );
    files.insert(
        Path::new(ROOT).join("Cargo.toml"),
        render_manifest(&inventory, &sources)?.into_bytes(),
    );
    Ok(GeneratedTree {
        roots: vec![PathBuf::from(ROOT)],
        files,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn workspace() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("xtask lives in the workspace")
            .to_owned()
    }

    fn fresh_schema() -> GeneratedTree {
        let registry = pse_schema::registry().expect("the registry assembles");
        pse_codegen::codegen::generate(registry, pse_codegen::codegen::Language::Postgres)
            .expect("the store schema renders")
    }

    #[test]
    fn normalized_manifest_passes_registration_rules() {
        let cornucopia = "[package]\nname = \"x\"\nversion = \"0.0.0\"\nedition = \"2024\"\nrust-version = \"1.85\"\n\n[dependencies]\nchrono = \"0.4\"\ndeadpool-postgres = { version = \"0.14\", optional = true }\nfutures = \"0.3\"\npostgres = { version = \"0.19\", optional = true }\npostgres-protocol = \"0.6\"\npostgres-types = { version = \"0.2\", features = [\"derive\"] }\nserde = \"1\"\nserde_json = \"1\"\ntokio-postgres = \"0.7\"\nuuid = \"1\"\n\n[features]\ndefault = [\"dep:postgres\", \"deadpool\"]\n";
        let inventory = dependency_inventory(cornucopia).unwrap();
        let rendered = render_manifest(&inventory, "chrono::DateTime serde_json::Value").unwrap();
        let manifest: toml::Table = toml::from_str(&rendered).unwrap();
        let package = manifest["package"].as_table().unwrap();
        for field in [
            "version",
            "edition",
            "rust-version",
            "license",
            "repository",
            "homepage",
            "authors",
            "publish",
        ] {
            assert_eq!(
                package[field]["workspace"].as_bool(),
                Some(true),
                "{field} is inherited"
            );
        }
        assert_eq!(manifest["lints"]["workspace"].as_bool(), Some(true));
        let dependencies = manifest["dependencies"].as_table().unwrap();
        for (name, value) in dependencies {
            assert_eq!(
                value["workspace"].as_bool(),
                Some(true),
                "{name} is a workspace dependency"
            );
        }
        // The synchronous client and unreferenced crates are dropped.
        for dropped in ["postgres", "serde", "uuid"] {
            assert!(!dependencies.contains_key(dropped), "{dropped} is dropped");
        }
        for kept in [
            "chrono",
            "serde_json",
            "tokio-postgres",
            "pse-ids",
            "pse-model",
        ] {
            assert!(dependencies.contains_key(kept), "{kept} is kept");
        }
        assert_eq!(
            manifest["features"]["default"].as_array().unwrap(),
            &vec![toml::Value::from("deadpool")]
        );
        // A dependency Cornucopia should never need fails generation.
        let unexpected = format!("{cornucopia}\n[dependencies.eui48]\nversion = \"1\"\n");
        assert!(dependency_inventory(&unexpected).is_err());
    }

    #[test]
    fn crate_root_is_rendered_with_reasoned_allow() {
        let lib = render_lib(&LibInventory { json: true });
        assert!(lib.contains("reason = \"Cornucopia-generated statement code"));
        assert!(lib.contains("pub use tokio_postgres;\n"));
        assert!(!lib.contains("postgres::fallible_iterator;\npub use postgres"));
        assert_eq!(lib.matches("#[rustfmt::skip]").count(), MODULES.len());
        assert!(lib_inventory("mod stray;").is_err());
    }

    #[test]
    fn store_queries_regenerate_identically() {
        let root = workspace();
        let schema = fresh_schema();
        let url = database_url(&root).unwrap();
        let first = generate_from(&root, &schema, &root.join(QUERIES), &url, true).unwrap();
        let second = generate_from(&root, &schema, &root.join(QUERIES), &url, true).unwrap();
        assert_eq!(first.files, second.files, "generation is deterministic");
        let scratch = tempfile::tempdir().unwrap();
        super::super::write_tree(scratch.path(), &first).unwrap();
        super::super::compare_tree(&root, scratch.path(), &first).unwrap();
    }

    #[test]
    fn generated_query_rejects_misspelled_column_and_literal() {
        let root = workspace();
        let schema = fresh_schema();
        let url = database_url(&root).unwrap();
        for (statement, expected) in [
            (
                "--! misspelled_column\nSELECT attempt_idd FROM pse_ops.attempts;\n",
                "attempt_idd",
            ),
            (
                "--! misspelled_literal\nSELECT attempt_id FROM pse_ops.attempts WHERE state = 'runing';\n",
                "runing",
            ),
        ] {
            let queries = tempfile::tempdir().unwrap();
            fs::write(queries.path().join("negative.sql"), statement).unwrap();
            let error = generate_from(&root, &schema, queries.path(), &url, true)
                .expect_err("a misspelling fails generation");
            assert!(
                format!("{error:?}").contains(expected),
                "the refusal names `{expected}`: {error:?}"
            );
        }
    }
}
