# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
"""The generated native stub describes the actual compiled Python surface."""

import ast
from pathlib import Path

import pytest

from pse import _native

STUB = Path(_native.__file__).with_name("_native.pyi")

#: Names every module has; they are not part of the extension's surface.
MODULE_DUNDERS = frozenset(
    {
        "__all__",
        "__builtins__",
        "__dict__",
        "__doc__",
        "__file__",
        "__loader__",
        "__name__",
        "__package__",
        "__path__",
        "__spec__",
    }
)


def _declared_in_stub() -> set[str]:
    tree = ast.parse(STUB.read_text(encoding="utf-8"))
    declared: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
            declared.add(node.name)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            declared.add(node.target.id)
        elif isinstance(node, ast.Assign):
            declared.update(
                target.id for target in node.targets if isinstance(target, ast.Name)
            )
    return declared


def _exported_by_extension() -> set[str]:
    return {
        name
        for name in dir(_native)
        if name not in MODULE_DUNDERS
        and (not name.startswith("_") or name.startswith("__"))
    }


@pytest.mark.unit
def test_stub_exists_beside_the_extension() -> None:
    assert STUB.is_file(), f"{STUB} is missing; the stub ships with the wheel"


@pytest.mark.unit
def test_stub_declares_exactly_the_extension_surface() -> None:
    declared = _declared_in_stub()
    exported = _exported_by_extension()
    assert declared == exported, (
        f"pse/_native.pyi declares {sorted(declared)} but pse._native exports "
        f"{sorted(exported)}; update the stub in the same commit as the crate"
    )


@pytest.mark.unit
def test_stub_is_generated_and_every_declared_member_exists_at_runtime() -> None:
    source = STUB.read_text(encoding="utf-8")
    assert "@generated by cargo xtask python-stubs" in source
    tree = ast.parse(source)
    for node in ast.walk(tree):
        assert not (isinstance(node, ast.Name) and node.id in {"Any", "Incomplete"})
        assert not (
            isinstance(node, ast.Attribute) and node.attr in {"Any", "Incomplete"}
        )
    for declaration in tree.body:
        if not isinstance(declaration, ast.ClassDef):
            continue
        native_class = getattr(_native, declaration.name)
        for member in declaration.body:
            if isinstance(member, ast.FunctionDef) and member.name != "__init__":
                assert hasattr(native_class, member.name), (
                    declaration.name,
                    member.name,
                )
    # Native exceptions inherit Exception and carry the fields from their one
    # typed runtime declaration, even where upstream introspection lacks a chunk.
    assert issubclass(_native.InspectionError, Exception)


@pytest.mark.unit
def test_enum_getters_and_owned_documents_have_their_actual_native_annotations() -> (
    None
):
    tree = ast.parse(STUB.read_text(encoding="utf-8"))
    classes = {node.name: node for node in tree.body if isinstance(node, ast.ClassDef)}
    expected = {
        "NativeAttempt": {
            "backend": "NativeBackend",
            "termination": "NativeTermination",
            "qualification": "NativeQualification",
        },
        "DiagnosticReport": {
            "code": "DiagnosticCode",
            "failure_class": "FailureClass",
            "boundary_class": "NativeBoundaryClass",
            "severity": "DiagnosticSeverity",
            "envelope": "BoundaryDiagnostic",
        },
    }
    for owner, getters in expected.items():
        methods = {
            member.name: member
            for member in classes[owner].body
            if isinstance(member, ast.FunctionDef)
        }
        for getter, document in getters.items():
            annotation = methods[getter].returns
            assert annotation is not None
            assert document in ast.unparse(annotation), (owner, getter, annotation)
    build_info = next(
        node
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name == "build_info"
    )
    assert build_info.returns is not None
    assert "BuildInfo" in ast.unparse(build_info.returns)
