# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Contracts generated from the sole registry declaration."""

from pse.contracts.extension_types import EXTENSION_NAMES, register_all
from pse.contracts.manifest import Manifest

__all__ = ["EXTENSION_NAMES", "REGISTRY_FINGERPRINT", "Manifest", "register_all"]

REGISTRY_FINGERPRINT = "blake3:37cf00bc621b871616851781a8aab6d8253ee878d30c92074da2f03f3ff2fee2"
