# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Contracts generated from the sole registry declaration."""

from pse.contracts.extension_types import EXTENSION_NAMES, register_all

__all__ = ["EXTENSION_NAMES", "REGISTRY_FINGERPRINT", "register_all"]

REGISTRY_FINGERPRINT = "blake3:4c400357da15bcc1c424d8201bd5fef328699d04417cdf6ef11e1ce14d6a78e9"
