# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Contracts generated from the sole registry declaration."""

from pse.contracts.extension_types import EXTENSION_NAMES, register_all

__all__ = ["EXTENSION_NAMES", "REGISTRY_FINGERPRINT", "register_all"]

REGISTRY_FINGERPRINT = "blake3:ef38e60c3ff901b6fc97307c6cdfc187c66327877e059f8ea612244ac9fc193d"
