# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Typed rows in the compiled namespace."""

import builtins as b

import attrs

from pse.contracts import enums as e
from pse.contracts import values as v


@attrs.frozen(kw_only=True)
class CompiledBackendBindingsRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    backend: e.Backend = attrs.field(validator=attrs.validators.instance_of(e.Backend))
    status: e.BindingStatus = attrs.field(validator=attrs.validators.instance_of(e.BindingStatus))
    unsupported_opcodes: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    artifact_hash: v.ContentHash | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.ContentHash)))


@attrs.frozen(kw_only=True)
class CompiledBlockMembersRow:
    """Declared relation row or nested value."""

    block_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.DMKind = attrs.field(validator=attrs.validators.instance_of(e.DMKind))
    id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledBlocksRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    block_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.BlockKind = attrs.field(validator=attrs.validators.instance_of(e.BlockKind))
    order: b.int = attrs.field(validator=v.integer_range(0, 4294967295))
    size: b.int = attrs.field(validator=v.integer_range(0, 4294967295))


@attrs.frozen(kw_only=True)
class CompiledBoundValuesRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    treatment: e.Treatment = attrs.field(validator=attrs.validators.instance_of(e.Treatment))
    value: b.float = attrs.field(validator=v.finite_float)
    unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    value_hash: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))
    source_spec_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))


@attrs.frozen(kw_only=True)
class CompiledCaseBoundSubstitutionsRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    value: b.float = attrs.field(validator=v.finite_float)
    unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    value_hash: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))
    source: e.ValueSource = attrs.field(validator=attrs.validators.instance_of(e.ValueSource))


@attrs.frozen(kw_only=True)
class CompiledContributionsRow:
    """Declared relation row or nested value."""

    contribution_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    contribution_decl_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    scope_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    expression_root: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    law_family: e.LawFamily = attrs.field(validator=attrs.validators.instance_of(e.LawFamily))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    basis_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    orientation: e.Orientation = attrs.field(validator=attrs.validators.instance_of(e.Orientation))
    transfer_connection_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    subject_kind: e.ContributionSubjectKind = attrs.field(validator=attrs.validators.instance_of(e.ContributionSubjectKind))
    subject_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    subject_axis: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    phase_axis: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    phase_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledDmPartitionRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.DMKind = attrs.field(validator=attrs.validators.instance_of(e.DMKind))
    id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    block: e.DMBlock = attrs.field(validator=attrs.validators.instance_of(e.DMBlock))
    matched_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))


@attrs.frozen(kw_only=True)
class CompiledElementProjectionCoefficientsRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    element_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    species_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    count: b.float = attrs.field(validator=v.finite_float)
    molecular_weight: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    value: b.float = attrs.field(validator=v.finite_float)
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledElementProjectionGroupsRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    application_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    contribution_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    law_template_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_basis_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    element_domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    species_domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    domain_ids: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledEquationBranchesFieldBranchGuardsItem:
    """Declared relation row or nested value."""

    source_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    predicate_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    expected: b.bool = attrs.field(validator=v.exact_type(b.bool))


@attrs.frozen(kw_only=True)
class CompiledEquationBranchesRow:
    """Declared relation row or nested value."""

    indexed_equation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    parent_indexed_equation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    equation_decl_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    equation_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    branch_guards: b.tuple[CompiledEquationBranchesFieldBranchGuardsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledEquationBranchesFieldBranchGuardsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledEquationOrderRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    equation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    position: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 9223372036854775807)))
    active: b.bool = attrs.field(validator=v.exact_type(b.bool))
    scale: b.float = attrs.field(validator=v.finite_float)
    kind: e.RowKind = attrs.field(validator=attrs.validators.instance_of(e.RowKind))


@attrs.frozen(kw_only=True)
class CompiledEquationScalesRow:
    """Declared relation row or nested value."""

    equation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    scale: b.float = attrs.field(validator=v.finite_float)
    scheme: e.ConstraintScalingScheme = attrs.field(validator=attrs.validators.instance_of(e.ConstraintScalingScheme))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledEvaluationProgramsRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    program_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    artifact_hash: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))
    instruction_count: b.int = attrs.field(validator=v.integer_range(0, 9223372036854775807))
    workspace_size: b.int = attrs.field(validator=v.integer_range(0, 9223372036854775807))


@attrs.frozen(kw_only=True)
class CompiledExpressionRootIndicesRow:
    """Declared relation row or nested value."""

    owner_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    role: e.ExpressionRootRole = attrs.field(validator=attrs.validators.instance_of(e.ExpressionRootRole))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    position: b.int = attrs.field(validator=v.integer_range(0, 65535))
    bound_index_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledExpressionRootsRow:
    """Declared relation row or nested value."""

    owner_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    role: e.ExpressionRootRole = attrs.field(validator=attrs.validators.instance_of(e.ExpressionRootRole))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledGroupCollectionMembersRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    symbol_decl_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledGroupCollectionsRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    root_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    path_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledGroupProjectionsFieldFixedCoordinatesItem:
    """Declared relation row or nested value."""

    axis: b.int = attrs.field(validator=v.integer_range(0, 65535))
    member_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledGroupProjectionsRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    fixed_coordinates: b.tuple[CompiledGroupProjectionsFieldFixedCoordinatesItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledGroupProjectionsFieldFixedCoordinatesItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledGroupReindexingMembersRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    source_index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledGroupReindexingsFieldFixedIndicesItem:
    """Declared relation row or nested value."""

    bound_index_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    member_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledGroupReindexingsRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    bound_indices: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    fixed_indices: b.tuple[CompiledGroupReindexingsFieldFixedIndicesItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledGroupReindexingsFieldFixedIndicesItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledIncidenceFieldDependenceLinear:
    """Declared relation row or nested value."""

    coefficient: b.float = attrs.field(validator=v.finite_float)


@attrs.frozen(kw_only=True)
class CompiledIncidenceFieldDependence:
    """Declared relation row or nested value."""

    kind: e.IncidenceKind = attrs.field(validator=attrs.validators.instance_of(e.IncidenceKind))
    linear: CompiledIncidenceFieldDependenceLinear | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(CompiledIncidenceFieldDependenceLinear)))

    def __attrs_post_init__(self) -> None:
        if not ((self.kind == "linear" and self.linear is not None) or (self.kind == "nonlinear" and self.linear is None)):
            message = "tagged value requires exactly its selected arm"
            raise ValueError(message)


@attrs.frozen(kw_only=True)
class CompiledIncidenceRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    equation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    dependence: CompiledIncidenceFieldDependence = attrs.field(validator=attrs.validators.instance_of(CompiledIncidenceFieldDependence))


@attrs.frozen(kw_only=True)
class CompiledInitStagesRow:
    """Declared relation row or nested value."""

    stage_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    plan_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    kind: e.StageKind = attrs.field(validator=attrs.validators.instance_of(e.StageKind))
    target_kind: e.StageTargetKind = attrs.field(validator=attrs.validators.instance_of(e.StageTargetKind))
    target_ids: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    overlay_case_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    solver_profile_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    tolerance: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    failure_policy: e.FailurePolicy = attrs.field(validator=attrs.validators.instance_of(e.FailurePolicy))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))


@attrs.frozen(kw_only=True)
class CompiledInitializationPlansRow:
    """Declared relation row or nested value."""

    plan_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    case_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    template_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))


@attrs.frozen(kw_only=True)
class CompiledKernelBindingsFieldParameterBindingsItem:
    """Declared relation row or nested value."""

    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    symbol_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    value: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    unit_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))


@attrs.frozen(kw_only=True)
class CompiledKernelBindingsFieldInputBindingsItem:
    """Declared relation row or nested value."""

    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))


@attrs.frozen(kw_only=True)
class CompiledKernelBindingsRow:
    """Declared relation row or nested value."""

    binding_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kernel_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    scope_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    parameter_bindings: b.tuple[CompiledKernelBindingsFieldParameterBindingsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledKernelBindingsFieldParameterBindingsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    input_bindings: b.tuple[CompiledKernelBindingsFieldInputBindingsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledKernelBindingsFieldInputBindingsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))


@attrs.frozen(kw_only=True)
class CompiledKernelOutputSymbolsRow:
    """Declared relation row or nested value."""

    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    requirement_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    state_scope_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    method_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kernel_binding_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    output_ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledLawApplicationsRow:
    """Declared relation row or nested value."""

    application_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    law_instance_decl_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    law_template_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    scope_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    law_family: e.LawFamily = attrs.field(validator=attrs.validators.instance_of(e.LawFamily))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    basis_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    subject_kind: e.ContributionSubjectKind = attrs.field(validator=attrs.validators.instance_of(e.ContributionSubjectKind))
    subject_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    subject_axis: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    phase_axis: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    phase_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    source_family: e.LawFamily = attrs.field(validator=attrs.validators.instance_of(e.LawFamily))
    subject_projection: e.LawSubjectProjection = attrs.field(validator=attrs.validators.instance_of(e.LawSubjectProjection))
    expansion: e.LawExpansion = attrs.field(validator=attrs.validators.instance_of(e.LawExpansion))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledLawParticipationRow:
    """Declared relation row or nested value."""

    application_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    contribution_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    decision: e.ParticipationDecision = attrs.field(validator=attrs.validators.instance_of(e.ParticipationDecision))
    reason: e.ParticipationReason = attrs.field(validator=attrs.validators.instance_of(e.ParticipationReason))
    sign: b.int = attrs.field(validator=v.integer_range(-2147483648, 2147483647))
    conversion_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathAffineFieldTermsItem:
    """Declared relation row or nested value."""

    coefficient: b.float = attrs.field(validator=v.finite_float)
    child_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))


@attrs.frozen(kw_only=True)
class CompiledMathAffineRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    constant: b.float = attrs.field(validator=v.finite_float)
    constant_quantity_type_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    constant_unit_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    terms: b.tuple[CompiledMathAffineFieldTermsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledMathAffineFieldTermsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))


@attrs.frozen(kw_only=True)
class CompiledMathBroadcastsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    bound_index_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathComplementarityRow:
    """Declared relation row or nested value."""

    pair_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    expr_a_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    expr_b_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    formulation: e.ComplementarityForm = attrs.field(validator=attrs.validators.instance_of(e.ComplementarityForm))


@attrs.frozen(kw_only=True)
class CompiledMathConditionalsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    guard_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))


@attrs.frozen(kw_only=True)
class CompiledMathDaeLinksRow:
    """Declared relation row or nested value."""

    derivative_symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    state_symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    wrt_domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivative_order: b.int = attrs.field(validator=v.integer_range(0, 255))


@attrs.frozen(kw_only=True)
class CompiledMathDerivativesRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    wrt_domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    order: b.int = attrs.field(validator=v.integer_range(0, 255))


@attrs.frozen(kw_only=True)
class CompiledMathEquationsRow:
    """Declared relation row or nested value."""

    equation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    equation_decl_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    parent_indexed_equation_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    qualified_name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    body_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    sense: e.Sense = attrs.field(validator=attrs.validators.instance_of(e.Sense))
    lower_node_id: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 18446744073709551615)))
    upper_node_id: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 18446744073709551615)))
    residual_quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    family: e.EquationFamily = attrs.field(validator=attrs.validators.instance_of(e.EquationFamily))
    role: e.EquationRole = attrs.field(validator=attrs.validators.instance_of(e.EquationRole))
    differentiability: e.Differentiability = attrs.field(validator=attrs.validators.instance_of(e.Differentiability))
    convexity: e.Convexity = attrs.field(validator=attrs.validators.instance_of(e.Convexity))
    monotonicity: e.Monotonicity = attrs.field(validator=attrs.validators.instance_of(e.Monotonicity))
    default_active: b.bool = attrs.field(validator=v.exact_type(b.bool))
    group_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    law_instance_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathExprArgsRow:
    """Declared relation row or nested value."""

    parent_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    argument_ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    child_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))


@attrs.frozen(kw_only=True)
class CompiledMathExprNodesRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    opcode: e.Opcode = attrs.field(validator=attrs.validators.instance_of(e.Opcode))
    quantity_type_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    scope_instance_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    subtree_hash: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))


@attrs.frozen(kw_only=True)
class CompiledMathFloatConstantsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    value: b.float = attrs.field(validator=v.finite_float)
    unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathFreeIndicesRow:
    """Declared relation row or nested value."""

    indexed_equation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    bound_index_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    position: b.int = attrs.field(validator=v.integer_range(0, 65535))


@attrs.frozen(kw_only=True)
class CompiledMathGathersFieldCoordinateMapItem:
    """Declared relation row or nested value."""

    bound_index_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    position: b.int = attrs.field(validator=v.integer_range(0, 65535))


@attrs.frozen(kw_only=True)
class CompiledMathGathersRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    coordinate_map: b.tuple[CompiledMathGathersFieldCoordinateMapItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledMathGathersFieldCoordinateMapItem), iterable_validator=attrs.validators.instance_of(b.tuple)))


@attrs.frozen(kw_only=True)
class CompiledMathImplicitRefsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    implicit_system_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    unknown_ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))


@attrs.frozen(kw_only=True)
class CompiledMathImplicitSystemsRow:
    """Declared relation row or nested value."""

    implicit_system_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    unknown_symbol_ids: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.and_(attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)), v.collection(0, None, unique=True)))
    equation_ids: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.and_(attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)), v.collection(0, None, unique=True)))
    branch_policy: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    kernel_binding_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))


@attrs.frozen(kw_only=True)
class CompiledMathIndexedEquationsRow:
    """Declared relation row or nested value."""

    indexed_equation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    equation_decl_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    qualified_name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    product_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    filter_node_id: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 18446744073709551615)))
    body_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    sense: e.Sense = attrs.field(validator=attrs.validators.instance_of(e.Sense))
    lower_node_id: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 18446744073709551615)))
    upper_node_id: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 18446744073709551615)))
    residual_quantity_type_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    law_instance_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathIntConstantsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    value: b.int = attrs.field(validator=v.integer_range(-9223372036854775808, 9223372036854775807))


@attrs.frozen(kw_only=True)
class CompiledMathIntegralsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    quadrature_policy_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    bound_index_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    filter_node_id: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 18446744073709551615)))


@attrs.frozen(kw_only=True)
class CompiledMathKernelCallsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    kernel_binding_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    output_ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))


@attrs.frozen(kw_only=True)
class CompiledMathObjectivesRow:
    """Declared relation row or nested value."""

    objective_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    body_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    sense: e.ObjectiveSense = attrs.field(validator=attrs.validators.instance_of(e.ObjectiveSense))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    default_active: b.bool = attrs.field(validator=v.exact_type(b.bool))


@attrs.frozen(kw_only=True)
class CompiledMathPiecewiseLinearFieldBreakpointsItem:
    """Declared relation row or nested value."""

    x: b.float = attrs.field(validator=v.finite_float)
    y: b.float = attrs.field(validator=v.finite_float)


@attrs.frozen(kw_only=True)
class CompiledMathPiecewiseLinearRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    breakpoints: b.tuple[CompiledMathPiecewiseLinearFieldBreakpointsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledMathPiecewiseLinearFieldBreakpointsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    input_quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    output_quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathQuantitySelectionsFieldConversionsItem:
    """Declared relation row or nested value."""

    operand: b.int = attrs.field(validator=v.integer_range(0, 65535))
    conversion_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathQuantitySelectionsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    operation_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    builtin_rule: e.BuiltinQuantityRule | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(e.BuiltinQuantityRule)))
    operand_permutation: b.tuple[b.int, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=v.integer_range(0, 65535), iterable_validator=attrs.validators.instance_of(b.tuple)))
    conversions: b.tuple[CompiledMathQuantitySelectionsFieldConversionsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledMathQuantitySelectionsFieldConversionsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    deferred_static_check: b.bool = attrs.field(validator=v.exact_type(b.bool))


@attrs.frozen(kw_only=True)
class CompiledMathReductionsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    kind: e.ReductionKind = attrs.field(validator=attrs.validators.instance_of(e.ReductionKind))
    domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    bound_index_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    filter_node_id: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 18446744073709551615)))


@attrs.frozen(kw_only=True)
class CompiledMathSmoothOpsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    eps: b.float = attrs.field(validator=v.finite_float)


@attrs.frozen(kw_only=True)
class CompiledMathSymbolRefsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathUnitConvertsRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    scale: b.float = attrs.field(validator=v.finite_float)
    offset: b.float = attrs.field(validator=v.finite_float)
    from_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    to_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMathWeightedMeansFieldPairsItem:
    """Declared relation row or nested value."""

    weight_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    value_node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))


@attrs.frozen(kw_only=True)
class CompiledMathWeightedMeansRow:
    """Declared relation row or nested value."""

    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    pairs: b.tuple[CompiledMathWeightedMeansFieldPairsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledMathWeightedMeansFieldPairsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    normalization: e.WeightNormalization = attrs.field(validator=attrs.validators.instance_of(e.WeightNormalization))
    unit_sum_invariant_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))


@attrs.frozen(kw_only=True)
class CompiledMeshNodesRow:
    """Declared relation row or nested value."""

    node_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    mesh_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 4294967295))
    coordinate: b.float = attrs.field(validator=v.finite_float)
    kind: e.NodeKind = attrs.field(validator=attrs.validators.instance_of(e.NodeKind))


@attrs.frozen(kw_only=True)
class CompiledMeshesRow:
    """Declared relation row or nested value."""

    mesh_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    domain_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    policy_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    node_count: b.int = attrs.field(validator=v.integer_range(0, 4294967295))
    nodes: b.tuple[b.float, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=v.finite_float, iterable_validator=attrs.validators.instance_of(b.tuple)))


@attrs.frozen(kw_only=True)
class CompiledMethodParameterBindingsRow:
    """Declared relation row or nested value."""

    method_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    symbol_decl_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    source_owner: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    parameter_kind: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    source_index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    value: b.float = attrs.field(validator=v.finite_float)
    unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledMethodRealizationsRow:
    """Declared relation row or nested value."""

    requirement_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    method_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    template_instance_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    kernel_binding_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    output_kind: e.MethodOutputKind = attrs.field(validator=attrs.validators.instance_of(e.MethodOutputKind))
    output_symbol_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    kernel_output_ordinal: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledPortMemberGroupsRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    port_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledPredicateMaskMembersRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    value: b.bool = attrs.field(validator=v.exact_type(b.bool))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledPredicateMasksRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    source_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    predicate_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledProblemsRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    model_revision_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    case_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    discretization_policy_ids: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    variable_count: b.int = attrs.field(validator=v.integer_range(0, 9223372036854775807))
    equation_count: b.int = attrs.field(validator=v.integer_range(0, 9223372036854775807))
    inequality_count: b.int = attrs.field(validator=v.integer_range(0, 9223372036854775807))
    objective_count: b.int = attrs.field(validator=v.integer_range(0, 9223372036854775807))
    degrees_of_freedom: b.int = attrs.field(validator=v.integer_range(-9223372036854775808, 9223372036854775807))
    input_bundle_hash: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))


@attrs.frozen(kw_only=True)
class CompiledQuadratureRulesRow:
    """Declared relation row or nested value."""

    rule_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    mesh_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    node_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    weight: b.float = attrs.field(validator=v.finite_float)


@attrs.frozen(kw_only=True)
class CompiledSolvePlansRow:
    """Declared relation row or nested value."""

    plan_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    class_: e.SolvePlanClass = attrs.field(validator=attrs.validators.instance_of(e.SolvePlanClass), metadata={v.FIELD_NAME_METADATA: "class"})
    justification: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    modifiers: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))


@attrs.frozen(kw_only=True)
class CompiledSparsityPatternsRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.SparsityKind = attrs.field(validator=attrs.validators.instance_of(e.SparsityKind))
    row_ptr: b.tuple[b.int, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=v.integer_range(0, 4294967295), iterable_validator=attrs.validators.instance_of(b.tuple)))
    col_idx: b.tuple[b.int, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=v.integer_range(0, 4294967295), iterable_validator=attrs.validators.instance_of(b.tuple)))
    content_hash: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))


@attrs.frozen(kw_only=True)
class CompiledStageBundlesFieldMembersItem:
    """Declared relation row or nested value."""

    port: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    schema_version: b.int = attrs.field(validator=v.integer_range(0, 4294967295))
    logical_hash: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))


@attrs.frozen(kw_only=True)
class CompiledStageBundlesRow:
    """Declared relation row or nested value."""

    bundle_id: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))
    pass_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    pass_version: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    members: b.tuple[CompiledStageBundlesFieldMembersItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(CompiledStageBundlesFieldMembersItem), iterable_validator=attrs.validators.instance_of(b.tuple)))


@attrs.frozen(kw_only=True)
class CompiledStencilsRow:
    """Declared relation row or nested value."""

    stencil_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    mesh_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    derivative_order: b.int = attrs.field(validator=v.integer_range(0, 255))
    scheme: e.DiscretizationScheme = attrs.field(validator=attrs.validators.instance_of(e.DiscretizationScheme))
    node_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    neighbor_node_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    weight: b.float = attrs.field(validator=v.finite_float)


@attrs.frozen(kw_only=True)
class CompiledSymbolExpressionsRow:
    """Declared relation row or nested value."""

    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    node_id: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledSymbolGroupMembersRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    tuple: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledSymbolGroupsRow:
    """Declared relation row or nested value."""

    group_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledSymbolReferencesRow:
    """Declared relation row or nested value."""

    alias_symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    target_symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.AliasKind = attrs.field(validator=attrs.validators.instance_of(e.AliasKind))


@attrs.frozen(kw_only=True)
class CompiledSymbolsRow:
    """Declared relation row or nested value."""

    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    owner_instance_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    symbol_decl_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    qualified_name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    role: e.SymbolRole = attrs.field(validator=attrs.validators.instance_of(e.SymbolRole))
    solver_type: e.SolverVariableType = attrs.field(validator=attrs.validators.instance_of(e.SolverVariableType))
    semantic_role: e.VariableSemanticRole = attrs.field(validator=attrs.validators.instance_of(e.VariableSemanticRole))
    lifecycle: e.VariableLifecycle = attrs.field(validator=attrs.validators.instance_of(e.VariableLifecycle))
    default_lower: v.Bound = attrs.field(validator=attrs.validators.instance_of(v.Bound))
    default_upper: v.Bound = attrs.field(validator=attrs.validators.instance_of(v.Bound))
    default_initial: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class CompiledVariableOrderRow:
    """Declared relation row or nested value."""

    problem_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    position: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 9223372036854775807)))
    treatment: e.Treatment = attrs.field(validator=attrs.validators.instance_of(e.Treatment))
    lower: v.Bound = attrs.field(validator=attrs.validators.instance_of(v.Bound))
    upper: v.Bound = attrs.field(validator=attrs.validators.instance_of(v.Bound))
    initial: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    scale: b.float = attrs.field(validator=v.finite_float)
    offset: b.float = attrs.field(validator=v.finite_float)


@attrs.frozen(kw_only=True)
class CompiledVariableScalesRow:
    """Declared relation row or nested value."""

    symbol_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    scale: b.float = attrs.field(validator=v.finite_float)
    offset: b.float = attrs.field(validator=v.finite_float)
    source: e.ScaleSource = attrs.field(validator=attrs.validators.instance_of(e.ScaleSource))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
