# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Declared entity identities: distinct aliases of their base identity values."""

from typing import NewType

from pse.contracts import values as v

# A scoped engineering output accuracy or decision goal (entity identity `accuracy_goal`).
AccuracyGoalId = NewType("AccuracyGoalId", v.SemanticId)

# One actual scientific attempt of a run, with its immutable generation and observations (entity identity `attempt`).
AttemptId = NewType("AttemptId", v.SemanticId)

# One authored modeling declaration. A specialization root, a definition and a member are declarations in a role, not separate entities (entity identity `declaration`).
DeclarationId = NewType("DeclarationId", v.SemanticId)

# A typed shared engineering allowance rule (entity identity `engineering_rule`).
EngineeringRuleId = NewType("EngineeringRuleId", v.SemanticId)

# An explicitly declared engineering characteristic magnitude (entity identity `engineering_scale`).
EngineeringScaleId = NewType("EngineeringScaleId", v.SemanticId)

# One authored shared-parameter fit over its experiments (entity identity `fit`).
FitId = NewType("FitId", v.SemanticId)

# One instantiated definition instance of a specialized model. A root instance takes its root declaration's identity unless it is a fit experiment, which prepares its case under the experiment's own identity; a nested instance is derived from its parent and member (entity identity `instance`).
InstanceId = NewType("InstanceId", v.SemanticId)

# One authored package (entity identity `package`).
PackageId = NewType("PackageId", v.SemanticId)

# One immutable problem request, whose actual scientific executions are distinct attempts (entity identity `run`).
RunId = NewType("RunId", v.SemanticId)

# One qualified portable scientific seed from an admitted attempt (entity identity `solution`).
SolutionId = NewType("SolutionId", v.SemanticId)

# One retained study coordinating distinct point occurrences (entity identity `study`).
StudyId = NewType("StudyId", v.SemanticId)
