# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Typed rows in the inferred namespace."""

import builtins as b

import attrs

from pse.contracts import enums as e
from pse.contracts import values as v


@attrs.frozen(kw_only=True)
class InferredMethodResolutionsFieldOutcomeResolved:
    """Declared relation row or nested value."""

    method_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class InferredMethodResolutionsFieldOutcome:
    """Declared relation row or nested value."""

    kind: e.ResolutionStatus = attrs.field(validator=attrs.validators.instance_of(e.ResolutionStatus))
    resolved: InferredMethodResolutionsFieldOutcomeResolved | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(InferredMethodResolutionsFieldOutcomeResolved)))

    def __attrs_post_init__(self) -> None:
        if not ((self.kind == "ambiguous" and self.resolved is None) or (self.kind == "resolved" and self.resolved is not None) or (self.kind == "unresolved" and self.resolved is None)):
            message = "tagged value requires exactly its selected arm"
            raise ValueError(message)


@attrs.frozen(kw_only=True)
class InferredMethodResolutionsRow:
    """Declared relation row or nested value."""

    requirement_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    outcome: InferredMethodResolutionsFieldOutcome = attrs.field(validator=attrs.validators.instance_of(InferredMethodResolutionsFieldOutcome))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class InferredPhaseSpeciesRow:
    """Declared relation row or nested value."""

    material_system_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    phase_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    species_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    henry: b.bool = attrs.field(validator=v.exact_type(b.bool))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class InferredPropertyRequirementsRow:
    """Declared relation row or nested value."""

    requirement_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    state_scope_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    property_kind_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    index: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class InferredStateFlashRequiredRow:
    """Declared relation row or nested value."""

    state_instance: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))


@attrs.frozen(kw_only=True)
class InferredValidIndexTuplesRow:
    """Declared relation row or nested value."""

    product_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    tuple: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
