# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""The declared snapshot envelope; logical validity is checked on admission."""

import re
from datetime import datetime
from typing import Annotated, Literal

import msgspec


def _validate_timestamp(value: str) -> None:
    if re.fullmatch(r"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-5][0-9](?:\.[0-9]{1,9})?Z", value) is None:
        message = "timestamp must use the exact UTC RFC3339 wire shape"
        raise ValueError(message)
    datetime.fromisoformat(value)


class ManifestRelationsItemEncodingsItem(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    format: str
    writer_version: str
    encoding_checksum: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]
    bytes: Annotated[int, msgspec.Meta(ge=0)]
    path: str

    def __post_init__(self) -> None:
        if type(self.bytes) is not int or not 0 <= self.bytes <= 18446744073709551615:
            message = "bytes must fit UInt64"
            raise ValueError(message)


class ManifestRelationsItem(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    port: str
    namespace: str
    relation_id: Annotated[str, msgspec.Meta(pattern=r"^[0-9a-f]{32}$")]
    name: str
    version: Annotated[int, msgspec.Meta(ge=0, le=4294967295)]
    logical_hash: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]
    rows: Annotated[int, msgspec.Meta(ge=0)]
    encodings: tuple[ManifestRelationsItemEncodingsItem, ...]

    def __post_init__(self) -> None:
        if type(self.rows) is not int or not 0 <= self.rows <= 18446744073709551615:
            message = "rows must fit UInt64"
            raise ValueError(message)


class ManifestPackagesItem(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    package_id: Annotated[str, msgspec.Meta(pattern=r"^[0-9a-f]{32}$")]
    version: str
    logical_hash: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]


class ManifestAdmissionBinding(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    encoding_checksum: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]


class ManifestCompilerPassesItem(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    pass_id: Annotated[str, msgspec.Meta(pattern=r"^[0-9a-f]{32}$")]
    version: str


class ManifestCompiler(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    version: str
    passes: tuple[ManifestCompilerPassesItem, ...]


class ManifestEngineProfile(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    engine_profile_id: Annotated[str, msgspec.Meta(pattern=r"^[0-9a-f]{32}$")]
    content_hash: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]


class ManifestNumericalPolicy(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    policy_id: Annotated[str, msgspec.Meta(pattern=r"^[0-9a-f]{32}$")]
    content_hash: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]


class ManifestToolchain(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    lockfile_hash: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]
    canonicalization: str


class ManifestKernelsItem(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    kernel_id: Annotated[str, msgspec.Meta(pattern=r"^[0-9a-f]{32}$")]
    version: str
    digest: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]


class ManifestSemanticParentsItem(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    role: str
    snapshot_id: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]


class ManifestEvidenceItem(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    kind: str
    canonical: bool
    encoding_checksum: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]
    codec_version: str
    path: str


class Manifest(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True):
    """Declared manifest object."""

    manifest_version: Literal["pse.manifest.v2"]
    snapshot_kind: str
    snapshot_id: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]
    membership_profile: Literal["pse.snapshot.v2"]
    created_at: str
    schema_registry_fingerprint: Annotated[str, msgspec.Meta(pattern=r"^blake3:[0-9a-f]{64}$")]
    relations: tuple[ManifestRelationsItem, ...]
    packages: tuple[ManifestPackagesItem, ...]
    admission_binding: ManifestAdmissionBinding | None = None
    compiler: ManifestCompiler
    engine_profile: ManifestEngineProfile | None = None
    numerical_policy: ManifestNumericalPolicy | None = None
    toolchain: ManifestToolchain
    kernels: tuple[ManifestKernelsItem, ...]
    semantic_parents: tuple[ManifestSemanticParentsItem, ...]
    evidence: tuple[ManifestEvidenceItem, ...]

    def __post_init__(self) -> None:
        _validate_timestamp(self.created_at)
