# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Typed rows in the provenance namespace."""

import builtins as b
from datetime import datetime

import attrs

from pse.contracts import enums as e
from pse.contracts import values as v


@attrs.frozen(kw_only=True)
class ProvenanceAssertionsRow:
    """Declared relation row or nested value."""

    assertion_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    package_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    expected: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    status: e.AssertionStatus = attrs.field(validator=attrs.validators.instance_of(e.AssertionStatus))
    reason: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))


@attrs.frozen(kw_only=True)
class ProvenanceDerivationsFieldSupportingItem:
    """Declared relation row or nested value."""

    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    row_key: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))


@attrs.frozen(kw_only=True)
class ProvenanceDerivationsRow:
    """Declared relation row or nested value."""

    derivation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    row_key: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    rule_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    pass_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    supporting: b.tuple[ProvenanceDerivationsFieldSupportingItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ProvenanceDerivationsFieldSupportingItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    snapshot_id: v.ContentHash | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.ContentHash)))
    fingerprint: v.ContentHash | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.ContentHash)))


@attrs.frozen(kw_only=True)
class ProvenancePassRecordsFieldPlanEvidenceItem:
    """Declared relation row or nested value."""

    encoding_checksum: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))
    encoding: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    codec_version: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))


@attrs.frozen(kw_only=True)
class ProvenancePassRecordsFieldRulesFiredItem:
    """Declared relation row or nested value."""

    plan_ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    rule_name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))


@attrs.frozen(kw_only=True)
class ProvenancePassRecordsFieldFindingsItem:
    """Declared relation row or nested value."""

    finding_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    subject_snapshot: v.ContentHash | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.ContentHash)))
    run_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    check_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    severity: e.FindingSeverity = attrs.field(validator=attrs.validators.instance_of(e.FindingSeverity))
    subjects: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    values: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    message: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    next_steps: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))


@attrs.frozen(kw_only=True)
class ProvenancePassRecordsRow:
    """Declared relation row or nested value."""

    pass_run_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    pass_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    version: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    snapshot_in: v.ContentHash | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.ContentHash)))
    snapshot_out: v.ContentHash | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.ContentHash)))
    engine_profile_hash: v.ContentHash | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.ContentHash)))
    plan_evidence: b.tuple[ProvenancePassRecordsFieldPlanEvidenceItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ProvenancePassRecordsFieldPlanEvidenceItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    plan_explain: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    rules_fired: b.tuple[ProvenancePassRecordsFieldRulesFiredItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ProvenancePassRecordsFieldRulesFiredItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    duration_ms: b.float = attrs.field(validator=v.finite_float)
    finding_count: b.int = attrs.field(validator=v.integer_range(0, 18446744073709551615))
    status: e.PassStatus = attrs.field(validator=attrs.validators.instance_of(e.PassStatus))
    findings: b.tuple[ProvenancePassRecordsFieldFindingsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ProvenancePassRecordsFieldFindingsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    failure_class: e.FailureClass | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(e.FailureClass)))


@attrs.frozen(kw_only=True)
class ProvenanceRefsRow:
    """Declared relation row or nested value."""

    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    snapshot_id: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))
    manifest_checksum: v.ContentHash = attrs.field(validator=attrs.validators.instance_of(v.ContentHash))
    updated_at: datetime = attrs.field(validator=v.utc_timestamp)
