# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Typed rows in the reference namespace."""

import builtins as b

import attrs

from pse.contracts import enums as e
from pse.contracts import identities as i
from pse.contracts import values as v


@attrs.frozen(kw_only=True)
class ReferenceAlgorithmArgumentsFieldConsumptionColumns:
    """Declared relation row or nested value."""

    names: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.sequence_key(v.scalar_key)(self.names),))


@attrs.frozen(kw_only=True)
class ReferenceAlgorithmArgumentsFieldConsumption:
    """Declared relation row or nested value."""

    kind: e.InputConsumptionKind = attrs.field(validator=attrs.validators.instance_of(e.InputConsumptionKind))
    columns: ReferenceAlgorithmArgumentsFieldConsumptionColumns | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(ReferenceAlgorithmArgumentsFieldConsumptionColumns)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.kind), v.optional_key(v.record_key)(self.columns),))

    def __attrs_post_init__(self) -> None:
        if not ((self.kind == "columns" and self.columns is not None) or (self.kind == "whole" and self.columns is None)):
            message = "tagged value requires exactly its selected arm"
            raise ValueError(message)


@attrs.frozen(kw_only=True)
class ReferenceAlgorithmArgumentsRow:
    """Declared relation row or nested value."""

    algorithm_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    port: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    required: b.bool = attrs.field(validator=v.exact_type(b.bool))
    consumption: ReferenceAlgorithmArgumentsFieldConsumption = attrs.field(validator=attrs.validators.instance_of(ReferenceAlgorithmArgumentsFieldConsumption))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.algorithm_id), v.scalar_key(self.port), v.scalar_key(self.relation_id), v.scalar_key(self.required), v.record_key(self.consumption),))


@attrs.frozen(kw_only=True)
class ReferenceAlgorithmResultsRow:
    """Declared relation row or nested value."""

    algorithm_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    port: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.algorithm_id), v.scalar_key(self.port), v.scalar_key(self.relation_id),))


@attrs.frozen(kw_only=True)
class ReferenceAlgorithmSpecsRow:
    """Declared relation row or nested value."""

    algorithm_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    version: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    preconditions: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    postconditions: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    determinism: e.Determinism = attrs.field(validator=attrs.validators.instance_of(e.Determinism))
    diagnostics: b.tuple[e.FailureClass, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(e.FailureClass), iterable_validator=attrs.validators.instance_of(b.tuple)))
    effects: b.tuple[e.OperationEffect, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(e.OperationEffect), iterable_validator=attrs.validators.instance_of(b.tuple)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.algorithm_id), v.scalar_key(self.name), v.scalar_key(self.version), v.sequence_key(v.scalar_key)(self.preconditions), v.sequence_key(v.scalar_key)(self.postconditions), v.scalar_key(self.determinism), v.sequence_key(v.scalar_key)(self.diagnostics), v.sequence_key(v.scalar_key)(self.effects),))


@attrs.frozen(kw_only=True)
class ReferenceAliasesRow:
    """Declared relation row or nested value."""

    alias_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    entity_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    old_qualified_name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    deprecated_in: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.alias_id), v.scalar_key(self.entity_id), v.scalar_key(self.old_qualified_name), v.scalar_key(self.deprecated_in),))


@attrs.frozen(kw_only=True)
class ReferenceArtifactProfilesRow:
    """Declared relation row or nested value."""

    kind: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    required_relations: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.kind), v.sequence_key(v.scalar_key)(self.required_relations),))


@attrs.frozen(kw_only=True)
class ReferenceBasesRow:
    """Declared relation row or nested value."""

    basis_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.BasisKind = attrs.field(validator=attrs.validators.instance_of(e.BasisKind))
    composition_basis: e.CompositionBasis | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(e.CompositionBasis)))
    rate_basis: e.RateBasis | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(e.RateBasis)))
    reference_conditions_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.basis_id), v.scalar_key(self.kind), v.optional_key(v.scalar_key)(self.composition_basis), v.optional_key(v.scalar_key)(self.rate_basis), v.optional_key(v.scalar_key)(self.reference_conditions_id),))


@attrs.frozen(kw_only=True)
class ReferenceConversionRulesRow:
    """Declared relation row or nested value."""

    conversion_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    from_quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    to_quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.ConversionKind = attrs.field(validator=attrs.validators.instance_of(e.ConversionKind))
    kernel_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    required_parameters: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    scale: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    offset: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.conversion_id), v.scalar_key(self.from_quantity_type_id), v.scalar_key(self.to_quantity_type_id), v.scalar_key(self.kind), v.optional_key(v.scalar_key)(self.kernel_id), v.sequence_key(v.scalar_key)(self.required_parameters), v.optional_key(v.scalar_key)(self.scale), v.optional_key(v.scalar_key)(self.offset),))


@attrs.frozen(kw_only=True)
class ReferenceDimensionsRow:
    """Declared relation row or nested value."""

    ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.ordinal), v.scalar_key(self.name),))


@attrs.frozen(kw_only=True)
class ReferenceEngineProfilesFieldSemanticSettingsItem:
    """Declared relation row or nested value."""

    key: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    value: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.key), v.scalar_key(self.value),))


@attrs.frozen(kw_only=True)
class ReferenceEngineProfilesRow:
    """Declared relation row or nested value."""

    engine_profile_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    datafusion_version: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    arrow_version: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    analyzer_rules: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    optimizer_rules: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    physical_rules: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    semantic_settings: b.tuple[ReferenceEngineProfilesFieldSemanticSettingsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ReferenceEngineProfilesFieldSemanticSettingsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    setting_allow_list_version: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.engine_profile_id), v.scalar_key(self.datafusion_version), v.scalar_key(self.arrow_version), v.sequence_key(v.scalar_key)(self.analyzer_rules), v.sequence_key(v.scalar_key)(self.optimizer_rules), v.sequence_key(v.scalar_key)(self.physical_rules), v.sequence_key(v.record_key)(self.semantic_settings), v.scalar_key(self.setting_allow_list_version),))


@attrs.frozen(kw_only=True)
class ReferenceFunctionCapabilitiesRow:
    """Declared relation row or nested value."""

    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    implementation: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.name), v.scalar_key(self.implementation),))


@attrs.frozen(kw_only=True)
class ReferenceMathContextRow:
    """Declared relation row or nested value."""

    package_id: i.PackageId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    neutral_quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    boolean_kind_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.package_id), v.scalar_key(self.neutral_quantity_type_id), v.scalar_key(self.boolean_kind_id),))


@attrs.frozen(kw_only=True)
class ReferenceQuantityKindsFieldDefinitionMonomialItem:
    """Declared relation row or nested value."""

    quantity_kind_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    num: b.int = attrs.field(validator=v.integer_range(-32768, 32767))
    den: b.int = attrs.field(validator=v.integer_range(-32768, 32767))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.quantity_kind_id), v.scalar_key(self.num), v.scalar_key(self.den),))


@attrs.frozen(kw_only=True)
class ReferenceQuantityKindsFieldDefinition:
    """Declared relation row or nested value."""

    monomial: b.tuple[ReferenceQuantityKindsFieldDefinitionMonomialItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ReferenceQuantityKindsFieldDefinitionMonomialItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    canonical_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    basis_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    reference_state_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    scale_kind: e.ScaleKind = attrs.field(validator=attrs.validators.instance_of(e.ScaleKind))
    subject_kind: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.sequence_key(v.record_key)(self.monomial), v.scalar_key(self.canonical_unit_id), v.optional_key(v.scalar_key)(self.basis_id), v.optional_key(v.scalar_key)(self.reference_state_id), v.scalar_key(self.scale_kind), v.optional_key(v.scalar_key)(self.subject_kind),))


@attrs.frozen(kw_only=True)
class ReferenceQuantityKindsRow:
    """Declared relation row or nested value."""

    quantity_kind_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    dimension: b.tuple[v.DimensionVectorItem, ...] | None = attrs.field(validator=attrs.validators.optional(attrs.validators.and_(attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.DimensionVectorItem), iterable_validator=attrs.validators.instance_of(b.tuple)), attrs.validators.min_len(8), attrs.validators.max_len(8))))
    extensive: b.bool = attrs.field(validator=v.exact_type(b.bool))
    addition_kind: e.QuantityAdditionKind = attrs.field(validator=attrs.validators.instance_of(e.QuantityAdditionKind))
    category: e.QuantityKindCategory | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(e.QuantityKindCategory)))
    definition: ReferenceQuantityKindsFieldDefinition | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(ReferenceQuantityKindsFieldDefinition)))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.quantity_kind_id), v.scalar_key(self.name), v.optional_key(v.sequence_key(v.record_key))(self.dimension), v.scalar_key(self.extensive), v.scalar_key(self.addition_kind), v.optional_key(v.scalar_key)(self.category), v.optional_key(v.record_key)(self.definition), v.scalar_key(self.doc),))


@attrs.frozen(kw_only=True)
class ReferenceQuantityOperationReductionsRow:
    """Declared relation row or nested value."""

    operation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    domain_kind: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.operation_id), v.scalar_key(self.domain_kind),))


@attrs.frozen(kw_only=True)
class ReferenceQuantityOperationsFieldInputConversionsItem:
    """Declared relation row or nested value."""

    operand: b.int = attrs.field(validator=v.integer_range(0, 65535))
    conversion_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.operand), v.scalar_key(self.conversion_id),))


@attrs.frozen(kw_only=True)
class ReferenceQuantityOperationsRow:
    """Declared relation row or nested value."""

    operation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    opcode: e.Opcode = attrs.field(validator=attrs.validators.instance_of(e.Opcode))
    input_kind_ids: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    result_kind_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    basis_rule: e.BasisRule = attrs.field(validator=attrs.validators.instance_of(e.BasisRule))
    reference_rule: e.ReferenceRule = attrs.field(validator=attrs.validators.instance_of(e.ReferenceRule))
    scale_rule: e.QuantityScaleRule = attrs.field(validator=attrs.validators.instance_of(e.QuantityScaleRule))
    shape_rule: e.QuantityShapeRule = attrs.field(validator=attrs.validators.instance_of(e.QuantityShapeRule))
    basis_source: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    reference_source: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    scale_source: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    shape_source: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    subject_rule: e.SubjectRule = attrs.field(validator=attrs.validators.instance_of(e.SubjectRule))
    subject_source: b.int | None = attrs.field(validator=attrs.validators.optional(v.integer_range(0, 65535)))
    result_subject_kind: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    result_basis_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    result_reference_state_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    input_conversions: b.tuple[ReferenceQuantityOperationsFieldInputConversionsItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ReferenceQuantityOperationsFieldInputConversionsItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    precondition_invariant_ids: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.operation_id), v.scalar_key(self.opcode), v.sequence_key(v.scalar_key)(self.input_kind_ids), v.scalar_key(self.result_kind_id), v.scalar_key(self.basis_rule), v.scalar_key(self.reference_rule), v.scalar_key(self.scale_rule), v.scalar_key(self.shape_rule), v.optional_key(v.scalar_key)(self.basis_source), v.optional_key(v.scalar_key)(self.reference_source), v.optional_key(v.scalar_key)(self.scale_source), v.optional_key(v.scalar_key)(self.shape_source), v.scalar_key(self.subject_rule), v.optional_key(v.scalar_key)(self.subject_source), v.optional_key(v.scalar_key)(self.result_subject_kind), v.optional_key(v.scalar_key)(self.result_basis_id), v.optional_key(v.scalar_key)(self.result_reference_state_id), v.sequence_key(v.record_key)(self.input_conversions), v.sequence_key(v.scalar_key)(self.precondition_invariant_ids),))


@attrs.frozen(kw_only=True)
class ReferenceQuantityPreconditionsRow:
    """Declared relation row or nested value."""

    invariant_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.QuantityPreconditionKind = attrs.field(validator=attrs.validators.instance_of(e.QuantityPreconditionKind))
    operand_positions: b.tuple[b.int, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=v.integer_range(0, 65535), iterable_validator=attrs.validators.instance_of(b.tuple)))
    required_basis_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    required_quantity_type_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    match_shape: b.bool | None = attrs.field(validator=attrs.validators.optional(v.exact_type(b.bool)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.invariant_id), v.scalar_key(self.kind), v.sequence_key(v.scalar_key)(self.operand_positions), v.optional_key(v.scalar_key)(self.required_basis_id), v.optional_key(v.scalar_key)(self.required_quantity_type_id), v.optional_key(v.scalar_key)(self.match_shape),))


@attrs.frozen(kw_only=True)
class ReferenceQuantityTypesRow:
    """Declared relation row or nested value."""

    quantity_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))
    quantity_kind_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    basis_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    reference_state_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    scale_kind: e.ScaleKind = attrs.field(validator=attrs.validators.instance_of(e.ScaleKind))
    shape: b.tuple[v.SemanticId, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.SemanticId), iterable_validator=attrs.validators.instance_of(b.tuple)))
    subject_kind: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    canonical_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    nominal_magnitude: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.quantity_type_id), v.optional_key(v.scalar_key)(self.name), v.scalar_key(self.quantity_kind_id), v.optional_key(v.scalar_key)(self.basis_id), v.optional_key(v.scalar_key)(self.reference_state_id), v.scalar_key(self.scale_kind), v.sequence_key(v.scalar_key)(self.shape), v.optional_key(v.scalar_key)(self.subject_kind), v.scalar_key(self.canonical_unit_id), v.optional_key(v.scalar_key)(self.nominal_magnitude), v.scalar_key(self.doc),))


@attrs.frozen(kw_only=True)
class ReferenceReferenceStatesRow:
    """Declared relation row or nested value."""

    reference_state_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    kind: e.ReferenceStateKind = attrs.field(validator=attrs.validators.instance_of(e.ReferenceStateKind))
    temperature: v.QuantityValue | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.QuantityValue)))
    pressure: v.QuantityValue | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.QuantityValue)))
    include_enthalpy_of_formation: b.bool = attrs.field(validator=v.exact_type(b.bool))
    subject_id: i.DeclarationId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.reference_state_id), v.scalar_key(self.name), v.scalar_key(self.kind), v.optional_key(v.record_key)(self.temperature), v.optional_key(v.record_key)(self.pressure), v.scalar_key(self.include_enthalpy_of_formation), v.optional_key(v.scalar_key)(self.subject_id), v.scalar_key(self.doc),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaColumnsRow:
    """Declared relation row or nested value."""

    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    logical_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    nullable: b.bool = attrs.field(validator=v.exact_type(b.bool))
    quantity_type_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    fk_relation_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    fk_column: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))
    role: e.ColumnRole = attrs.field(validator=attrs.validators.instance_of(e.ColumnRole))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    native_field: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    identity_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.relation_id), v.scalar_key(self.ordinal), v.scalar_key(self.name), v.scalar_key(self.logical_type_id), v.scalar_key(self.nullable), v.optional_key(v.scalar_key)(self.quantity_type_id), v.optional_key(v.scalar_key)(self.fk_relation_id), v.optional_key(v.scalar_key)(self.fk_column), v.scalar_key(self.role), v.scalar_key(self.doc), v.scalar_key(self.native_field), v.optional_key(v.scalar_key)(self.identity_id),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaDocumentSectionsRow:
    """Declared relation row or nested value."""

    document_name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    ordinal: b.int = attrs.field(validator=v.integer_range(0, 4294967295))
    key: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    repeated: b.bool = attrs.field(validator=v.exact_type(b.bool))
    identity_column: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))
    entity_kind: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))
    name_column: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))
    naming_scope_column: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.document_name), v.scalar_key(self.ordinal), v.scalar_key(self.key), v.scalar_key(self.relation_id), v.scalar_key(self.repeated), v.optional_key(v.scalar_key)(self.identity_column), v.optional_key(v.scalar_key)(self.entity_kind), v.optional_key(v.scalar_key)(self.name_column), v.optional_key(v.scalar_key)(self.naming_scope_column), v.scalar_key(self.doc),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaDocumentsRow:
    """Declared relation row or nested value."""

    document_name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    kind: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    path_glob: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.document_name), v.scalar_key(self.kind), v.scalar_key(self.path_glob), v.scalar_key(self.doc),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaEnumTypesRow:
    """Declared relation row or nested value."""

    enum_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    idaes_source: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.enum_id), v.scalar_key(self.name), v.optional_key(v.scalar_key)(self.idaes_source),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaEnumsRow:
    """Declared relation row or nested value."""

    enum_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    member_ordinal: b.int = attrs.field(validator=v.integer_range(0, 65535))
    member: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    idaes_name: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))
    deprecated: b.bool = attrs.field(validator=v.exact_type(b.bool))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.enum_id), v.scalar_key(self.member_ordinal), v.scalar_key(self.member), v.optional_key(v.scalar_key)(self.idaes_name), v.scalar_key(self.deprecated), v.scalar_key(self.doc),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaIdentitiesRow:
    """Declared relation row or nested value."""

    identity_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    base_logical_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    owner_relation_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    owner_column: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.identity_id), v.scalar_key(self.name), v.scalar_key(self.doc), v.scalar_key(self.base_logical_type_id), v.optional_key(v.scalar_key)(self.owner_relation_id), v.optional_key(v.scalar_key)(self.owner_column),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaInvariantsRow:
    """Declared relation row or nested value."""

    invariant_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    kind: e.InvariantKind = attrs.field(validator=attrs.validators.instance_of(e.InvariantKind))
    query: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    inputs: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    key_columns: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    severity: e.Severity = attrs.field(validator=attrs.validators.instance_of(e.Severity))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.invariant_id), v.scalar_key(self.relation_id), v.scalar_key(self.kind), v.scalar_key(self.query), v.sequence_key(v.scalar_key)(self.inputs), v.sequence_key(v.scalar_key)(self.key_columns), v.scalar_key(self.severity), v.scalar_key(self.doc),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaLogicalTypesRow:
    """Declared relation row or nested value."""

    logical_type_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    arrow_storage: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    extension_name: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))
    metadata_schema: b.str | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(b.str)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.logical_type_id), v.scalar_key(self.name), v.scalar_key(self.arrow_storage), v.optional_key(v.scalar_key)(self.extension_name), v.optional_key(v.scalar_key)(self.metadata_schema),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaMigrationsRow:
    """Declared relation row or nested value."""

    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    from_version: b.int = attrs.field(validator=v.integer_range(0, 4294967295))
    to_version: b.int = attrs.field(validator=v.integer_range(0, 4294967295))
    plan_spec: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.relation_id), v.scalar_key(self.from_version), v.scalar_key(self.to_version), v.scalar_key(self.plan_spec), v.scalar_key(self.doc),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaRelationsFieldChecksItem:
    """Declared relation row or nested value."""

    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    sql: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.name), v.scalar_key(self.sql),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaRelationsFieldUniqueKeysItem:
    """Declared relation row or nested value."""

    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    columns: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.name), v.sequence_key(v.scalar_key)(self.columns),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaRelationsFieldForeignKeysItem:
    """Declared relation row or nested value."""

    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    columns: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    target_relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    target_columns: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.name), v.sequence_key(v.scalar_key)(self.columns), v.scalar_key(self.target_relation_id), v.sequence_key(v.scalar_key)(self.target_columns),))


@attrs.frozen(kw_only=True)
class ReferenceSchemaRelationsRow:
    """Declared relation row or nested value."""

    relation_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    namespace: e.Namespace = attrs.field(validator=attrs.validators.instance_of(e.Namespace))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    version: b.int = attrs.field(validator=v.integer_range(0, 4294967295))
    authority: e.Authority = attrs.field(validator=attrs.validators.instance_of(e.Authority))
    snapshot_class: e.SnapshotClass = attrs.field(validator=attrs.validators.instance_of(e.SnapshotClass))
    primary_key: b.tuple[b.str, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(b.str), iterable_validator=attrs.validators.instance_of(b.tuple)))
    derivation_granularity: e.DerivationGranularity | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(e.DerivationGranularity)))
    stability: e.Stability = attrs.field(validator=attrs.validators.instance_of(e.Stability))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    checks: b.tuple[ReferenceSchemaRelationsFieldChecksItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ReferenceSchemaRelationsFieldChecksItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    unique_keys: b.tuple[ReferenceSchemaRelationsFieldUniqueKeysItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ReferenceSchemaRelationsFieldUniqueKeysItem), iterable_validator=attrs.validators.instance_of(b.tuple)))
    foreign_keys: b.tuple[ReferenceSchemaRelationsFieldForeignKeysItem, ...] = attrs.field(validator=attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ReferenceSchemaRelationsFieldForeignKeysItem), iterable_validator=attrs.validators.instance_of(b.tuple)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.relation_id), v.scalar_key(self.namespace), v.scalar_key(self.name), v.scalar_key(self.version), v.scalar_key(self.authority), v.scalar_key(self.snapshot_class), v.sequence_key(v.scalar_key)(self.primary_key), v.optional_key(v.scalar_key)(self.derivation_granularity), v.scalar_key(self.stability), v.scalar_key(self.doc), v.sequence_key(v.record_key)(self.checks), v.sequence_key(v.record_key)(self.unique_keys), v.sequence_key(v.record_key)(self.foreign_keys),))


@attrs.frozen(kw_only=True)
class ReferenceUnitSetsRow:
    """Declared relation row or nested value."""

    unit_set_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    time_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    length_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    mass_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    amount_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    temperature_unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    current_unit_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    luminous_intensity_unit_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    currency_unit_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.unit_set_id), v.scalar_key(self.name), v.scalar_key(self.time_unit_id), v.scalar_key(self.length_unit_id), v.scalar_key(self.mass_unit_id), v.scalar_key(self.amount_unit_id), v.scalar_key(self.temperature_unit_id), v.optional_key(v.scalar_key)(self.current_unit_id), v.optional_key(v.scalar_key)(self.luminous_intensity_unit_id), v.optional_key(v.scalar_key)(self.currency_unit_id),))


@attrs.frozen(kw_only=True)
class ReferenceUnitsFieldDefinitionItem:
    """Declared relation row or nested value."""

    unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    num: b.int = attrs.field(validator=v.integer_range(-32768, 32767))
    den: b.int = attrs.field(validator=v.integer_range(-32768, 32767))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.unit_id), v.scalar_key(self.num), v.scalar_key(self.den),))


@attrs.frozen(kw_only=True)
class ReferenceUnitsRow:
    """Declared relation row or nested value."""

    unit_id: v.SemanticId = attrs.field(validator=attrs.validators.instance_of(v.SemanticId))
    symbol: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    name: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    dimension: b.tuple[v.DimensionVectorItem, ...] | None = attrs.field(validator=attrs.validators.optional(attrs.validators.and_(attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(v.DimensionVectorItem), iterable_validator=attrs.validators.instance_of(b.tuple)), attrs.validators.min_len(8), attrs.validators.max_len(8))))
    scale_to_canonical: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    offset_to_canonical: b.float | None = attrs.field(validator=attrs.validators.optional(v.finite_float))
    is_affine: b.bool | None = attrs.field(validator=attrs.validators.optional(v.exact_type(b.bool)))
    reference_state_id: v.SemanticId | None = attrs.field(validator=attrs.validators.optional(attrs.validators.instance_of(v.SemanticId)))
    definition: b.tuple[ReferenceUnitsFieldDefinitionItem, ...] | None = attrs.field(validator=attrs.validators.optional(attrs.validators.deep_iterable(member_validator=attrs.validators.instance_of(ReferenceUnitsFieldDefinitionItem), iterable_validator=attrs.validators.instance_of(b.tuple))))
    system: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))
    doc: b.str = attrs.field(validator=attrs.validators.instance_of(b.str))

    def _pse_equality_key(self) -> v.EqualityKey:
        return (type(self), (v.scalar_key(self.unit_id), v.scalar_key(self.symbol), v.scalar_key(self.name), v.optional_key(v.sequence_key(v.record_key))(self.dimension), v.optional_key(v.scalar_key)(self.scale_to_canonical), v.optional_key(v.scalar_key)(self.offset_to_canonical), v.optional_key(v.scalar_key)(self.is_affine), v.optional_key(v.scalar_key)(self.reference_state_id), v.optional_key(v.sequence_key(v.record_key))(self.definition), v.scalar_key(self.system), v.scalar_key(self.doc),))
