# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# @generated by pse-schema; do not edit
"""Validated Python scalar identities and mechanical field validators."""

import builtins as b
import math
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Never, Self

import attrs

from pse.contracts import enums as e

# Exact source field spelling for attributes escaped by the Python generator.
FIELD_NAME_METADATA = "pse.field_name"


def _reject(message: str) -> Never:
    raise ValueError(message)


class SemanticId(bytes):
    """Exactly sixteen identity bytes, with an explicit hexadecimal text codec."""

    def __new__(cls, value: bytes) -> Self:
        if not isinstance(value, bytes) or len(value) != 16:
            _reject("semantic identity requires exactly 16 bytes")
        return super().__new__(cls, value)

    @classmethod
    def from_hex(cls, value: str) -> Self:
        if len(value) != 32 or any(char not in "0123456789abcdef" for char in value):
            _reject("semantic identity requires 32 lowercase hexadecimal characters")
        return cls(bytes.fromhex(value))


class ContentHash(bytes):
    """Exactly thirty-two digest bytes; no validity assertion is implied."""

    def __new__(cls, value: bytes) -> Self:
        if not isinstance(value, bytes) or len(value) != 32:
            _reject("content digest requires exactly 32 bytes")
        return super().__new__(cls, value)

    @classmethod
    def from_prefixed(cls, value: str) -> Self:
        if not value.startswith("blake3:") or len(value) != 71:
            _reject("content digest requires blake3: and 64 hexadecimal characters")
        digits = value[7:]
        if any(char not in "0123456789abcdef" for char in digits):
            _reject("content digest requires lowercase hexadecimal characters")
        return cls(bytes.fromhex(digits))

    def to_prefixed(self) -> str:
        return f"blake3:{self.hex()}"


# These validators inspect only the value. Accept the unused callback context as
# object; attrs.Attribute is generic in type stubs, but not at runtime on Python 3.13.
def exact_type(expected: type[object]) -> Callable[[object, object, object], None]:
    def validate(_instance: object, _attribute: object, value: object) -> None:
        if type(value) is not expected:
            _reject(f"expected exact type {expected.__name__}")

    return validate


def integer_range(lower: int, upper: int) -> Callable[[object, object, object], None]:
    def validate(_instance: object, _attribute: object, value: object) -> None:
        if type(value) is not int or not lower <= value <= upper:
            _reject(f"integer must be in [{lower}, {upper}]")

    return validate


def collection(minimum: int, maximum: int | None, *, unique: bool) -> Callable[[object, object, object], None]:
    """Validate visible collection cardinality and declared member uniqueness."""
    def validate(_instance: object, _attribute: object, value: object) -> None:
        if not isinstance(value, tuple):
            _reject("collection requires a tuple")
        if len(value) < minimum or (maximum is not None and len(value) > maximum):
            _reject("collection violates cardinality")
        if unique and any(item in value[:index] for index, item in enumerate(value)):
            _reject("collection violates uniqueness")
    return validate


def finite_float(_instance: object, _attribute: object, value: object) -> None:
    if type(value) is not float or not math.isfinite(value):
        _reject("expected a finite Float64 value")


def utc_timestamp(_instance: object, _attribute: object, value: object) -> None:
    if not isinstance(value, datetime) or value.tzinfo is None or value.utcoffset() != UTC.utcoffset(None):
        _reject("timestamp must be an aware UTC datetime")


@attrs.frozen(kw_only=True)
class DimensionVectorItem:
    """Declared relation row or nested value."""

    num: b.int = attrs.field(validator=integer_range(-32768, 32767))
    den: b.int = attrs.field(validator=integer_range(-32768, 32767))


@attrs.frozen(kw_only=True)
class QuantityValue:
    """Declared relation row or nested value."""

    value: b.float = attrs.field(validator=finite_float)
    quantity_type_id: SemanticId = attrs.field(validator=attrs.validators.instance_of(SemanticId))
    unit_id: SemanticId = attrs.field(validator=attrs.validators.instance_of(SemanticId))


@attrs.frozen(kw_only=True)
class Bound:
    """Declared relation row or nested value."""

    kind: e.BoundKind = attrs.field(validator=attrs.validators.instance_of(e.BoundKind))
    value: b.float | None = attrs.field(validator=attrs.validators.optional(finite_float))


@attrs.frozen(kw_only=True)
class SourceSpan:
    """Declared relation row or nested value."""

    document_id: SemanticId = attrs.field(validator=attrs.validators.instance_of(SemanticId))
    start: b.int = attrs.field(validator=integer_range(0, 4294967295))
    end: b.int = attrs.field(validator=integer_range(0, 4294967295))
