# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# Upstream parity targets; the authored enum is the member-name authority.

[enums.BlowerMaterial]
module = "idaes.models.costing.SSLW"

[enums.BlowerType]
module = "idaes.models.costing.SSLW"

[enums.ComponentType]
module = "idaes.core.base.components"

[enums.CompressorDriveType]
module = "idaes.models.costing.SSLW"

[enums.CompressorMaterial]
module = "idaes.models.costing.SSLW"

[enums.CompressorType]
module = "idaes.models.costing.SSLW"

[enums.ConcentrationForm]
module = "idaes.models.properties.modular_properties.base.utility"

[enums.ControllerAntiwindupType]
module = "idaes.models.control.controller"

[enums.ControllerMVBoundType]
module = "idaes.models.control.controller"

[enums.ControllerType]
module = "idaes.models.control.controller"

[enums.CubicType]
module = "idaes.models.properties.modular_properties.eos.ceos_common"

[enums.DaeVarTypes]
module = "idaes.core.solvers.petsc"

[enums.DefaultScalingRecommendation]
module = "idaes.core.scaling.custom_scaler_base"

[enums.DiscretizationScheme]
module = "pyomo.dae"
aliases = {LAGRANGE_RADAU = "LAGRANGE-RADAU", LAGRANGE_LEGENDRE = "LAGRANGE-LEGENDRE"}

[enums.DistributedVars]
module = "idaes.core.base.control_volume1d"

[enums.EnergyBalanceType]
module = "idaes.core.base.control_volume_base"

[enums.EnergySplittingType]
module = "idaes.models.unit_models.separator"

[enums.FanMaterial]
module = "idaes.models.costing.SSLW"

[enums.FanType]
module = "idaes.models.costing.SSLW"

[enums.FlashType]
module = "idaes.models.unit_models.feed_flash"

[enums.FlowDirection]
module = "idaes.core.base.control_volume_base"

[enums.HXMaterial]
module = "idaes.models.costing.SSLW"

[enums.HXTubeLength]
module = "idaes.models.costing.SSLW"

[enums.HXType]
module = "idaes.models.costing.SSLW"

[enums.HeatExchangerFlowPattern]
module = "idaes.models.unit_models.heat_exchanger"

[enums.HeaterMaterial]
module = "idaes.models.costing.SSLW"

[enums.HeaterSource]
module = "idaes.models.costing.SSLW"

[enums.HenryType]
module = "idaes.models.properties.modular_properties.phase_equil.henry"

[enums.InitializationStatus]
module = "idaes.core.initialization.initializer_base"

[enums.MaterialBalanceType]
module = "idaes.core.base.control_volume_base"

[enums.MaterialFlowBasis]
module = "idaes.core.base.process_base"

[enums.MixingType]
module = "idaes.models.unit_models.mixer"

[enums.MomentumBalanceType]
module = "idaes.core.base.control_volume_base"

[enums.MomentumMixingType]
module = "idaes.models.unit_models.mixer"

[enums.PhaseType]
module = "idaes.core.base.phases"

[enums.PumpMaterial]
module = "idaes.models.costing.SSLW"

[enums.PumpMotorType]
module = "idaes.models.costing.SSLW"

[enums.PumpType]
module = "idaes.models.costing.SSLW"

[enums.SplittingType]
module = "idaes.models.unit_models.separator"

[enums.StateIndex]
module = "idaes.models.properties.modular_properties.base.utility"

[enums.ThermodynamicAssumption]
module = "idaes.models.unit_models.pressure_changer"

[enums.TrayMaterial]
module = "idaes.models.costing.SSLW"

[enums.TrayType]
module = "idaes.models.costing.SSLW"

[enums.ValveFunctionType]
module = "idaes.models.unit_models.valve"

[enums.VesselMaterial]
module = "idaes.models.costing.SSLW"
