// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

#![allow(
    clippy::print_stdout,
    reason = "a build script talks to cargo on stdout"
)]

//! Link directives for the Ipopt C API. This build script never generates bindings:
//! `crates/pse-ipopt-sys/src/bindings.rs` is committed and regenerated by
//! `cargo xtask codegen --only bindgen` inside the solver container (blueprint §3.1,
//! plan §4).

use sha2::{Digest, Sha256};
use std::env;
use std::error::Error;
use std::fs;
use std::path::Path;

/// Minimum Ipopt supported by the platform: current-iterate and violation APIs
/// arrived in 3.14; resetting per-attempt TNLP restart options requires 3.14.2.
const MIN_VERSION: &str = "3.14.2";

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-env-changed=IPOPT_DIR");
    println!("cargo:rerun-if-env-changed=PKG_CONFIG_PATH");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=bridge/pse_ipopt_sequence.cpp");
    println!("cargo:rerun-if-changed=bridge/pse_ipopt_sequence.h");

    if env::var_os("CARGO_FEATURE_LINK").is_none() {
        // Compile-only shell; see the `link` feature comment in Cargo.toml.
        return Ok(());
    }

    let version = if let Some(dir) = env::var_os("IPOPT_DIR") {
        let dir = Path::new(&dir);
        println!("cargo:rustc-link-search=native={}/lib", dir.display());
        println!("cargo:rustc-link-lib=dylib=ipopt");
        let pc = dir.join("lib/pkgconfig/ipopt.pc");
        println!("cargo:rerun-if-changed={}", pc.display());
        version_from_pc(&pc)?
    } else {
        let lib = pkg_config::Config::new()
            .atleast_version(MIN_VERSION)
            .probe("ipopt")
            .map_err(|err| help(&err.to_string()))?;
        lib.version
    };

    println!("cargo:version={version}");
    let mut sequence_identity = Sha256::new();
    sequence_identity.update(version.as_bytes());
    for source in [
        "bridge/pse_ipopt_sequence.cpp",
        "bridge/pse_ipopt_sequence.h",
    ] {
        sequence_identity.update(fs::read(source)?);
    }
    let sequence_identity: String = sequence_identity
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect();
    println!("cargo:rustc-env=PSE_IPOPT_SEQUENCE_BUILD_ID={sequence_identity}");
    let mut sequence = cc::Build::new();
    sequence
        .cpp(true)
        .std("c++17")
        .file("bridge/pse_ipopt_sequence.cpp")
        .flag("-ffp-contract=off")
        .flag("-fno-fast-math");
    if let Some(prefix) = env::var_os("IPOPT_DIR") {
        sequence.include(Path::new(&prefix).join("include/coin-or"));
    } else {
        for include in pkg_config::Config::new()
            .atleast_version(MIN_VERSION)
            .probe("ipopt")?
            .include_paths
        {
            sequence.include(include);
        }
    }
    sequence.try_compile("pse_ipopt_sequence")?;
    println!("cargo:rustc-link-lib=stdc++");
    Ok(())
}

/// Reads `Version:` out of an `ipopt.pc`. `IPOPT_DIR` is trusted for the link path but
/// not for the version: `probe_host` reports what the `.pc` says.
fn version_from_pc(pc: &Path) -> Result<String, Box<dyn Error>> {
    let text = fs::read_to_string(pc).map_err(|err| -> Box<dyn Error> {
        help(&format!(
            "IPOPT_DIR is set but {} is unreadable: {err}",
            pc.display()
        ))
        .into()
    })?;
    text.lines()
        .find_map(|line| line.strip_prefix("Version:"))
        .map(|v| v.trim().to_owned())
        .ok_or_else(|| help(&format!("{} has no `Version:` field", pc.display())).into())
}

/// Every failure path ends here: a build error that names the three supported ways to get
/// a new enough Ipopt instead of leaving the reader with a bare pkg-config message.
fn help(detail: &str) -> BuildError {
    BuildError(format!(
        "pse-ipopt-sys: Ipopt >= {MIN_VERSION} was not found.

{detail}

The `ipopt` feature is off by default, so something turned it on. Provide the library in
one of these ways, then re-run:

  * the pinned solver container (the supported path; it exports IPOPT_DIR,
    PKG_CONFIG_PATH and LD_LIBRARY_PATH already):
        docker build -t pse-solvers docker/solvers
        docker run --rm -it -v \"$PWD:/w\" -w /w pse-solvers
  * macOS:         brew install ipopt
  * conda / pixi:  conda install -c conda-forge 'ipopt>=3.14.2'
  * a manual build: set IPOPT_DIR=<prefix> so that
    $IPOPT_DIR/lib/pkgconfig/ipopt.pc exists.

A system Ipopt on the 3.11 line (Debian/Ubuntu `coinor-libipopt-dev`) is NOT enough: the
iterate and violation APIs of blueprint §18.3 arrived in 3.14; per-attempt
restart-option reset requires OptionsList::UnsetValue from 3.14.2."
    ))
}

/// A build failure whose `Debug` rendering is its message.
///
/// `main`'s `Termination` prints the `Debug` form of the error, and the derived `Debug` of
/// a boxed string escapes every newline — which would collapse the guidance above into one
/// unreadable line. This is the whole reason the type exists.
struct BuildError(String);

impl std::fmt::Display for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::fmt::Debug for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl Error for BuildError {}
