# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse

"""The residue report: what the surveys say a mapping loses, and what has no disposition.

The report is generated from the surveys and the dispositions alone and carries nothing that
varies between runs, so regenerating it from the same inputs is byte-identical.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field

from thermo_knowledge.survey_index import structs as st
from thermo_knowledge.survey_index.dispositions import (
    DISPOSITION_DIR,
    KINDS,
    MODEL_CHANGE,
    Disposition,
    is_scheduled,
    needs_disposition,
)
from thermo_knowledge.survey_index.loader import SURVEY_DIR

REPORT_RELATIVE = f"{SURVEY_DIR}/residue-report.md"
"""The generated report, relative to the tree."""

_HEADER = (
    f"<!-- @generated by `tk survey --report` from {SURVEY_DIR}/*.toml and "
    f"{DISPOSITION_DIR}/*.toml; do not edit -->"
)


@dataclass(frozen=True)
class SourceResidue:
    """The counts of one source."""

    source: str
    total: int
    by_precision: dict[str, int]
    needing: int
    by_kind: dict[str, int]
    undispositioned: tuple[st.Construct, ...]
    model_changes: tuple[tuple[st.Construct, Disposition], ...] = field(default=())


def residue(
    surveys: dict[str, st.Survey], dispositions: dict[str, dict[str, Disposition]]
) -> list[SourceResidue]:
    """The counts of every source, by source id."""
    rows: list[SourceResidue] = []
    for source in sorted(surveys):
        constructs = surveys[source].construct
        recorded = dispositions.get(source, {})
        precision = Counter(item.precision for item in constructs)
        kinds: Counter[str] = Counter()
        open_items: list[st.Construct] = []
        changes: list[tuple[st.Construct, Disposition]] = []
        needing = 0
        for construct in constructs:
            if not needs_disposition(construct):
                continue
            needing += 1
            disposition = recorded.get(construct.name)
            if disposition is None:
                open_items.append(construct)
                continue
            kinds[disposition.disposition] += 1
            if disposition.disposition == MODEL_CHANGE:
                changes.append((construct, disposition))
        rows.append(
            SourceResidue(
                source=source,
                total=len(constructs),
                by_precision={name: precision.get(name, 0) for name in st.PRECISIONS},
                needing=needing,
                by_kind={name: kinds.get(name, 0) for name in KINDS},
                undispositioned=tuple(open_items),
                model_changes=tuple(changes),
            )
        )
    return rows


def undispositioned_total(rows: list[SourceResidue]) -> int:
    return sum(len(row.undispositioned) for row in rows)


def _one_line(text: str) -> str:
    return " ".join(text.split())


def _cell(text: str) -> str:
    return _one_line(text).replace("|", "\\|")


def _counts_line(row: SourceResidue) -> list[str]:
    return [
        str(row.total),
        *(str(row.by_precision[name]) for name in st.PRECISIONS),
        str(row.needing),
        *(str(row.by_kind[name]) for name in KINDS),
        str(len(row.undispositioned)),
    ]


def _table_header() -> list[str]:
    columns = [
        "constructs",
        *st.PRECISIONS,
        "need a disposition",
        *KINDS,
        "undispositioned",
    ]
    return [
        "| source | " + " | ".join(columns) + " |",
        "|---|" + "---:|" * len(columns),
    ]


def summary_lines(rows: list[SourceResidue]) -> list[str]:
    """The totals across sources, for the terminal."""
    total = sum(row.total for row in rows)
    needing = sum(row.needing for row in rows)
    open_items = undispositioned_total(rows)
    precision = {name: sum(row.by_precision[name] for row in rows) for name in st.PRECISIONS}
    kinds = {name: sum(row.by_kind[name] for row in rows) for name in KINDS}
    return [
        f"sources: {len(rows)}",
        f"constructs: {total} ("
        + ", ".join(f"{name} {precision[name]}" for name in st.PRECISIONS)
        + ")",
        f"need a disposition: {needing}",
        "dispositioned: "
        + ", ".join(f"{name} {kinds[name]}" for name in KINDS)
        + f" (total {sum(kinds.values())})",
        f"undispositioned: {open_items}",
    ]


def render_report(
    rows: list[SourceResidue], *, survey_files: int, disposition_files: int
) -> str:
    """The report text (UTF-8, LF line ends, ending in one newline)."""
    out: list[str] = [_HEADER, "", "# Survey residue report", ""]
    out.append(
        f"Generated by `tk survey --report` from {survey_files} survey files "
        f"(`{SURVEY_DIR}/*.toml`) and {disposition_files} disposition files "
        f"(`{DISPOSITION_DIR}/*.toml`). Regenerate it; never edit it. The format and the rule "
        "for which constructs need a disposition are in `docs/survey.md` (section 4): a "
        "construct needs one when its `precision` is not `exact`, or its `loss` is non-empty "
        "and not a bare \"none\"."
    )
    out.append("")
    out += ["## Per source", ""]
    out += _table_header()
    for row in rows:
        out.append(f"| {row.source} | " + " | ".join(_counts_line(row)) + " |")
    out.append("")
    out += ["## Totals", ""]
    out += [f"- {line}" for line in summary_lines(rows)]
    out.append("")
    out += _model_change_section(rows)
    out += ["## Undispositioned constructs", ""]
    open_total = undispositioned_total(rows)
    if open_total == 0:
        out += ["Every construct that needs a disposition has one.", ""]
    else:
        out += [
            f"{open_total} constructs need a disposition and have none, grouped by source, in "
            "the order the survey lists them.",
            "",
        ]
        for row in rows:
            if not row.undispositioned:
                continue
            out += [f"### {row.source} ({len(row.undispositioned)})", ""]
            for construct in row.undispositioned:
                loss = _one_line(construct.loss) or "(no loss stated)"
                out.append(f"- `{construct.precision}` {_one_line(construct.name)}: {loss}")
            out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def _model_change_section(rows: list[SourceResidue]) -> list[str]:
    out = ["## Model changes by ref", ""]
    grouped: dict[str, list[tuple[str, st.Construct, Disposition]]] = {}
    for row in rows:
        for construct, disposition in row.model_changes:
            grouped.setdefault(disposition.ref, []).append((row.source, construct, disposition))
    if not grouped:
        return [*out, "No construct is dispositioned as `model_change`.", ""]
    out += [
        "Each `model_change` disposition, grouped by the `ref` that holds it: the alignment item "
        "or finding that schedules the change, or what else it names. Sorted by constructs, most "
        "first.",
        "",
        "| ref | constructs | sources |",
        "|---|---:|---|",
    ]
    for ref, items in sorted(grouped.items(), key=lambda entry: (-len(entry[1]), entry[0])):
        sources = sorted({source for source, _, _ in items})
        out.append(f"| {_cell(ref)} | {len(items)} | {', '.join(sources)} |")
    out.append("")
    unscheduled = [
        (ref, item) for ref, items in sorted(grouped.items()) if not is_scheduled(ref)
        for item in items
    ]
    out += ["### Model changes that name no scheduled change", ""]
    if not unscheduled:
        out += ["Every `model_change` names an alignment item or a review finding.", ""]
    else:
        out += [
            "These `model_change` dispositions name neither an alignment-notes item nor a "
            "review finding.",
            "",
        ]
        for ref, (source, construct, disposition) in unscheduled:
            out.append(
                f"- {source}: {_one_line(construct.name)} (`{_one_line(ref)}`): "
                f"{_one_line(disposition.reason)}"
            )
        out.append("")
    return out
