# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse

"""The residue report and `tk survey`: counts, byte-identical regeneration and `--strict`."""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from declaration_support import full_declaration
from survey_support import (
    complete_dispositions,
    edit,
    entry,
    make_tree,
    write_dispositions,
)
from thermo_knowledge.cli import app
from thermo_knowledge.declaration import LoadResult
from thermo_knowledge.survey_index import command
from thermo_knowledge.survey_index.command import (
    evaluate,
    load_tree_declaration,
    report_text,
    write_report,
)

runner = CliRunner()


@pytest.fixture(autouse=True)
def fixture_declaration(monkeypatch: pytest.MonkeyPatch) -> None:
    """`tk survey` reads the tree's declaration; the fixture trees have none of their own."""
    monkeypatch.setattr(
        command, "load_declaration", lambda *args, **kwargs: LoadResult(full_declaration(), ())
    )


def partial_dispositions(tree: Path) -> None:
    write_dispositions(
        tree,
        "alpha",
        entry("exact but lossy", "held_by_model", "mechanism:unit handling")
        + entry("close record", "model_change", "alignment-notes #2"),
    )


def rows(text: str) -> dict[str, list[str]]:
    """The per-source table of a report: source -> cells."""
    table: dict[str, list[str]] = {}
    section = text.split("## Per source")[1].split("## Totals")[0]
    for line in section.splitlines():
        if line.startswith("| ") and not line.startswith("| source") and not line.startswith("|--"):
            cells = [cell.strip() for cell in line.strip("|").split("|")]
            table[cells[0]] = cells[1:]
    return table


def test_counts_on_the_fixture(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    partial_dispositions(tree)
    outcome = evaluate(tree, full_declaration())
    assert outcome.diagnostics == ()
    text = report_text(tree, outcome)
    # constructs, exact, narrower, broader, close, unmapped, need, model_change, mapping_loss,
    # out_of_scope, held_by_model, undispositioned
    assert rows(text) == {
        "alpha": ["6", "3", "1", "0", "1", "1", "4", "1", "0", "0", "1", "2"],
        "beta": ["2", "1", "0", "1", "0", "0", "1", "0", "0", "0", "0", "1"],
    }
    totals = text.split("## Totals")[1].split("##")[0]
    assert "- sources: 2" in totals
    assert "- constructs: 8 (exact 4, narrower 1, broader 1, close 1, unmapped 1)" in totals
    assert "- need a disposition: 5" in totals
    assert (
        "- dispositioned: model_change 1, mapping_loss 0, out_of_scope 0, held_by_model 1 "
        "(total 2)" in totals
    )
    assert "- undispositioned: 3" in totals


def test_undispositioned_constructs_are_listed_by_source_with_precision_and_loss(
    tmp_path: Path,
) -> None:
    tree = make_tree(tmp_path)
    partial_dispositions(tree)
    text = report_text(tree, evaluate(tree, full_declaration()))
    listing = text.split("## Undispositioned constructs")[1]
    assert "3 constructs need a disposition and have none" in listing
    assert listing.index("### alpha (2)") < listing.index("### beta (1)")
    assert "- `narrower` narrower record: (no loss stated)" in listing
    assert "- `unmapped` unmapped record: There is no concept to map to." in listing
    assert "- `broader` broad table: Two columns have no slot." in listing
    # A dispositioned construct and one that needs none are not listed.
    assert "close record" not in listing and "plain record" not in listing
    assert "exact but lossy" not in listing


def test_the_header_says_it_is_generated_and_from_what(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    partial_dispositions(tree)
    text = report_text(tree, evaluate(tree, full_declaration()))
    first = text.splitlines()[0]
    assert first.startswith("<!-- @generated by `tk survey --report` from survey/*.toml")
    assert first.endswith("do not edit -->")
    assert "from 2 survey files" in text and "1 disposition files" in text


def test_regeneration_is_byte_identical(tmp_path: Path) -> None:
    first_tree = make_tree(tmp_path / "one")
    second_tree = make_tree(tmp_path / "two")
    for tree in (first_tree, second_tree):
        partial_dispositions(tree)

    def generate(tree: Path) -> Path:
        return write_report(tree, report_text(tree, evaluate(tree, full_declaration())))

    first = generate(first_tree)
    before = first.read_bytes()
    generate(first_tree)
    assert first.read_bytes() == before
    second = generate(second_tree)
    assert second.read_bytes() == before
    assert before.endswith(b"\n") and b"\r" not in before and not before.endswith(b"\n\n")
    assert first == first_tree / "survey" / "residue-report.md"
    assert not list((first_tree / "survey").glob(".residue-report.*"))


def test_model_changes_are_grouped_by_ref(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    write_dispositions(
        tree,
        "alpha",
        entry("close record", "model_change", "alignment-notes #2")
        + entry("narrower record", "model_change", "unscheduled", "No item exists yet.")
        + entry("unmapped record", "model_change", "alignment-notes #2")
        + entry("exact but lossy", "model_change", "review F14"),
    )
    write_dispositions(tree, "beta", entry("broad table", "model_change", "alignment-notes #2"))
    text = report_text(tree, evaluate(tree, full_declaration()))
    section = text.split("## Model changes by ref")[1].split("## Undispositioned")[0]
    table = [line for line in section.splitlines() if line.startswith("| ") and "---" not in line]
    assert table[1:] == [
        "| alignment-notes #2 | 3 | alpha, beta |",
        "| review F14 | 1 | alpha |",
        "| unscheduled | 1 | alpha |",
    ]
    unscheduled = section.split("### Model changes that name no scheduled change")[1]
    assert "- alpha: narrower record (`unscheduled`): No item exists yet." in unscheduled
    assert "close record" not in unscheduled and "broad table" not in unscheduled
    assert "- undispositioned: 0" in text
    assert "Every construct that needs a disposition has one." in text


def test_no_model_change_says_so(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    text = report_text(tree, evaluate(tree, full_declaration()))
    assert "No construct is dispositioned as `model_change`." in text
    assert "- undispositioned: 5" in text


# -- tk survey ---------------------------------------------------------------------------------


def run(tree: Path, *args: str) -> tuple[int, str]:
    result = runner.invoke(app, ["survey", "--tree", str(tree), *args])
    return result.exit_code, result.output


def test_check_passes_on_a_valid_tree_and_fails_on_a_diagnostic(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    code, output = run(tree, "--check")
    assert code == 0
    assert "surveys and dispositions are valid: 2 sources, 8 constructs" in output
    edit(tree, "alpha", 'precision = "close"', 'precision = "nearly"')
    code, output = run(tree, "--check")
    assert code == 1
    assert "survey/alpha.toml [[construct]] 'close record' precision: [bad-value]" in output
    assert "error: 1 diagnostics" in output


def test_default_mode_is_check(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    assert run(tree)[0] == 0
    assert not (tree / "survey" / "residue-report.md").exists()


def test_report_writes_the_file_and_prints_the_summary(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    partial_dispositions(tree)
    code, output = run(tree, "--report")
    assert code == 0
    assert "wrote survey/residue-report.md" in output
    assert "undispositioned: 3" in output
    text = (tree / "survey" / "residue-report.md").read_text(encoding="utf-8")
    assert text == report_text(tree, evaluate(tree, full_declaration()))


def test_report_is_refused_while_there_are_diagnostics(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    edit(tree, "beta", 'origin = "authored (by hand)"', 'origin = "by hand"')
    code, _ = run(tree, "--report")
    assert code == 1
    assert not (tree / "survey" / "residue-report.md").exists()


def test_strict_fails_while_a_construct_has_no_disposition(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    partial_dispositions(tree)
    code, output = run(tree, "--report", "--strict")
    assert code == 1
    assert "error: 3 constructs have no disposition" in output
    assert (tree / "survey" / "residue-report.md").is_file()
    assert run(tree, "--report")[0] == 0


def test_strict_passes_when_every_construct_has_one(tmp_path: Path) -> None:
    tree = make_tree(tmp_path)
    complete_dispositions(tree)
    code, output = run(tree, "--report", "--strict")
    assert code == 0
    assert "undispositioned: 0" in output
    assert run(tree, "--check", "--strict")[0] == 0


def test_a_declaration_that_is_refused_is_a_diagnostic(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    tree = make_tree(tmp_path)
    monkeypatch.setattr(command, "load_declaration", lambda *args, **kwargs: LoadResult(None, ()))
    declaration, diagnostics = load_tree_declaration(tree)
    assert declaration is None
    assert [d.code.value for d in diagnostics] == ["declaration-unavailable"]
    code, output = run(tree, "--check")
    assert code == 1 and "declaration-unavailable" in output


def test_the_cli_registers_survey_beside_the_stages() -> None:
    result = runner.invoke(app, ["--help"])
    assert result.exit_code == 0 and "survey" in result.output
