// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse
// @generated by cargo xtask codegen (Cornucopia 1.0.1) from crates/pse-operations/queries; do not edit

//! The operational store's statements, compiled by Cornucopia 1.0.1 from
//! `crates/pse-operations/queries/*.sql` against the registry-generated schema
//! (ADR-0114 Outcome 24). `pse-operations` is its only consumer; `just codegen`
//! regenerates it and `just codegen-queries-check` compares a fresh generation.

#![allow(
    missing_docs,
    unreachable_pub,
    missing_debug_implementations,
    unused_qualifications,
    trivial_casts,
    rust_2018_idioms,
    dead_code,
    unused_imports,
    unused_variables,
    clippy::all,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::allow_attributes_without_reason,
    rustdoc::broken_intra_doc_links,
    rustdoc::bare_urls,
    reason = "Cornucopia-generated statement code; statements are checked at generation and by store tests"
)]

#[rustfmt::skip]
mod array_iterator;
#[rustfmt::skip]
pub mod client;
#[rustfmt::skip]
mod domain;
#[rustfmt::skip]
pub mod queries;
#[rustfmt::skip]
mod type_traits;
#[rustfmt::skip]
pub mod types;
#[rustfmt::skip]
mod utils;

pub use array_iterator::ArrayIterator;
#[cfg(feature = "deadpool")]
pub use deadpool_postgres;
pub use domain::{Domain, DomainArray};
pub use tokio_postgres;
pub use tokio_postgres::fallible_iterator;
pub use type_traits::JsonSql;
pub use type_traits::{ArraySql, BytesSql, IterSql, StringSql};
pub(crate) use utils::slice_iter;
