// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Rust-owned boundary documents (ADR-0116 Outcome 7): their published JSON Schemas and
//! the Python msgspec types generated from those schemas.
//!
//! Each document's serde type is its authority. schemars derives its JSON Schema (draft
//! 2020-12) in the crate that owns it; the caller, which links those crates, hands the
//! schemas over and this module renders them without touching the filesystem:
//!
//! - every schema in canonical form (sorted keys, two-space indentation), so a schema
//!   difference between two versions of a document is its compatibility record;
//! - one Python module of frozen msgspec `Struct` types, emitted here rather than by an
//!   external generator so that every enumeration is the registry's generated `StrEnum`
//!   (one Python type per vocabulary) and no annotation is `Any` or a bare container.
//!
//! The mapping is closed: a schema construct outside it is a generation error, never an
//! untyped fallback. Objects become structs that refuse unknown fields; a choice tagged by
//! a constant property becomes msgspec tagged structs and their union; string
//! enumerations must be registry vocabularies; numeric and pattern constraints become
//! `msgspec.Meta`; defaults are the schema's.
//!
//! The authoring JSON Schema is published beside the documents by its own emitter
//! ([`super::jsonschema`]).

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::PathBuf;

use serde_json::Value;

use super::GeneratedTree;
use super::rust::types::pascal;
use crate::{Registry, SchemaError};

/// Where the JSON Schemas are published.
pub const SCHEMA_ROOT: &str = "docs/generated/schema";
/// Where the generated Python document types live.
pub const PYTHON_ROOT: &str = "python/pse/contracts/documents";

/// The committed trees this generator owns.
pub fn roots() -> Vec<PathBuf> {
    vec![PathBuf::from(SCHEMA_ROOT), PathBuf::from(PYTHON_ROOT)]
}

/// One Rust-owned document: its published name and its derived JSON Schema.
#[derive(Clone, Debug)]
pub struct Document {
    /// File stem of the published schema, such as `solve-settings`.
    pub name: &'static str,
    /// The schemars-derived root schema, with its `$defs`.
    pub schema: Value,
}

/// Python's keywords, which cannot name an attribute.
const KEYWORDS: [&str; 35] = [
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

const PYTHON_HEADER: &str = "# SPDX-License-Identifier: MIT OR Apache-2.0\n# Copyright (c) 2026 Paul Heyse\n# @generated by pse-schema; do not edit\n";

fn error(reason: impl Into<String>) -> SchemaError {
    SchemaError::Codegen {
        language: "documents",
        reason: reason.into(),
    }
}

/// Renders the published schemas, the authoring schema and the Python document types.
///
/// # Errors
/// [`SchemaError::Codegen`] for a schema construct outside the closed mapping, a string
/// enumeration that is not a registry vocabulary, or two different types of one name.
pub fn generate(reg: &Registry, documents: &[Document]) -> Result<GeneratedTree, SchemaError> {
    let mut tree = GeneratedTree::empty(roots());
    for document in documents {
        tree.files.insert(
            format!("{SCHEMA_ROOT}/{}.schema.json", document.name).into(),
            canonical(&document.schema)?.into_bytes(),
        );
    }
    tree.files.insert(
        format!("{SCHEMA_ROOT}/authoring.schema.json").into(),
        super::jsonschema::generate(reg)?.into_bytes(),
    );
    tree.files.insert(
        format!("{PYTHON_ROOT}/__init__.py").into(),
        python(reg, documents)?.into_bytes(),
    );
    Ok(tree)
}

/// A schema in canonical form: the generated marker, sorted keys, two-space indentation
/// and a final newline, whatever JSON features the build graph enabled.
fn canonical(schema: &Value) -> Result<String, SchemaError> {
    let mut value = schema.clone();
    let object = value
        .as_object_mut()
        .ok_or_else(|| error("a document schema is not an object"))?;
    object.insert(
        "$comment".into(),
        Value::String("@generated by pse-schema; do not edit".into()),
    );
    value.sort_all_objects();
    let mut text = serde_json::to_string_pretty(&value).map_err(|e| error(e.to_string()))?;
    text.push('\n');
    Ok(text)
}

/// A Python string literal.
fn py_str(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            other if other.is_control() => {
                let _ = write!(out, "\\u{:04x}", u32::from(other));
            }
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

/// A Python literal of a JSON value.
fn py_literal(value: &Value) -> String {
    match value {
        Value::Null => "None".into(),
        Value::Bool(true) => "True".into(),
        Value::Bool(false) => "False".into(),
        Value::Number(number) => number.to_string(),
        Value::String(text) => py_str(text),
        Value::Array(items) => format!(
            "[{}]",
            items.iter().map(py_literal).collect::<Vec<_>>().join(", ")
        ),
        Value::Object(map) => {
            let mut entries = map.iter().collect::<Vec<_>>();
            entries.sort_by(|a, b| a.0.cmp(b.0));
            format!(
                "{{{}}}",
                entries
                    .iter()
                    .map(|(key, value)| format!("{}: {}", py_str(key), py_literal(value)))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
    }
}

/// The last segment of a local `$ref`.
fn reference(schema: &Value) -> Option<&str> {
    schema
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|target| target.strip_prefix("#/$defs/"))
}

fn text<'a>(schema: &'a Value, key: &str) -> Option<&'a str> {
    schema.get(key).and_then(Value::as_str)
}

/// The type names of a schema's `type` keyword, and whether it admits null.
fn types(schema: &Value) -> (Vec<&str>, bool) {
    match schema.get("type") {
        Some(Value::String(name)) if name == "null" => (Vec::new(), true),
        Some(Value::String(name)) => (vec![name.as_str()], false),
        Some(Value::Array(names)) => {
            let names = names.iter().filter_map(Value::as_str).collect::<Vec<_>>();
            let nullable = names.contains(&"null");
            (
                names.into_iter().filter(|name| *name != "null").collect(),
                nullable,
            )
        }
        _ => (Vec::new(), false),
    }
}

/// The msgspec constraints a schema states for one scalar.
fn constraints(schema: &Value) -> Vec<String> {
    let mut meta = Vec::new();
    for (keyword, argument) in [
        ("minimum", "ge"),
        ("maximum", "le"),
        ("exclusiveMinimum", "gt"),
        ("exclusiveMaximum", "lt"),
        ("minLength", "min_length"),
        ("maxLength", "max_length"),
    ] {
        if let Some(bound) = schema.get(keyword).filter(|v| v.is_number()) {
            meta.push(format!("{argument}={bound}"));
        }
    }
    if let Some(pattern) = text(schema, "pattern") {
        meta.push(format!("pattern={}", py_str(pattern)));
    }
    meta
}

fn annotated(base: &str, meta: &[String]) -> String {
    if meta.is_empty() {
        base.to_owned()
    } else {
        format!("Annotated[{base}, msgspec.Meta({})]", meta.join(", "))
    }
}

/// A tagged choice: every alternative is an object whose one constant string property
/// is the same tag field.
fn tagged(alternatives: &[Value]) -> Option<String> {
    let mut field = None;
    for alternative in alternatives {
        let properties = alternative.get("properties")?.as_object()?;
        let candidates = properties
            .iter()
            .filter(|(_, property)| property.get("const").is_some_and(Value::is_string))
            .map(|(name, _)| name.clone())
            .collect::<Vec<_>>();
        let [candidate] = candidates.as_slice() else {
            return None;
        };
        match &field {
            None => field = Some(candidate.clone()),
            Some(existing) if existing == candidate => {}
            Some(_) => return None,
        }
    }
    field
}

struct Emitter<'a> {
    /// Registry vocabularies by their Python class name, with their member spellings.
    vocabularies: BTreeMap<String, Vec<&'a str>>,
    /// Every named schema of every document.
    definitions: BTreeMap<String, Value>,
    /// Scalar and map aliases, emitted first.
    aliases: BTreeMap<String, String>,
    /// Struct classes.
    classes: BTreeMap<String, String>,
    /// Unions of tagged structs, emitted after the classes.
    unions: BTreeMap<String, String>,
    /// Names already defined or being defined.
    defined: BTreeSet<String>,
}

impl<'a> Emitter<'a> {
    fn new(reg: &'a Registry) -> Self {
        Self {
            vocabularies: reg
                .enums()
                .iter()
                .map(|spec| {
                    (
                        pascal(spec.name),
                        spec.members.iter().map(|member| member.name).collect(),
                    )
                })
                .collect(),
            definitions: BTreeMap::new(),
            aliases: BTreeMap::new(),
            classes: BTreeMap::new(),
            unions: BTreeMap::new(),
            defined: BTreeSet::new(),
        }
    }

    /// Record every named schema of a document, refusing two different types of one name.
    fn collect(&mut self, document: &Document) -> Result<String, SchemaError> {
        let mut root = document.schema.clone();
        let definitions = root
            .as_object_mut()
            .and_then(|object| object.remove("$defs"))
            .unwrap_or(Value::Object(serde_json::Map::new()));
        let title = text(&root, "title")
            .ok_or_else(|| error(format!("document {} has no title", document.name)))?
            .to_owned();
        if let Some(object) = root.as_object_mut() {
            // As a root it is titled; as a definition elsewhere it is named instead.
            object.remove("$schema");
            object.remove("title");
        }
        let mut named = definitions
            .as_object()
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .collect::<Vec<_>>();
        named.push((title.clone(), root));
        for (name, schema) in named {
            match self.definitions.get(&name) {
                Some(existing) if *existing != schema => {
                    return Err(error(format!("two different types are named {name}")));
                }
                Some(_) => {}
                None => {
                    self.definitions.insert(name, schema);
                }
            }
        }
        Ok(title)
    }

    /// The Python name of a referenced definition, defining it on first use.
    fn named(&mut self, name: &str) -> Result<String, SchemaError> {
        if self.vocabularies.contains_key(name) {
            let schema = self
                .definitions
                .get(name)
                .ok_or_else(|| error(format!("unknown definition {name}")))?;
            let members = schema
                .get("enum")
                .and_then(Value::as_array)
                .map(|values| values.iter().filter_map(Value::as_str).collect::<Vec<_>>())
                .ok_or_else(|| {
                    error(format!(
                        "{name} is a registry vocabulary but not a string enumeration"
                    ))
                })?;
            if members != self.vocabularies[name] {
                return Err(error(format!(
                    "{name} does not state the registry vocabulary's members"
                )));
            }
            return Ok(format!("enums.{name}"));
        }
        self.define(name)?;
        Ok(name.to_owned())
    }

    fn define(&mut self, name: &str) -> Result<(), SchemaError> {
        if !self.defined.insert(name.to_owned()) {
            return Ok(());
        }
        let schema = self
            .definitions
            .get(name)
            .cloned()
            .ok_or_else(|| error(format!("unknown definition {name}")))?;
        if schema.get("enum").is_some() {
            return Err(error(format!(
                "{name} is an enumeration crossing the boundary that is not a registry vocabulary"
            )));
        }
        let alternatives = schema
            .get("oneOf")
            .or_else(|| schema.get("anyOf"))
            .and_then(Value::as_array)
            .cloned();
        if let Some(alternatives) = alternatives {
            if let Some(field) = tagged(&alternatives) {
                return self.tagged_union(name, &schema, &alternatives, &field);
            }
            let annotation = self.annotation(&schema)?;
            self.aliases.insert(name.to_owned(), annotation);
            return Ok(());
        }
        let (kinds, _) = types(&schema);
        if kinds == ["object"] && schema.get("properties").is_some() {
            let source = self.structure(name, &schema, None)?;
            self.classes.insert(name.to_owned(), source);
        } else {
            let annotation = self.annotation(&schema)?;
            self.aliases.insert(name.to_owned(), annotation);
        }
        Ok(())
    }

    fn tagged_union(
        &mut self,
        name: &str,
        schema: &Value,
        alternatives: &[Value],
        field: &str,
    ) -> Result<(), SchemaError> {
        let mut members = Vec::new();
        for alternative in alternatives {
            let tag = alternative["properties"][field]["const"]
                .as_str()
                .ok_or_else(|| error(format!("{name}: tag without a constant")))?;
            let class = text(alternative, "title")
                .map_or_else(|| format!("{name}{}", pascal(tag)), ToOwned::to_owned);
            if !self.defined.insert(class.clone()) {
                return Err(error(format!("{name}: the class {class} is defined twice")));
            }
            let mut alternative = alternative.clone();
            if alternative.get("description").is_none()
                && let Some(description) = schema.get("description")
            {
                alternative["description"] = description.clone();
            }
            let source = self.structure(&class, &alternative, Some((field, tag)))?;
            self.classes.insert(class.clone(), source);
            members.push(class);
        }
        self.unions.insert(name.to_owned(), members.join(" | "));
        Ok(())
    }

    /// A struct class; `tag` names the tag field and value of a tagged alternative.
    fn structure(
        &mut self,
        name: &str,
        schema: &Value,
        tag: Option<(&str, &str)>,
    ) -> Result<String, SchemaError> {
        if schema.get("additionalProperties") != Some(&Value::Bool(false)) {
            return Err(error(format!("{name} admits unknown fields")));
        }
        let properties = schema
            .get("properties")
            .and_then(Value::as_object)
            .cloned()
            .unwrap_or_default();
        let required = schema
            .get("required")
            .and_then(Value::as_array)
            .map(|names| {
                names
                    .iter()
                    .filter_map(Value::as_str)
                    .map(ToOwned::to_owned)
                    .collect::<BTreeSet<_>>()
            })
            .unwrap_or_default();
        let mut options = String::from("frozen=True, forbid_unknown_fields=True, kw_only=True");
        if let Some((field, value)) = tag {
            let _ = write!(
                options,
                ", tag_field={}, tag={}",
                py_str(field),
                py_str(value)
            );
        }
        let mut source = format!("class {name}(msgspec.Struct, {options}):\n");
        let doc = text(schema, "description")
            .map_or_else(|| format!("The `{name}` document type."), ToOwned::to_owned);
        // `version` first, so a reader meets it first; then every field by name.
        let mut names = properties
            .keys()
            .filter(|field| tag.is_none_or(|(tag_field, _)| tag_field != field.as_str()))
            .cloned()
            .collect::<Vec<_>>();
        names.sort_by_key(|field| (field != "version", field.clone()));
        // The docstring is the body of a class with no fields; `pass` would be redundant.
        let _ = writeln!(source, "    {}", docstring(&doc));
        if !names.is_empty() {
            source.push('\n');
        }
        for field in names {
            let property = &properties[&field];
            let annotation = self.annotation(property)?;
            if let Some(description) = text(property, "description") {
                for line in description.lines() {
                    let _ = writeln!(source, "    #: {line}");
                }
            }
            let default = match self.default(property, &annotation)? {
                Some(default) => Some(default),
                None if required.contains(&field) => None,
                // serde decodes an absent optional value as null.
                None if annotation.ends_with(" | None") => Some("None".to_owned()),
                None => {
                    return Err(error(format!(
                        "{name}.{field} is optional without a default"
                    )));
                }
            };
            // A field spelled as a Python keyword keeps its wire name under a new attribute.
            let (attribute, default) = if KEYWORDS.contains(&field.as_str()) {
                let renamed = format!("name={}", py_str(&field));
                let default = match default {
                    None => format!("msgspec.field({renamed})"),
                    Some(factory) if factory.starts_with("msgspec.field(") => {
                        format!("{}, {renamed})", factory.trim_end_matches(')'))
                    }
                    Some(value) => format!("msgspec.field(default={value}, {renamed})"),
                };
                (format!("{field}_"), Some(default))
            } else {
                (field.clone(), default)
            };
            match default {
                Some(default) => {
                    let _ = writeln!(source, "    {attribute}: {annotation} = {default}");
                }
                None => {
                    let _ = writeln!(source, "    {attribute}: {annotation}");
                }
            }
        }
        Ok(source)
    }

    /// The Python default of a property, when its schema states one.
    fn default(&self, property: &Value, annotation: &str) -> Result<Option<String>, SchemaError> {
        if let Some(constant) = property.get("const") {
            return Ok(Some(py_literal(constant)));
        }
        let Some(value) = property.get("default") else {
            return Ok(None);
        };
        Ok(Some(match value {
            Value::String(member) => match reference(property) {
                Some(vocabulary) if self.vocabularies.contains_key(vocabulary) => {
                    format!("enums.{vocabulary}.{}", super::python::member_name(member))
                }
                _ => py_str(member),
            },
            Value::Array(items) if items.is_empty() => {
                "msgspec.field(default_factory=tuple)".into()
            }
            Value::Object(map) if map.is_empty() && annotation.starts_with("dict[") => {
                "msgspec.field(default_factory=dict)".into()
            }
            Value::Array(_) | Value::Object(_) => format!(
                "msgspec.field(default_factory=lambda: msgspec.convert({}, type={}))",
                py_literal(value),
                annotation.trim_end_matches(" | None")
            ),
            scalar => py_literal(scalar),
        }))
    }

    /// The Python annotation of a schema.
    fn annotation(&mut self, schema: &Value) -> Result<String, SchemaError> {
        if let Some(name) = reference(schema) {
            return self.named(name);
        }
        if let Some(constant) = schema.get("const") {
            return Ok(format!("Literal[{}]", py_literal(constant)));
        }
        if schema.get("enum").is_some() {
            return Err(error(format!(
                "an inline enumeration {schema}; declare a registry vocabulary"
            )));
        }
        if let Some(alternatives) = schema
            .get("anyOf")
            .or_else(|| schema.get("oneOf"))
            .and_then(Value::as_array)
        {
            if tagged(alternatives).is_some() {
                return Err(error(format!("an inline tagged choice {schema}; name it")));
            }
            let mut members = Vec::new();
            let mut nullable = false;
            for alternative in alternatives {
                if types(alternative) == (vec![], true) {
                    nullable = true;
                } else {
                    members.push(self.annotation(alternative)?);
                }
            }
            if nullable {
                members.push("None".into());
            }
            return Ok(members.join(" | "));
        }
        let (kinds, nullable) = types(schema);
        let base = match kinds.as_slice() {
            ["boolean"] => "bool".to_owned(),
            ["integer"] => annotated("int", &constraints(schema)),
            ["number"] => annotated("float", &constraints(schema)),
            ["string"] => annotated("str", &constraints(schema)),
            ["array"] => {
                let items = schema
                    .get("items")
                    .ok_or_else(|| error(format!("an array without items {schema}")))?;
                let item = self.annotation(items)?;
                let fixed = schema
                    .get("minItems")
                    .zip(schema.get("maxItems"))
                    .and_then(|(low, high)| (low == high).then(|| low.as_u64()).flatten())
                    .filter(|length| (1..=8).contains(length));
                match fixed {
                    Some(length) => format!(
                        "tuple[{}]",
                        vec![item; usize::try_from(length).unwrap_or(1)].join(", ")
                    ),
                    None => format!("tuple[{item}, ...]"),
                }
            }
            ["object"] => {
                if schema.get("properties").is_some() {
                    return Err(error(format!("an inline object {schema}; name it")));
                }
                // A map: typed values under any key, or under keys of one pattern.
                let patterned = schema
                    .get("patternProperties")
                    .and_then(Value::as_object)
                    .filter(|patterns| patterns.len() == 1)
                    .and_then(|patterns| patterns.iter().next());
                let (key, values) = match (patterned, schema.get("additionalProperties")) {
                    (Some((pattern, values)), Some(Value::Bool(false))) => (
                        annotated("str", &[format!("pattern={}", py_str(pattern))]),
                        values,
                    ),
                    (None, Some(values)) if values.is_object() => ("str".to_owned(), values),
                    _ => {
                        return Err(error(format!("an object without typed values {schema}")));
                    }
                };
                format!("dict[{key}, {}]", self.annotation(values)?)
            }
            _ => return Err(error(format!("an untyped schema {schema}"))),
        };
        Ok(if nullable {
            format!("{base} | None")
        } else {
            base
        })
    }
}

fn docstring(text: &str) -> String {
    let text = text
        .trim()
        .replace('\\', "\\\\")
        .replace("\"\"\"", "\\\"\\\"\\\"");
    if text.contains('\n') {
        let body = text
            .lines()
            .map(|line| {
                if line.is_empty() {
                    String::new()
                } else {
                    format!("    {line}")
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        format!("\"\"\"{}\n    \"\"\"", body.trim_start())
    } else {
        format!("\"\"\"{text}\"\"\"")
    }
}

/// The Python module of every document type.
fn python(reg: &Registry, documents: &[Document]) -> Result<String, SchemaError> {
    let mut emitter = Emitter::new(reg);
    let mut roots = Vec::new();
    for document in documents {
        roots.push(emitter.collect(document)?);
    }
    for root in &roots {
        emitter.named(root)?;
    }
    let mut source = String::from(PYTHON_HEADER);
    source.push_str(
        "\"\"\"Rust-owned boundary documents as frozen msgspec types (ADR-0116 Outcome 7).\n\nGenerated from the documents' JSON Schemas in `docs/generated/schema/`; the Rust serde\ntypes are the authority. Every enumeration is a registry vocabulary.\n\"\"\"\n\n",
    );
    source.push_str(
        "from __future__ import annotations\n\nfrom typing import Annotated, Literal\n\nimport msgspec\n\nfrom pse.contracts import enums\n\n",
    );
    for (name, annotation) in &emitter.aliases {
        let _ = write!(source, "{name} = {annotation}\n\n");
    }
    for class in emitter.classes.values() {
        let _ = write!(source, "\n{class}\n");
    }
    for (name, members) in &emitter.unions {
        let _ = write!(source, "\n{name} = {members}\n");
    }
    let names = emitter
        .aliases
        .keys()
        .chain(emitter.classes.keys())
        .chain(emitter.unions.keys())
        .collect::<BTreeSet<_>>();
    source.push_str("\n__all__ = [\n");
    for name in names {
        let _ = writeln!(source, "    {},", py_str(name));
    }
    source.push_str("]\n");
    // Annotations mention `Annotated`/`Literal` only when a schema needs them.
    if !source.contains("Annotated[") {
        source = source.replace(
            "from typing import Annotated, Literal",
            "from typing import Literal",
        );
    }
    if !source.contains("Literal[") {
        source = source
            .replace(
                "from typing import Annotated, Literal",
                "from typing import Annotated",
            )
            .replace("from typing import Literal\n\n", "");
    }
    Ok(source)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn document(schema: Value) -> Document {
        Document {
            name: "probe",
            schema,
        }
    }

    #[test]
    fn python_documents_are_closed_typed_structs() {
        let registry = crate::registry().unwrap();
        let schema = serde_json::json!({
            "title": "Probe",
            "type": "object",
            "additionalProperties": false,
            "required": ["version", "choice"],
            "properties": {
                "version": {"type": "integer", "const": 1, "default": 1},
                "hessian": {"$ref": "#/$defs/HessianMode", "default": "limited_memory"},
                "choice": {"$ref": "#/$defs/Choice"},
                "budget": {"$ref": "#/$defs/Budget", "default": 0.5},
                "items": {"type": "array", "items": {"type": "string"}, "default": []},
                "pair": {"type": ["array", "null"], "items": {"type": "number"}, "minItems": 2, "maxItems": 2, "default": null},
            },
            "$defs": {
                "HessianMode": {"type": "string", "enum": ["exact", "limited_memory"]},
                "Budget": {"type": "number", "exclusiveMinimum": 0.0},
                "Choice": {"oneOf": [
                    {"type": "object", "additionalProperties": false, "required": ["kind"],
                     "properties": {"kind": {"type": "string", "const": "plain"}}},
                    {"type": "object", "additionalProperties": false, "required": ["kind", "size"],
                     "properties": {"kind": {"type": "string", "const": "sized"},
                                    "size": {"type": "integer", "minimum": 1}}},
                ]},
            },
        });
        let source = python(registry, &[document(schema)]).unwrap();
        for expected in [
            "Budget = Annotated[float, msgspec.Meta(gt=0.0)]",
            "class ChoicePlain(msgspec.Struct, frozen=True, forbid_unknown_fields=True, kw_only=True, tag_field=\"kind\", tag=\"plain\"):",
            "    size: Annotated[int, msgspec.Meta(ge=1)]",
            "Choice = ChoicePlain | ChoiceSized",
            "    version: Literal[1] = 1",
            "    hessian: enums.HessianMode = enums.HessianMode.LIMITED_MEMORY",
            "    choice: Choice\n",
            "    items: tuple[str, ...] = msgspec.field(default_factory=tuple)",
            "    pair: tuple[float, float] | None = None",
        ] {
            assert!(source.contains(expected), "{expected}\n{source}");
        }
        assert!(!source.contains("Any"));
    }

    #[test]
    fn non_registry_enumerations_and_open_objects_are_refused() {
        let registry = crate::registry().unwrap();
        let enumeration = serde_json::json!({
            "title": "Probe", "type": "object", "additionalProperties": false,
            "required": ["mode"],
            "properties": {"mode": {"$ref": "#/$defs/Mode"}},
            "$defs": {"Mode": {"type": "string", "enum": ["a", "b"]}},
        });
        assert!(python(registry, &[document(enumeration)]).is_err());
        let open = serde_json::json!({
            "title": "Probe", "type": "object", "required": [],
            "properties": {"x": {"type": "number", "default": 1.0}},
        });
        assert!(python(registry, &[document(open)]).is_err());
        let wrong = serde_json::json!({
            "title": "Probe", "type": "object", "additionalProperties": false,
            "required": ["hessian"],
            "properties": {"hessian": {"$ref": "#/$defs/HessianMode"}},
            "$defs": {"HessianMode": {"type": "string", "enum": ["exact"]}},
        });
        assert!(python(registry, &[document(wrong)]).is_err());
    }

    #[test]
    fn published_schemas_are_canonical() {
        let text = canonical(&serde_json::json!({"b": 1, "a": {"d": 2, "c": 3}})).unwrap();
        assert_eq!(
            text,
            "{\n  \"$comment\": \"@generated by pse-schema; do not edit\",\n  \"a\": {\n    \"c\": 3,\n    \"d\": 2\n  },\n  \"b\": 1\n}\n"
        );
    }
}
