// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Surreal lowerings of registry-owned canonical envelopes.

use super::GeneratedTree;
use crate::{Registry, SchemaError};
use arrow_schema::DataType;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::{fmt::Write as _, path::PathBuf};

pub(super) fn append(registry: &Registry, tree: &mut GeneratedTree) -> Result<(), SchemaError> {
    let mut ddl = String::from("-- @generated by pse-schema; do not edit\n");
    let mut codecs = Vec::new();
    for relation in registry
        .relations()
        .iter()
        .filter(|relation| relation.key.name.starts_with("canonical_"))
    {
        let table = relation.key.name;
        let endpoints = relation
            .columns
            .iter()
            .filter_map(|column| column.graph_endpoint().map(|endpoint| (endpoint, column)))
            .collect::<Vec<_>>();
        if endpoints.is_empty() {
            let _ = writeln!(ddl, "DEFINE TABLE {table} SCHEMAFULL;");
        } else {
            let target = |endpoint: &str| -> Result<&str, SchemaError> {
                endpoints.iter().find(|(name,_)| *name == endpoint).and_then(|(_,column)| column.fk()).and_then(|fk| fk.relation.strip_prefix("runtime.")).ok_or_else(|| SchemaError::Codegen { language: "surreal", reason: format!("{table} graph endpoint {endpoint} requires a declared runtime record target") })
            };
            let _ = writeln!(
                ddl,
                "DEFINE TABLE {table} TYPE RELATION IN {} OUT {} SCHEMAFULL;",
                target("in")?,
                target("out")?
            );
        }
        let module = format_ident!("{table}");
        let row_name = format_ident!("Runtime{}Row", super::rust::types::pascal(table));
        let row_path = quote!(pse_model::generated::runtime::#module::#row_name);
        let encode = format_ident!("encode_{table}");
        let decode = format_ident!("decode_{table}");
        let mut encoders = Vec::new();
        let mut decoders = Vec::new();
        let mut link_decoders = Vec::new();
        for column in &relation.columns {
            let name = column.name();
            let ident = format_ident!("r#{name}");
            if let Some(endpoint) = column.graph_endpoint() {
                let target = column
                    .fk()
                    .and_then(|fk| fk.relation.strip_prefix("runtime."))
                    .ok_or_else(|| SchemaError::Codegen {
                        language: "surreal",
                        reason: format!("{table}.{name} graph endpoint lacks its record target"),
                    })?;
                let _ = writeln!(
                    ddl,
                    "DEFINE FIELD OVERWRITE {endpoint} ON {table} TYPE record<{target}> ASSERT $value = type::record('{target}', $this.{name});"
                );
                encoders.push(quote! { object.insert(#endpoint, crate::canonical_codec::record_link(#target, &row.#ident)); });
                link_decoders.push(quote! { crate::canonical_codec::check_record_link(&mut object, #endpoint, #target, &row.#ident)?; });
            }
            let (ty, codec) = match column.value_type().data_type() {
                DataType::Utf8 => ("string", "string"),
                DataType::Binary => ("bytes", "bytes"),
                DataType::UInt64 => ("decimal", "uint"),
                DataType::Int64 | DataType::Timestamp(_, _) => ("int", "int"),
                DataType::Boolean => ("bool", "boolean"),
                DataType::Float64 => ("object", "finite"),
                other => {
                    return Err(SchemaError::Codegen {
                        language: "surreal",
                        reason: format!(
                            "unsupported declared canonical field {table}.{name}: {other:?}"
                        ),
                    });
                }
            };
            let declared_ty = if column.nullable() {
                format!("option<{ty}>")
            } else {
                ty.to_owned()
            };
            let assertion = if ty == "decimal" {
                " ASSERT $value = NONE OR ($value >= 0dec AND $value <= 18446744073709551615dec AND math::floor($value) = $value)"
            } else if ty == "object" {
                " ASSERT $value = NONE OR ($value.projection >= -1.7976931348623157e308f AND $value.projection <= 1.7976931348623157e308f)"
            } else {
                ""
            };
            let _ = writeln!(
                ddl,
                "DEFINE FIELD {name} ON {table} TYPE {declared_ty}{assertion};"
            );
            if ty == "object" {
                let _ = writeln!(
                    ddl,
                    "DEFINE FIELD {name}.bits ON {table} TYPE option<bytes> ASSERT ($this.{name} = NONE AND $value = NONE) OR ($value != NONE AND bytes::len($value) = 8);\nDEFINE FIELD {name}.projection ON {table} TYPE option<float> ASSERT ($this.{name} = NONE AND $value = NONE) OR ($value >= -1.7976931348623157e308f AND $value <= 1.7976931348623157e308f);"
                );
            }
            let encode_field = format_ident!("encode_{codec}");
            let decode_field = format_ident!("decode_{codec}");
            let copy = matches!(codec, "uint" | "int" | "boolean" | "finite");
            if column.nullable() {
                let value = if copy {
                    quote!(*value)
                } else {
                    quote!(value.clone())
                };
                encoders.push(quote! { if let Some(value) = &row.#ident { object.insert(#name, crate::canonical_codec::#encode_field(#value)?); } });
                decoders.push(quote! { #ident: match object.remove(#name) { None | Some(surrealdb::types::Value::None) => None, Some(value) => Some(crate::canonical_codec::#decode_field(value)?), } });
            } else {
                let value = if copy {
                    quote!(row.#ident)
                } else {
                    quote!(row.#ident.clone())
                };
                encoders.push(quote! { object.insert(#name, crate::canonical_codec::#encode_field(#value)?); });
                decoders.push(quote! { #ident: crate::canonical_codec::#decode_field(crate::canonical_codec::required(&mut object, #name)?)? });
            }
        }
        let _ = writeln!(
            ddl,
            "DEFINE INDEX {table}_key ON {table} FIELDS key UNIQUE;\n"
        );
        codecs.push(quote! {
            #[doc = "Encode the registry row using native exact values."]
            pub fn #encode(row: &#row_path) -> Result<surrealdb::types::Object, crate::canonical_codec::CodecError> {
                let mut object = surrealdb::types::Object::new();
                #(#encoders)*
                Ok(object)
            }
            #[doc = "Decode the registry row; native id metadata is distinct from the declared key."]
            pub fn #decode(mut object: surrealdb::types::Object) -> Result<#row_path, crate::canonical_codec::CodecError> {
                let native_id = object.remove("id");
                let row = #row_path { #(#decoders,)* };
                if let Some(native_id) = native_id { crate::canonical_codec::check_record_identity(native_id, #table, &row.r#key)?; }
                #(#link_decoders)*
                if !object.is_empty() { return Err(crate::canonical_codec::CodecError::UnknownFields); }
                Ok(row)
            }
        });
    }
    // Physical access paths are declared beside their canonical relation authority.
    for index in pse_schema::catalog::substrate::INDEXES {
        let relation = registry
            .relations()
            .iter()
            .find(|relation| relation.key.name == index.table)
            .ok_or_else(|| SchemaError::Codegen {
                language: "surreal",
                reason: format!("index {} names an undeclared table", index.name),
            })?;
        for field in index.fields {
            if !relation
                .columns
                .iter()
                .any(|column| column.name() == *field)
            {
                return Err(SchemaError::Codegen {
                    language: "surreal",
                    reason: format!("index {} names an undeclared field {field}", index.name),
                });
            }
        }
        let _ = writeln!(
            ddl,
            "DEFINE INDEX {} ON {} FIELDS {}{};",
            index.name,
            index.table,
            index.fields.join(", "),
            if index.unique { " UNIQUE" } else { "" }
        );
    }
    let mut digest = pse_ids::FramedHasher::new(pse_ids::Frame::CanonicalSchemaV1);
    digest.str("pse.substrate.v1").part(ddl.as_bytes());
    for codec in &codecs {
        digest.str(&codec.to_string());
    }
    let schema_digest = digest.finish_hash().to_hex();
    let source: TokenStream = quote! {
        /// Exact interpretation of schema, codec and structural operations.
        pub const INTERPRETATION: &str = "pse.substrate.v1";
        /// Exact generated schema and codec compatibility identity.
        pub const SCHEMA_DIGEST: &str = #schema_digest;
        /// Registry-derived database declarations.
        pub const SCHEMA: &str = include_str!("surreal.surql");
        #(#codecs)*
    };
    let file = syn::parse2::<syn::File>(source).map_err(|error| SchemaError::Codegen {
        language: "surreal",
        reason: error.to_string(),
    })?;
    tree.files.insert(
        PathBuf::from("crates/pse-operations/src/generated/surreal.surql"),
        ddl.into_bytes(),
    );
    tree.files.insert(PathBuf::from("crates/pse-operations/src/generated/surreal.rs"), format!("// SPDX-License-Identifier: MIT OR Apache-2.0\n// Copyright (c) 2026 Paul Heyse\n// @generated by pse-schema; do not edit\n\n{}", prettyplease::unparse(&file)).into_bytes());
    Ok(())
}
