// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse
// Frozen Plan 25e admission layout, copied before the Plan 25f registry cutover.

/// Expected exact column layout (table, column, ordinal, PostgreSQL type, nullable).
pub(super) const COLUMNS: &[(&str, &str, i32, &str, bool)] = &[
    ("attempt_transitions", "attempt_id", 1i32, "pse_ops.attempt_id", false),
    ("attempt_transitions", "seq", 2i32, "integer", false),
    ("attempt_transitions", "from_state", 3i32, "pse_ops.attempt_state", true),
    ("attempt_transitions", "to_state", 4i32, "pse_ops.attempt_state", false),
    ("attempt_transitions", "actor", 5i32, "text", true),
    ("attempt_transitions", "reason", 6i32, "text", true),
    ("attempt_transitions", "at", 7i32, "timestamp with time zone", false),
    ("attempts", "attempt_id", 1i32, "pse_ops.attempt_id", false),
    ("attempts", "run_id", 2i32, "pse_ops.run_id", false),
    ("attempts", "kind", 3i32, "pse_ops.attempt_kind", false),
    ("attempts", "request_identity", 4i32, "pse_ops.content_hash", false),
    ("attempts", "preparation_identity", 5i32, "pse_ops.content_hash", true),
    ("attempts", "state", 6i32, "pse_ops.attempt_state", false),
    ("attempts", "state_version", 7i32, "integer", false),
    ("attempts", "parent_attempt", 8i32, "pse_ops.attempt_id", true),
    ("attempts", "worker", 9i32, "text", true),
    ("attempts", "lease_expires_at", 10i32, "timestamp with time zone", true),
    ("attempts", "heartbeat_at", 11i32, "timestamp with time zone", true),
    ("attempts", "cancel_requested", 12i32, "boolean", false),
    ("attempts", "cancel_requested_at", 13i32, "timestamp with time zone", true),
    ("attempts", "termination_class", 14i32, "pse_ops.termination_class", true),
    ("attempts", "termination_native", 15i32, "pse_ops.native_termination", true),
    ("attempts", "termination_run_state", 16i32, "pse_ops.native_run_state", true),
    (
        "attempts",
        "termination_trajectory",
        17i32,
        "pse_ops.trajectory_termination",
        true,
    ),
    ("attempts", "termination_runtime", 18i32, "pse_ops.runtime_termination", true),
    ("attempts", "termination_rule", 19i32, "pse_ops.diagnostic_code", true),
    ("attempts", "termination_detail", 20i32, "jsonb", true),
    ("attempts", "created_at", 21i32, "timestamp with time zone", false),
    ("attempts", "updated_at", 22i32, "timestamp with time zone", false),
    ("attempts", "started_at", 23i32, "timestamp with time zone", true),
    ("attempts", "finished_at", 24i32, "timestamp with time zone", true),
    ("incumbents", "attempt_id", 1i32, "pse_ops.attempt_id", false),
    ("incumbents", "seq", 2i32, "bigint", false),
    ("incumbents", "step", 3i32, "integer", false),
    ("incumbents", "at", 4i32, "timestamp with time zone", false),
    ("incumbents", "elapsed_seconds", 5i32, "double precision", false),
    ("incumbents", "phase", 6i32, "text", false),
    ("incumbents", "objective", 7i32, "double precision", false),
    ("incumbents", "dual_bound", 8i32, "double precision", true),
    ("incumbents", "gap", 9i32, "double precision", true),
    ("incumbents", "nodes", 10i32, "bigint", true),
    ("incumbents", "seconds", 11i32, "double precision", true),
    ("incumbents", "solution_id", 12i32, "pse_ops.solution_id", true),
    ("jobs", "job_id", 1i32, "pse_ops.job_id", false),
    ("jobs", "attempt_id", 2i32, "pse_ops.attempt_id", false),
    ("jobs", "idempotency_key", 3i32, "text", false),
    ("jobs", "payload_version", 4i32, "integer", false),
    ("jobs", "payload", 5i32, "jsonb", false),
    ("jobs", "priority", 6i32, "integer", false),
    ("jobs", "state", 7i32, "pse_ops.job_state", false),
    ("jobs", "tries", 8i32, "integer", false),
    ("jobs", "max_tries", 9i32, "integer", false),
    ("jobs", "backoff_base_us", 10i32, "bigint", false),
    ("jobs", "backoff_cap_us", 11i32, "bigint", false),
    ("jobs", "available_at", 12i32, "timestamp with time zone", false),
    ("jobs", "enqueued_at", 13i32, "timestamp with time zone", false),
    ("jobs", "updated_at", 14i32, "timestamp with time zone", false),
    ("jobs", "last_error", 15i32, "text", true),
    ("progress_events", "attempt_id", 1i32, "pse_ops.attempt_id", false),
    ("progress_events", "seq", 2i32, "bigint", false),
    ("progress_events", "step", 3i32, "integer", false),
    ("progress_events", "at", 4i32, "timestamp with time zone", false),
    ("progress_events", "elapsed_seconds", 5i32, "double precision", false),
    ("progress_events", "phase", 6i32, "text", false),
    ("progress_values", "attempt_id", 1i32, "pse_ops.attempt_id", false),
    ("progress_values", "seq", 2i32, "bigint", false),
    ("progress_values", "name", 3i32, "text", false),
    ("progress_values", "kind", 4i32, "pse_ops.native_metric_kind", false),
    ("progress_values", "real", 5i32, "double precision", true),
    ("progress_values", "integer", 6i32, "bigint", true),
    ("progress_values", "boolean", 7i32, "boolean", true),
    ("progress_values", "text", 8i32, "text", true),
    (
        "progress_values",
        "unavailable",
        9i32,
        "pse_ops.evidence_unavailable_reason",
        true,
    ),
    ("publication_heads", "workspace_id", 1i32, "pse_ops.workspace_id", false),
    ("publication_heads", "publication_id", 2i32, "pse_ops.publication_id", true),
    ("publication_heads", "advanced_at", 3i32, "timestamp with time zone", false),
    ("publication_intents", "publication_id", 1i32, "pse_ops.publication_id", false),
    ("publication_intents", "workspace_id", 2i32, "pse_ops.workspace_id", false),
    ("publication_intents", "attempt_id", 3i32, "pse_ops.attempt_id", false),
    ("publication_intents", "member_prefix", 4i32, "text", false),
    ("publication_intents", "prepared_at", 5i32, "timestamp with time zone", false),
    ("publication_intents", "abandoned_at", 6i32, "timestamp with time zone", true),
    ("publication_intents", "reclaimed_at", 7i32, "timestamp with time zone", true),
    ("publication_members", "publication_id", 1i32, "pse_ops.publication_id", false),
    ("publication_members", "role", 2i32, "pse_ops.publication_member_role", false),
    ("publication_members", "catalog_name", 3i32, "text", false),
    ("publication_members", "schema_name", 4i32, "text", false),
    ("publication_members", "table_name", 5i32, "text", false),
    ("publication_members", "relation_id", 6i32, "uuid", false),
    ("publication_members", "relation_version", 7i32, "bigint", false),
    ("publication_members", "contract_fingerprint", 8i32, "pse_ops.content_hash", false),
    ("publication_members", "table_uri", 9i32, "text", false),
    ("publication_members", "delta_version", 10i32, "bigint", false),
    (
        "publication_members",
        "selection_kind",
        11i32,
        "pse_ops.member_selection_kind",
        false,
    ),
    ("publication_members", "revision_column", 12i32, "text", true),
    ("publication_members", "revision_id", 13i32, "uuid", true),
    ("publication_windows", "publication_id", 1i32, "pse_ops.publication_id", false),
    ("publication_windows", "table_uri", 2i32, "text", false),
    ("publication_windows", "from_version", 3i32, "bigint", false),
    ("publication_windows", "through_version", 4i32, "bigint", false),
    ("publications", "publication_id", 1i32, "pse_ops.publication_id", false),
    ("publications", "workspace_id", 2i32, "pse_ops.workspace_id", false),
    ("publications", "parent_publication", 3i32, "pse_ops.publication_id", true),
    ("publications", "attempt_id", 4i32, "pse_ops.attempt_id", false),
    ("publications", "kind", 5i32, "pse_ops.publication_kind", false),
    ("publications", "committed_at", 6i32, "timestamp with time zone", false),
    ("reader_leases", "lease_id", 1i32, "pse_ops.reader_lease_id", false),
    ("reader_leases", "publication_id", 2i32, "pse_ops.publication_id", false),
    ("reader_leases", "head_of", 3i32, "pse_ops.workspace_id", true),
    ("reader_leases", "holder", 4i32, "text", false),
    ("reader_leases", "acquired_at", 5i32, "timestamp with time zone", false),
    ("reader_leases", "expires_at", 6i32, "timestamp with time zone", false),
    ("reader_leases", "released_at", 7i32, "timestamp with time zone", true),
    ("retention_marks", "publication_id", 1i32, "pse_ops.publication_id", false),
    ("retention_marks", "phase", 2i32, "pse_ops.retention_phase", false),
    ("retention_marks", "marked_at", 3i32, "timestamp with time zone", false),
    ("retention_marks", "deleted_at", 4i32, "timestamp with time zone", true),
    ("schema_support_state", "history", 1i32, "text", false),
    ("schema_support_state", "shared_version", 2i32, "integer", false),
    ("schema_support_state", "source", 3i32, "text", false),
    ("schema_support_state", "target", 4i32, "text", false),
    ("schema_support_state", "ready", 5i32, "boolean", false),
    ("settlements", "settlement_id", 1i32, "pse_ops.settlement_id", false),
    ("settlements", "attempt_id", 2i32, "pse_ops.attempt_id", false),
    ("settlements", "outcome", 3i32, "pse_ops.settlement_outcome", false),
    ("settlements", "publication_id", 4i32, "pse_ops.publication_id", true),
    ("settlements", "reason", 5i32, "text", true),
    ("settlements", "conflict_head", 6i32, "pse_ops.publication_id", true),
    ("settlements", "settled_at", 7i32, "timestamp with time zone", false),
    ("solutions", "solution_id", 1i32, "pse_ops.solution_id", false),
    ("solutions", "compatibility_stamp", 2i32, "pse_ops.content_hash", false),
    ("solutions", "preparation_identity", 3i32, "pse_ops.content_hash", false),
    ("solutions", "kind", 4i32, "pse_ops.stored_seed_kind", false),
    ("solutions", "origin", 5i32, "pse_ops.stored_solution_origin", false),
    ("solutions", "backend", 6i32, "pse_ops.native_backend", false),
    ("solutions", "profile_stamp", 7i32, "pse_ops.content_hash", false),
    ("solutions", "data_stamp", 8i32, "pse_ops.content_hash", false),
    ("solutions", "primal", 9i32, "double precision[]", true),
    ("solutions", "lower_bound_duals", 10i32, "double precision[]", true),
    ("solutions", "upper_bound_duals", 11i32, "double precision[]", true),
    ("solutions", "column_duals", 12i32, "double precision[]", true),
    ("solutions", "row_duals", 13i32, "double precision[]", true),
    ("solutions", "barrier", 14i32, "double precision", true),
    ("solutions", "basis_columns", 15i32, "integer[]", true),
    ("solutions", "basis_rows", 16i32, "integer[]", true),
    ("solutions", "created_by", 17i32, "pse_ops.attempt_id", true),
    ("solutions", "created_at", 18i32, "timestamp with time zone", false),
    ("source_bundles", "bundle_hash", 1i32, "pse_ops.source_bundle_id", false),
    ("source_bundles", "manifest", 2i32, "jsonb", false),
    ("source_bundles", "created_at", 3i32, "timestamp with time zone", false),
    ("source_documents", "bundle_hash", 1i32, "pse_ops.source_bundle_id", false),
    ("source_documents", "path", 2i32, "text", false),
    ("source_documents", "content_hash", 3i32, "pse_ops.content_hash", false),
    ("source_documents", "content", 4i32, "bytea", false),
    ("studies", "study_id", 1i32, "pse_ops.study_id", false),
    ("studies", "attempt_id", 2i32, "pse_ops.attempt_id", false),
    ("studies", "publication_id", 3i32, "pse_ops.publication_id", false),
    ("studies", "finalization_job", 4i32, "pse_ops.job_id", false),
    ("studies", "definition", 5i32, "jsonb", false),
    ("studies", "state", 6i32, "pse_ops.study_state", false),
    ("studies", "created_at", 7i32, "timestamp with time zone", false),
    ("studies", "updated_at", 8i32, "timestamp with time zone", false),
    ("study_point_members", "study_id", 1i32, "pse_ops.study_id", false),
    ("study_point_members", "point_index", 2i32, "integer", false),
    ("study_point_members", "catalog_name", 3i32, "text", false),
    ("study_point_members", "schema_name", 4i32, "text", false),
    ("study_point_members", "table_name", 5i32, "text", false),
    ("study_point_members", "relation_id", 6i32, "uuid", false),
    ("study_point_members", "relation_version", 7i32, "bigint", false),
    ("study_point_members", "contract_fingerprint", 8i32, "pse_ops.content_hash", false),
    ("study_point_members", "table_uri", 9i32, "text", false),
    ("study_point_members", "delta_version", 10i32, "bigint", false),
    (
        "study_point_members",
        "selection_kind",
        11i32,
        "pse_ops.member_selection_kind",
        false,
    ),
    ("study_point_members", "revision_column", 12i32, "text", true),
    ("study_point_members", "revision_id", 13i32, "uuid", true),
    ("study_points", "study_id", 1i32, "pse_ops.study_id", false),
    ("study_points", "point_index", 2i32, "integer", false),
    ("study_points", "binding_hash", 3i32, "pse_ops.content_hash", false),
    ("study_points", "predecessor", 4i32, "integer", true),
    ("study_points", "job_id", 5i32, "pse_ops.job_id", false),
    ("study_points", "state", 6i32, "pse_ops.study_point_state", false),
    ("study_points", "updated_at", 7i32, "timestamp with time zone", false),
    ("workspaces", "workspace_id", 1i32, "pse_ops.workspace_id", false),
    ("workspaces", "name", 2i32, "text", false),
    ("workspaces", "root_uri", 3i32, "text", false),
    ("workspaces", "maintenance_epoch", 4i32, "bigint", false),
    ("workspaces", "created_at", 5i32, "timestamp with time zone", false),
];
/// Required generated constraints (table, constraint name, PostgreSQL kind).
pub(super) const CONSTRAINTS: &[(&str, &str, &str)] = &[
    ("attempt_transitions", "attempt_transitions_pkey", "p"),
    (
        "attempt_transitions",
        "attempt_transitions_creation_has_no_previous_state_check",
        "c",
    ),
    ("attempt_transitions", "attempt_transitions_seq_nonnegative_check", "c"),
    ("attempts", "attempts_pkey", "p"),
    ("attempts", "attempts_cancel_request_timed_check", "c"),
    ("attempts", "attempts_one_termination_check", "c"),
    ("attempts", "attempts_parent_is_another_attempt_check", "c"),
    ("attempts", "attempts_running_has_worker_check", "c"),
    ("attempts", "attempts_running_holds_lease_check", "c"),
    ("attempts", "attempts_state_version_nonnegative_check", "c"),
    ("attempts", "attempts_worker_nonempty_check", "c"),
    ("incumbents", "incumbents_pkey", "p"),
    ("incumbents", "incumbents_dual_bound_finite", "c"),
    ("incumbents", "incumbents_elapsed_nonnegative_check", "c"),
    ("incumbents", "incumbents_elapsed_seconds_finite", "c"),
    ("incumbents", "incumbents_gap_finite", "c"),
    ("incumbents", "incumbents_gap_nonnegative_check", "c"),
    ("incumbents", "incumbents_nodes_nonnegative_check", "c"),
    ("incumbents", "incumbents_objective_finite", "c"),
    ("incumbents", "incumbents_phase_nonempty_check", "c"),
    ("incumbents", "incumbents_seconds_finite", "c"),
    ("incumbents", "incumbents_seconds_nonnegative_check", "c"),
    ("incumbents", "incumbents_seq_nonnegative_check", "c"),
    ("incumbents", "incumbents_step_nonnegative_check", "c"),
    ("jobs", "jobs_pkey", "p"),
    ("jobs", "jobs_attempt_id_key", "u"),
    ("jobs", "jobs_idempotency_key_key", "u"),
    ("jobs", "jobs_backoff_base_nonnegative_check", "c"),
    ("jobs", "jobs_backoff_cap_covers_base_check", "c"),
    ("jobs", "jobs_idempotency_key_nonempty_check", "c"),
    ("jobs", "jobs_max_tries_positive_check", "c"),
    ("jobs", "jobs_payload_version_positive_check", "c"),
    ("jobs", "jobs_tries_nonnegative_check", "c"),
    ("jobs", "jobs_tries_within_max_check", "c"),
    ("progress_events", "progress_events_pkey", "p"),
    ("progress_events", "progress_events_elapsed_nonnegative_check", "c"),
    ("progress_events", "progress_events_elapsed_seconds_finite", "c"),
    ("progress_events", "progress_events_phase_nonempty_check", "c"),
    ("progress_events", "progress_events_seq_nonnegative_check", "c"),
    ("progress_events", "progress_events_step_nonnegative_check", "c"),
    ("progress_values", "progress_values_pkey", "p"),
    ("progress_values", "progress_values_name_nonempty_check", "c"),
    ("progress_values", "progress_values_one_evidence_value_check", "c"),
    ("progress_values", "progress_values_real_finite", "c"),
    ("publication_heads", "publication_heads_pkey", "p"),
    ("publication_intents", "publication_intents_pkey", "p"),
    ("publication_intents", "publication_intents_member_prefix_key", "u"),
    ("publication_intents", "publication_intents_identity_key", "u"),
    ("publication_intents", "publication_intents_member_prefix_nonempty_check", "c"),
    ("publication_intents", "publication_intents_reclaimed_after_abandoned_check", "c"),
    ("publication_members", "publication_members_pkey", "p"),
    ("publication_members", "publication_members_catalog_name_nonempty_check", "c"),
    ("publication_members", "publication_members_delta_version_nonnegative_check", "c"),
    ("publication_members", "publication_members_one_selection_check", "c"),
    (
        "publication_members",
        "publication_members_relation_version_nonnegative_check",
        "c",
    ),
    ("publication_members", "publication_members_schema_name_nonempty_check", "c"),
    ("publication_members", "publication_members_table_name_nonempty_check", "c"),
    ("publication_members", "publication_members_table_uri_nonempty_check", "c"),
    ("publication_windows", "publication_windows_pkey", "p"),
    ("publication_windows", "publication_windows_from_version_nonnegative_check", "c"),
    ("publication_windows", "publication_windows_ordered_window_check", "c"),
    ("publication_windows", "publication_windows_table_uri_nonempty_check", "c"),
    ("publications", "publications_pkey", "p"),
    ("publications", "publications_attempt_id_key", "u"),
    ("publications", "publications_parent_is_another_publication_check", "c"),
    ("reader_leases", "reader_leases_pkey", "p"),
    ("reader_leases", "reader_leases_expires_after_acquired_check", "c"),
    ("reader_leases", "reader_leases_holder_nonempty_check", "c"),
    ("retention_marks", "retention_marks_pkey", "p"),
    ("retention_marks", "retention_marks_deleted_when_marked_deleted_check", "c"),
    ("schema_support_state", "schema_support_state_pkey", "p"),
    ("schema_support_state", "schema_support_state_history_known_check", "c"),
    ("schema_support_state", "schema_support_state_shared_version_positive_check", "c"),
    ("settlements", "settlements_pkey", "p"),
    ("settlements", "settlements_committed_names_publication_check", "c"),
    ("settlements", "settlements_conflict_has_reason_check", "c"),
    ("settlements", "settlements_conflict_head_of_conflict_check", "c"),
    ("settlements", "settlements_reason_nonempty_check", "c"),
    ("solutions", "solutions_pkey", "p"),
    ("solutions", "solutions_barrier_finite", "c"),
    ("solutions", "solutions_barrier_positive_check", "c"),
    ("solutions", "solutions_basis_columns_elements", "c"),
    ("solutions", "solutions_basis_rows_elements", "c"),
    ("solutions", "solutions_capture_has_attempt_check", "c"),
    ("solutions", "solutions_column_duals_elements", "c"),
    ("solutions", "solutions_lower_bound_duals_elements", "c"),
    ("solutions", "solutions_primal_elements", "c"),
    ("solutions", "solutions_row_duals_elements", "c"),
    ("solutions", "solutions_upper_bound_duals_elements", "c"),
    ("solutions", "solutions_vectors_check", "c"),
    ("source_bundles", "source_bundles_pkey", "p"),
    ("source_documents", "source_documents_pkey", "p"),
    ("source_documents", "source_documents_path_nonempty_check", "c"),
    ("studies", "studies_pkey", "p"),
    ("studies", "studies_attempt_id_key", "u"),
    ("studies", "studies_publication_id_key", "u"),
    ("studies", "studies_finalization_job_key", "u"),
    ("study_point_members", "study_point_members_pkey", "p"),
    ("study_point_members", "study_point_members_catalog_name_nonempty_check", "c"),
    ("study_point_members", "study_point_members_delta_version_nonnegative_check", "c"),
    ("study_point_members", "study_point_members_one_selection_check", "c"),
    (
        "study_point_members",
        "study_point_members_relation_version_nonnegative_check",
        "c",
    ),
    ("study_point_members", "study_point_members_schema_name_nonempty_check", "c"),
    ("study_point_members", "study_point_members_table_name_nonempty_check", "c"),
    ("study_point_members", "study_point_members_table_uri_nonempty_check", "c"),
    ("study_points", "study_points_pkey", "p"),
    ("study_points", "study_points_job_id_key", "u"),
    ("study_points", "study_points_binding_key", "u"),
    ("study_points", "study_points_point_index_nonnegative_check", "c"),
    ("study_points", "study_points_predecessor_is_earlier_check", "c"),
    ("workspaces", "workspaces_pkey", "p"),
    ("workspaces", "workspaces_name_key", "u"),
    ("workspaces", "workspaces_root_uri_key", "u"),
    ("workspaces", "workspaces_maintenance_epoch_nonnegative_check", "c"),
    ("workspaces", "workspaces_name_nonempty_check", "c"),
    ("workspaces", "workspaces_root_uri_nonempty_check", "c"),
    ("attempt_transitions", "attempt_transitions_attempt_id_fkey", "f"),
    ("attempts", "attempts_parent_attempt_fkey", "f"),
    ("incumbents", "incumbents_attempt_id_fkey", "f"),
    ("incumbents", "incumbents_solution_id_fkey", "f"),
    ("jobs", "jobs_attempt_id_fkey", "f"),
    ("progress_events", "progress_events_attempt_id_fkey", "f"),
    ("progress_values", "progress_values_attempt_id_fkey", "f"),
    ("progress_values", "progress_values_progress_event_fkey", "f"),
    ("publication_heads", "publication_heads_workspace_id_fkey", "f"),
    ("publication_heads", "publication_heads_publication_id_fkey", "f"),
    ("publication_intents", "publication_intents_workspace_id_fkey", "f"),
    ("publication_intents", "publication_intents_attempt_id_fkey", "f"),
    ("publication_members", "publication_members_publication_id_fkey", "f"),
    ("publication_windows", "publication_windows_publication_id_fkey", "f"),
    ("publications", "publications_publication_id_fkey", "f"),
    ("publications", "publications_workspace_id_fkey", "f"),
    ("publications", "publications_parent_publication_fkey", "f"),
    ("publications", "publications_attempt_id_fkey", "f"),
    ("publications", "publications_intent_fkey", "f"),
    ("reader_leases", "reader_leases_publication_id_fkey", "f"),
    ("reader_leases", "reader_leases_head_of_fkey", "f"),
    ("retention_marks", "retention_marks_publication_id_fkey", "f"),
    ("settlements", "settlements_attempt_id_fkey", "f"),
    ("settlements", "settlements_publication_id_fkey", "f"),
    ("settlements", "settlements_conflict_head_fkey", "f"),
    ("solutions", "solutions_created_by_fkey", "f"),
    ("source_documents", "source_documents_bundle_hash_fkey", "f"),
    ("studies", "studies_attempt_id_fkey", "f"),
    ("studies", "studies_publication_id_fkey", "f"),
    ("studies", "studies_finalization_job_fkey", "f"),
    ("study_point_members", "study_point_members_study_id_fkey", "f"),
    ("study_point_members", "study_point_members_point_fkey", "f"),
    ("study_points", "study_points_study_id_fkey", "f"),
    ("study_points", "study_points_job_id_fkey", "f"),
    ("study_points", "study_points_predecessor_fkey", "f"),
];
/// Consumed recorded enum domains, including their order.
pub(super) const ENUMS: &[(&str, &[&str])] = &[
    (
        "attempt_kind",
        &["modeling", "simulation", "shooting", "fit", "study", "study_finalization"],
    ),
    (
        "attempt_state",
        &[
            "planned",
            "queued",
            "running",
            "completed",
            "partial",
            "failed",
            "cancelled",
            "stale",
            "superseded",
        ],
    ),
    (
        "diagnostic_code",
        &[
            "authoring.parse",
            "authoring.parse.ambiguous_unary_power",
            "authoring.parse.budget",
            "authoring.parse.document_io",
            "authoring.parse.missing_id",
            "authoring.parse.nonfinite_number",
            "authoring.parse.syntax",
            "authoring.parse.unknown_key",
            "authoring.parse.unresolved_target",
            "authoring.pkg.unresolved",
            "authoring.pkg.version_conflict",
            "authoring.reference",
            "authoring.reference.contract",
            "authoring.reference.derived_write",
            "authoring.reference.rename_named",
            "authoring.reference.unknown_row_key",
            "capability.backend",
            "compile.discretization",
            "compile.feature",
            "compile.law",
            "compile.math",
            "compile.math.cyclic_expression",
            "compile.math.domain_violation_static",
            "compile.math.quantity_operation_unsupported",
            "compile.math.unit_inconsistent",
            "compile.property",
            "config.invalid",
            "internal.invariant",
            "kernel.unbound_parameter",
            "plan.initialization",
            "rule.float_key",
            "rule.head_schema_mismatch",
            "runtime.cancelled",
            "runtime.infrastructure",
            "runtime.resource_limit",
            "runtime.timeout",
            "schema.admission",
            "schema.arrow",
            "schema.codegen",
            "schema.contract_mismatch",
            "schema.duplicate_declaration",
            "schema.enum_member",
            "schema.extension_metadata",
            "schema.extension_type",
            "schema.fingerprint_mismatch",
            "schema.invalid_declaration",
            "schema.invalid_key",
            "schema.missing_granularity",
            "schema.missing_snapshot_class",
            "schema.nullability",
            "schema.ordinal_range",
            "schema.rule_float_key",
            "schema.rule_stratification",
            "schema.storage",
            "schema.unknown_metadata",
            "schema.unknown_reference",
            "schema.unknown_registry",
            "schema.unsupported_layout",
            "schema.version_mismatch",
            "solve.evaluation_error",
            "solve.infeasible",
            "solve.limit",
            "solve.locally_infeasible",
            "solve.solver_error",
            "solve.unbounded",
            "template.guard_undecidable",
            "user.model",
            "validation.invariant",
        ],
    ),
    (
        "evidence_unavailable_reason",
        &[
            "not_requested",
            "not_computed",
            "not_applicable",
            "unsupported",
            "failed",
            "unknown",
            "nonfinite",
        ],
    ),
    ("job_state", &["waiting", "queued", "running", "completed", "failed", "cancelled"]),
    ("member_selection_kind", &["full", "revision"]),
    (
        "native_backend",
        &[
            "ipopt",
            "pounce",
            "kinsol",
            "highs",
            "clarabel",
            "diffsol",
            "idas",
            "scip",
            "pounce_convex",
        ],
    ),
    ("native_metric_kind", &["real", "integer", "boolean", "text", "unavailable"]),
    ("native_run_state", &["native", "constant_evaluation", "rejected", "unattempted"]),
    (
        "native_termination",
        &[
            "success",
            "acceptable",
            "feasible_only",
            "infeasible",
            "unbounded",
            "infeasible_or_unbounded",
            "limit",
            "iteration_limit",
            "node_limit",
            "resource_exhausted",
            "inconclusive",
            "objective_limit",
            "solution_limit",
            "time_limit",
            "cancelled",
            "numerical",
            "evaluation",
            "panic",
            "invalid",
        ],
    ),
    (
        "publication_kind",
        &[
            "relations",
            "source",
            "model",
            "case",
            "problem",
            "run",
            "diagnostics",
            "inspection",
        ],
    ),
    ("publication_member_role", &["output", "input"]),
    ("retention_phase", &["expiring", "deleted"]),
    (
        "runtime_termination",
        &[
            "cancelled",
            "infrastructure",
            "unattempted",
            "constant_evaluation",
            "unassessed",
        ],
    ),
    ("settlement_outcome", &["committed", "proved_noncommit", "conflict"]),
    ("stored_seed_kind", &["root", "nlp", "highs"]),
    ("stored_solution_origin", &["output", "incumbent"]),
    ("study_point_state", &["pending", "assigned", "completed", "failed", "cancelled"]),
    ("study_state", &["open", "concluded", "published"]),
    ("termination_class", &["native", "run_state", "trajectory", "runtime", "rule"]),
    (
        "trajectory_termination",
        &[
            "completed",
            "event",
            "cancelled",
            "time_limit",
            "step_limit",
            "event_limit",
            "failed",
            "panic",
        ],
    ),
];
