// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Generated frozen attrs rows and Arrow extension contracts.

mod extensions;
mod identifiers;
mod types;

use std::fmt::Write as _;

use crate::model::ExtensionUse;
use crate::{Registry, SchemaError};

use super::rust::types::pascal;
use super::{GeneratedTree, Language};

const ROOT: &str = "python/pse/contracts";
const HEADER: &str = "# SPDX-License-Identifier: MIT OR Apache-2.0\n# Copyright (c) 2026 Paul Heyse\n# @generated by pse-schema; do not edit\n";

fn error(reason: String) -> SchemaError {
    SchemaError::Codegen {
        language: "python",
        reason,
    }
}

fn emit(tree: &mut GeneratedTree, name: &str, source: &str) {
    tree.files.insert(
        format!("{ROOT}/{name}.py").into(),
        format!("{HEADER}{source}").into_bytes(),
    );
}

pub(super) fn generate(reg: &Registry) -> Result<GeneratedTree, SchemaError> {
    let mut tree = GeneratedTree::empty(Language::Python.roots());
    emit(&mut tree, "enums", &enumerations(reg));
    emit(&mut tree, "values", &values()?);
    emit(&mut tree, "extension_types", &extensions::render(reg)?);
    emit(&mut tree, "identities", &identities(reg));
    emit(&mut tree, "structures", &structures(reg)?);
    let mut namespaces = std::collections::BTreeMap::<&str, (String, bool)>::new();
    for spec in reg.relations() {
        let namespace = spec.key.namespace.as_str();
        let stem = format!("{}{}", pascal(namespace), pascal(spec.key.name));
        let mut declarations = String::new();
        let mut typed_ids = false;
        let fields = spec
            .columns
            .iter()
            .map(|column| {
                let ty = match column.identity().and_then(|name| reg.identity(name)) {
                    // A typed id annotates as its alias and validates as its base value.
                    Some(identity) => {
                        typed_ids = true;
                        types::Type {
                            annotation: format!(
                                "i.{}",
                                super::rust::identities::type_name(identity.name)
                            ),
                            validator: format!(
                                "attrs.validators.instance_of(v.{})",
                                base_class(identity.base)
                            ),
                        }
                    }
                    None => {
                        typed_ids |= carries_identity(column);
                        types::logical(
                            &column.value_type(),
                            &format!("{stem}Field{}", pascal(column.name())),
                            &mut declarations,
                        )?
                    }
                };
                Ok((
                    column.name().to_owned(),
                    types::optional(ty, column.nullable()),
                ))
            })
            .collect::<Result<Vec<_>, SchemaError>>()?;
        declarations.push_str(&types::structure(&format!("{stem}Row"), &fields));
        let entry = namespaces.entry(namespace).or_default();
        entry.0.push_str(&declarations);
        entry.1 |= typed_ids;
    }
    for (namespace, (declarations, typed_ids)) in namespaces {
        let mut source = format!(
            "\"\"\"Typed rows in the {namespace} namespace.\"\"\"\n\nimport builtins as b\n"
        );
        if declarations.contains(": datetime") {
            source.push_str("from datetime import datetime\n");
        }
        source.push_str("\nimport attrs\n\n");
        // Sorted by module, as the linter's import order requires.
        if uses_alias(&declarations, "e") {
            source.push_str("from pse.contracts import enums as e\n");
        }
        if typed_ids {
            source.push_str("from pse.contracts import identities as i\n");
        }
        if references_structures(reg, &declarations) {
            source.push_str("from pse.contracts import structures as s\n");
        }
        if uses_alias(&declarations, "v") {
            source.push_str("from pse.contracts import values as v\n");
        }
        source.push_str(&declarations);
        emit(&mut tree, namespace, &source);
    }
    emit(
        &mut tree,
        "__init__",
        &format!(
            "\"\"\"Contracts generated from the sole registry declaration.\"\"\"\n\nfrom pse.contracts.extension_types import EXTENSION_NAMES, register_all\n\n__all__ = [\"EXTENSION_NAMES\", \"REGISTRY_FINGERPRINT\", \"register_all\"]\n\nREGISTRY_FINGERPRINT = {:?}\n",
            reg.fingerprint().to_prefixed()
        ),
    );
    Ok(tree)
}

/// Whether generated declarations qualify a name through a module alias: `alias.` at an
/// identifier boundary, so prose such as "nested value." does not import `e`.
fn uses_alias(declarations: &str, alias: &str) -> bool {
    let qualifier = format!("{alias}.");
    declarations.match_indices(&qualifier).any(|(at, _)| {
        declarations[..at]
            .chars()
            .next_back()
            .is_none_or(|before| !(before.is_alphanumeric() || before == '_' || before == '.'))
    })
}

/// Whether generated declarations reference a named structure.
fn references_structures(reg: &Registry, declarations: &str) -> bool {
    reg.structures()
        .keys()
        .any(|name| declarations.contains(&format!("s.{name}")))
}

/// Every registry named structure, declared once (Plan 22 X11); relation rows refer to
/// these classes by name.
fn structures(reg: &Registry) -> Result<String, SchemaError> {
    let mut declarations = String::new();
    let mut typed_ids = false;
    for (name, contract) in reg.structures() {
        typed_ids |= carries_identity(contract);
        types::logical(&contract.clone().unnamed(), name, &mut declarations)?;
    }
    let mut source = String::from("\"\"\"Registry named structures, each declared once.\"\"\"\n");
    if declarations.is_empty() {
        return Ok(source);
    }
    source.push_str("\nimport builtins as b\n");
    if declarations.contains(": datetime") {
        source.push_str("from datetime import datetime\n");
    }
    source.push_str("\nimport attrs\n\n");
    if uses_alias(&declarations, "e") {
        source.push_str("from pse.contracts import enums as e\n");
    }
    if typed_ids {
        source.push_str("from pse.contracts import identities as i\n");
    }
    if uses_alias(&declarations, "v") {
        source.push_str("from pse.contracts import values as v\n");
    }
    // A structure nested in another refers to it locally, not through the package.
    let mut local = declarations;
    for name in reg.structures().keys() {
        local = local.replace(&format!("s.{name}"), name);
    }
    source.push_str(&local);
    Ok(source)
}

/// Whether a value nested in the column names an entity identity.
fn carries_identity(column: &crate::model::FieldContract) -> bool {
    column.extension().is_none()
        && column
            .children()
            .iter()
            .any(|child| child.identity().is_some() || carries_identity(child))
}

/// The Python class of an identity's base value.
const fn base_class(base: crate::model::IdentityBase) -> &'static str {
    match base {
        crate::model::IdentityBase::SemanticId => "SemanticId",
        crate::model::IdentityBase::ContentHash => "ContentHash",
    }
}

/// One `NewType` per declared entity identity: the alias a type checker keeps apart
/// from every other identity, over the validated base class (ADR-0115).
fn identities(reg: &Registry) -> String {
    let mut source = String::from(
        "\"\"\"Declared entity identities: distinct aliases of their base identity values.\"\"\"\n",
    );
    if reg.identities().is_empty() {
        return source;
    }
    source.push_str("\nfrom typing import NewType\n\nfrom pse.contracts import values as v\n");
    for identity in reg.identities() {
        let name = super::rust::identities::type_name(identity.name);
        let _ = write!(
            source,
            "\n# {} (entity identity `{}`).\n{name} = NewType({name:?}, v.{})\n",
            identity.doc.trim_end_matches('.'),
            identity.name,
            base_class(identity.base)
        );
    }
    source
}

/// The Python member name of a declared enumeration member spelling.
pub(super) fn member_name(spelling: &str) -> String {
    let variant = spelling.to_ascii_uppercase().replace(['-', '.'], "_");
    if variant.starts_with(|character: char| character.is_ascii_digit()) {
        format!("MEMBER_{variant}")
    } else {
        variant
    }
}

fn enumerations(reg: &Registry) -> String {
    let mut source = String::from(
        "\"\"\"Declared string enumerations; ordinal codes are presentation only.\"\"\"\n\nfrom enum import StrEnum\n",
    );
    let mut mappings = Vec::new();
    for spec in reg.enums() {
        let name = pascal(spec.name);
        let _ = writeln!(
            source,
            "\n\nclass {name}(StrEnum):\n    \"\"\"The declared {} enumeration.\"\"\"\n",
            spec.name
        );
        for member in &spec.members {
            let variant = member_name(member.name);
            let annotation = if variant == "PASS" {
                "  # noqa: S105 -- declared enumeration spelling"
            } else {
                ""
            };
            let _ = writeln!(source, "    {variant} = {:?}{annotation}", member.name);
        }
        if let Some(module) = spec.idaes_source {
            let members = spec
                .members
                .iter()
                .filter_map(|member| {
                    member
                        .idaes_name
                        .map(|idaes| format!("{:?}: {idaes:?}", member.name))
                })
                .collect::<Vec<_>>()
                .join(", ");
            mappings.push(format!("    {name:?}: ({module:?}, {{{members}}}),\n"));
        }
    }
    source.push_str("\n\nIDAES_NAMES: dict[str, tuple[str, dict[str, str]]] = {\n");
    source.push_str(&mappings.concat());
    source.push_str("}\n");
    source
}

fn values() -> Result<String, SchemaError> {
    let mut source = include_str!("values.py.template")
        .replace("@SEMANTIC_WIDTH@", &pse_ids::SemanticId::WIDTH.to_string())
        .replace("@CONTENT_WIDTH@", &pse_ids::ContentHash::WIDTH.to_string());
    let mut declarations = String::new();
    for use_ in [
        ExtensionUse::DimensionVector,
        ExtensionUse::QuantityValue,
        ExtensionUse::Bound,
        ExtensionUse::SourceSpan,
    ] {
        types::storage(
            &use_.spec().storage(),
            &pascal(&use_.name()),
            &mut declarations,
        )?;
    }
    // This module owns the scalar helpers and extension classes; its projections use
    // local names instead of importing itself through the public package.
    source.push_str(&declarations.replace("v.", ""));
    Ok(source)
}
