// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Generated frozen attrs rows and Arrow extension contracts.

mod extensions;
mod identifiers;
mod types;

use std::fmt::Write as _;

use crate::model::ExtensionUse;
use crate::{Registry, SchemaError};

use super::rust::types::pascal;
use super::{GeneratedTree, Language};

const ROOT: &str = "python/pse/contracts";
const HEADER: &str = "# SPDX-License-Identifier: MIT OR Apache-2.0\n# Copyright (c) 2026 Paul Heyse\n# @generated by pse-schema; do not edit\n";

fn error(reason: String) -> SchemaError {
    SchemaError::Codegen {
        language: "python",
        reason,
    }
}

fn emit(tree: &mut GeneratedTree, name: &str, source: &str) {
    tree.files.insert(
        format!("{ROOT}/{name}.py").into(),
        format!("{HEADER}{source}").into_bytes(),
    );
}

pub(super) fn generate(reg: &Registry) -> Result<GeneratedTree, SchemaError> {
    let mut tree = GeneratedTree::empty(Language::Python.roots());
    emit(&mut tree, "enums", &enumerations(reg));
    emit(&mut tree, "values", &values()?);
    emit(&mut tree, "extension_types", &extensions::render(reg)?);
    emit(&mut tree, "identities", &identities(reg));
    emit(&mut tree, "structures", &structures(reg)?);
    let mut namespaces = std::collections::BTreeMap::<&str, (String, bool)>::new();
    for spec in reg.relations() {
        let namespace = spec.key.namespace.as_str();
        let stem = format!("{}{}", pascal(namespace), pascal(spec.key.name));
        let mut declarations = String::new();
        let mut typed_ids = false;
        let fields = spec
            .columns
            .iter()
            .map(|column| {
                let ty = match column.identity().and_then(|name| reg.identity(name)) {
                    // A typed id annotates as its alias and validates as its base value.
                    Some(identity) => {
                        typed_ids = true;
                        types::Type {
                            equality_key: "v.scalar_key".into(),
                            item_key: None,
                            annotation: format!(
                                "i.{}",
                                super::rust::identities::type_name(identity.name)
                            ),
                            validator: format!(
                                "attrs.validators.instance_of(v.{})",
                                base_class(identity.base)
                            ),
                        }
                    }
                    None => {
                        typed_ids |= carries_identity(column);
                        types::logical(
                            &column.value_type(),
                            &format!("{stem}Field{}", pascal(column.name())),
                            &mut declarations,
                        )?
                    }
                };
                Ok((
                    column.name().to_owned(),
                    types::optional(ty, column.nullable()),
                ))
            })
            .collect::<Result<Vec<_>, SchemaError>>()?;
        declarations.push_str(&types::structure(&format!("{stem}Row"), &fields));
        let entry = namespaces.entry(namespace).or_default();
        entry.0.push_str(&declarations);
        entry.1 |= typed_ids;
    }
    for (namespace, (declarations, typed_ids)) in namespaces {
        let mut source = format!(
            "\"\"\"Typed rows in the {namespace} namespace.\"\"\"\n\nimport builtins as b\n"
        );
        if declarations.contains(": datetime") {
            source.push_str("from datetime import datetime\n");
        }
        source.push_str("\nimport attrs\n\n");
        // Sorted by module, as the linter's import order requires.
        if uses_alias(&declarations, "e") {
            source.push_str("from pse.contracts import enums as e\n");
        }
        if typed_ids {
            source.push_str("from pse.contracts import identities as i\n");
        }
        if references_structures(reg, &declarations) {
            source.push_str("from pse.contracts import structures as s\n");
        }
        if uses_alias(&declarations, "v") {
            source.push_str("from pse.contracts import values as v\n");
        }
        source.push_str(&declarations);
        emit(&mut tree, namespace, &source);
    }
    emit(
        &mut tree,
        "__init__",
        &format!(
            "\"\"\"Contracts generated from the sole registry declaration.\"\"\"\n\nfrom pse.contracts.extension_types import EXTENSION_NAMES, register_all\n\n__all__ = [\"EXTENSION_NAMES\", \"REGISTRY_FINGERPRINT\", \"register_all\"]\n\nREGISTRY_FINGERPRINT = {:?}\n",
            reg.fingerprint().to_prefixed()
        ),
    );
    Ok(tree)
}

/// Whether generated declarations qualify a name through a module alias: `alias.` at an
/// identifier boundary, so prose such as "nested value." does not import `e`.
fn uses_alias(declarations: &str, alias: &str) -> bool {
    let qualifier = format!("{alias}.");
    declarations.match_indices(&qualifier).any(|(at, _)| {
        declarations[..at]
            .chars()
            .next_back()
            .is_none_or(|before| !(before.is_alphanumeric() || before == '_' || before == '.'))
    })
}

/// Whether generated declarations reference a named structure.
fn references_structures(reg: &Registry, declarations: &str) -> bool {
    reg.structures()
        .keys()
        .any(|name| declarations.contains(&format!("s.{name}")))
}

/// The named structures a contract nests directly: a nested named structure is referenced
/// by name, so its own nesting belongs to its own declaration.
fn nested_names(contract: &crate::model::FieldContract, out: &mut Vec<String>) {
    for child in contract.children() {
        match child.structure_name() {
            Some(name) => out.push(name.to_owned()),
            None => nested_names(&child, out),
        }
    }
}

/// Named structures in dependency order: each after every named structure it nests, and
/// with deterministic ties from sorted graph insertion. A class body evaluates its annotations and validators when it is
/// defined, so a structure declared before one it nests raises a `NameError` on import.
fn dependency_order(
    structures: &std::collections::BTreeMap<String, crate::model::FieldContract>,
) -> Result<Vec<&str>, SchemaError> {
    let mut graph = petgraph::graph::DiGraph::<&str, ()>::new();
    // Sorted insertion makes ties independent of declaration traversal order.
    let nodes = structures
        .keys()
        .map(|name| (name.as_str(), graph.add_node(name.as_str())))
        .collect::<std::collections::BTreeMap<_, _>>();
    for (name, contract) in structures {
        let mut nested = Vec::new();
        nested_names(&contract.clone().unnamed(), &mut nested);
        nested.sort();
        nested.dedup();
        for dependency in nested {
            let from = nodes
                .get(dependency.as_str())
                .ok_or_else(|| error(format!("named structure {dependency} is not declared")))?;
            graph.add_edge(*from, nodes[name.as_str()], ());
        }
    }
    petgraph::algo::toposort(&graph, None)
        .map(|order| order.into_iter().map(|node| graph[node]).collect())
        .map_err(|cycle| {
            error(format!(
                "named structure {} participates in a nesting cycle",
                graph[cycle.node_id()]
            ))
        })
}

/// Every registry named structure, declared once (Plan 22 X11) and in dependency order;
/// relation rows refer to these classes by name.
fn structures(reg: &Registry) -> Result<String, SchemaError> {
    let mut declarations = String::new();
    let mut typed_ids = false;
    for name in dependency_order(reg.structures())? {
        let contract = &reg.structures()[name];
        typed_ids |= carries_identity(contract);
        types::logical(&contract.clone().unnamed(), name, &mut declarations)?;
    }
    let mut source = String::from("\"\"\"Registry named structures, each declared once.\"\"\"\n");
    if declarations.is_empty() {
        return Ok(source);
    }
    source.push_str("\nimport builtins as b\n");
    if declarations.contains(": datetime") {
        source.push_str("from datetime import datetime\n");
    }
    source.push_str("\nimport attrs\n\n");
    if uses_alias(&declarations, "e") {
        source.push_str("from pse.contracts import enums as e\n");
    }
    if typed_ids {
        source.push_str("from pse.contracts import identities as i\n");
    }
    if uses_alias(&declarations, "v") {
        source.push_str("from pse.contracts import values as v\n");
    }
    // A structure nested in another refers to it locally, not through the package.
    let mut local = declarations;
    for name in reg.structures().keys() {
        local = local.replace(&format!("s.{name}"), name);
    }
    source.push_str(&local);
    Ok(source)
}

/// Whether a value nested in the column names an entity identity.
fn carries_identity(column: &crate::model::FieldContract) -> bool {
    column.extension().is_none()
        && column
            .children()
            .iter()
            .any(|child| child.identity().is_some() || carries_identity(child))
}

/// The Python class of an identity's base value.
const fn base_class(base: crate::model::IdentityBase) -> &'static str {
    match base {
        crate::model::IdentityBase::SemanticId => "SemanticId",
        crate::model::IdentityBase::ContentHash => "ContentHash",
    }
}

/// One `NewType` per declared entity identity: the alias a type checker keeps apart
/// from every other identity, over the validated base class (ADR-0115).
fn identities(reg: &Registry) -> String {
    let mut source = String::from(
        "\"\"\"Declared entity identities: distinct aliases of their base identity values.\"\"\"\n",
    );
    if reg.identities().is_empty() {
        return source;
    }
    source.push_str("\nfrom typing import NewType\n\nfrom pse.contracts import values as v\n");
    for identity in reg.identities() {
        let name = super::rust::identities::type_name(identity.name);
        let _ = write!(
            source,
            "\n# {} (entity identity `{}`).\n{name} = NewType({name:?}, v.{})\n",
            identity.doc.trim_end_matches('.'),
            identity.name,
            base_class(identity.base)
        );
    }
    source
}

/// The Python member name of a declared enumeration member spelling.
pub(super) fn member_name(spelling: &str) -> String {
    let variant = spelling.to_ascii_uppercase().replace(['-', '.'], "_");
    if variant.starts_with(|character: char| character.is_ascii_digit()) {
        format!("MEMBER_{variant}")
    } else {
        variant
    }
}

fn enumerations(reg: &Registry) -> String {
    let mut source = String::from(
        "\"\"\"Declared string enumerations; ordinal codes are presentation only.\"\"\"\n\nfrom enum import StrEnum\n",
    );
    let mut mappings = Vec::new();
    for spec in reg.enums() {
        let name = pascal(spec.name);
        let _ = writeln!(
            source,
            "\n\nclass {name}(StrEnum):\n    \"\"\"The declared {} enumeration.\"\"\"\n",
            spec.name
        );
        for member in &spec.members {
            let variant = member_name(member.name);
            let annotation = if variant == "PASS" {
                "  # noqa: S105 -- declared enumeration spelling"
            } else {
                ""
            };
            let _ = writeln!(source, "    {variant} = {:?}{annotation}", member.name);
        }
        if let Some(module) = spec.idaes_source {
            let members = spec
                .members
                .iter()
                .filter_map(|member| {
                    member
                        .idaes_name
                        .map(|idaes| format!("{:?}: {idaes:?}", member.name))
                })
                .collect::<Vec<_>>()
                .join(", ");
            mappings.push(format!("    {name:?}: ({module:?}, {{{members}}}),\n"));
        }
    }
    source.push_str("\n\nIDAES_NAMES: dict[str, tuple[str, dict[str, str]]] = {\n");
    source.push_str(&mappings.concat());
    source.push_str("}\n");
    source
}

fn values() -> Result<String, SchemaError> {
    let mut source = include_str!("values.py.template")
        .replace("@SEMANTIC_WIDTH@", &pse_ids::SemanticId::WIDTH.to_string())
        .replace("@CONTENT_WIDTH@", &pse_ids::ContentHash::WIDTH.to_string());
    let mut declarations = String::new();
    for use_ in [
        ExtensionUse::DimensionVector,
        ExtensionUse::QuantityValue,
        ExtensionUse::Bound,
        ExtensionUse::SourceSpan,
    ] {
        types::storage(
            &use_.spec().storage(),
            &pascal(&use_.name()),
            &mut declarations,
        )?;
    }
    // This module owns the scalar helpers and extension classes; its projections use
    // local names instead of importing itself through the public package.
    source.push_str(&declarations.replace("v.", ""));
    Ok(source)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, reason = "assertions over a small test registry")]

    use crate::model::{Authority, FieldContract as F, Namespace, RelationDecl, SnapshotClass};
    use arrow_schema::DataType;

    /// A named structure is declared after every named structure it nests, whatever their
    /// names; alphabetical order would define `Alpha` before the `Zulu` it validates with.
    #[test]
    fn nested_named_structures_are_declared_in_dependency_order() {
        let zulu =
            || F::structure(vec![F::native(DataType::Utf8).with_name("symbol")]).named("Zulu");
        let alpha = F::structure(vec![
            F::native(DataType::Int64).with_name("count"),
            F::list(zulu()).with_name("factors"),
        ])
        .named("Alpha");
        let middle = F::structure(vec![alpha.clone().with_name("inner")]).named("Middle");
        let mut builder = crate::RegistryBuilder::new();
        builder.declare_relation(
            RelationDecl::new(
                Namespace::Authored,
                "nested",
                1,
                Authority::Authored,
                SnapshotClass::Model,
                "Nested named structure test relation",
            )
            .pk(&["id"])
            .columns(vec![
                F::key("id", F::native(DataType::Int64), "Key"),
                F::payload("middle", middle, "Middle"),
                F::payload("zulus", F::list(zulu()), "Zulus"),
            ]),
        );
        let registry = builder.build().unwrap();
        assert_eq!(
            super::dependency_order(registry.structures()).unwrap(),
            ["Zulu", "Alpha", "Middle"]
        );
        let source = super::structures(&registry).unwrap();
        let position = |name: &str| source.find(&format!("class {name}:")).unwrap();
        assert!(position("Zulu") < position("Alpha"), "{source}");
        assert!(position("Alpha") < position("Middle"), "{source}");
        // Nested structures refer to one another locally, never through the package.
        assert!(
            !source.contains("s.Zulu") && source.contains("instance_of(Zulu)"),
            "{source}"
        );
    }
    #[test]
    fn dependency_cycles_and_missing_declarations_are_attributable() {
        let reference =
            F::structure(vec![F::native(DataType::Utf8).with_name("value")]).named("Alpha");
        let recursive = F::structure(vec![reference.with_name("child")]).named("Alpha");
        let structures = std::collections::BTreeMap::from([("Alpha".to_owned(), recursive)]);
        assert!(
            super::dependency_order(&structures)
                .unwrap_err()
                .to_string()
                .contains("Alpha")
        );
        let missing = F::structure(vec![
            F::structure(vec![F::native(DataType::Utf8).with_name("value")])
                .named("Missing")
                .with_name("child"),
        ])
        .named("Root");
        let structures = std::collections::BTreeMap::from([("Root".to_owned(), missing)]);
        assert!(
            super::dependency_order(&structures)
                .unwrap_err()
                .to_string()
                .contains("Missing")
        );
    }

    #[test]
    fn independent_dependency_ties_are_deterministic() {
        let structures = ["Zulu", "Alpha", "Middle"]
            .into_iter()
            .map(|name| {
                (
                    name.to_owned(),
                    F::structure(vec![F::native(DataType::Utf8).with_name("value")]).named(name),
                )
            })
            .collect();
        let first = super::dependency_order(&structures).unwrap();
        assert_eq!(first, super::dependency_order(&structures).unwrap());
        assert_eq!(first.len(), 3);
    }
}
