// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! The operational store's DDL, rendered from the registry (ADR-0114 Outcome 22).
//!
//! One ENUM type per registry enumeration a store relation uses; a `content_hash` domain
//! over 32-byte `bytea`; one domain per entity identity; one table per store relation
//! with NOT NULL, a named primary key, named unique keys, named CHECKs from the declared
//! row checks and field domains, and named foreign keys added once every table exists.
//! There are no defaults, no `ON DELETE CASCADE` and no identity-minting functions: those
//! are access-path and lifecycle decisions (`physical.sql`, the runtime), not meaning.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use arrow_schema::{DataType, TimeUnit};

use crate::model::{ExtensionUse, FieldContract, IdentityBase, IntegerRange, RelationSpec};
use crate::{Registry, SchemaError};

use super::names::{
    CONTENT_HASH_DOMAIN, bounded, constraint, enum_type, identity_domain, qualified, quote,
};

/// The enumerations store columns use, by registry name.
pub(super) fn enums(reg: &Registry) -> BTreeSet<&str> {
    pse_schema::store::relations(reg)
        .into_iter()
        .flat_map(|(_, spec)| spec.columns.iter().flat_map(FieldContract::enum_domains))
        .filter_map(|name| reg.enum_spec(&name).map(|spec| spec.name))
        .collect()
}

/// The entity identities store columns carry, by name.
pub(super) fn identities(reg: &Registry) -> BTreeSet<&str> {
    pse_schema::store::relations(reg)
        .into_iter()
        .flat_map(|(_, spec)| spec.columns.iter().filter_map(FieldContract::identity))
        .filter_map(|name| reg.identity(name).map(|identity| identity.name))
        .collect()
}

pub(super) fn render(reg: &Registry) -> Result<String, SchemaError> {
    let mut sql = format!(
        "-- SPDX-License-Identifier: MIT OR Apache-2.0\n-- Copyright (c) 2026 Paul Heyse\n-- @generated by pse-schema; do not edit\n--\n-- The operational store's schema, generated from the registry relations\n-- runtime.{}<table> (ADR-0114 Outcome 22). Indexes, defaults and grants are in\n-- crates/pse-operations/physical.sql.\n\nCREATE SCHEMA {};\n",
        pse_schema::store::RELATION_PREFIX,
        pse_schema::store::SCHEMA
    );
    let content_hash = qualified(CONTENT_HASH_DOMAIN);
    let _ = write!(
        sql,
        "\n-- A 32-byte BLAKE3 content hash (blueprint §5.1).\nCREATE DOMAIN {content_hash} AS bytea\n    CONSTRAINT {} CHECK (octet_length(VALUE) = 32);\n",
        bounded(format!("{CONTENT_HASH_DOMAIN}_width"))?
    );
    for name in enums(reg) {
        let spec = reg
            .enum_spec(name)
            .ok_or_else(|| super::error(format!("unknown enum {name}")))?;
        let labels = spec
            .members
            .iter()
            .map(|member| literal(member.name))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = write!(
            sql,
            "\n-- Registry enumeration {name}.\nCREATE TYPE {} AS ENUM ({labels});\n",
            qualified(&bounded(enum_type(name))?)
        );
    }
    for name in identities(reg) {
        let identity = reg
            .identity(name)
            .ok_or_else(|| super::error(format!("unknown identity {name}")))?;
        let base = match identity.base {
            IdentityBase::SemanticId => "uuid".to_owned(),
            IdentityBase::ContentHash => content_hash.clone(),
        };
        let _ = write!(
            sql,
            "\n-- Entity identity {name}: {}\nCREATE DOMAIN {} AS {base};\n",
            identity.doc,
            qualified(&bounded(identity_domain(name))?)
        );
    }
    let mut references = Vec::new();
    for (table, spec) in pse_schema::store::relations(reg) {
        table_sql(reg, table, spec, &mut sql, &mut references)?;
    }
    for reference in references {
        sql.push_str(&reference);
    }
    Ok(sql)
}

fn table_sql(
    reg: &Registry,
    table: &str,
    spec: &RelationSpec,
    sql: &mut String,
    references: &mut Vec<String>,
) -> Result<(), SchemaError> {
    let table_name = bounded(table.to_owned())?;
    let mut lines = Vec::new();
    for column in &spec.columns {
        let null = if column.nullable() { "" } else { " NOT NULL" };
        lines.push(format!(
            "{} {}{null}",
            quote(column.name()),
            column_type(reg, spec, column)?
        ));
    }
    lines.push(format!(
        "CONSTRAINT {} PRIMARY KEY ({})",
        bounded(format!("{table}_pkey"))?,
        columns(spec.primary_key.iter().copied())
    ));
    for key in &spec.unique_keys {
        lines.push(format!(
            "CONSTRAINT {} UNIQUE ({})",
            constraint(table, key.name, "key")?,
            columns(key.columns.iter().copied())
        ));
    }
    let mut checks = BTreeMap::new();
    for column in &spec.columns {
        let name = quote(column.name());
        // The registry's Float64 is finite (the native storage predicate refuses NaN and
        // infinity); PostgreSQL orders NaN above every number, so the bounds exclude it too.
        match column.data_type() {
            DataType::Float64 => {
                checks.insert(
                    constraint(table, column.name(), "finite")?,
                    format!(
                        "{name} > '-Infinity'::double precision AND {name} < 'Infinity'::double precision"
                    ),
                );
            }
            DataType::List(element) => {
                // Arrays hold exactly the declared elements: never null when the element is
                // required, and finite when they are Float64.
                let mut rules = Vec::new();
                if !element.is_nullable() {
                    rules.push(format!("array_position({name}, NULL) IS NULL"));
                }
                if element.data_type() == &DataType::Float64 {
                    rules.push(format!(
                        "NOT ({name} && ARRAY['NaN', 'Infinity', '-Infinity']::double precision[])"
                    ));
                }
                if !rules.is_empty() {
                    checks.insert(
                        constraint(table, column.name(), "elements")?,
                        rules.join(" AND "),
                    );
                }
            }
            _ => {}
        }
        if let Some(range) = IntegerRange::from_field(column.field())? {
            checks.insert(
                constraint(table, column.name(), "range")?,
                format!("{name} BETWEEN {} AND {}", range.minimum, range.maximum),
            );
        }
    }
    for (name, predicate) in &spec.checks {
        // Declared checks are written in the dialect both targets share (they are
        // parsed by DataFusion at admission and by PostgreSQL here).
        checks.insert(constraint(table, name, "check")?, predicate.clone());
    }
    for (name, predicate) in checks {
        lines.push(format!("CONSTRAINT {name} CHECK ({predicate})"));
    }
    let _ = write!(
        sql,
        "\n-- {}\nCREATE TABLE {} (\n    {}\n);\n",
        spec.qualified_name(),
        qualified(&quote(&table_name)),
        lines.join(",\n    ")
    );
    let mut foreign = Vec::new();
    for column in &spec.columns {
        if let Some(fk) = column.fk() {
            foreign.push((
                constraint(table, column.name(), "fkey")?,
                vec![column.name()],
                fk.relation,
                vec![fk.column],
            ));
        }
    }
    for reference in &spec.foreign_keys {
        foreign.push((
            constraint(table, reference.name, "fkey")?,
            reference.columns.clone(),
            reference.target,
            reference.target_columns.clone(),
        ));
    }
    for (name, local, target, remote) in foreign {
        let target_spec = reg
            .relation(target)
            .ok_or_else(|| super::error(format!("unknown reference target {target}")))?;
        let target_table = pse_schema::store::table(target_spec).ok_or_else(|| {
            super::error(format!(
                "{} references {target}, which is not a store relation",
                spec.qualified_name()
            ))
        })?;
        references.push(format!(
            "\nALTER TABLE {} ADD CONSTRAINT {name}\n    FOREIGN KEY ({}) REFERENCES {} ({});\n",
            qualified(&quote(table)),
            columns(local.into_iter()),
            qualified(&quote(target_table)),
            columns(remote.into_iter())
        ));
    }
    Ok(())
}

fn columns<'a>(names: impl Iterator<Item = &'a str>) -> String {
    names.map(quote).collect::<Vec<_>>().join(", ")
}

fn literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// The PostgreSQL type of a store column.
fn column_type(
    reg: &Registry,
    spec: &RelationSpec,
    column: &FieldContract,
) -> Result<String, SchemaError> {
    if let Some(identity) = column.identity() {
        reg.identity(identity)
            .ok_or_else(|| super::error(format!("unknown identity {identity}")))?;
        return Ok(qualified(&identity_domain(identity)));
    }
    value_type(column).ok_or_else(|| {
        super::error(format!(
            "{}.{} has no PostgreSQL representation ({})",
            spec.qualified_name(),
            column.name(),
            column.data_type()
        ))
    })
}

fn value_type(column: &FieldContract) -> Option<String> {
    match column.extension() {
        Some(ExtensionUse::SemanticId) => return Some("uuid".into()),
        Some(ExtensionUse::ContentHash) => return Some(qualified(CONTENT_HASH_DOMAIN)),
        Some(ExtensionUse::Enum(name)) => return Some(qualified(&enum_type(name))),
        Some(_) => return None,
        None => {}
    }
    if column.document() == Some(crate::model::field::JSON_DOCUMENT) {
        return Some("jsonb".into());
    }
    Some(match column.data_type() {
        DataType::Boolean => "boolean".into(),
        DataType::Int16 => "smallint".into(),
        DataType::Int32 => "integer".into(),
        DataType::Int64 => "bigint".into(),
        DataType::Float64 => "double precision".into(),
        DataType::Utf8 => "text".into(),
        DataType::Binary => "bytea".into(),
        DataType::Timestamp(TimeUnit::Microsecond, Some(zone)) if zone.as_ref() == "UTC" => {
            "timestamptz".into()
        }
        DataType::List(element) => {
            let element = FieldContract::from_field(element.as_ref().clone());
            if element.data_type().is_nested() {
                return None;
            }
            format!("{}[]", value_type(&element)?)
        }
        _ => return None,
    })
}
