// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Cornucopia's type mapping: which Rust type each store type decodes to and encodes from
//! (ADR-0114 Outcome 25). ENUM types map to the generated registry enums, identity
//! domains to the generated typed ids, and each table's composite row type to the
//! registry row it stores (Plan 22 X7), so a whole-row statement returns that row. Their
//! `ToSql`/`FromSql` live in `pse-model` behind its `postgres` feature.

use std::fmt::Write as _;

use crate::Registry;
use crate::codegen::rust::types::pascal;

use super::names::{CONTENT_HASH_DOMAIN, enum_type, identity_domain, qualified};

pub(super) fn render(reg: &Registry) -> String {
    // A plain mapping is a copyable scalar; a row is owned (`is-copy = false`).
    let mut mapping = vec![
        (
            "pg_catalog.timestamptz".to_owned(),
            "\"chrono::DateTime<chrono::Utc>\"".to_owned(),
        ),
        (
            "pg_catalog.uuid".to_owned(),
            "\"pse_ids::SemanticId\"".to_owned(),
        ),
        (
            qualified(CONTENT_HASH_DOMAIN),
            "\"pse_ids::ContentHash\"".to_owned(),
        ),
    ];
    for name in super::ddl::enums(reg) {
        mapping.push((
            qualified(&enum_type(name)),
            format!("\"pse_model::generated::enums::{}\"", pascal(name)),
        ));
    }
    for name in super::ddl::identities(reg) {
        mapping.push((
            qualified(&identity_domain(name)),
            format!(
                "\"pse_model::generated::identities::{}\"",
                crate::codegen::rust::identities::type_name(name)
            ),
        ));
    }
    for (table, spec) in pse_schema::store::relations(reg) {
        let namespace = spec.key.namespace.as_str();
        mapping.push((
            qualified(table),
            format!(
                "{{ rust-type = \"pse_model::generated::{namespace}::{}::{}{}Row\", is-copy = false }}",
                spec.key.name,
                pascal(namespace),
                pascal(spec.key.name)
            ),
        ));
    }
    mapping.sort();
    let mut toml = String::from(
        "# SPDX-License-Identifier: MIT OR Apache-2.0\n# Copyright (c) 2026 Paul Heyse\n# @generated by pse-schema; do not edit\n#\n# Cornucopia type mapping of the operational store (ADR-0114 Outcome 25).\n\n[types.mapping]\n",
    );
    for (postgres, rust) in mapping {
        let _ = writeln!(toml, "\"{postgres}\" = {rust}");
    }
    toml
}
