# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# Experimental until Plan 15 qualification; stable remains the canonical toolchain.
nightly = "nightly-2026-09-13"
frontend_threads = 1
jobs = 16
cache_size = "32G"
free_space_gib = 50
