# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
# Local compiler-cache and storage budgets. The toolchain is rust-toolchain.toml's dated
# nightly; nothing here names another one (ADR-0122).
cache_size = "100G"
free_space_gib = 50
