#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
"""Decision-record tooling for pse-arrow (standard library only, Python >= 3.11).

    python3 scripts/adr.py new <slug> --title "..."   allocate the next number
    python3 scripts/adr.py lint                       validate every record
    python3 scripts/adr.py index [--check]            regenerate the index
    python3 scripts/adr.py supersede <old> <new>      symmetric supersession

The front-matter parser understands the small YAML subset the template uses:
scalars, ``[a, b]`` inline lists and ``null``. PyYAML is deliberately not a
dependency: the tool has to run in a bare CI container before any environment
is synced.
"""

from __future__ import annotations

import argparse
import datetime
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ADR_DIR = ROOT / "docs" / "adr"
TEMPLATE = ADR_DIR / "template.md"
README = ADR_DIR / "README.md"
SUMMARY = ROOT / "docs" / "SUMMARY.md"
BLUEPRINT = ROOT / "docs" / "authoritative_design" / "blueprint.md"

FILENAME_RE = re.compile(r"^\d{4}-[a-z0-9-]+\.md$")
ID_RE = re.compile(r"^ADR-(\d{4})$")
PRINCIPLE_RE = re.compile(r"^DM-\d{2}$")
SECTION_RE = re.compile(r"^§([0-9]+(?:\.[0-9]+)*|[A-Z][0-9]+)$")
HEADING_RE = re.compile(r"^#{2,4}\s+(?:([0-9]+(?:\.[0-9]+)*)|([A-Z][0-9]+))\.?\s")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

REQUIRED_KEYS = (
    "id",
    "title",
    "status",
    "date",
    "deciders",
    "level",
    "principles",
    "blueprint",
    "review",
    "evidence",
    "supersedes",
    "superseded-by",
    "revisit",
    "verification",
)
STATUSES = {"proposed", "accepted", "rejected", "deprecated", "superseded"}
LEVELS = {"decision", "should-deviation", "must-gap"}
EVIDENCE = {
    "Proposed",
    "Interface-checked",
    "Implemented",
    "Tested",
    "Measured",
    "Formally established",
}
MUTABLE_KEYS = {"status", "superseded-by"}
MUTABLE_SECTION = "Status history"

README_PREAMBLE = """# Decision records

<!-- @generated by scripts/adr.py index; do not edit -->

Each record states one decision, the blueprint sections it governs, the charter
§H fields (principles, level, evidence, revisit trigger, verification), and the
design-review finding that motivated it. A record is immutable once accepted:
it changes only by superseding it with a new record, or by a status edit and an
appended `## Status history` line. `docs/authoritative_design/blueprint.md` is
the authoritative design; these records say *why* it reads the way it does.

Run `just adr-new <slug>` to start one and `just adr-lint` before opening the PR.
Open items that were deliberately deferred live in [`register.md`](register.md).
"""


# --------------------------------------------------------------------------- #
# front matter
# --------------------------------------------------------------------------- #
def parse_scalar(raw: str) -> object:
    raw = raw.strip()
    if raw in ("", "null", "~"):
        return None
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [parse_scalar(part) for part in inner.split(",")]
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        return raw[1:-1]
    return raw


def split_front_matter(text: str, where: str) -> tuple[dict[str, object], str]:
    if not text.startswith("---\n"):
        raise ValueError(f"{where}: missing YAML front matter")
    end = text.find("\n---\n", 3)
    if end < 0:
        raise ValueError(f"{where}: unterminated YAML front matter")
    front: dict[str, object] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"{where}: unparsable front-matter line {line!r}")
        key, _, value = line.partition(":")
        front[key.strip()] = parse_scalar(value)
    return front, text[end + 5 :]


def as_list(value: object) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v) for v in value]
    return [str(value)]


def body_sections(body: str) -> dict[str, str]:
    sections: dict[str, list[str]] = {"": []}
    current = ""
    for line in body.splitlines():
        if line.startswith("## "):
            current = line[3:].strip()
            sections.setdefault(current, [])
        else:
            sections[current].append(line)
    return {k: "\n".join(v).strip() for k, v in sections.items()}


# --------------------------------------------------------------------------- #
# repository facts
# --------------------------------------------------------------------------- #
def adr_paths() -> list[Path]:
    return sorted(
        p
        for p in ADR_DIR.glob("*.md")
        if p.name not in {"README.md", "template.md", "register.md"}
    )


def blueprint_sections() -> set[str]:
    found: set[str] = set()
    for line in BLUEPRINT.read_text(encoding="utf-8").splitlines():
        m = HEADING_RE.match(line)
        if m:
            found.add(m.group(1) or m.group(2))
    return found


def git(*args: str) -> tuple[int, str]:
    proc = subprocess.run(
        ["git", "-C", str(ROOT), *args], capture_output=True, text=True, check=False
    )
    return proc.returncode, proc.stdout


def origin_main_exists() -> bool:
    return git("rev-parse", "--verify", "--quiet", "origin/main")[0] == 0


# --------------------------------------------------------------------------- #
# lint
# --------------------------------------------------------------------------- #
def lint() -> int:
    errors: list[str] = []
    paths = adr_paths()
    if not paths:
        print("adr: no records under docs/adr/", file=sys.stderr)
        return 1
    sections = blueprint_sections()
    records: dict[str, dict[str, object]] = {}

    for path in paths:
        rel = path.relative_to(ROOT)
        if not FILENAME_RE.match(path.name):
            errors.append(f"{rel}: filename must match ^\\d{{4}}-[a-z0-9-]+\\.md$")
            continue
        try:
            front, _body = split_front_matter(
                path.read_text(encoding="utf-8"), str(rel)
            )
        except ValueError as exc:
            errors.append(str(exc))
            continue

        missing = [k for k in REQUIRED_KEYS if k not in front]
        if missing:
            errors.append(f"{rel}: missing front-matter keys {', '.join(missing)}")
        number = path.name[:4]
        ident = str(front.get("id", ""))
        m = ID_RE.match(ident)
        if not m:
            errors.append(f"{rel}: id must be ADR-NNNN, found {ident!r}")
        elif m.group(1) != number:
            errors.append(f"{rel}: id {ident} does not match filename number {number}")
        else:
            records[ident] = front

        if front.get("status") not in STATUSES:
            errors.append(
                f"{rel}: status {front.get('status')!r} not in {sorted(STATUSES)}"
            )
        if front.get("level") not in LEVELS:
            errors.append(
                f"{rel}: level {front.get('level')!r} not in {sorted(LEVELS)}"
            )
        if front.get("evidence") not in EVIDENCE:
            errors.append(
                f"{rel}: evidence {front.get('evidence')!r} is not a charter §D label"
            )
        if not DATE_RE.match(str(front.get("date", ""))):
            errors.append(f"{rel}: date must be YYYY-MM-DD")
        for principle in as_list(front.get("principles")):
            if not PRINCIPLE_RE.match(principle):
                errors.append(f"{rel}: principle {principle!r} must match DM-NN")
        for citation in as_list(front.get("blueprint")):
            sm = SECTION_RE.match(citation)
            if not sm:
                errors.append(
                    f"{rel}: blueprint citation {citation!r} must look like §14.3 or §D1"
                )
            elif sm.group(1) not in sections:
                errors.append(
                    f"{rel}: blueprint citation {citation} resolves to no heading in blueprint.md"
                )
        review = str(front.get("review") or "")
        if not review.startswith("not-required:"):
            target = ROOT / review.split("#", 1)[0]
            if not target.is_file():
                errors.append(f"{rel}: review path {review!r} does not exist")
        for key in ("revisit", "verification"):
            if not str(front.get(key) or "").strip():
                errors.append(f"{rel}: {key} must state something observable")

    numbers = sorted(int(p.name[:4]) for p in paths if FILENAME_RE.match(p.name))
    expected = list(range(1, len(numbers) + 1))
    if numbers != expected:
        errors.append(f"adr numbering is not contiguous from 0001: {numbers}")

    for ident, front in records.items():
        for other in as_list(front.get("supersedes")):
            peer = records.get(other)
            if peer is None:
                errors.append(f"{ident}: supersedes unknown record {other}")
            elif str(peer.get("superseded-by") or "") != ident:
                errors.append(
                    f"{ident}: supersedes {other}, which does not name it in superseded-by"
                )
        by = front.get("superseded-by")
        if by:
            peer = records.get(str(by))
            if peer is None:
                errors.append(f"{ident}: superseded-by unknown record {by}")
            elif ident not in as_list(peer.get("supersedes")):
                errors.append(
                    f"{ident}: superseded-by {by}, which does not name it in supersedes"
                )
            elif front.get("status") != "superseded":
                errors.append(
                    f"{ident}: has superseded-by but status is {front.get('status')!r}"
                )

    errors.extend(lint_immutability(paths))

    generated_readme, generated_summary = render_index()
    if README.exists() and README.read_text(encoding="utf-8") != generated_readme:
        errors.append("docs/adr/README.md is stale; run `python3 scripts/adr.py index`")
    elif not README.exists():
        errors.append(
            "docs/adr/README.md is missing; run `python3 scripts/adr.py index`"
        )
    if SUMMARY.exists() and SUMMARY.read_text(encoding="utf-8") != generated_summary:
        errors.append(
            "docs/SUMMARY.md ADR block is stale; run `python3 scripts/adr.py index`"
        )

    for err in errors:
        print(f"error: {err}", file=sys.stderr)
    if errors:
        print(
            f"adr lint: {len(errors)} problem(s) in {len(paths)} record(s)",
            file=sys.stderr,
        )
        return 1
    print(f"adr lint: {len(paths)} record(s) OK")
    return 0


def lint_immutability(paths: list[Path]) -> list[str]:
    if not origin_main_exists():
        print(
            "note: origin/main does not exist yet; skipping the ADR immutability check"
        )
        return []
    errors: list[str] = []
    for path in paths:
        rel = path.relative_to(ROOT).as_posix()
        code, old_text = git("show", f"origin/main:{rel}")
        if code != 0:
            continue  # new record in this branch
        try:
            old_front, old_body = split_front_matter(old_text, rel)
            new_front, new_body = split_front_matter(
                path.read_text(encoding="utf-8"), rel
            )
        except ValueError as exc:
            errors.append(str(exc))
            continue
        if old_front.get("status") == "proposed":
            continue
        for key in sorted(set(old_front) | set(new_front)):
            if key in MUTABLE_KEYS:
                continue
            if old_front.get(key) != new_front.get(key):
                errors.append(
                    f"{rel}: {key} changed on an accepted record; supersede it instead"
                )
        old_sections, new_sections = body_sections(old_body), body_sections(new_body)
        for name in sorted(set(old_sections) | set(new_sections)):
            if name == MUTABLE_SECTION:
                continue
            if old_sections.get(name) != new_sections.get(name):
                label = name or "(preamble)"
                errors.append(
                    f"{rel}: section '{label}' changed on an accepted record; supersede it instead"
                )
    return errors


# --------------------------------------------------------------------------- #
# index
# --------------------------------------------------------------------------- #
def render_index() -> tuple[str, str]:
    rows, links = [], []
    for path in adr_paths():
        front, _ = split_front_matter(path.read_text(encoding="utf-8"), str(path))
        ident = str(front.get("id"))
        title = str(front.get("title"))
        blueprint = ", ".join(as_list(front.get("blueprint"))) or "—"
        rows.append(
            f"| [{ident}]({path.name}) | {title} | {front.get('status')} "
            f"| {front.get('date')} | {blueprint} | {front.get('revisit')} |"
        )
        links.append(f"  - [{ident}: {title}]({ADR_DIR.name}/{path.name})")

    readme = (
        README_PREAMBLE
        + "\n| ID | Title | Status | Date | Blueprint | Revisit |\n"
        + "|---|---|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n"
    )

    summary_text = SUMMARY.read_text(encoding="utf-8") if SUMMARY.exists() else ""
    begin, end = "<!-- adr:begin -->", "<!-- adr:end -->"
    if begin in summary_text and end in summary_text:
        head = summary_text.split(begin)[0]
        tail = summary_text.split(end, 1)[1]
        summary_text = head + begin + "\n" + "\n".join(links) + "\n" + end + tail
    return readme, summary_text


def index(check: bool) -> int:
    readme, summary_text = render_index()
    if check:
        stale = []
        if not README.exists() or README.read_text(encoding="utf-8") != readme:
            stale.append("docs/adr/README.md")
        if SUMMARY.exists() and SUMMARY.read_text(encoding="utf-8") != summary_text:
            stale.append("docs/SUMMARY.md")
        if stale:
            print(
                f"error: stale generated file(s): {', '.join(stale)}", file=sys.stderr
            )
            return 1
        print("adr index: up to date")
        return 0
    README.write_text(readme, encoding="utf-8")
    if SUMMARY.exists():
        SUMMARY.write_text(summary_text, encoding="utf-8")
    print(f"adr index: wrote {README.relative_to(ROOT)} and the SUMMARY block")
    return 0


# --------------------------------------------------------------------------- #
# new / supersede
# --------------------------------------------------------------------------- #
def next_number() -> int:
    return max((int(p.name[:4]) for p in adr_paths()), default=0) + 1


def resolve(ref: str) -> Path:
    digits = re.sub(r"\D", "", ref)[-4:].zfill(4)
    for path in adr_paths():
        if path.name.startswith(digits):
            return path
    raise SystemExit(f"error: no record matching {ref!r}")


def new(slug: str, title: str) -> int:
    if not re.fullmatch(r"[a-z0-9-]+", slug):
        raise SystemExit(f"error: slug {slug!r} must be lowercase kebab-case")
    number = next_number()
    path = ADR_DIR / f"{number:04d}-{slug}.md"
    text = TEMPLATE.read_text(encoding="utf-8")
    text = text.replace("ADR-NNNN", f"ADR-{number:04d}")
    text = text.replace("TITLE", title)
    text = text.replace("YYYY-MM-DD", datetime.date.today().isoformat())
    path.write_text(text, encoding="utf-8")
    print(f"adr new: {path.relative_to(ROOT)}")
    print("next: fill the §H fields, then run `python3 scripts/adr.py index`")
    return 0


def set_field(path: Path, key: str, value: str) -> None:
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith(f"{key}:"):
            lines[i] = f"{key}: {value}\n"
            break
    else:
        raise SystemExit(f"error: {path.name} has no {key}: line")
    path.write_text("".join(lines), encoding="utf-8")


def supersede(old_ref: str, new_ref: str) -> int:
    old, new_path = resolve(old_ref), resolve(new_ref)
    old_front, _ = split_front_matter(old.read_text(encoding="utf-8"), str(old))
    new_front, _ = split_front_matter(
        new_path.read_text(encoding="utf-8"), str(new_path)
    )
    set_field(old, "status", "superseded")
    set_field(old, "superseded-by", str(new_front["id"]))
    predecessors = sorted(
        set(as_list(new_front.get("supersedes"))) | {str(old_front["id"])}
    )
    set_field(new_path, "supersedes", f"[{', '.join(predecessors)}]")
    today = datetime.date.today().isoformat()
    with old.open("a", encoding="utf-8") as handle:
        handle.write(f"- {today} — superseded by {new_front['id']}.\n")
    print(f"adr supersede: {old_front['id']} -> {new_front['id']}")
    print(
        "next: append the reason to the new record's Status history, then run `index`"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="adr.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_new = sub.add_parser(
        "new", help="allocate the next number and write the template"
    )
    p_new.add_argument("slug")
    p_new.add_argument("--title", required=True)
    sub.add_parser("lint", help="validate every record")
    p_index = sub.add_parser(
        "index", help="regenerate docs/adr/README.md and the SUMMARY block"
    )
    p_index.add_argument("--check", action="store_true")
    p_sup = sub.add_parser("supersede", help="mark <old> superseded by <new>")
    p_sup.add_argument("old")
    p_sup.add_argument("new")
    args = parser.parse_args(argv)
    if args.cmd == "new":
        return new(args.slug, args.title)
    if args.cmd == "lint":
        return lint()
    if args.cmd == "index":
        return index(args.check)
    return supersede(args.old, args.new)


if __name__ == "__main__":
    sys.exit(main())
