#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
"""Decision-record tooling for pse-arrow (standard library only, Python >= 3.11).

    python3 scripts/adr.py new <slug> --title "..."   allocate the next number
    python3 scripts/adr.py lint                       validate every record
    python3 scripts/adr.py index [--check]            regenerate the index
    python3 scripts/adr.py supersede <old> <new>      symmetric supersession

The front-matter parser understands the small YAML subset the template uses:
scalars, ``[a, b]`` inline lists and ``null``. PyYAML is deliberately not a
dependency: the tool has to run in a bare CI container before any environment
is synced.
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterator

ROOT = Path(__file__).resolve().parents[1]
ADR_DIR = ROOT / "docs" / "adr"
TEMPLATE = ADR_DIR / "template.md"
README = ADR_DIR / "README.md"
BLUEPRINT = ROOT / "docs" / "authoritative_design" / "blueprint.md"

FILENAME_RE = re.compile(r"^\d{4}-[a-z0-9-]+\.md$")
ID_RE = re.compile(r"^ADR-(\d{4})$")
# AP foundations, DP refinements and PS profile principles; DM is the retired charter,
# still cited by accepted records (its text is in Git history, ADR-0096).
PRINCIPLE_RE = re.compile(r"^(AP|DP|PS|DM)-\d{2}$")
SECTION_RE = re.compile(r"^§([0-9]+(?:\.[0-9]+)*|[A-Z][0-9]+)$")
HEADING_RE = re.compile(r"^#{2,4}\s+(?:([0-9]+(?:\.[0-9]+)*)|([A-Z][0-9]+))\.?\s")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
# An immutable historical source for a retired review (ADR-0096).
GIT_REVIEW_RE = re.compile(r"^git:([0-9a-f]{12,40}):([^#\s]+)(#\S+)?$")
# A body link to a retired file, relocated to the same path at an immutable commit.
PERMALINK_RE = re.compile(
    r"\]\(https://github\.com/([\w.-]+/[\w.-]+)/blob/([0-9a-f]{12,40})/([^)#\s]+)"
)

REQUIRED_KEYS = (
    "id",
    "title",
    "status",
    "date",
    "deciders",
    "level",
    "principles",
    "blueprint",
    "review",
    "evidence",
    "supersedes",
    "superseded-by",
    "revisit",
    "verification",
)
STATUSES = {"proposed", "accepted", "rejected", "deprecated", "superseded"}
LEVELS = {"decision", "should-deviation", "must-gap"}
EVIDENCE = {
    "Proposed",
    "Interface-checked",
    "Implemented",
    "Tested",
    "Measured",
    "Formally established",
}
MUTABLE_KEYS = {"status", "superseded-by"}
MUTABLE_SECTION = "Status history"

README_PREAMBLE = """# Decision records

<!-- @generated by scripts/adr.py index; do not edit -->

Each record states one decision, the architecture sections it governs, the design
principles §H fields (principles, level, evidence, revisit trigger, verification), and the
design-review finding that motivated it. A record is immutable once accepted:
it changes only by superseding it with a new record, or by a status edit and an
appended `## Status history` line. `docs/authoritative_design/README.md` routes to
the authoritative design collection; these records say *why* it reads the way it does.

This index lists the retained decisions. Records whose rationale no longer explains the
current system were retired under ADR-0096 and remain in Git history; numbers are never
reused, so gaps are expected.

Run `just adr-new <slug>` to start one and `just adr-lint` before opening the PR.
Open items that were deliberately deferred live in [`register.md`](register.md).
"""


# --------------------------------------------------------------------------- #
# front matter
# --------------------------------------------------------------------------- #
def parse_scalar(raw: str) -> object:
    raw = raw.strip()
    if raw in ("", "null", "~"):
        return None
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [parse_scalar(part) for part in inner.split(",")]
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        return raw[1:-1]
    return raw


def split_front_matter(text: str, where: str) -> tuple[dict[str, object], str]:
    if not text.startswith("---\n"):
        raise ValueError(f"{where}: missing YAML front matter")
    end = text.find("\n---\n", 3)
    if end < 0:
        raise ValueError(f"{where}: unterminated YAML front matter")
    front: dict[str, object] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"{where}: unparsable front-matter line {line!r}")
        key, _, value = line.partition(":")
        front[key.strip()] = parse_scalar(value)
    return front, text[end + 5 :]


def as_list(value: object) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v) for v in value]
    return [str(value)]


def body_sections(body: str) -> dict[str, str]:
    sections: dict[str, list[str]] = {"": []}
    current = ""
    for line in body.splitlines():
        if line.startswith("## "):
            current = line[3:].strip()
            sections.setdefault(current, [])
        else:
            sections[current].append(line)
    return {k: "\n".join(v).strip() for k, v in sections.items()}


# --------------------------------------------------------------------------- #
# repository facts
# --------------------------------------------------------------------------- #
def adr_paths() -> list[Path]:
    return sorted(
        p
        for p in ADR_DIR.glob("*.md")
        if p.name not in {"README.md", "template.md", "register.md"}
    )


def markdown_headings(text: str) -> Iterator[tuple[int, str]]:
    """Yield actual ATX heading lines and positions, excluding fenced examples."""
    fence = ""
    for position, line in enumerate(text.splitlines()):
        marker = re.match(r"^\s{0,3}(`{3,}|~{3,})", line)
        if marker:
            token = marker.group(1)
            if not fence:
                fence = token
            elif token[0] == fence[0] and len(token) >= len(fence):
                fence = ""
            continue
        if not fence and re.match(r"^#{1,6}\s+", line):
            yield position, line


def section_owners(blueprint: Path | None = None) -> dict[str, tuple[Path, str]]:
    """Numbered headings own identities; fences and legacy link stubs do not."""
    blueprint = BLUEPRINT if blueprint is None else blueprint
    owners: dict[str, tuple[Path, str]] = {}
    paths = [blueprint, *sorted((blueprint.parent / "sections").rglob("*.md"))]
    for path in paths:
        for _, line in markdown_headings(path.read_text(encoding="utf-8")):
            match = HEADING_RE.match(line)
            if match:
                ident = match.group(1) or match.group(2)
                if ident in owners:
                    raise ValueError(
                        f"duplicate section §{ident}: {owners[ident][0]} and {path}"
                    )
                owners[ident] = (path, line)
    return owners


def blueprint_sections() -> set[str]:
    return set(section_owners())


def git(*args: str) -> tuple[int, str]:
    proc = subprocess.run(
        ["git", "-C", str(ROOT), *args], capture_output=True, text=True, check=False
    )
    return proc.returncode, proc.stdout


def origin_main_exists() -> bool:
    return git("rev-parse", "--verify", "--quiet", "origin/main")[0] == 0


# --------------------------------------------------------------------------- #
# lint
# --------------------------------------------------------------------------- #
def lint() -> int:
    errors: list[str] = []
    paths = adr_paths()
    if not paths:
        print("adr: no records under docs/adr/", file=sys.stderr)
        return 1
    try:
        sections = blueprint_sections()
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    records: dict[str, dict[str, object]] = {}

    for path in paths:
        rel = path.relative_to(ROOT)
        if not FILENAME_RE.match(path.name):
            errors.append(f"{rel}: filename must match ^\\d{{4}}-[a-z0-9-]+\\.md$")
            continue
        try:
            front, _body = split_front_matter(
                path.read_text(encoding="utf-8"), str(rel)
            )
        except ValueError as exc:
            errors.append(str(exc))
            continue

        missing = [k for k in REQUIRED_KEYS if k not in front]
        if missing:
            errors.append(f"{rel}: missing front-matter keys {', '.join(missing)}")
        number = path.name[:4]
        ident = str(front.get("id", ""))
        m = ID_RE.match(ident)
        if not m:
            errors.append(f"{rel}: id must be ADR-NNNN, found {ident!r}")
        elif m.group(1) != number:
            errors.append(f"{rel}: id {ident} does not match filename number {number}")
        else:
            records[ident] = front

        if front.get("status") not in STATUSES:
            errors.append(
                f"{rel}: status {front.get('status')!r} not in {sorted(STATUSES)}"
            )
        if front.get("level") not in LEVELS:
            errors.append(
                f"{rel}: level {front.get('level')!r} not in {sorted(LEVELS)}"
            )
        if front.get("evidence") not in EVIDENCE:
            errors.append(
                f"{rel}: evidence {front.get('evidence')!r} is not a design principles §D label"
            )
        if not DATE_RE.match(str(front.get("date", ""))):
            errors.append(f"{rel}: date must be YYYY-MM-DD")
        for principle in as_list(front.get("principles")):
            if not PRINCIPLE_RE.match(principle):
                errors.append(
                    f"{rel}: principle {principle!r} must match AP-NN, DP-NN, PS-NN or legacy DM-NN"
                )
        for citation in as_list(front.get("blueprint")):
            sm = SECTION_RE.match(citation)
            if not sm:
                errors.append(
                    f"{rel}: blueprint citation {citation!r} must look like §14.3 or §D1"
                )
            elif sm.group(1) not in sections:
                errors.append(
                    f"{rel}: blueprint citation {citation} resolves to no heading in blueprint.md"
                )
        review_problem = review_error(str(front.get("review") or ""))
        if review_problem:
            errors.append(f"{rel}: {review_problem}")
        for key in ("revisit", "verification"):
            if not str(front.get(key) or "").strip():
                errors.append(f"{rel}: {key} must state something observable")

    numbers = [int(p.name[:4]) for p in paths if FILENAME_RE.match(p.name)]
    duplicates = sorted({n for n in numbers if numbers.count(n) > 1})
    if duplicates:
        errors.append(f"adr numbers are issued more than once: {duplicates}")

    errors.extend(supersession_errors(records, issued_history("HEAD")))
    errors.extend(lint_immutability(paths))
    errors.extend(lint_highest_issued(paths))

    generated_readme = render_index()
    if README.exists() and README.read_text(encoding="utf-8") != generated_readme:
        errors.append("docs/adr/README.md is stale; run `python3 scripts/adr.py index`")
    elif not README.exists():
        errors.append(
            "docs/adr/README.md is missing; run `python3 scripts/adr.py index`"
        )

    for err in errors:
        print(f"error: {err}", file=sys.stderr)
    if errors:
        print(
            f"adr lint: {len(errors)} problem(s) in {len(paths)} record(s)",
            file=sys.stderr,
        )
        return 1
    print(f"adr lint: {len(paths)} record(s) OK")
    return 0


def object_state(commit: str, path: str) -> str:
    """Classify a historical file reference as `present`, `absent` or `unknown`.

    `present` means `path` exists at a commit reachable from HEAD; `unknown` means a shallow
    clone lacks that history, so only the reference's shape is checked.
    """
    if git("cat-file", "-e", f"{commit}:{path}")[0] == 0:
        reachable = git("merge-base", "--is-ancestor", commit, "HEAD")[0] == 0
        return "present" if reachable else "absent"
    shallow = git("rev-parse", "--is-shallow-repository")[1].strip() == "true"
    if shallow and git("cat-file", "-e", f"{commit}^{{commit}}")[0] != 0:
        return "unknown"
    return "absent"


def same_as_baseline(commit: str, path: str) -> bool:
    """A relocation cites the file as `origin/main` held it, when that is still known."""
    code, base = git("rev-parse", "--verify", "--quiet", f"origin/main:{path}")
    if code != 0:
        return True
    return git("rev-parse", "--verify", "--quiet", f"{commit}:{path}")[1] == base


def repository_slug() -> str | None:
    url = git("remote", "get-url", "origin")[1].strip()
    match = re.search(r"github\.com[:/]([\w.-]+/[\w.-]+?)(?:\.git)?$", url)
    return match.group(1) if match else None


def review_error(review: str) -> str | None:
    """A review is a reason, a retained local file or an immutable Git source."""
    if review.startswith("not-required:"):
        return None
    match = GIT_REVIEW_RE.match(review)
    if match:
        state = object_state(match.group(1), match.group(2))
        if state == "unknown":
            print(f"note: history unavailable; checked the shape of {review!r} only")
        if state == "absent":
            return f"review {review!r} names no file at that commit reachable from HEAD"
        return None
    if review.startswith("git:"):
        return f"review {review!r} must be git:<12-40 hex commit>:<path>[#anchor]"
    if not (ROOT / review.split("#", 1)[0]).is_file():
        return (
            f"review path {review!r} does not exist; cite a retained review "
            "or its immutable git:<commit>:<path> source"
        )
    return None


def relocated_review(old: str, new: str) -> bool:
    """A retired local review moved to the same file at a commit keeps its meaning."""
    match = GIT_REVIEW_RE.match(new)
    if not match or match.group(2) + (match.group(3) or "") != old:
        return False
    commit, path = match.group(1), match.group(2)
    return (
        not (ROOT / path).exists()
        and object_state(commit, path) != "absent"
        and same_as_baseline(commit, path)
    )


def unrelocate_links(
    text: str, record_dir: Path, already: str = ""
) -> tuple[str, list[str]]:
    """Map permalinks back to record-relative links; report new ones that are not relocations.

    Permalinks already present in `already` (the accepted text) were checked when added.
    """
    problems: list[str] = []
    slug = repository_slug()

    def local(match: re.Match[str]) -> str:
        repository, commit, path = match.group(1), match.group(2), match.group(3)
        where = f"{repository}@{commit[:12]}:{path}"
        relative = os.path.relpath(ROOT / path, record_dir)
        if match.group(0) in already:
            return f"]({Path(relative).as_posix()}"
        if slug and repository != slug:
            problems.append(f"{where} is not this repository")
        elif (ROOT / path).exists():
            problems.append(f"{where} still exists locally; link it directly")
        elif object_state(commit, path) == "absent":
            problems.append(f"{where} names no file at a commit reachable from HEAD")
        elif not same_as_baseline(commit, path):
            problems.append(f"{where} differs from the file the record cited")
        return f"]({Path(relative).as_posix()}"

    return PERMALINK_RE.sub(local, text), problems


def issued_history(ref: str) -> set[int] | None:
    """Every ADR number ever added on `ref`, or None when this clone lacks the history."""
    if git("rev-parse", "--is-shallow-repository")[1].strip() == "true":
        return None
    code, listing = git(
        "log",
        ref,
        "--no-renames",
        "--diff-filter=A",
        "--name-only",
        "--format=",
        "--",
        "docs/adr/",
    )
    if code != 0:
        return None
    return {
        int(Path(name).name[:4])
        for name in listing.splitlines()
        if FILENAME_RE.match(Path(name).name)
    }


def issued_number(ident: str) -> int | None:
    match = ID_RE.match(ident)
    return int(match.group(1)) if match else None


def supersession_errors(
    records: dict[str, dict[str, object]], issued: set[int] | None = None
) -> list[str]:
    """Retained pairs stay symmetric; links into retired history need no counterpart.

    A peer that is not retained counts as retired when history shows it was issued, or,
    without history, when its number is below the highest retained record.
    """
    errors: list[str] = []
    highest = max((issued_number(i) or 0 for i in records), default=0)

    def retired(ident: str) -> bool:
        number = issued_number(ident)
        if number is None or ident in records:
            return False
        return number in issued if issued is not None else number < highest

    for ident, front in records.items():
        for other in as_list(front.get("supersedes")):
            peer = records.get(other)
            if peer is None:
                if not retired(other):
                    errors.append(f"{ident}: supersedes unknown record {other}")
            elif str(peer.get("superseded-by") or "") != ident:
                errors.append(
                    f"{ident}: supersedes {other}, which does not name it in superseded-by"
                )
        by = front.get("superseded-by")
        if by:
            peer = records.get(str(by))
            if peer is None:
                errors.append(
                    f"{ident}: superseded-by {by}, which is not retained; "
                    "retire the superseded record too"
                )
            elif ident not in as_list(peer.get("supersedes")):
                errors.append(
                    f"{ident}: superseded-by {by}, which does not name it in supersedes"
                )
            elif front.get("status") != "superseded":
                errors.append(
                    f"{ident}: has superseded-by but status is {front.get('status')!r}"
                )
    return errors


def lint_highest_issued(paths: list[Path]) -> list[str]:
    """Keep the highest number ever issued on `origin/main` until a newer one exists."""
    if not origin_main_exists():
        print("note: origin/main does not exist; skipping the highest-issued check")
        return []
    issued = issued_history("origin/main")
    if issued is None:
        print("note: ADR history unavailable; skipping the highest-issued check")
        return []
    current = [int(p.name[:4]) for p in paths if FILENAME_RE.match(p.name)]
    if issued and max(current, default=0) < max(issued):
        return [
            (
                f"ADR-{max(issued):04d} is the highest issued record; keep it until a "
                "newer record exists so allocation cannot reuse its number"
            )
        ]
    return []


def lint_immutability(paths: list[Path]) -> list[str]:
    if not origin_main_exists():
        print(
            "note: origin/main does not exist yet; skipping the ADR immutability check"
        )
        return []
    errors: list[str] = []
    for path in paths:
        rel = path.relative_to(ROOT).as_posix()
        code, old_text = git("show", f"origin/main:{rel}")
        if code != 0:
            continue  # new record in this branch
        try:
            old_front, old_body = split_front_matter(old_text, rel)
            new_front, new_body = split_front_matter(
                path.read_text(encoding="utf-8"), rel
            )
        except ValueError as exc:
            errors.append(str(exc))
            continue
        if old_front.get("status") == "proposed":
            continue
        for key in sorted(set(old_front) | set(new_front)):
            if key in MUTABLE_KEYS:
                continue
            if key == "review" and relocated_review(
                str(old_front.get(key) or ""), str(new_front.get(key) or "")
            ):
                continue
            if old_front.get(key) != new_front.get(key):
                errors.append(
                    f"{rel}: {key} changed on an accepted record; supersede it instead"
                )
        old_sections, new_sections = body_sections(old_body), body_sections(new_body)
        for name in sorted(set(old_sections) | set(new_sections)):
            if old_sections.get(name) == new_sections.get(name):
                continue
            before = old_sections.get(name) or ""
            relocated, problems = unrelocate_links(
                new_sections.get(name) or "", path.parent, already=before
            )
            original, _ = unrelocate_links(before, path.parent, already=before)
            errors.extend(f"{rel}: relocated link {problem}" for problem in problems)
            if name == MUTABLE_SECTION:
                if not relocated.startswith(original):
                    errors.append(f"{rel}: Status history is append-only")
                continue
            if original != relocated:
                label = name or "(preamble)"
                errors.append(
                    f"{rel}: section '{label}' changed on an accepted record; supersede it instead"
                )
    return errors


# --------------------------------------------------------------------------- #
# index
# --------------------------------------------------------------------------- #
def render_index() -> str:
    rows = []
    for path in adr_paths():
        front, _ = split_front_matter(path.read_text(encoding="utf-8"), str(path))
        ident = str(front.get("id"))
        title = str(front.get("title"))
        blueprint = ", ".join(as_list(front.get("blueprint"))) or "—"
        rows.append(
            f"| [{ident}]({path.name}) | {title} | {front.get('status')} "
            f"| {front.get('date')} | {blueprint} | {front.get('revisit')} |"
        )

    return (
        README_PREAMBLE
        + "\n| ID | Title | Status | Date | Blueprint | Revisit |\n"
        + "|---|---|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n"
    )


def index(check: bool) -> int:
    readme = render_index()
    if check:
        stale = []
        if not README.exists() or README.read_text(encoding="utf-8") != readme:
            stale.append("docs/adr/README.md")
        if stale:
            print(
                f"error: stale generated file(s): {', '.join(stale)}", file=sys.stderr
            )
            return 1
        print("adr index: up to date")
        return 0
    README.write_text(readme, encoding="utf-8")
    print(f"adr index: wrote {README.relative_to(ROOT)}")
    return 0


# --------------------------------------------------------------------------- #
# new / supersede
# --------------------------------------------------------------------------- #
def next_number() -> int:
    """Highest number retained or ever issued on HEAD, plus one; never a reuse."""
    retained = [int(p.name[:4]) for p in adr_paths() if FILENAME_RE.match(p.name)]
    return max([0, *retained, *(issued_history("HEAD") or ())]) + 1


def resolve(ref: str) -> Path:
    digits = re.sub(r"\D", "", ref)[-4:].zfill(4)
    for path in adr_paths():
        if path.name.startswith(digits):
            return path
    raise SystemExit(f"error: no record matching {ref!r}")


def new(slug: str, title: str) -> int:
    if not re.fullmatch(r"[a-z0-9-]+", slug):
        raise SystemExit(f"error: slug {slug!r} must be lowercase kebab-case")
    number = next_number()
    path = ADR_DIR / f"{number:04d}-{slug}.md"
    text = TEMPLATE.read_text(encoding="utf-8")
    text = text.replace("ADR-NNNN", f"ADR-{number:04d}")
    text = text.replace("TITLE", title)
    text = text.replace("YYYY-MM-DD", datetime.date.today().isoformat())
    path.write_text(text, encoding="utf-8")
    print(f"adr new: {path.relative_to(ROOT)}")
    print("next: fill the §H fields, then run `python3 scripts/adr.py index`")
    return 0


def set_field(path: Path, key: str, value: str) -> None:
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith(f"{key}:"):
            lines[i] = f"{key}: {value}\n"
            break
    else:
        raise SystemExit(f"error: {path.name} has no {key}: line")
    path.write_text("".join(lines), encoding="utf-8")


def supersede(old_ref: str, new_ref: str) -> int:
    old, new_path = resolve(old_ref), resolve(new_ref)
    old_front, _ = split_front_matter(old.read_text(encoding="utf-8"), str(old))
    new_front, _ = split_front_matter(
        new_path.read_text(encoding="utf-8"), str(new_path)
    )
    set_field(old, "status", "superseded")
    set_field(old, "superseded-by", str(new_front["id"]))
    predecessors = sorted(
        set(as_list(new_front.get("supersedes"))) | {str(old_front["id"])}
    )
    set_field(new_path, "supersedes", f"[{', '.join(predecessors)}]")
    today = datetime.date.today().isoformat()
    with old.open("a", encoding="utf-8") as handle:
        handle.write(f"- {today} — superseded by {new_front['id']}.\n")
    print(f"adr supersede: {old_front['id']} -> {new_front['id']}")
    print(
        "next: append the reason to the new record's Status history, then run `index`"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="adr.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_new = sub.add_parser(
        "new", help="allocate the next number and write the template"
    )
    p_new.add_argument("slug")
    p_new.add_argument("--title", required=True)
    sub.add_parser("lint", help="validate every record")
    p_index = sub.add_parser("index", help="regenerate docs/adr/README.md")
    p_index.add_argument("--check", action="store_true")
    p_sup = sub.add_parser("supersede", help="mark <old> superseded by <new>")
    p_sup.add_argument("old")
    p_sup.add_argument("new")
    args = parser.parse_args(argv)
    if args.cmd == "new":
        return new(args.slug, args.title)
    if args.cmd == "lint":
        return lint()
    if args.cmd == "index":
        return index(args.check)
    return supersede(args.old, args.new)


if __name__ == "__main__":
    sys.exit(main())
