#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
"""Materialize native Codex roles from canonical Claude instructions."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = "# Generated by scripts/agent-config.py; edit .claude/agents instead.\n"


def definitions(root: Path) -> dict[str, str]:
    result = {}
    for source in sorted((root / ".claude/agents").glob("*.md")):
        _, front, body = source.read_text().split("---", 2)
        fields = dict(line.split(":", 1) for line in front.strip().splitlines())
        name = fields["name"].strip()
        description = json.loads(fields["description"].strip())
        if name != source.stem:
            raise ValueError(f"agent name differs from filename: {source}")
        config = {
            "name": name,
            "description": description,
            "developer_instructions": body.strip() + "\n",
        }
        if "Write" not in fields.get("tools", ""):
            config["sandbox_mode"] = "read-only"
        rendered = (
            HEADER
            + "\n".join(
                f"{key} = {json.dumps(value, ensure_ascii=False)}"
                for key, value in config.items()
            )
            + "\n"
        )
        tomllib.loads(rendered)
        result[name + ".toml"] = rendered
    if len(result) != 9:
        raise ValueError(f"expected nine canonical roles, found {len(result)}")
    return result


def skill_alias(root: Path, directory: str) -> None:
    alias = root / directory / "skills"
    target = root / ".codex/skills"
    alias.parent.mkdir(exist_ok=True)
    if alias.is_symlink():
        if alias.resolve() != target.resolve():
            raise ValueError(f"unexpected skill symlink: {alias}")
        return
    if alias.is_file():
        if alias.read_text().strip() != "../.codex/skills":
            raise ValueError(f"refusing to replace {alias}")
        alias.unlink()
    if not alias.exists():
        try:
            alias.symlink_to("../.codex/skills", target_is_directory=True)
        except OSError:
            pass  # Windows without symlink privileges uses a checked materialization.
        else:
            return
    shutil.copytree(target, alias, dirs_exist_ok=True)


def synchronize(root: Path, *, check: bool) -> list[str]:
    expected = definitions(root)
    destination = root / ".codex/agents"
    problems = []
    if not check:
        if destination.is_symlink():
            if destination.resolve() != (root / ".claude/agents").resolve():
                raise ValueError("refusing to replace an unexpected agents symlink")
            destination.unlink()
        elif destination.is_file():
            if destination.read_text().strip() != "../.claude/agents":
                raise ValueError("refusing to replace an unexpected agents file")
            destination.unlink()
        destination.mkdir(exist_ok=True)
        for alias in (".claude", ".agents"):
            skill_alias(root, alias)
    if destination.is_symlink() or not destination.is_dir():
        return [".codex/agents must be a native directory; run just agent-config-sync"]
    for name, body in expected.items():
        path = destination / name
        if check:
            if not path.is_file() or path.read_text() != body:
                problems.append(
                    f"native agent drift: {name}; run just agent-config-sync"
                )
        else:
            path.write_text(body)
    extras = {p.name for p in destination.iterdir()} - expected.keys()
    problems.extend(f"unexpected native agent file: {name}" for name in sorted(extras))
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        problems = synchronize(ROOT, check=args.check)
    except (ValueError, OSError) as exc:
        problems = [str(exc)]
    for problem in problems:
        print(problem, file=sys.stderr)
    return int(bool(problems))


if __name__ == "__main__":
    sys.exit(main())
