#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Paul Heyse
"""Verify the agent working environment is internally consistent.

Agent instructions are the one class of document with no compiler and no test: a
`CLAUDE.md` that points at a directory which was renamed six months ago fails silently,
at the moment an agent tries to follow it. This script is the missing compiler. It
checks five things:

1. **Skill aliases resolve and native adapters load shared contracts.** Skills are canonical in
   ``.codex/skills`` with ``.claude/skills`` and ``.agents/skills`` pointing at them;
   shared role behavior lives in ``.agents/roles``. Native adapters are maintained separately,
   never regenerated by alias synchronization. A Windows checkout without developer mode materialises a
   symlink as a directory (or as a one-line text file), so a materialised pair is
   accepted when the two trees are byte-identical -- and rejected when they are not,
   which is the drift this exists to catch.
2. **``CLAUDE.md`` starts with ``@AGENTS.md``.** That import is why ``AGENTS.md`` can be
   canonical for both runtimes.
3. **Every repository path named in the repository instructions exists.** Local process
   skills, roles and native adapters are included; shared library bundles are excluded. Paths created
   later in the build-out live in ``.claude/path-allowlist.txt``, each with a comment
   saying when it appears; a line carrying ``agent-config: ignore`` is skipped.
4. **Every ``just`` recipe named in the instructions exists.** ``just --list`` is
   advertised as the contract, so a recipe that was renamed without updating the prose
   is a broken contract.
5. **Every file-path deny rule in ``.claude/settings.json`` is an anchored ``Edit`` or
   ``Read`` rule.** Claude Code consults only ``Edit(...)`` and ``Read(...)`` for file paths
   (``Edit`` covers every editing tool), so a ``Write(...)`` path rule is accepted and never
   applied. A ``./path`` or bare ``path`` resolves against the session's current directory,
   and a single-segment deny such as ``./build/**`` matches a ``build`` directory at any depth
   below it -- which denied every skill's own ``build/``. ``/path`` anchors at the repository
   root, which is what the protection means.

Run by ``just lint-agents`` and by the ``governance / agent-config`` CI job.
Standard library only: it has to run before any environment exists.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tomllib
from fnmatch import fnmatch
from pathlib import Path


def repo_root() -> Path:
    """The repository root, resolved from git so no absolute path is ever hard-coded."""
    try:
        out = subprocess.run(
            ("git", "rev-parse", "--show-toplevel"),
            capture_output=True,
            text=True,
            check=True,
            cwd=Path(__file__).resolve().parent,
            timeout=10,
        ).stdout.strip()
        if out:
            return Path(out)
    except (OSError, subprocess.SubprocessError):
        pass
    return Path(__file__).resolve().parents[1]


ROOT = repo_root()
ALLOWLIST_FILE = ROOT / ".claude" / "path-allowlist.txt"
IGNORE_MARKER = "agent-config: ignore"

# Top-level directories that make a token a repository path rather than prose. A
# match is only a candidate; templated and globbed forms are dropped below.
PATH_ROOTS = (
    "docs",
    "scripts",
    "crates",
    "python",
    "tests",
    "xtask",
    "benches",
    r"\.github",
    r"\.claude",
    r"\.codex",
    r"\.agents",
)
PATH_RE = re.compile(
    r"(?<![\w./-])(?:"
    + "|".join(PATH_ROOTS)
    + r")/[A-Za-z0-9_.*{}<>?-][A-Za-z0-9_./*{}<>?-]*"
)
# A path that is a pattern, not a file: globs in a rules `paths:` list, `{slug}` in a
# filename template, `<name>` in a usage line. Nothing to check on disk.
TEMPLATE_CHARS = set("*{}<>?")

BACKTICK_RE = re.compile(r"`([^`\n]+)`")
FENCE_RE = re.compile(r"^\s*just\s+(\S+)")
FRONT_MATTER_RE = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
ROLE_NAMES = (
    "code-mapper",
    "library-research",
    "design-reviewer",
    "executor",
    "implementation-reviewer",
    "test-agent",
)
PROCESS_SKILLS = (
    "adr",
    "design-review",
    "design-review-process-simulator",
    "plan-design-review",
    "plan-creation",
    "create-plan",
    "plan-execution",
    "execute-plan",
)


def scanned_files() -> list[Path]:
    """Instruction files whose contents are checked, in report order."""
    files = [ROOT / "AGENTS.md", ROOT / "CLAUDE.md"]
    files += sorted((ROOT / ".claude" / "rules").glob("*.md"))
    files += sorted((ROOT / ".claude" / "agents").glob("*.md"))
    files += sorted((ROOT / ".codex" / "agents").glob("*.toml"))
    files += sorted((ROOT / ".agents" / "roles").glob("*.md"))
    files.append(ROOT / ".codex/skills/README.md")
    for name in PROCESS_SKILLS:
        files += sorted((ROOT / ".codex/skills" / name).rglob("*.md"))
    return [f for f in files if f.is_file()]


def body_of(text: str) -> str:
    """Drop YAML front matter.

    A rules file's `paths:` globs and an agent's `description:` few-shot examples are
    not references to files in this repository, and treating them as such would make the
    check a source of noise rather than signal.
    """
    return FRONT_MATTER_RE.sub("", text, count=1)


def load_allowlist() -> list[str]:
    """Patterns from .claude/path-allowlist.txt, minus comments and blank lines."""
    if not ALLOWLIST_FILE.is_file():
        return []
    entries = []
    for line in ALLOWLIST_FILE.read_text(encoding="utf-8").splitlines():
        entry = line.split("#", 1)[0].strip()
        if entry:
            entries.append(entry.rstrip("/"))
    return entries


def allowed(ref: str, allowlist: list[str]) -> bool:
    """Does an allowlist pattern cover `ref`, either exactly or as a directory?"""
    return any(
        fnmatch(ref, pattern) or fnmatch(ref, pattern + "/*") for pattern in allowlist
    )


def path_refs(text: str) -> set[str]:
    """Repository paths named in `text`, excluding ignored lines and templated forms."""
    refs: set[str] = set()
    for line in text.splitlines():
        if IGNORE_MARKER in line:
            continue
        for raw in PATH_RE.findall(line):
            ref = raw.rstrip(".,;:)]`'\"").rstrip("/")
            if not ref or set(ref) & TEMPLATE_CHARS:
                continue
            refs.add(ref)
    return refs


def just_recipes(text: str) -> set[str]:
    """Recipe names invoked as `just <name>` in backticks or in a fenced block."""
    names: set[str] = set()
    for raw in BACKTICK_RE.findall(text):
        span = raw.strip()
        if span.startswith("just "):
            names.add(span[len("just ") :].split()[0])
    for line in text.splitlines():
        match = FENCE_RE.match(line)
        if match:
            names.add(match.group(1))
    return {n for n in names if not n.startswith("-")}


def trees_identical(left: Path, right: Path) -> bool:
    """Byte equality for local copies; compare live library links without traversing them."""
    if left.is_symlink() or right.is_symlink():
        return (
            left.is_symlink()
            and right.is_symlink()
            and left.resolve() == right.resolve()
        )
    if left.is_dir() and right.is_dir():
        names = {path.name for path in left.iterdir()}
        return names == {path.name for path in right.iterdir()} and all(
            trees_identical(left / name, right / name) for name in names
        )
    return (
        left.is_file() and right.is_file() and left.read_bytes() == right.read_bytes()
    )


def check_native_adapters(problems: list[str]) -> None:
    """Native definitions own defaults and refer to shared role behavior."""
    for role in ROLE_NAMES:
        for runtime, suffix, name in (
            (".codex", ".toml", role),
            (".claude", ".md", "implementer" if role == "executor" else role),
        ):
            path = ROOT / runtime / "agents" / (name + suffix)
            if not path.is_file():
                problems.append(f"missing native adapter: {path.relative_to(ROOT)}")
                continue
            text = path.read_text(encoding="utf-8")
            for contract in (".agents/roles/worker.md", f".agents/roles/{role}.md"):
                if contract not in text or not (ROOT / contract).is_file():
                    problems.append(
                        f"{path.relative_to(ROOT)}: missing shared contract {contract}"
                    )
            if runtime == ".codex":
                try:
                    config = tomllib.loads(text)
                except tomllib.TOMLDecodeError as exc:
                    problems.append(f"{path.relative_to(ROOT)}: {exc}")
                    continue
                for key in (
                    "name",
                    "description",
                    "model",
                    "model_reasoning_effort",
                    "developer_instructions",
                ):
                    if not config.get(key):
                        problems.append(f"{path.relative_to(ROOT)}: missing {key}")
                if config.get("name") != role:
                    problems.append(f"{path.relative_to(ROOT)}: name must be {role}")
                if "Generated by scripts/agent-config.py" in text:
                    problems.append(
                        f"{path.relative_to(ROOT)}: retire generated adapter ownership"
                    )
    if (ROOT / ".codex/agents/implementer.toml").exists():
        problems.append(
            ".codex/agents/implementer.toml is obsolete; Codex uses executor"
        )


def check_link(link: Path, target: Path, problems: list[str]) -> None:
    """`link` is a symlink to `target`, or a byte-identical copy of it."""
    rel = link.relative_to(ROOT).as_posix()
    target_rel = target.relative_to(ROOT).as_posix()
    if not target.is_dir():
        problems.append(
            f"{target_rel} does not exist; it is the canonical copy for {rel}"
        )
        return
    if link.is_symlink():
        if link.resolve() != target.resolve():
            problems.append(
                f"{rel} is a symlink to {link.resolve()}, expected {target.resolve()}"
            )
        return
    if link.is_dir():
        if trees_identical(link, target):
            print(f"  note: {rel} is a materialised copy of {target_rel}")
            print("        (Windows checkout): identical, but edit the canonical one.")
        else:
            problems.append(
                f"{rel} is a directory, not a symlink, and its contents differ from "
                f"{target_rel}. The two runtimes have drifted. Restore the symlink: "
                f"rm -rf {rel} && ln -s {'../' + target_rel} {rel}"
            )
        return
    problems.append(
        f"{rel} is neither a symlink nor a directory. A Windows checkout without "
        f"developer mode writes the link target as a text file; enable directory symlinks "
        f"and run just agent-config-sync. Do not copy shared library bundles."
    )


FILE_TOOLS = ("Edit", "Read", "Write", "NotebookEdit", "MultiEdit", "Glob")
ANCHORS = ("/", "~/")


# The shared hook scripts: protected-edit policy, and the end-of-turn pipeline.
HOOK_SCRIPTS = ("scripts/agent-hooks.py", "scripts/after_turn.py")
REQUIRED_HOOK_EVENTS = ("PreToolUse", "Stop", "UserPromptSubmit")


def check_hook_wiring(config: Path, problems: list[str]) -> None:
    """Both runtimes wire the required events, and every hook runs a shared hook script."""
    hooks = json.loads(config.read_text())["hooks"]
    for event in REQUIRED_HOOK_EVENTS:
        if not hooks.get(event):
            problems.append(f"{config}: missing {event} hook")
    for event, groups in hooks.items():
        for group in groups:
            for hook in group["hooks"]:
                if not any(script in hook["command"] for script in HOOK_SCRIPTS):
                    problems.append(
                        f"{config}: {event} hook does not use shared policy"
                    )


def check_deny_rules(settings: Path, problems: list[str]) -> int:
    """Every file-path deny rule must be an ``Edit``/``Read`` rule anchored at a fixed root."""
    rules = json.loads(settings.read_text()).get("permissions", {}).get("deny", [])
    checked = 0
    for rule in rules:
        found = re.fullmatch(r"(\w+)\((.*)\)", rule)
        if not found or found.group(1) not in FILE_TOOLS:
            continue
        checked += 1
        tool, path = found.groups()
        if tool not in ("Edit", "Read"):
            problems.append(
                f"{settings.name}: deny rule {rule!r} is never consulted -- Claude Code checks "
                f"file paths against Edit(...) and Read(...) only; write Edit({path})"
            )
        if not path.startswith(ANCHORS):
            problems.append(
                f"{settings.name}: deny rule {rule!r} resolves against the current directory "
                f"and, as a deny, may match the same name at any depth; anchor it as "
                f"{tool}(/{path.removeprefix('./')})"
            )
    return checked


def main() -> int:
    """Run every check, report each problem with its fix, and return an exit code."""
    problems: list[str] = []
    allowlist = load_allowlist()

    print(f"agent config check in {ROOT}")

    # 1. symlinks
    check_link(ROOT / ".claude" / "skills", ROOT / ".codex" / "skills", problems)
    check_link(ROOT / ".agents" / "skills", ROOT / ".codex" / "skills", problems)
    aliases = subprocess.run(
        [sys.executable, str(ROOT / "scripts/agent-config.py"), "--check"],
        capture_output=True,
        text=True,
        check=False,
    )
    if aliases.returncode:
        problems.append(aliases.stdout + aliases.stderr)
    check_native_adapters(problems)
    for config in (ROOT / ".codex/hooks.json", ROOT / ".claude/settings.json"):
        check_hook_wiring(config, problems)

    deny_rules = check_deny_rules(ROOT / ".claude/settings.json", problems)

    # 2. the CLAUDE.md import
    claude_md = ROOT / "CLAUDE.md"
    if not claude_md.is_file():
        problems.append("CLAUDE.md is missing")
    else:
        if claude_md.is_symlink():
            problems.append(
                "CLAUDE.md is a symlink. It must be a real file: a Windows runner "
                "checks a symlink out as a text file and the @AGENTS.md import is lost."
            )
        first = claude_md.read_text(encoding="utf-8").splitlines()[:1]
        if first != ["@AGENTS.md"]:
            problems.append(
                f"CLAUDE.md line 1 is {first!r}, expected '@AGENTS.md' -- without that "
                "import Claude Code never reads the canonical instructions."
            )

    # 3 and 4. references inside the instruction files
    files = scanned_files()
    checked_paths = 0
    checked_recipes = 0
    recipes: set[str] = set()
    summary = subprocess.run(
        ("just", "--summary"), capture_output=True, text=True, cwd=ROOT, check=False
    )
    have_just = summary.returncode == 0
    if have_just:
        recipes = set(summary.stdout.split())
    else:
        print("  note: `just --summary` unavailable; skipping the recipe-name check")

    for path in files:
        rel = path.relative_to(ROOT).as_posix()
        text = body_of(path.read_text(encoding="utf-8", errors="replace"))
        for ref in sorted(path_refs(text)):
            checked_paths += 1
            if (ROOT / ref).exists() or allowed(ref, allowlist):
                continue
            problems.append(f"{rel}: path does not exist: {ref}")
        if have_just:
            for name in sorted(just_recipes(text)):
                checked_recipes += 1
                if name not in recipes:
                    problems.append(f"{rel}: no such just recipe: `just {name}`")

    print(
        f"  {len(files)} file(s), {checked_paths} path reference(s), "
        f"{checked_recipes} recipe reference(s), {len(allowlist)} allowlist entr(ies), "
        f"{deny_rules} file-path deny rule(s)"
    )

    if problems:
        print(f"\n{len(problems)} problem(s):", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(
            "\nA path that does not exist yet belongs in "
            ".claude/path-allowlist.txt with a comment saying when it appears; a "
            f"line that is illustrative can carry `{IGNORE_MARKER}`.",
            file=sys.stderr,
        )
        return 1

    print("agent config ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
