// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse
// @generated by cargo xtask codegen (Cornucopia 1.0.1) from crates/pse-operations/queries; do not edit

#[derive(Debug)]
pub struct ExistingProgressSeqsParams<T1: crate::ArraySql<Item = i64>> {
    pub attempt_id: pse_model::generated::identities::AttemptId,
    pub seqs: T1,
}
#[derive(Clone, Copy, Debug)]
pub struct ProgressPageParams {
    pub attempt_id: pse_model::generated::identities::AttemptId,
    pub after: Option<i64>,
    pub limit: i64,
}
#[derive(Clone, Copy, Debug)]
pub struct ProgressValuesParams {
    pub attempt_id: pse_model::generated::identities::AttemptId,
    pub first: i64,
    pub last: i64,
}
#[derive(Debug)]
pub struct ExistingIncumbentSeqsParams<T1: crate::ArraySql<Item = i64>> {
    pub attempt_id: pse_model::generated::identities::AttemptId,
    pub seqs: T1,
}
#[derive(Clone, Copy, Debug)]
pub struct IncumbentPageParams {
    pub attempt_id: pse_model::generated::identities::AttemptId,
    pub after: Option<i64>,
    pub limit: i64,
}
use crate::client::async_::GenericClient;
use futures::{self, StreamExt, TryStreamExt};
pub struct I64Query<'c, 'a, 's, C: GenericClient, T, const N: usize> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(&tokio_postgres::Row) -> Result<i64, tokio_postgres::Error>,
    mapper: fn(i64) -> T,
}
impl<'c, 'a, 's, C, T: 'c, const N: usize> I64Query<'c, 'a, 's, C, T, N>
where
    C: GenericClient,
{
    pub fn map<R>(self, mapper: fn(i64) -> R) -> I64Query<'c, 'a, 's, C, R, N> {
        I64Query {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct ExistingProgressSeqsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn existing_progress_seqs() -> ExistingProgressSeqsStmt {
    ExistingProgressSeqsStmt(
        "SELECT seq FROM pse_ops.progress_events WHERE attempt_id = $1::pse_ops.attempt_id AND seq = ANY($2::bigint[])",
        None,
    )
}
impl ExistingProgressSeqsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<'c, 'a, 's, C: GenericClient, T1: crate::ArraySql<Item = i64>>(
        &'s self,
        client: &'c C,
        attempt_id: &'a pse_model::generated::identities::AttemptId,
        seqs: &'a T1,
    ) -> I64Query<'c, 'a, 's, C, i64, 2> {
        I64Query {
            client,
            params: [attempt_id, seqs],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it,
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = i64>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ExistingProgressSeqsParams<T1>,
    I64Query<'c, 'a, 's, C, i64, 2>,
    C,
> for ExistingProgressSeqsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ExistingProgressSeqsParams<T1>,
    ) -> I64Query<'c, 'a, 's, C, i64, 2> {
        self.bind(client, &params.attempt_id, &params.seqs)
    }
}
pub struct ProgressPageStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn progress_page() -> ProgressPageStmt {
    ProgressPageStmt(
        "SELECT e FROM pse_ops.progress_events AS e WHERE e.attempt_id = $1::pse_ops.attempt_id AND e.seq > coalesce($2::bigint, -1) ORDER BY e.seq LIMIT $3",
        None,
    )
}
impl ProgressPageStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        attempt_id: &'a pse_model::generated::identities::AttemptId,
        after: &'a Option<i64>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        3,
    > {
        PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery {
            client,
            params: [attempt_id, after, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ProgressPageParams,
    PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        3,
    >,
    C,
> for ProgressPageStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ProgressPageParams,
    ) -> PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        3,
    > {
        self.bind(client, &params.attempt_id, &params.after, &params.limit)
    }
}
pub struct ProgressValuesStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn progress_values() -> ProgressValuesStmt {
    ProgressValuesStmt(
        "SELECT v FROM pse_ops.progress_values AS v WHERE v.attempt_id = $1::pse_ops.attempt_id AND v.seq BETWEEN $2 AND $3 ORDER BY v.seq, v.name",
        None,
    )
}
impl ProgressValuesStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        attempt_id: &'a pse_model::generated::identities::AttemptId,
        first: &'a i64,
        last: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        3,
    > {
        PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery {
            client,
            params: [attempt_id, first, last],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ProgressValuesParams,
    PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        3,
    >,
    C,
> for ProgressValuesStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ProgressValuesParams,
    ) -> PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        3,
    > {
        self.bind(client, &params.attempt_id, &params.first, &params.last)
    }
}
pub struct DeleteFinishedValuesStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn delete_finished_values() -> DeleteFinishedValuesStmt {
    DeleteFinishedValuesStmt(
        "DELETE FROM pse_ops.progress_values AS v USING pse_ops.attempts AS a WHERE v.attempt_id = a.attempt_id AND a.finished_at IS NOT NULL AND a.finished_at < now() - $1::bigint * interval '1 microsecond'",
        None,
    )
}
impl DeleteFinishedValuesStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub async fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        age_us: &'a i64,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(self.0, &[age_us]).await
    }
}
pub struct DeleteFinishedEventsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn delete_finished_events() -> DeleteFinishedEventsStmt {
    DeleteFinishedEventsStmt(
        "DELETE FROM pse_ops.progress_events AS e USING pse_ops.attempts AS a WHERE e.attempt_id = a.attempt_id AND a.finished_at IS NOT NULL AND a.finished_at < now() - $1::bigint * interval '1 microsecond'",
        None,
    )
}
impl DeleteFinishedEventsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub async fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        age_us: &'a i64,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(self.0, &[age_us]).await
    }
}
pub struct DeleteFinishedIncumbentsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn delete_finished_incumbents() -> DeleteFinishedIncumbentsStmt {
    DeleteFinishedIncumbentsStmt(
        "DELETE FROM pse_ops.incumbents AS i USING pse_ops.attempts AS a WHERE i.attempt_id = a.attempt_id AND i.solution_id IS NULL AND a.finished_at IS NOT NULL AND a.finished_at < now() - $1::bigint * interval '1 microsecond'",
        None,
    )
}
impl DeleteFinishedIncumbentsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub async fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        age_us: &'a i64,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(self.0, &[age_us]).await
    }
}
pub struct ExistingIncumbentSeqsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn existing_incumbent_seqs() -> ExistingIncumbentSeqsStmt {
    ExistingIncumbentSeqsStmt(
        "SELECT seq FROM pse_ops.incumbents WHERE attempt_id = $1::pse_ops.attempt_id AND seq = ANY($2::bigint[])",
        None,
    )
}
impl ExistingIncumbentSeqsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<'c, 'a, 's, C: GenericClient, T1: crate::ArraySql<Item = i64>>(
        &'s self,
        client: &'c C,
        attempt_id: &'a pse_model::generated::identities::AttemptId,
        seqs: &'a T1,
    ) -> I64Query<'c, 'a, 's, C, i64, 2> {
        I64Query {
            client,
            params: [attempt_id, seqs],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it,
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = i64>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ExistingIncumbentSeqsParams<T1>,
    I64Query<'c, 'a, 's, C, i64, 2>,
    C,
> for ExistingIncumbentSeqsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ExistingIncumbentSeqsParams<T1>,
    ) -> I64Query<'c, 'a, 's, C, i64, 2> {
        self.bind(client, &params.attempt_id, &params.seqs)
    }
}
pub struct IncumbentPageStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn incumbent_page() -> IncumbentPageStmt {
    IncumbentPageStmt(
        "SELECT i FROM pse_ops.incumbents AS i WHERE i.attempt_id = $1::pse_ops.attempt_id AND i.seq > coalesce($2::bigint, -1) ORDER BY i.seq LIMIT $3",
        None,
    )
}
impl IncumbentPageStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        attempt_id: &'a pse_model::generated::identities::AttemptId,
        after: &'a Option<i64>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        3,
    > {
        PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery {
            client,
            params: [attempt_id, after, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    IncumbentPageParams,
    PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        3,
    >,
    C,
> for IncumbentPageStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a IncumbentPageParams,
    ) -> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        3,
    > {
        self.bind(client, &params.attempt_id, &params.after, &params.limit)
    }
}
pub struct LatestIncumbentStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn latest_incumbent() -> LatestIncumbentStmt {
    LatestIncumbentStmt(
        "SELECT i FROM pse_ops.incumbents AS i WHERE i.attempt_id = $1::pse_ops.attempt_id ORDER BY i.seq DESC LIMIT 1",
        None,
    )
}
impl LatestIncumbentStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        attempt_id: &'a pse_model::generated::identities::AttemptId,
    ) -> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        1,
    > {
        PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery {
            client,
            params: [attempt_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
