// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse
// @generated by cargo xtask codegen (Cornucopia 1.0.1) from crates/pse-operations/queries; do not edit

#[derive(Debug)]
pub struct InsertStudyParams<T1: crate::JsonSql> {
    pub study_id: pse_model::generated::identities::StudyId,
    pub attempt_id: pse_model::generated::identities::AttemptId,
    pub publication_id: pse_model::generated::identities::PublicationId,
    pub finalization_job: pse_model::generated::identities::JobId,
    pub definition: T1,
    pub state: pse_model::generated::enums::StudyState,
}
#[derive(Clone, Copy, Debug)]
pub struct InsertPointParams {
    pub study_id: pse_model::generated::identities::StudyId,
    pub point_index: i32,
    pub binding_hash: pse_ids::ContentHash,
    pub predecessor: Option<i32>,
    pub job_id: pse_model::generated::identities::JobId,
    pub state: pse_model::generated::enums::StudyPointState,
}
#[derive(Debug)]
pub struct InsertPointMemberParams<
    T1: crate::StringSql,
    T2: crate::StringSql,
    T3: crate::StringSql,
    T4: crate::StringSql,
    T5: crate::StringSql,
> {
    pub study_id: pse_model::generated::identities::StudyId,
    pub point_index: i32,
    pub catalog_name: T1,
    pub schema_name: T2,
    pub table_name: T3,
    pub relation_id: pse_ids::SemanticId,
    pub relation_version: i64,
    pub contract_fingerprint: pse_ids::ContentHash,
    pub table_uri: T4,
    pub delta_version: i64,
    pub selection_kind: pse_model::generated::enums::MemberSelectionKind,
    pub revision_column: Option<T5>,
    pub revision_id: Option<pse_ids::SemanticId>,
}
#[derive(Debug)]
pub struct ListStudiesParams<
    T1: crate::ArraySql<Item = pse_model::generated::enums::StudyState>,
> {
    pub states: T1,
    pub limit: i64,
}
#[derive(Clone, Copy, Debug)]
pub struct SetStudyStateParams {
    pub state: pse_model::generated::enums::StudyState,
    pub study_id: pse_model::generated::identities::StudyId,
}
#[derive(Clone, Copy, Debug)]
pub struct PointParams {
    pub study_id: pse_model::generated::identities::StudyId,
    pub point_index: i32,
}
#[derive(Clone, Copy, Debug)]
pub struct SetPointStateParams {
    pub state: pse_model::generated::enums::StudyPointState,
    pub study_id: pse_model::generated::identities::StudyId,
    pub point_index: i32,
}
#[derive(Clone, Copy, Debug)]
pub struct DependentsParams {
    pub study_id: pse_model::generated::identities::StudyId,
    pub point_index: i32,
}
#[derive(Clone, Copy, Debug)]
pub struct OnePointStatusParams {
    pub study_id: pse_model::generated::identities::StudyId,
    pub point_index: i32,
}
#[derive(Debug, Clone, PartialEq)]
pub struct PointStatus {
    pub point_index: i32,
    pub binding_hash: Vec<u8>,
    pub predecessor: Option<i32>,
    pub state: pse_model::generated::enums::StudyPointState,
    pub job_id: pse_ids::SemanticId,
    pub job_state: pse_model::generated::enums::JobState,
    pub attempt_id: pse_ids::SemanticId,
    pub attempt_state: pse_model::generated::enums::AttemptState,
    pub last_error: Option<String>,
}
pub struct PointStatusBorrowed<'a> {
    pub point_index: i32,
    pub binding_hash: &'a [u8],
    pub predecessor: Option<i32>,
    pub state: pse_model::generated::enums::StudyPointState,
    pub job_id: pse_ids::SemanticId,
    pub job_state: pse_model::generated::enums::JobState,
    pub attempt_id: pse_ids::SemanticId,
    pub attempt_state: pse_model::generated::enums::AttemptState,
    pub last_error: Option<&'a str>,
}
impl<'a> From<PointStatusBorrowed<'a>> for PointStatus {
    fn from(
        PointStatusBorrowed {
            point_index,
            binding_hash,
            predecessor,
            state,
            job_id,
            job_state,
            attempt_id,
            attempt_state,
            last_error,
        }: PointStatusBorrowed<'a>,
    ) -> Self {
        Self {
            point_index,
            binding_hash: binding_hash.into(),
            predecessor,
            state,
            job_id,
            job_state,
            attempt_id,
            attempt_state,
            last_error: last_error.map(|v| v.into()),
        }
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct OnePointStatus {
    pub point_index: i32,
    pub binding_hash: Vec<u8>,
    pub predecessor: Option<i32>,
    pub state: pse_model::generated::enums::StudyPointState,
    pub job_id: pse_ids::SemanticId,
    pub job_state: pse_model::generated::enums::JobState,
    pub attempt_id: pse_ids::SemanticId,
    pub attempt_state: pse_model::generated::enums::AttemptState,
    pub last_error: Option<String>,
}
pub struct OnePointStatusBorrowed<'a> {
    pub point_index: i32,
    pub binding_hash: &'a [u8],
    pub predecessor: Option<i32>,
    pub state: pse_model::generated::enums::StudyPointState,
    pub job_id: pse_ids::SemanticId,
    pub job_state: pse_model::generated::enums::JobState,
    pub attempt_id: pse_ids::SemanticId,
    pub attempt_state: pse_model::generated::enums::AttemptState,
    pub last_error: Option<&'a str>,
}
impl<'a> From<OnePointStatusBorrowed<'a>> for OnePointStatus {
    fn from(
        OnePointStatusBorrowed {
            point_index,
            binding_hash,
            predecessor,
            state,
            job_id,
            job_state,
            attempt_id,
            attempt_state,
            last_error,
        }: OnePointStatusBorrowed<'a>,
    ) -> Self {
        Self {
            point_index,
            binding_hash: binding_hash.into(),
            predecessor,
            state,
            job_id,
            job_state,
            attempt_id,
            attempt_state,
            last_error: last_error.map(|v| v.into()),
        }
    }
}
use crate::client::async_::GenericClient;
use futures::{self, StreamExt, TryStreamExt};
pub struct PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct I64Query<'c, 'a, 's, C: GenericClient, T, const N: usize> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(&tokio_postgres::Row) -> Result<i64, tokio_postgres::Error>,
    mapper: fn(i64) -> T,
}
impl<'c, 'a, 's, C, T: 'c, const N: usize> I64Query<'c, 'a, 's, C, T, N>
where
    C: GenericClient,
{
    pub fn map<R>(self, mapper: fn(i64) -> R) -> I64Query<'c, 'a, 's, C, R, N> {
        I64Query {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PointStatusQuery<'c, 'a, 's, C: GenericClient, T, const N: usize> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<PointStatusBorrowed, tokio_postgres::Error>,
    mapper: fn(PointStatusBorrowed) -> T,
}
impl<'c, 'a, 's, C, T: 'c, const N: usize> PointStatusQuery<'c, 'a, 's, C, T, N>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(PointStatusBorrowed) -> R,
    ) -> PointStatusQuery<'c, 'a, 's, C, R, N> {
        PointStatusQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct OnePointStatusQuery<'c, 'a, 's, C: GenericClient, T, const N: usize> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<OnePointStatusBorrowed, tokio_postgres::Error>,
    mapper: fn(OnePointStatusBorrowed) -> T,
}
impl<'c, 'a, 's, C, T: 'c, const N: usize> OnePointStatusQuery<'c, 'a, 's, C, T, N>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(OnePointStatusBorrowed) -> R,
    ) -> OnePointStatusQuery<'c, 'a, 's, C, R, N> {
        OnePointStatusQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalstudypointmembersRuntimeOperationalStudyPointMembersRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_study_point_members::RuntimeOperationalStudyPointMembersRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_study_point_members::RuntimeOperationalStudyPointMembersRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalstudypointmembersRuntimeOperationalStudyPointMembersRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_study_point_members::RuntimeOperationalStudyPointMembersRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointmembersRuntimeOperationalStudyPointMembersRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalstudypointmembersRuntimeOperationalStudyPointMembersRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct InsertStudyStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn insert_study() -> InsertStudyStmt {
    InsertStudyStmt(
        "INSERT INTO pse_ops.studies (study_id, attempt_id, publication_id, finalization_job, definition, state) VALUES ($1, $2, $3, $4, $5, $6)",
        None,
    )
}
impl InsertStudyStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    async fn bind<'c, 'a, 's, C: GenericClient, T1: crate::JsonSql>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
        attempt_id: &'a pse_model::generated::identities::AttemptId,
        publication_id: &'a pse_model::generated::identities::PublicationId,
        finalization_job: &'a pse_model::generated::identities::JobId,
        definition: &'a T1,
        state: &'a pse_model::generated::enums::StudyState,
    ) -> Result<u64, tokio_postgres::Error> {
        client
            .execute(
                self.0,
                &[
                    study_id,
                    attempt_id,
                    publication_id,
                    finalization_job,
                    definition,
                    state,
                ],
            )
            .await
    }
}
impl<
    'a,
    C: GenericClient + Send + Sync,
    T1: crate::JsonSql,
> crate::client::async_::Params<
    'a,
    'a,
    'a,
    InsertStudyParams<T1>,
    std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    >,
    C,
> for InsertStudyStmt {
    fn params(
        &'a self,
        client: &'a C,
        params: &'a InsertStudyParams<T1>,
    ) -> std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    > {
        Box::pin(
            self
                .bind(
                    client,
                    &params.study_id,
                    &params.attempt_id,
                    &params.publication_id,
                    &params.finalization_job,
                    &params.definition,
                    &params.state,
                ),
        )
    }
}
pub struct InsertPointStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn insert_point() -> InsertPointStmt {
    InsertPointStmt(
        "INSERT INTO pse_ops.study_points (study_id, point_index, binding_hash, predecessor, job_id, state) VALUES ($1, $2, $3, $4, $5, $6)",
        None,
    )
}
impl InsertPointStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    async fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
        point_index: &'a i32,
        binding_hash: &'a pse_ids::ContentHash,
        predecessor: &'a Option<i32>,
        job_id: &'a pse_model::generated::identities::JobId,
        state: &'a pse_model::generated::enums::StudyPointState,
    ) -> Result<u64, tokio_postgres::Error> {
        client
            .execute(
                self.0,
                &[study_id, point_index, binding_hash, predecessor, job_id, state],
            )
            .await
    }
}
impl<
    'a,
    C: GenericClient + Send + Sync,
> crate::client::async_::Params<
    'a,
    'a,
    'a,
    InsertPointParams,
    std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    >,
    C,
> for InsertPointStmt {
    fn params(
        &'a self,
        client: &'a C,
        params: &'a InsertPointParams,
    ) -> std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    > {
        Box::pin(
            self
                .bind(
                    client,
                    &params.study_id,
                    &params.point_index,
                    &params.binding_hash,
                    &params.predecessor,
                    &params.job_id,
                    &params.state,
                ),
        )
    }
}
pub struct InsertPointMemberStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn insert_point_member() -> InsertPointMemberStmt {
    InsertPointMemberStmt(
        "INSERT INTO pse_ops.study_point_members (study_id, point_index, catalog_name, schema_name, table_name, relation_id, relation_version, contract_fingerprint, table_uri, delta_version, selection_kind, revision_column, revision_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)",
        None,
    )
}
impl InsertPointMemberStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    async fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::StringSql,
        T2: crate::StringSql,
        T3: crate::StringSql,
        T4: crate::StringSql,
        T5: crate::StringSql,
    >(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
        point_index: &'a i32,
        catalog_name: &'a T1,
        schema_name: &'a T2,
        table_name: &'a T3,
        relation_id: &'a pse_ids::SemanticId,
        relation_version: &'a i64,
        contract_fingerprint: &'a pse_ids::ContentHash,
        table_uri: &'a T4,
        delta_version: &'a i64,
        selection_kind: &'a pse_model::generated::enums::MemberSelectionKind,
        revision_column: &'a Option<T5>,
        revision_id: &'a Option<pse_ids::SemanticId>,
    ) -> Result<u64, tokio_postgres::Error> {
        client
            .execute(
                self.0,
                &[
                    study_id,
                    point_index,
                    catalog_name,
                    schema_name,
                    table_name,
                    relation_id,
                    relation_version,
                    contract_fingerprint,
                    table_uri,
                    delta_version,
                    selection_kind,
                    revision_column,
                    revision_id,
                ],
            )
            .await
    }
}
impl<
    'a,
    C: GenericClient + Send + Sync,
    T1: crate::StringSql,
    T2: crate::StringSql,
    T3: crate::StringSql,
    T4: crate::StringSql,
    T5: crate::StringSql,
> crate::client::async_::Params<
    'a,
    'a,
    'a,
    InsertPointMemberParams<T1, T2, T3, T4, T5>,
    std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    >,
    C,
> for InsertPointMemberStmt {
    fn params(
        &'a self,
        client: &'a C,
        params: &'a InsertPointMemberParams<T1, T2, T3, T4, T5>,
    ) -> std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    > {
        Box::pin(
            self
                .bind(
                    client,
                    &params.study_id,
                    &params.point_index,
                    &params.catalog_name,
                    &params.schema_name,
                    &params.table_name,
                    &params.relation_id,
                    &params.relation_version,
                    &params.contract_fingerprint,
                    &params.table_uri,
                    &params.delta_version,
                    &params.selection_kind,
                    &params.revision_column,
                    &params.revision_id,
                ),
        )
    }
}
pub struct StudyStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn study() -> StudyStmt {
    StudyStmt(
        "SELECT s FROM pse_ops.studies AS s WHERE s.study_id = $1::pse_ops.study_id",
        None,
    )
}
impl StudyStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        1,
    > {
        PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery {
            client,
            params: [study_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
pub struct LockStudyStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn lock_study() -> LockStudyStmt {
    LockStudyStmt(
        "SELECT s FROM pse_ops.studies AS s WHERE s.study_id = $1::pse_ops.study_id FOR UPDATE",
        None,
    )
}
impl LockStudyStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        1,
    > {
        PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery {
            client,
            params: [study_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
pub struct StudyOfAttemptStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn study_of_attempt() -> StudyOfAttemptStmt {
    StudyOfAttemptStmt(
        "SELECT s FROM pse_ops.studies AS s WHERE s.attempt_id = $1::pse_ops.attempt_id",
        None,
    )
}
impl StudyOfAttemptStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        attempt_id: &'a pse_model::generated::identities::AttemptId,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        1,
    > {
        PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery {
            client,
            params: [attempt_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
pub struct ListStudiesStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn list_studies() -> ListStudiesStmt {
    ListStudiesStmt(
        "SELECT s FROM pse_ops.studies AS s WHERE cardinality($1::pse_ops.study_state[]) = 0 OR s.state = ANY($1) ORDER BY s.created_at DESC, s.study_id DESC LIMIT $2",
        None,
    )
}
impl ListStudiesStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::enums::StudyState>,
    >(
        &'s self,
        client: &'c C,
        states: &'a T1,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        2,
    > {
        PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery {
            client,
            params: [states, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::enums::StudyState>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ListStudiesParams<T1>,
    PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        2,
    >,
    C,
> for ListStudiesStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ListStudiesParams<T1>,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        2,
    > {
        self.bind(client, &params.states, &params.limit)
    }
}
pub struct SetStudyStateStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn set_study_state() -> SetStudyStateStmt {
    SetStudyStateStmt(
        "UPDATE pse_ops.studies SET state = $1, updated_at = now() WHERE study_id = $2::pse_ops.study_id",
        None,
    )
}
impl SetStudyStateStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    async fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        state: &'a pse_model::generated::enums::StudyState,
        study_id: &'a pse_model::generated::identities::StudyId,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(self.0, &[state, study_id]).await
    }
}
impl<
    'a,
    C: GenericClient + Send + Sync,
> crate::client::async_::Params<
    'a,
    'a,
    'a,
    SetStudyStateParams,
    std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    >,
    C,
> for SetStudyStateStmt {
    fn params(
        &'a self,
        client: &'a C,
        params: &'a SetStudyStateParams,
    ) -> std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    > {
        Box::pin(self.bind(client, &params.state, &params.study_id))
    }
}
pub struct PointOfJobStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn point_of_job() -> PointOfJobStmt {
    PointOfJobStmt(
        "SELECT p FROM pse_ops.study_points AS p WHERE p.job_id = $1::pse_ops.job_id",
        None,
    )
}
impl PointOfJobStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        job_id: &'a pse_model::generated::identities::JobId,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        1,
    > {
        PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery {
            client,
            params: [job_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
pub struct PointStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn point() -> PointStmt {
    PointStmt(
        "SELECT p FROM pse_ops.study_points AS p WHERE p.study_id = $1::pse_ops.study_id AND p.point_index = $2",
        None,
    )
}
impl PointStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
        point_index: &'a i32,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        2,
    > {
        PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery {
            client,
            params: [study_id, point_index],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    PointParams,
    PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        2,
    >,
    C,
> for PointStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a PointParams,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        2,
    > {
        self.bind(client, &params.study_id, &params.point_index)
    }
}
pub struct SetPointStateStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn set_point_state() -> SetPointStateStmt {
    SetPointStateStmt(
        "UPDATE pse_ops.study_points SET state = $1, updated_at = now() WHERE study_id = $2::pse_ops.study_id AND point_index = $3",
        None,
    )
}
impl SetPointStateStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    async fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        state: &'a pse_model::generated::enums::StudyPointState,
        study_id: &'a pse_model::generated::identities::StudyId,
        point_index: &'a i32,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(self.0, &[state, study_id, point_index]).await
    }
}
impl<
    'a,
    C: GenericClient + Send + Sync,
> crate::client::async_::Params<
    'a,
    'a,
    'a,
    SetPointStateParams,
    std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    >,
    C,
> for SetPointStateStmt {
    fn params(
        &'a self,
        client: &'a C,
        params: &'a SetPointStateParams,
    ) -> std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    > {
        Box::pin(self.bind(client, &params.state, &params.study_id, &params.point_index))
    }
}
pub struct DependentsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn dependents() -> DependentsStmt {
    DependentsStmt(
        "SELECT p FROM pse_ops.study_points AS p WHERE p.study_id = $1::pse_ops.study_id AND p.predecessor = $2 AND p.state = 'pending' ORDER BY p.point_index",
        None,
    )
}
impl DependentsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
        point_index: &'a i32,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        2,
    > {
        PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery {
            client,
            params: [study_id, point_index],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    DependentsParams,
    PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        2,
    >,
    C,
> for DependentsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a DependentsParams,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        2,
    > {
        self.bind(client, &params.study_id, &params.point_index)
    }
}
pub struct UnfinishedPointsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn unfinished_points() -> UnfinishedPointsStmt {
    UnfinishedPointsStmt(
        "SELECT count(*) AS unfinished FROM pse_ops.study_points WHERE study_id = $1::pse_ops.study_id AND state IN ('pending', 'assigned')",
        None,
    )
}
impl UnfinishedPointsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
    ) -> I64Query<'c, 'a, 's, C, i64, 1> {
        I64Query {
            client,
            params: [study_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it,
        }
    }
}
pub struct CompletedPointsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn completed_points() -> CompletedPointsStmt {
    CompletedPointsStmt(
        "SELECT count(*) AS completed FROM pse_ops.study_points WHERE study_id = $1::pse_ops.study_id AND state = 'completed'",
        None,
    )
}
impl CompletedPointsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
    ) -> I64Query<'c, 'a, 's, C, i64, 1> {
        I64Query {
            client,
            params: [study_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it,
        }
    }
}
pub struct LockPointJobsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn lock_point_jobs() -> LockPointJobsStmt {
    LockPointJobsStmt(
        "SELECT j FROM pse_ops.jobs AS j WHERE j.job_id IN ( SELECT p.job_id FROM pse_ops.study_points AS p WHERE p.study_id = $1::pse_ops.study_id) ORDER BY j.job_id FOR UPDATE",
        None,
    )
}
impl LockPointJobsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
    ) -> PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
        1,
    > {
        PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery {
            client,
            params: [study_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
pub struct PointStatusStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn point_status() -> PointStatusStmt {
    PointStatusStmt(
        "SELECT p.point_index, p.binding_hash, p.predecessor, p.state, p.job_id, j.state AS job_state, j.attempt_id, a.state AS attempt_state, j.last_error FROM pse_ops.study_points AS p JOIN pse_ops.jobs AS j ON j.job_id = p.job_id JOIN pse_ops.attempts AS a ON a.attempt_id = j.attempt_id WHERE p.study_id = $1::pse_ops.study_id ORDER BY p.point_index",
        None,
    )
}
impl PointStatusStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
    ) -> PointStatusQuery<'c, 'a, 's, C, PointStatus, 1> {
        PointStatusQuery {
            client,
            params: [study_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |
                row: &tokio_postgres::Row,
            | -> Result<PointStatusBorrowed, tokio_postgres::Error> {
                Ok(PointStatusBorrowed {
                    point_index: row.try_get(0)?,
                    binding_hash: row.try_get(1)?,
                    predecessor: row.try_get(2)?,
                    state: row.try_get(3)?,
                    job_id: row.try_get(4)?,
                    job_state: row.try_get(5)?,
                    attempt_id: row.try_get(6)?,
                    attempt_state: row.try_get(7)?,
                    last_error: row.try_get(8)?,
                })
            },
            mapper: |it| PointStatus::from(it),
        }
    }
}
pub struct OnePointStatusStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn one_point_status() -> OnePointStatusStmt {
    OnePointStatusStmt(
        "SELECT p.point_index, p.binding_hash, p.predecessor, p.state, p.job_id, j.state AS job_state, j.attempt_id, a.state AS attempt_state, j.last_error FROM pse_ops.study_points AS p JOIN pse_ops.jobs AS j ON j.job_id = p.job_id JOIN pse_ops.attempts AS a ON a.attempt_id = j.attempt_id WHERE p.study_id = $1::pse_ops.study_id AND p.point_index = $2",
        None,
    )
}
impl OnePointStatusStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
        point_index: &'a i32,
    ) -> OnePointStatusQuery<'c, 'a, 's, C, OnePointStatus, 2> {
        OnePointStatusQuery {
            client,
            params: [study_id, point_index],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |
                row: &tokio_postgres::Row,
            | -> Result<OnePointStatusBorrowed, tokio_postgres::Error> {
                Ok(OnePointStatusBorrowed {
                    point_index: row.try_get(0)?,
                    binding_hash: row.try_get(1)?,
                    predecessor: row.try_get(2)?,
                    state: row.try_get(3)?,
                    job_id: row.try_get(4)?,
                    job_state: row.try_get(5)?,
                    attempt_id: row.try_get(6)?,
                    attempt_state: row.try_get(7)?,
                    last_error: row.try_get(8)?,
                })
            },
            mapper: |it| OnePointStatus::from(it),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    OnePointStatusParams,
    OnePointStatusQuery<'c, 'a, 's, C, OnePointStatus, 2>,
    C,
> for OnePointStatusStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a OnePointStatusParams,
    ) -> OnePointStatusQuery<'c, 'a, 's, C, OnePointStatus, 2> {
        self.bind(client, &params.study_id, &params.point_index)
    }
}
pub struct CompletedMembersStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn completed_members() -> CompletedMembersStmt {
    CompletedMembersStmt(
        "SELECT m FROM pse_ops.study_point_members AS m JOIN pse_ops.study_points AS p ON p.study_id = m.study_id AND p.point_index = m.point_index WHERE m.study_id = $1::pse_ops.study_id AND p.state = 'completed' ORDER BY m.point_index, m.catalog_name, m.schema_name, m.table_name",
        None,
    )
}
impl CompletedMembersStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub fn bind<'c, 'a, 's, C: GenericClient>(
        &'s self,
        client: &'c C,
        study_id: &'a pse_model::generated::identities::StudyId,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointmembersRuntimeOperationalStudyPointMembersRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_point_members::RuntimeOperationalStudyPointMembersRow,
        1,
    > {
        PsemodelGeneratedRuntimeOperationalstudypointmembersRuntimeOperationalStudyPointMembersRowQuery {
            client,
            params: [study_id],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
