// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse
// @generated by cargo xtask codegen (Cornucopia 1.0.1) from crates/pse-operations/queries; do not edit

#[derive(Debug)]
pub struct ScanAttemptsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::RunId>,
    T3: crate::ArraySql<Item = pse_model::generated::enums::AttemptState>,
> {
    pub after: Option<pse_model::generated::identities::AttemptId>,
    pub attempts: T1,
    pub runs: T2,
    pub states: T3,
    pub created_from: Option<chrono::DateTime<chrono::Utc>>,
    pub created_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanAttemptTransitionsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> {
    pub after_attempt: Option<pse_model::generated::identities::AttemptId>,
    pub after_seq: Option<i32>,
    pub attempts: T1,
    pub at_from: Option<chrono::DateTime<chrono::Utc>>,
    pub at_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanJobsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::JobId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    T3: crate::ArraySql<Item = pse_model::generated::enums::JobState>,
> {
    pub after: Option<pse_model::generated::identities::JobId>,
    pub jobs: T1,
    pub attempts: T2,
    pub states: T3,
    pub enqueued_from: Option<chrono::DateTime<chrono::Utc>>,
    pub enqueued_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanProgressEventsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> {
    pub after_attempt: Option<pse_model::generated::identities::AttemptId>,
    pub after_seq: Option<i64>,
    pub attempts: T1,
    pub at_from: Option<chrono::DateTime<chrono::Utc>>,
    pub at_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanProgressValuesParams<
    T1: crate::StringSql,
    T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> {
    pub after_attempt: Option<pse_model::generated::identities::AttemptId>,
    pub after_seq: Option<i64>,
    pub after_name: Option<T1>,
    pub attempts: T2,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanIncumbentsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> {
    pub after_attempt: Option<pse_model::generated::identities::AttemptId>,
    pub after_seq: Option<i64>,
    pub attempts: T1,
    pub at_from: Option<chrono::DateTime<chrono::Utc>>,
    pub at_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanSolutionsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::SolutionId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> {
    pub after: Option<pse_model::generated::identities::SolutionId>,
    pub solutions: T1,
    pub creators: T2,
    pub created_from: Option<chrono::DateTime<chrono::Utc>>,
    pub created_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanStudiesParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::StudyId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    T3: crate::ArraySql<Item = pse_model::generated::enums::StudyState>,
> {
    pub after: Option<pse_model::generated::identities::StudyId>,
    pub studies: T1,
    pub attempts: T2,
    pub states: T3,
    pub created_from: Option<chrono::DateTime<chrono::Utc>>,
    pub created_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanStudyPointsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::StudyId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::JobId>,
    T3: crate::ArraySql<Item = pse_model::generated::enums::StudyPointState>,
> {
    pub after_study: Option<pse_model::generated::identities::StudyId>,
    pub after_index: Option<i32>,
    pub studies: T1,
    pub jobs: T2,
    pub states: T3,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanWorkspacesParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::WorkspaceId>,
> {
    pub after: Option<pse_model::generated::identities::WorkspaceId>,
    pub workspaces: T1,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanPublicationsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::PublicationId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::WorkspaceId>,
    T3: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> {
    pub after: Option<pse_model::generated::identities::PublicationId>,
    pub publications: T1,
    pub workspaces: T2,
    pub attempts: T3,
    pub committed_from: Option<chrono::DateTime<chrono::Utc>>,
    pub committed_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanPublicationMembersParams<
    T1: crate::StringSql,
    T2: crate::StringSql,
    T3: crate::StringSql,
    T4: crate::ArraySql<Item = pse_model::generated::identities::PublicationId>,
> {
    pub after_publication: Option<pse_model::generated::identities::PublicationId>,
    pub after_role: Option<pse_model::generated::enums::PublicationMemberRole>,
    pub after_catalog: Option<T1>,
    pub after_schema: Option<T2>,
    pub after_table: Option<T3>,
    pub publications: T4,
    pub limit: i64,
}
#[derive(Debug)]
pub struct ScanSettlementsParams<
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> {
    pub after: Option<pse_model::generated::identities::SettlementId>,
    pub attempts: T1,
    pub settled_from: Option<chrono::DateTime<chrono::Utc>>,
    pub settled_to: Option<chrono::DateTime<chrono::Utc>>,
    pub limit: i64,
}
use crate::client::async_::GenericClient;
use futures::{self, StreamExt, TryStreamExt};
pub struct PsemodelGeneratedRuntimeOperationalattemptsRuntimeOperationalAttemptsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_attempts::RuntimeOperationalAttemptsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_attempts::RuntimeOperationalAttemptsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalattemptsRuntimeOperationalAttemptsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_attempts::RuntimeOperationalAttemptsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalattemptsRuntimeOperationalAttemptsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalattemptsRuntimeOperationalAttemptsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalattempttransitionsRuntimeOperationalAttemptTransitionsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_attempt_transitions::RuntimeOperationalAttemptTransitionsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_attempt_transitions::RuntimeOperationalAttemptTransitionsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalattempttransitionsRuntimeOperationalAttemptTransitionsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_attempt_transitions::RuntimeOperationalAttemptTransitionsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalattempttransitionsRuntimeOperationalAttemptTransitionsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalattempttransitionsRuntimeOperationalAttemptTransitionsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalsolutionsRuntimeOperationalSolutionsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_solutions::RuntimeOperationalSolutionsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_solutions::RuntimeOperationalSolutionsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalsolutionsRuntimeOperationalSolutionsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_solutions::RuntimeOperationalSolutionsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalsolutionsRuntimeOperationalSolutionsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalsolutionsRuntimeOperationalSolutionsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalworkspacesRuntimeOperationalWorkspacesRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_workspaces::RuntimeOperationalWorkspacesRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_workspaces::RuntimeOperationalWorkspacesRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalworkspacesRuntimeOperationalWorkspacesRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_workspaces::RuntimeOperationalWorkspacesRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalworkspacesRuntimeOperationalWorkspacesRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalworkspacesRuntimeOperationalWorkspacesRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalpublicationsRuntimeOperationalPublicationsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_publications::RuntimeOperationalPublicationsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_publications::RuntimeOperationalPublicationsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalpublicationsRuntimeOperationalPublicationsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_publications::RuntimeOperationalPublicationsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalpublicationsRuntimeOperationalPublicationsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalpublicationsRuntimeOperationalPublicationsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalpublicationmembersRuntimeOperationalPublicationMembersRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_publication_members::RuntimeOperationalPublicationMembersRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_publication_members::RuntimeOperationalPublicationMembersRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalpublicationmembersRuntimeOperationalPublicationMembersRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_publication_members::RuntimeOperationalPublicationMembersRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalpublicationmembersRuntimeOperationalPublicationMembersRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalpublicationmembersRuntimeOperationalPublicationMembersRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct PsemodelGeneratedRuntimeOperationalsettlementsRuntimeOperationalSettlementsRowQuery<
    'c,
    'a,
    's,
    C: GenericClient,
    T,
    const N: usize,
> {
    client: &'c C,
    params: [&'a (dyn postgres_types::ToSql + Sync); N],
    query: &'static str,
    cached: Option<&'s tokio_postgres::Statement>,
    extractor: fn(
        &tokio_postgres::Row,
    ) -> Result<
        pse_model::generated::runtime::operational_settlements::RuntimeOperationalSettlementsRow,
        tokio_postgres::Error,
    >,
    mapper: fn(
        pse_model::generated::runtime::operational_settlements::RuntimeOperationalSettlementsRow,
    ) -> T,
}
impl<
    'c,
    'a,
    's,
    C,
    T: 'c,
    const N: usize,
> PsemodelGeneratedRuntimeOperationalsettlementsRuntimeOperationalSettlementsRowQuery<
    'c,
    'a,
    's,
    C,
    T,
    N,
>
where
    C: GenericClient,
{
    pub fn map<R>(
        self,
        mapper: fn(
            pse_model::generated::runtime::operational_settlements::RuntimeOperationalSettlementsRow,
        ) -> R,
    ) -> PsemodelGeneratedRuntimeOperationalsettlementsRuntimeOperationalSettlementsRowQuery<
        'c,
        'a,
        's,
        C,
        R,
        N,
    > {
        PsemodelGeneratedRuntimeOperationalsettlementsRuntimeOperationalSettlementsRowQuery {
            client: self.client,
            params: self.params,
            query: self.query,
            cached: self.cached,
            extractor: self.extractor,
            mapper,
        }
    }
    pub async fn one(self) -> Result<T, tokio_postgres::Error> {
        let row = crate::client::async_::one(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok((self.mapper)((self.extractor)(&row)?))
    }
    pub async fn all(self) -> Result<Vec<T>, tokio_postgres::Error> {
        self.iter().await?.try_collect().await
    }
    pub async fn opt(self) -> Result<Option<T>, tokio_postgres::Error> {
        let opt_row = crate::client::async_::opt(
                self.client,
                self.query,
                &self.params,
                self.cached,
            )
            .await?;
        Ok(
            opt_row
                .map(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
                .transpose()?,
        )
    }
    pub async fn iter(
        self,
    ) -> Result<
        impl futures::Stream<Item = Result<T, tokio_postgres::Error>> + 'c,
        tokio_postgres::Error,
    > {
        let stream = crate::client::async_::raw(
                self.client,
                self.query,
                crate::slice_iter(&self.params),
                self.cached,
            )
            .await?;
        let mapped = stream
            .map(move |res| {
                res.and_then(|row| {
                    let extracted = (self.extractor)(&row)?;
                    Ok((self.mapper)(extracted))
                })
            })
            .into_stream();
        Ok(mapped)
    }
}
pub struct ScanAttemptsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_attempts() -> ScanAttemptsStmt {
    ScanAttemptsStmt(
        "SELECT a FROM pse_ops.attempts AS a WHERE ($1::pse_ops.attempt_id IS NULL OR a.attempt_id > $1) AND (cardinality($2::pse_ops.attempt_id[]) = 0 OR a.attempt_id = ANY($2)) AND (cardinality($3::pse_ops.run_id[]) = 0 OR a.run_id = ANY($3)) AND (cardinality($4::pse_ops.attempt_state[]) = 0 OR a.state = ANY($4)) AND ($5::timestamptz IS NULL OR a.created_at >= $5) AND ($6::timestamptz IS NULL OR a.created_at <= $6) ORDER BY a.attempt_id LIMIT $7",
        None,
    )
}
impl ScanAttemptsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
        T2: crate::ArraySql<Item = pse_model::generated::identities::RunId>,
        T3: crate::ArraySql<Item = pse_model::generated::enums::AttemptState>,
    >(
        &'s self,
        client: &'c C,
        after: &'a Option<pse_model::generated::identities::AttemptId>,
        attempts: &'a T1,
        runs: &'a T2,
        states: &'a T3,
        created_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        created_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalattemptsRuntimeOperationalAttemptsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_attempts::RuntimeOperationalAttemptsRow,
        7,
    > {
        PsemodelGeneratedRuntimeOperationalattemptsRuntimeOperationalAttemptsRowQuery {
            client,
            params: [after, attempts, runs, states, created_from, created_to, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::RunId>,
    T3: crate::ArraySql<Item = pse_model::generated::enums::AttemptState>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanAttemptsParams<T1, T2, T3>,
    PsemodelGeneratedRuntimeOperationalattemptsRuntimeOperationalAttemptsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_attempts::RuntimeOperationalAttemptsRow,
        7,
    >,
    C,
> for ScanAttemptsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanAttemptsParams<T1, T2, T3>,
    ) -> PsemodelGeneratedRuntimeOperationalattemptsRuntimeOperationalAttemptsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_attempts::RuntimeOperationalAttemptsRow,
        7,
    > {
        self.bind(
            client,
            &params.after,
            &params.attempts,
            &params.runs,
            &params.states,
            &params.created_from,
            &params.created_to,
            &params.limit,
        )
    }
}
pub struct ScanAttemptTransitionsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_attempt_transitions() -> ScanAttemptTransitionsStmt {
    ScanAttemptTransitionsStmt(
        "SELECT t FROM pse_ops.attempt_transitions AS t WHERE ($1::pse_ops.attempt_id IS NULL OR (t.attempt_id, t.seq) > ($1, $2::integer)) AND (cardinality($3::pse_ops.attempt_id[]) = 0 OR t.attempt_id = ANY($3)) AND ($4::timestamptz IS NULL OR t.at >= $4) AND ($5::timestamptz IS NULL OR t.at <= $5) ORDER BY t.attempt_id, t.seq LIMIT $6",
        None,
    )
}
impl ScanAttemptTransitionsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    >(
        &'s self,
        client: &'c C,
        after_attempt: &'a Option<pse_model::generated::identities::AttemptId>,
        after_seq: &'a Option<i32>,
        attempts: &'a T1,
        at_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        at_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalattempttransitionsRuntimeOperationalAttemptTransitionsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_attempt_transitions::RuntimeOperationalAttemptTransitionsRow,
        6,
    > {
        PsemodelGeneratedRuntimeOperationalattempttransitionsRuntimeOperationalAttemptTransitionsRowQuery {
            client,
            params: [after_attempt, after_seq, attempts, at_from, at_to, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanAttemptTransitionsParams<T1>,
    PsemodelGeneratedRuntimeOperationalattempttransitionsRuntimeOperationalAttemptTransitionsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_attempt_transitions::RuntimeOperationalAttemptTransitionsRow,
        6,
    >,
    C,
> for ScanAttemptTransitionsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanAttemptTransitionsParams<T1>,
    ) -> PsemodelGeneratedRuntimeOperationalattempttransitionsRuntimeOperationalAttemptTransitionsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_attempt_transitions::RuntimeOperationalAttemptTransitionsRow,
        6,
    > {
        self.bind(
            client,
            &params.after_attempt,
            &params.after_seq,
            &params.attempts,
            &params.at_from,
            &params.at_to,
            &params.limit,
        )
    }
}
pub struct ScanJobsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_jobs() -> ScanJobsStmt {
    ScanJobsStmt(
        "SELECT j FROM pse_ops.jobs AS j WHERE ($1::pse_ops.job_id IS NULL OR j.job_id > $1) AND (cardinality($2::pse_ops.job_id[]) = 0 OR j.job_id = ANY($2)) AND (cardinality($3::pse_ops.attempt_id[]) = 0 OR j.attempt_id = ANY($3)) AND (cardinality($4::pse_ops.job_state[]) = 0 OR j.state = ANY($4)) AND ($5::timestamptz IS NULL OR j.enqueued_at >= $5) AND ($6::timestamptz IS NULL OR j.enqueued_at <= $6) ORDER BY j.job_id LIMIT $7",
        None,
    )
}
impl ScanJobsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::JobId>,
        T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
        T3: crate::ArraySql<Item = pse_model::generated::enums::JobState>,
    >(
        &'s self,
        client: &'c C,
        after: &'a Option<pse_model::generated::identities::JobId>,
        jobs: &'a T1,
        attempts: &'a T2,
        states: &'a T3,
        enqueued_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        enqueued_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
        7,
    > {
        PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery {
            client,
            params: [after, jobs, attempts, states, enqueued_from, enqueued_to, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::JobId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    T3: crate::ArraySql<Item = pse_model::generated::enums::JobState>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanJobsParams<T1, T2, T3>,
    PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
        7,
    >,
    C,
> for ScanJobsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanJobsParams<T1, T2, T3>,
    ) -> PsemodelGeneratedRuntimeOperationaljobsRuntimeOperationalJobsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_jobs::RuntimeOperationalJobsRow,
        7,
    > {
        self.bind(
            client,
            &params.after,
            &params.jobs,
            &params.attempts,
            &params.states,
            &params.enqueued_from,
            &params.enqueued_to,
            &params.limit,
        )
    }
}
pub struct ScanProgressEventsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_progress_events() -> ScanProgressEventsStmt {
    ScanProgressEventsStmt(
        "SELECT e FROM pse_ops.progress_events AS e WHERE ($1::pse_ops.attempt_id IS NULL OR (e.attempt_id, e.seq) > ($1, $2::bigint)) AND (cardinality($3::pse_ops.attempt_id[]) = 0 OR e.attempt_id = ANY($3)) AND ($4::timestamptz IS NULL OR e.at >= $4) AND ($5::timestamptz IS NULL OR e.at <= $5) ORDER BY e.attempt_id, e.seq LIMIT $6",
        None,
    )
}
impl ScanProgressEventsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    >(
        &'s self,
        client: &'c C,
        after_attempt: &'a Option<pse_model::generated::identities::AttemptId>,
        after_seq: &'a Option<i64>,
        attempts: &'a T1,
        at_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        at_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        6,
    > {
        PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery {
            client,
            params: [after_attempt, after_seq, attempts, at_from, at_to, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanProgressEventsParams<T1>,
    PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        6,
    >,
    C,
> for ScanProgressEventsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanProgressEventsParams<T1>,
    ) -> PsemodelGeneratedRuntimeOperationalprogresseventsRuntimeOperationalProgressEventsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_events::RuntimeOperationalProgressEventsRow,
        6,
    > {
        self.bind(
            client,
            &params.after_attempt,
            &params.after_seq,
            &params.attempts,
            &params.at_from,
            &params.at_to,
            &params.limit,
        )
    }
}
pub struct ScanProgressValuesStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_progress_values() -> ScanProgressValuesStmt {
    ScanProgressValuesStmt(
        "SELECT v FROM pse_ops.progress_values AS v WHERE ($1::pse_ops.attempt_id IS NULL OR (v.attempt_id, v.seq, v.name) > ($1, $2::bigint, $3::text)) AND (cardinality($4::pse_ops.attempt_id[]) = 0 OR v.attempt_id = ANY($4)) ORDER BY v.attempt_id, v.seq, v.name LIMIT $5",
        None,
    )
}
impl ScanProgressValuesStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::StringSql,
        T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    >(
        &'s self,
        client: &'c C,
        after_attempt: &'a Option<pse_model::generated::identities::AttemptId>,
        after_seq: &'a Option<i64>,
        after_name: &'a Option<T1>,
        attempts: &'a T2,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        5,
    > {
        PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery {
            client,
            params: [after_attempt, after_seq, after_name, attempts, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::StringSql,
    T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanProgressValuesParams<T1, T2>,
    PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        5,
    >,
    C,
> for ScanProgressValuesStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanProgressValuesParams<T1, T2>,
    ) -> PsemodelGeneratedRuntimeOperationalprogressvaluesRuntimeOperationalProgressValuesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_progress_values::RuntimeOperationalProgressValuesRow,
        5,
    > {
        self.bind(
            client,
            &params.after_attempt,
            &params.after_seq,
            &params.after_name,
            &params.attempts,
            &params.limit,
        )
    }
}
pub struct ScanIncumbentsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_incumbents() -> ScanIncumbentsStmt {
    ScanIncumbentsStmt(
        "SELECT i FROM pse_ops.incumbents AS i WHERE ($1::pse_ops.attempt_id IS NULL OR (i.attempt_id, i.seq) > ($1, $2::bigint)) AND (cardinality($3::pse_ops.attempt_id[]) = 0 OR i.attempt_id = ANY($3)) AND ($4::timestamptz IS NULL OR i.at >= $4) AND ($5::timestamptz IS NULL OR i.at <= $5) ORDER BY i.attempt_id, i.seq LIMIT $6",
        None,
    )
}
impl ScanIncumbentsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    >(
        &'s self,
        client: &'c C,
        after_attempt: &'a Option<pse_model::generated::identities::AttemptId>,
        after_seq: &'a Option<i64>,
        attempts: &'a T1,
        at_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        at_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        6,
    > {
        PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery {
            client,
            params: [after_attempt, after_seq, attempts, at_from, at_to, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanIncumbentsParams<T1>,
    PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        6,
    >,
    C,
> for ScanIncumbentsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanIncumbentsParams<T1>,
    ) -> PsemodelGeneratedRuntimeOperationalincumbentsRuntimeOperationalIncumbentsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_incumbents::RuntimeOperationalIncumbentsRow,
        6,
    > {
        self.bind(
            client,
            &params.after_attempt,
            &params.after_seq,
            &params.attempts,
            &params.at_from,
            &params.at_to,
            &params.limit,
        )
    }
}
pub struct ScanSolutionsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_solutions() -> ScanSolutionsStmt {
    ScanSolutionsStmt(
        "SELECT s FROM pse_ops.solutions AS s WHERE ($1::pse_ops.solution_id IS NULL OR s.solution_id > $1) AND (cardinality($2::pse_ops.solution_id[]) = 0 OR s.solution_id = ANY($2)) AND (cardinality($3::pse_ops.attempt_id[]) = 0 OR s.created_by = ANY($3)) AND ($4::timestamptz IS NULL OR s.created_at >= $4) AND ($5::timestamptz IS NULL OR s.created_at <= $5) ORDER BY s.solution_id LIMIT $6",
        None,
    )
}
impl ScanSolutionsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::SolutionId>,
        T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    >(
        &'s self,
        client: &'c C,
        after: &'a Option<pse_model::generated::identities::SolutionId>,
        solutions: &'a T1,
        creators: &'a T2,
        created_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        created_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalsolutionsRuntimeOperationalSolutionsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_solutions::RuntimeOperationalSolutionsRow,
        6,
    > {
        PsemodelGeneratedRuntimeOperationalsolutionsRuntimeOperationalSolutionsRowQuery {
            client,
            params: [after, solutions, creators, created_from, created_to, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::SolutionId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanSolutionsParams<T1, T2>,
    PsemodelGeneratedRuntimeOperationalsolutionsRuntimeOperationalSolutionsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_solutions::RuntimeOperationalSolutionsRow,
        6,
    >,
    C,
> for ScanSolutionsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanSolutionsParams<T1, T2>,
    ) -> PsemodelGeneratedRuntimeOperationalsolutionsRuntimeOperationalSolutionsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_solutions::RuntimeOperationalSolutionsRow,
        6,
    > {
        self.bind(
            client,
            &params.after,
            &params.solutions,
            &params.creators,
            &params.created_from,
            &params.created_to,
            &params.limit,
        )
    }
}
pub struct ScanStudiesStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_studies() -> ScanStudiesStmt {
    ScanStudiesStmt(
        "SELECT s FROM pse_ops.studies AS s WHERE ($1::pse_ops.study_id IS NULL OR s.study_id > $1) AND (cardinality($2::pse_ops.study_id[]) = 0 OR s.study_id = ANY($2)) AND (cardinality($3::pse_ops.attempt_id[]) = 0 OR s.attempt_id = ANY($3)) AND (cardinality($4::pse_ops.study_state[]) = 0 OR s.state = ANY($4)) AND ($5::timestamptz IS NULL OR s.created_at >= $5) AND ($6::timestamptz IS NULL OR s.created_at <= $6) ORDER BY s.study_id LIMIT $7",
        None,
    )
}
impl ScanStudiesStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::StudyId>,
        T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
        T3: crate::ArraySql<Item = pse_model::generated::enums::StudyState>,
    >(
        &'s self,
        client: &'c C,
        after: &'a Option<pse_model::generated::identities::StudyId>,
        studies: &'a T1,
        attempts: &'a T2,
        states: &'a T3,
        created_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        created_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        7,
    > {
        PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery {
            client,
            params: [after, studies, attempts, states, created_from, created_to, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::StudyId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    T3: crate::ArraySql<Item = pse_model::generated::enums::StudyState>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanStudiesParams<T1, T2, T3>,
    PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        7,
    >,
    C,
> for ScanStudiesStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanStudiesParams<T1, T2, T3>,
    ) -> PsemodelGeneratedRuntimeOperationalstudiesRuntimeOperationalStudiesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_studies::RuntimeOperationalStudiesRow,
        7,
    > {
        self.bind(
            client,
            &params.after,
            &params.studies,
            &params.attempts,
            &params.states,
            &params.created_from,
            &params.created_to,
            &params.limit,
        )
    }
}
pub struct ScanStudyPointsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_study_points() -> ScanStudyPointsStmt {
    ScanStudyPointsStmt(
        "SELECT p FROM pse_ops.study_points AS p WHERE ($1::pse_ops.study_id IS NULL OR (p.study_id, p.point_index) > ($1, $2::integer)) AND (cardinality($3::pse_ops.study_id[]) = 0 OR p.study_id = ANY($3)) AND (cardinality($4::pse_ops.job_id[]) = 0 OR p.job_id = ANY($4)) AND (cardinality($5::pse_ops.study_point_state[]) = 0 OR p.state = ANY($5)) ORDER BY p.study_id, p.point_index LIMIT $6",
        None,
    )
}
impl ScanStudyPointsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::StudyId>,
        T2: crate::ArraySql<Item = pse_model::generated::identities::JobId>,
        T3: crate::ArraySql<Item = pse_model::generated::enums::StudyPointState>,
    >(
        &'s self,
        client: &'c C,
        after_study: &'a Option<pse_model::generated::identities::StudyId>,
        after_index: &'a Option<i32>,
        studies: &'a T1,
        jobs: &'a T2,
        states: &'a T3,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        6,
    > {
        PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery {
            client,
            params: [after_study, after_index, studies, jobs, states, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::StudyId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::JobId>,
    T3: crate::ArraySql<Item = pse_model::generated::enums::StudyPointState>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanStudyPointsParams<T1, T2, T3>,
    PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        6,
    >,
    C,
> for ScanStudyPointsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanStudyPointsParams<T1, T2, T3>,
    ) -> PsemodelGeneratedRuntimeOperationalstudypointsRuntimeOperationalStudyPointsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_study_points::RuntimeOperationalStudyPointsRow,
        6,
    > {
        self.bind(
            client,
            &params.after_study,
            &params.after_index,
            &params.studies,
            &params.jobs,
            &params.states,
            &params.limit,
        )
    }
}
pub struct ScanWorkspacesStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_workspaces() -> ScanWorkspacesStmt {
    ScanWorkspacesStmt(
        "SELECT w FROM pse_ops.workspaces AS w WHERE ($1::pse_ops.workspace_id IS NULL OR w.workspace_id > $1) AND (cardinality($2::pse_ops.workspace_id[]) = 0 OR w.workspace_id = ANY($2)) ORDER BY w.workspace_id LIMIT $3",
        None,
    )
}
impl ScanWorkspacesStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::WorkspaceId>,
    >(
        &'s self,
        client: &'c C,
        after: &'a Option<pse_model::generated::identities::WorkspaceId>,
        workspaces: &'a T1,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalworkspacesRuntimeOperationalWorkspacesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_workspaces::RuntimeOperationalWorkspacesRow,
        3,
    > {
        PsemodelGeneratedRuntimeOperationalworkspacesRuntimeOperationalWorkspacesRowQuery {
            client,
            params: [after, workspaces, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::WorkspaceId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanWorkspacesParams<T1>,
    PsemodelGeneratedRuntimeOperationalworkspacesRuntimeOperationalWorkspacesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_workspaces::RuntimeOperationalWorkspacesRow,
        3,
    >,
    C,
> for ScanWorkspacesStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanWorkspacesParams<T1>,
    ) -> PsemodelGeneratedRuntimeOperationalworkspacesRuntimeOperationalWorkspacesRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_workspaces::RuntimeOperationalWorkspacesRow,
        3,
    > {
        self.bind(client, &params.after, &params.workspaces, &params.limit)
    }
}
pub struct ScanPublicationsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_publications() -> ScanPublicationsStmt {
    ScanPublicationsStmt(
        "SELECT p FROM pse_ops.publications AS p WHERE ($1::pse_ops.publication_id IS NULL OR p.publication_id > $1) AND (cardinality($2::pse_ops.publication_id[]) = 0 OR p.publication_id = ANY($2)) AND (cardinality($3::pse_ops.workspace_id[]) = 0 OR p.workspace_id = ANY($3)) AND (cardinality($4::pse_ops.attempt_id[]) = 0 OR p.attempt_id = ANY($4)) AND ($5::timestamptz IS NULL OR p.committed_at >= $5) AND ($6::timestamptz IS NULL OR p.committed_at <= $6) ORDER BY p.publication_id LIMIT $7",
        None,
    )
}
impl ScanPublicationsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::PublicationId>,
        T2: crate::ArraySql<Item = pse_model::generated::identities::WorkspaceId>,
        T3: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    >(
        &'s self,
        client: &'c C,
        after: &'a Option<pse_model::generated::identities::PublicationId>,
        publications: &'a T1,
        workspaces: &'a T2,
        attempts: &'a T3,
        committed_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        committed_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalpublicationsRuntimeOperationalPublicationsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_publications::RuntimeOperationalPublicationsRow,
        7,
    > {
        PsemodelGeneratedRuntimeOperationalpublicationsRuntimeOperationalPublicationsRowQuery {
            client,
            params: [
                after,
                publications,
                workspaces,
                attempts,
                committed_from,
                committed_to,
                limit,
            ],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::PublicationId>,
    T2: crate::ArraySql<Item = pse_model::generated::identities::WorkspaceId>,
    T3: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanPublicationsParams<T1, T2, T3>,
    PsemodelGeneratedRuntimeOperationalpublicationsRuntimeOperationalPublicationsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_publications::RuntimeOperationalPublicationsRow,
        7,
    >,
    C,
> for ScanPublicationsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanPublicationsParams<T1, T2, T3>,
    ) -> PsemodelGeneratedRuntimeOperationalpublicationsRuntimeOperationalPublicationsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_publications::RuntimeOperationalPublicationsRow,
        7,
    > {
        self.bind(
            client,
            &params.after,
            &params.publications,
            &params.workspaces,
            &params.attempts,
            &params.committed_from,
            &params.committed_to,
            &params.limit,
        )
    }
}
pub struct ScanPublicationMembersStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_publication_members() -> ScanPublicationMembersStmt {
    ScanPublicationMembersStmt(
        "SELECT m FROM pse_ops.publication_members AS m WHERE ($1::pse_ops.publication_id IS NULL OR (m.publication_id, m.role, m.catalog_name, m.schema_name, m.table_name) > ($1, $2::pse_ops.publication_member_role, $3::text, $4::text, $5::text)) AND (cardinality($6::pse_ops.publication_id[]) = 0 OR m.publication_id = ANY($6)) ORDER BY m.publication_id, m.role, m.catalog_name, m.schema_name, m.table_name LIMIT $7",
        None,
    )
}
impl ScanPublicationMembersStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::StringSql,
        T2: crate::StringSql,
        T3: crate::StringSql,
        T4: crate::ArraySql<Item = pse_model::generated::identities::PublicationId>,
    >(
        &'s self,
        client: &'c C,
        after_publication: &'a Option<pse_model::generated::identities::PublicationId>,
        after_role: &'a Option<pse_model::generated::enums::PublicationMemberRole>,
        after_catalog: &'a Option<T1>,
        after_schema: &'a Option<T2>,
        after_table: &'a Option<T3>,
        publications: &'a T4,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalpublicationmembersRuntimeOperationalPublicationMembersRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_publication_members::RuntimeOperationalPublicationMembersRow,
        7,
    > {
        PsemodelGeneratedRuntimeOperationalpublicationmembersRuntimeOperationalPublicationMembersRowQuery {
            client,
            params: [
                after_publication,
                after_role,
                after_catalog,
                after_schema,
                after_table,
                publications,
                limit,
            ],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::StringSql,
    T2: crate::StringSql,
    T3: crate::StringSql,
    T4: crate::ArraySql<Item = pse_model::generated::identities::PublicationId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanPublicationMembersParams<T1, T2, T3, T4>,
    PsemodelGeneratedRuntimeOperationalpublicationmembersRuntimeOperationalPublicationMembersRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_publication_members::RuntimeOperationalPublicationMembersRow,
        7,
    >,
    C,
> for ScanPublicationMembersStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanPublicationMembersParams<T1, T2, T3, T4>,
    ) -> PsemodelGeneratedRuntimeOperationalpublicationmembersRuntimeOperationalPublicationMembersRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_publication_members::RuntimeOperationalPublicationMembersRow,
        7,
    > {
        self.bind(
            client,
            &params.after_publication,
            &params.after_role,
            &params.after_catalog,
            &params.after_schema,
            &params.after_table,
            &params.publications,
            &params.limit,
        )
    }
}
pub struct ScanSettlementsStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn scan_settlements() -> ScanSettlementsStmt {
    ScanSettlementsStmt(
        "SELECT s FROM pse_ops.settlements AS s WHERE ($1::pse_ops.settlement_id IS NULL OR s.settlement_id > $1) AND (cardinality($2::pse_ops.attempt_id[]) = 0 OR s.attempt_id = ANY($2)) AND ($3::timestamptz IS NULL OR s.settled_at >= $3) AND ($4::timestamptz IS NULL OR s.settled_at <= $4) ORDER BY s.settlement_id LIMIT $5",
        None,
    )
}
impl ScanSettlementsStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
    >(
        &'s self,
        client: &'c C,
        after: &'a Option<pse_model::generated::identities::SettlementId>,
        attempts: &'a T1,
        settled_from: &'a Option<chrono::DateTime<chrono::Utc>>,
        settled_to: &'a Option<chrono::DateTime<chrono::Utc>>,
        limit: &'a i64,
    ) -> PsemodelGeneratedRuntimeOperationalsettlementsRuntimeOperationalSettlementsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_settlements::RuntimeOperationalSettlementsRow,
        5,
    > {
        PsemodelGeneratedRuntimeOperationalsettlementsRuntimeOperationalSettlementsRowQuery {
            client,
            params: [after, attempts, settled_from, settled_to, limit],
            query: self.0,
            cached: self.1.as_ref(),
            extractor: |row| Ok(row.try_get(0)?),
            mapper: |it| it.into(),
        }
    }
}
impl<
    'c,
    'a,
    's,
    C: GenericClient,
    T1: crate::ArraySql<Item = pse_model::generated::identities::AttemptId>,
> crate::client::async_::Params<
    'c,
    'a,
    's,
    ScanSettlementsParams<T1>,
    PsemodelGeneratedRuntimeOperationalsettlementsRuntimeOperationalSettlementsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_settlements::RuntimeOperationalSettlementsRow,
        5,
    >,
    C,
> for ScanSettlementsStmt {
    fn params(
        &'s self,
        client: &'c C,
        params: &'a ScanSettlementsParams<T1>,
    ) -> PsemodelGeneratedRuntimeOperationalsettlementsRuntimeOperationalSettlementsRowQuery<
        'c,
        'a,
        's,
        C,
        pse_model::generated::runtime::operational_settlements::RuntimeOperationalSettlementsRow,
        5,
    > {
        self.bind(
            client,
            &params.after,
            &params.attempts,
            &params.settled_from,
            &params.settled_to,
            &params.limit,
        )
    }
}
