// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

// Match runtime-owned scientific preparation's nested async ownership proof.
#![recursion_limit = "256"]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::exit,
    clippy::disallowed_types,
    clippy::print_stdout,
    clippy::print_stderr,
    reason = "driver binary: xtask is the command surface, so it prints, exits with codes, \
              and is the one place allowed to use anyhow (blueprint §23.2, clippy.toml)"
)]

//! `cargo xtask` — everything that needs Rust APIs, structured data, or cross-platform
//! behaviour. The justfile is the one-line surface; this is the logic (plan §3).
//!
//! Schema generation writes deterministic output and checks regeneration equivalence.
//! `doc-lint` waits for extracted API facts.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, anyhow, bail, ensure};
use clap::{Parser, Subcommand, ValueEnum};
use regex::Regex;
use serde::Deserialize;

mod codegen;
mod dependency_ceilings;
#[cfg(feature = "thermodynamic-oracles")]
mod feos_reference;
mod producer_identity;
#[cfg(any(feature = "package-fixtures", test))]
mod python_tests;
#[path = "../../scripts/workspace.rs"]
mod workspace;

/// Committed evidence is checked by both public dependency-family entry points.
const EVIDENCE_LOCKS: &[&str] = &[
    "docs/capability-maps/evidence/rust/apisurface-Cargo.lock",
    "docs/capability-maps/evidence/rust/support-Cargo.lock",
];

/// Workspace driver for pse-arrow.
#[derive(Debug, Parser)]
#[command(
    name = "cargo xtask",
    about = "Workspace driver for pse-arrow (plan §3)",
    version
)]
struct Cli {
    #[command(subcommand)]
    command: Cmd,
}

#[derive(Debug, Subcommand)]
enum Cmd {
    /// Initialize a clean canonical database through its generated declaration route.
    #[cfg(feature = "canonical-tools")]
    CanonicalInit {
        state: PathBuf,
    },
    /// Derive a relevant producer identity from selected Cargo units and consumed inputs.
    ProducerIdentityFixture {
        #[arg(long)]
        output: PathBuf,
    },
    ProducerIdentity(Box<ProducerIdentityArgs>),
    /// Verify a reviewed provider association without Cargo discovery or building.
    VerifyNativeProvider {
        #[arg(long)]
        receipt: PathBuf,
        #[arg(long)]
        package_id: String,
        #[arg(long)]
        out_dir: PathBuf,
    },
    /// Independently verify actual deployed bytes and their current consumed inputs.
    VerifyDeploymentArtifact {
        #[arg(long)]
        receipt: PathBuf,
        #[arg(long)]
        artifact: PathBuf,
    },
    /// Observe complete dirty outer context without compiling it into consumers.
    ObserveDeployment {
        #[arg(long)]
        output: PathBuf,
    },
    /// Freeze independent FeOS PC-SAFT properties as typed oracle Parquet banks.
    #[cfg(feature = "thermodynamic-oracles")]
    FeosReference {
        output: PathBuf,
    },
    /// Run Python tests using their operation-owned canonical fixtures.
    #[cfg(feature = "package-fixtures")]
    PythonTests {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    /// Assert one resolved version per dependency family, equal to the declared pin.
    FamilyCheck {
        /// Additional `Cargo.lock` files whose shared packages must agree with ours.
        #[arg(long, value_name = "LOCK")]
        evidence: Vec<PathBuf>,
        /// Compare only packages that belong to a declared family. The evidence lockfiles
        /// were resolved on their own day; unrelated transitive crates drift by patch
        /// version without telling us anything about the pins.
        #[arg(long)]
        evidence_families_only: bool,
    },
    /// Regenerate declared sources or check byte-for-byte regeneration equivalence.
    Codegen {
        /// Regenerate in scratch space and reject differing or untracked output.
        #[arg(long)]
        check: bool,
        /// Restrict to one generator.
        #[arg(long, value_enum, value_name = "TARGET")]
        only: Option<Target>,
    },
    /// Generate the exact compiled native Python API stub (run py-sync first).
    PythonStubs {
        /// Compare generated bytes without changing the committed stub.
        #[arg(long)]
        check: bool,
        /// Exact compiled extension; defaults to the checkout's active .venv module.
        #[arg(long)]
        extension: Option<PathBuf>,
    },
    /// The full governance gate: governance tests, codegen diff, family check.
    Governance,
    /// Resolve backticked API paths in `docs/**` against the extracted facts.
    DocLint,
    /// Report what this host can do: toolchain, Ipopt, external function libraries.
    ProbeHost {
        /// Emit JSON instead of a human-readable report.
        #[arg(long)]
        json: bool,
    },
}

/// Inputs to one producer derivation; boxed in the command enum.
#[derive(Debug, clap::Args)]
struct ProducerIdentityArgs {
    #[arg(long)]
    package: String,
    #[arg(long, default_value = "dev")]
    profile: String,
    #[arg(long)]
    target: Option<String>,
    /// Capture the package's library target (the default).
    #[arg(long, conflicts_with_all = ["bin", "cdylib_manifest"])]
    lib: bool,
    /// Capture only this production binary and its consumed dependencies.
    #[arg(long, conflicts_with_all = ["lib", "cdylib_manifest"])]
    bin: Option<String>,
    /// Capture the declared cdylib through Cargo rustc, as Maturin does.
    #[arg(long, conflicts_with_all = ["lib", "bin"])]
    cdylib_manifest: Option<PathBuf>,
    #[arg(long, value_delimiter = ',')]
    features: Vec<String>,
    #[arg(long)]
    no_default_features: bool,
    #[arg(long)]
    dep_info: Vec<PathBuf>,
    #[arg(long = "input")]
    declared_inputs: Vec<PathBuf>,
    #[arg(long)]
    native_input: Vec<PathBuf>,
    #[arg(long = "environment")]
    environment: Vec<String>,
    #[arg(long)]
    declarations: Option<PathBuf>,
    /// Private actual build/unit/command evidence for source review, not a grant.
    #[arg(long)]
    build_evidence: Option<PathBuf>,
    /// Refresh only selected build-script/proc-macro packages with Cargo clean
    /// in the selected profile before guarded actual capture.
    #[arg(long)]
    refresh_executors: bool,
    #[arg(long)]
    output: PathBuf,
}

/// Committed generators and the contract bootstrap phase.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum Target {
    /// `pse-schema` output: typed relation views.
    Relations,
    /// Rust registry contracts only, before rebuilding the ordinary package loader.
    RustContracts,
    /// `pse-schema` output: the Python contract classes.
    Python,
    /// `pse-schema` output: the reference tables in the book.
    Docs,
    /// Registry-generated canonical native schema and codecs.
    Surreal,
    /// `bindgen` output for the Ipopt C API.
    Bindgen,
    /// The JSON Schemas of the Rust-owned boundary documents and of the authoring
    /// documents, and the Python msgspec document types (ADR-0116 Outcome 7). Derived from
    /// the owning crates' types, so it needs the complete (package-fixtures) build.
    Schemas,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let root = workspace_root()?;
    match cli.command {
        #[cfg(feature = "canonical-tools")]
        Cmd::CanonicalInit { state } => {
            let options = pse_operations::canonical::CanonicalOptions::from_state(&state)?;
            let executor = tokio::runtime::Builder::new_multi_thread()
                .worker_threads(2)
                .enable_all()
                .build()?;
            executor.block_on(async {
                let store = pse_operations::canonical::CanonicalStore::connect(&options).await?;
                store.create().await?;
                store.open().await
            })?;
            println!("canonical database initialized and interpretation verified");
            Ok(())
        }
        Cmd::ProducerIdentityFixture { output } => {
            producer_identity::qualified_fixture(&root, &output)?;
            Ok(())
        }
        Cmd::VerifyNativeProvider {
            receipt,
            package_id,
            out_dir,
        } => producer_identity::verify_native_provider(&receipt, &package_id, &out_dir),
        Cmd::VerifyDeploymentArtifact { receipt, artifact } => {
            producer_identity::verify_deployment_artifact(&receipt, &artifact)
        }
        Cmd::ObserveDeployment { output } => producer_identity::observe_deployment(&root, &output),
        Cmd::ProducerIdentity(args) => {
            let ProducerIdentityArgs {
                package,
                profile,
                target,
                lib: _,
                bin,
                cdylib_manifest,
                features,
                no_default_features,
                dep_info,
                declared_inputs,
                native_input,
                environment,
                declarations,
                build_evidence,
                refresh_executors,
                output,
            } = *args;
            let declared_environment = environment
                .into_iter()
                .map(|entry| {
                    let (key, value) = entry
                        .split_once('=')
                        .context("environment must be KEY=VALUE")?;
                    ensure!(!key.is_empty(), "environment key must be nonempty");
                    Ok((key.to_owned(), value.to_owned()))
                })
                .collect::<Result<BTreeMap<_, _>>>()?;
            let mut declarations: producer_identity::InputDeclarations = match declarations {
                Some(path) => serde_json::from_slice(&std::fs::read(path)?)?,
                None => producer_identity::InputDeclarations::default(),
            };
            if let Some(path) = build_evidence {
                declarations.actual_build_evidence = Some(path);
            }
            declarations.refresh_executors |= refresh_executors;
            let identity = producer_identity::run(&producer_identity::ProducerOptions {
                workspace_root: root,
                package,
                profile,
                target,
                production_target: match (bin, cdylib_manifest) {
                    (Some(name), _) => producer_identity::ProducerTarget::Binary(name),
                    (_, Some(manifest)) => producer_identity::ProducerTarget::Cdylib(manifest),
                    _ => producer_identity::ProducerTarget::Library,
                },
                features,
                no_default_features,
                dep_info,
                declared_inputs,
                native_inputs: native_input,
                declared_environment,
                declarations,
            })?;
            producer_identity::write_if_changed(&output, &identity)?;
            println!(
                "producer identity {}: persistent reuse eligible={}",
                identity.identity, identity.persistent_reuse_eligible
            );
            Ok(())
        }
        #[cfg(feature = "thermodynamic-oracles")]
        Cmd::FeosReference { output } => feos_reference::run(&root, &output),
        #[cfg(feature = "package-fixtures")]
        Cmd::PythonTests { args } => python_tests::run(&root, &args),
        Cmd::FamilyCheck {
            evidence,
            evidence_families_only,
        } => {
            family_check(&root, &default_evidence(), true)?;
            if evidence.is_empty() {
                Ok(())
            } else {
                family_check(&root, &evidence, evidence_families_only)
            }
        }
        Cmd::Codegen { check, only } => codegen(&root, check, only),
        Cmd::PythonStubs { check, extension } => {
            codegen::python_stubs::run(&root, extension.as_deref(), check)
        }
        Cmd::Governance => governance(&root),
        Cmd::DocLint => {
            println!("doc-lint: not implemented in phase 0 (see docs/adr/register.md)");
            std::process::exit(2);
        }
        Cmd::ProbeHost { json } => {
            probe_host(json);
            Ok(())
        }
    }
}

/// Resolve the runtime checkout, never the location baked into a cached executable.
fn workspace_root() -> Result<PathBuf> {
    let start = std::env::current_dir().context("reading invocation directory")?;
    workspace::find_workspace_root(&start).map_err(|error| anyhow!(error))
}

fn default_evidence() -> Vec<PathBuf> {
    EVIDENCE_LOCKS.iter().map(PathBuf::from).collect()
}

// ---------------------------------------------------------------------------
// family-check
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct RootManifest {
    workspace: WorkspaceSection,
}

#[derive(Debug, Deserialize)]
struct WorkspaceSection {
    metadata: MetadataSection,
}

#[derive(Debug, Deserialize)]
struct MetadataSection {
    pse: PseMetadata,
}

#[derive(Debug, Deserialize)]
struct PseMetadata {
    families: BTreeMap<String, Family>,
}

#[derive(Debug, Deserialize)]
struct Family {
    version: String,
    #[serde(default, rename = "match")]
    match_kind: Option<String>,
    crates: Vec<String>,
    #[serde(default)]
    exclude: BTreeSet<String>,
}

#[derive(Debug, Deserialize)]
struct Lockfile {
    #[serde(default)]
    package: Vec<LockPackage>,
}

#[derive(Debug, Deserialize)]
struct LockPackage {
    name: String,
    version: String,
}

/// One resolved version per family, equal to the declared pin.
///
/// `=` pins bind direct dependencies only, and `cargo tree -d` does not report a mixed
/// family because a family is not a duplicate: two arrow majors in the graph make
/// `downcast_ref` return `None` with no compile error (blueprint §3.1).
fn family_check(root: &Path, evidence: &[PathBuf], families_only: bool) -> Result<()> {
    let manifest_path = root.join("Cargo.toml");
    let text = std::fs::read_to_string(&manifest_path)
        .with_context(|| format!("reading {}", manifest_path.display()))?;
    let manifest: RootManifest =
        toml::from_str(&text).with_context(|| format!("parsing {}", manifest_path.display()))?;
    let families = manifest.workspace.metadata.pse.families;

    let metadata = cargo_metadata::MetadataCommand::new()
        .manifest_path(&manifest_path)
        .other_options(vec!["--locked".to_owned()])
        .exec()
        .context("cargo metadata --locked --format-version 1")?;

    let resolved: BTreeMap<String, BTreeSet<String>> =
        metadata
            .packages
            .iter()
            .fold(BTreeMap::new(), |mut acc, pkg| {
                acc.entry(pkg.name.to_string())
                    .or_default()
                    .insert(pkg.version.to_string());
                acc
            });

    let mut failures = dependency_ceilings::check(root, &metadata)?;
    let mut in_family: BTreeSet<String> = BTreeSet::new();

    println!("family            declared   match   resolved   packages");
    println!("----------------- ---------- ------- ---------- --------");
    for (name, family) in &families {
        if let Some(failure) = check_family(name, family, &resolved, &mut in_family)? {
            failures.push(failure);
        }
    }

    for lock in evidence {
        let path = if lock.is_absolute() {
            lock.clone()
        } else {
            root.join(lock)
        };
        if let Some(failure) = compare_evidence(&path, &resolved, &in_family, families_only)? {
            failures.push(failure);
        }
    }

    if failures.is_empty() {
        println!("\nfamily-check: OK");
        Ok(())
    } else {
        for failure in &failures {
            eprintln!("family-check: {failure}");
        }
        bail!("family-check failed with {} problem(s)", failures.len())
    }
}

/// One family: collect its members from the resolved graph, print the row, and return the
/// failure message if there is one.
fn check_family(
    name: &str,
    family: &Family,
    resolved: &BTreeMap<String, BTreeSet<String>>,
    in_family: &mut BTreeSet<String>,
) -> Result<Option<String>> {
    let matchers = family
        .crates
        .iter()
        .map(|glob| glob_to_regex(glob))
        .collect::<Result<Vec<_>>>()?;
    let mut versions: BTreeSet<String> = BTreeSet::new();
    let mut members: Vec<String> = Vec::new();
    for (pkg, pkg_versions) in resolved {
        if !family.exclude.contains(pkg) && matchers.iter().any(|re| re.is_match(pkg)) {
            in_family.insert(pkg.clone());
            members.push(pkg.clone());
            versions.extend(pkg_versions.iter().cloned());
        }
    }
    let kind = family.match_kind.as_deref().unwrap_or("exact");
    let shown: Vec<String> = versions.iter().cloned().collect();
    println!(
        "{:<17} {:<10} {:<7} {:<10} {}",
        name,
        family.version,
        kind,
        shown.join(", "),
        members.len()
    );
    if members.is_empty() {
        return Ok(Some(format!(
            "family `{name}`: no package in the resolved graph matches {:?}",
            family.crates
        )));
    }
    if versions.len() != 1 {
        return Ok(Some(format!(
            "family `{name}`: {} versions in the resolved graph ({}); members: {}",
            versions.len(),
            shown.join(", "),
            members.join(", ")
        )));
    }
    let resolved_version = shown.first().cloned().unwrap_or_default();
    if version_matches(&resolved_version, &family.version, kind)? {
        Ok(None)
    } else {
        Ok(Some(format!(
            "family `{name}`: resolved {resolved_version}, declared {} (match = {kind})",
            family.version
        )))
    }
}

/// One evidence lockfile: every package it shares with our resolved graph must be at the
/// same version. The capability-map lockfiles are what the API surfaces were extracted
/// from, so a divergence means the maps describe a different build than ours.
fn compare_evidence(
    path: &Path,
    resolved: &BTreeMap<String, BTreeSet<String>>,
    in_family: &BTreeSet<String>,
    families_only: bool,
) -> Result<Option<String>> {
    let text = std::fs::read_to_string(path)
        .with_context(|| format!("reading evidence lockfile {}", path.display()))?;
    let parsed: Lockfile = toml::from_str(&text)
        .with_context(|| format!("parsing evidence lockfile {}", path.display()))?;

    let mut compared = 0_usize;
    let mut diffs: Vec<String> = Vec::new();
    for pkg in &parsed.package {
        if families_only && !in_family.contains(&pkg.name) {
            continue;
        }
        let Some(ours) = resolved.get(&pkg.name) else {
            continue;
        };
        compared += 1;
        if !ours.contains(&pkg.version) {
            diffs.push(format!(
                "  {} evidence {} vs resolved {}",
                pkg.name,
                pkg.version,
                ours.iter().cloned().collect::<Vec<_>>().join(", ")
            ));
        }
    }

    println!(
        "\nevidence {}: {compared} shared package(s){}",
        path.display(),
        if families_only {
            " (families only)"
        } else {
            ""
        }
    );
    if diffs.is_empty() {
        println!("  all shared packages agree");
        return Ok(None);
    }
    diffs.sort();
    for line in &diffs {
        println!("{line}");
    }
    Ok(Some(format!(
        "evidence {}: {} shared package(s) differ",
        path.display(),
        diffs.len()
    )))
}

/// `arrow-*` style globs. Only `*` is special; everything else is literal.
fn glob_to_regex(pattern: &str) -> Result<Regex> {
    let mut source = String::from("^");
    for ch in pattern.chars() {
        if ch == '*' {
            source.push_str(".*");
        } else {
            source.push_str(&regex::escape(&ch.to_string()));
        }
    }
    source.push('$');
    Regex::new(&source).with_context(|| format!("glob `{pattern}`"))
}

/// `match = "minor"` compares `major.minor`; anything else is an exact string compare.
fn version_matches(resolved: &str, declared: &str, kind: &str) -> Result<bool> {
    match kind {
        "exact" => Ok(resolved == declared),
        "minor" => {
            let r = semver::Version::parse(resolved)
                .with_context(|| format!("resolved version `{resolved}`"))?;
            let parts: Vec<&str> = declared.split('.').collect();
            let [major, minor, ..] = parts.as_slice() else {
                bail!("declared version `{declared}` has no minor component");
            };
            Ok(r.major.to_string() == *major && r.minor.to_string() == *minor)
        }
        other => bail!("unknown family match kind `{other}` (use \"exact\" or \"minor\")"),
    }
}

// ---------------------------------------------------------------------------
// codegen
// ---------------------------------------------------------------------------

fn codegen(root: &Path, check: bool, only: Option<Target>) -> Result<()> {
    codegen::run(root, check, only)
}

// ---------------------------------------------------------------------------
// governance
// ---------------------------------------------------------------------------

/// The gate `governance / *` runs: the governance test crate, then the two checks that
/// need a resolved graph or git.
fn governance(root: &Path) -> Result<()> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    // `cargo -C <path>` is nightly-only; the working directory is the portable form.
    let status = Command::new(cargo)
        .args([
            "nextest",
            "run",
            "-p",
            "pse-tests-governance",
            "-p",
            "pse-relations",
            "--features",
            "pse-relations/force-validate",
            "--no-fail-fast",
            "--locked",
        ])
        .current_dir(root)
        .status()
        .context("running cargo nextest for pse-tests-governance")?;
    let generated = codegen(root, true, None);
    let families = family_check(root, &default_evidence(), true);
    ensure!(
        status.success() && generated.is_ok() && families.is_ok(),
        "governance tests: {status}; generation: {generated:?}; families: {families:?}"
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// probe-host
// ---------------------------------------------------------------------------

/// What this host can do. The runtime's own `probe_host()` (blueprint §20) supersedes
/// this once it exists; today it answers "why did the ipopt feature not link?".
fn probe_host(json: bool) {
    let rustc = rustc_version();
    let dep_ipopt = std::env::var("DEP_IPOPT_VERSION").ok();
    let ipopt_on_path = which("ipopt");

    if json {
        println!("{{");
        println!("  \"rustc_version\": {},", json_string(&rustc));
        println!(
            "  \"dep_ipopt_version\": {},",
            dep_ipopt
                .as_deref()
                .map_or_else(|| "null".to_owned(), json_string)
        );
        println!(
            "  \"ipopt_on_path\": {}",
            ipopt_on_path.as_ref().map_or_else(
                || "null".to_owned(),
                |p| json_string(&p.display().to_string())
            )
        );
        println!("}}");
    } else {
        println!("rustc               {rustc}");
        println!(
            "DEP_IPOPT_VERSION   {}",
            dep_ipopt
                .as_deref()
                .unwrap_or("(unset — the `ipopt` feature is off, or nothing built the -sys crate)")
        );
        match &ipopt_on_path {
            Some(path) => println!("ipopt on PATH       {}", path.display()),
            None => println!(
                "ipopt on PATH       no (the NL backend needs the binary; see docker/solvers)"
            ),
        }
    }
}

/// `rustc -vV`'s `release:` line, or `unknown`.
fn rustc_version() -> String {
    let rustc = std::env::var_os("RUSTC").unwrap_or_else(|| "rustc".into());
    Command::new(rustc).arg("-vV").output().map_or_else(
        |_| "unknown".to_owned(),
        |out| {
            String::from_utf8_lossy(&out.stdout)
                .lines()
                .find_map(|line| line.strip_prefix("release: "))
                .map_or("unknown", str::trim)
                .to_owned()
        },
    )
}

/// First `name` on `PATH` (no `which` binary dependency: this has to work on Windows).
fn which(name: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path).find_map(|dir| {
        let direct = dir.join(name);
        if direct.is_file() {
            return Some(direct);
        }
        let exe = dir.join(format!("{name}.exe"));
        exe.is_file().then_some(exe)
    })
}

/// Minimal JSON string escaping; the probe emits three scalars and never needs `serde_json`.
fn json_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                use std::fmt::Write as _;
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
