// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Generated frozen attrs rows and Arrow extension contracts.

mod extensions;
mod identifiers;
mod types;

use std::fmt::Write as _;

use crate::model::ExtensionUse;
use crate::{Registry, SchemaError};

use super::rust::types::pascal;
use super::{GeneratedTree, Language};

const ROOT: &str = "python/pse/contracts";
const HEADER: &str = "# SPDX-License-Identifier: MIT OR Apache-2.0\n# Copyright (c) 2026 Paul Heyse\n# @generated by pse-schema; do not edit\n";

fn error(reason: String) -> SchemaError {
    SchemaError::Codegen {
        language: "python",
        reason,
    }
}

fn emit(tree: &mut GeneratedTree, name: &str, source: &str) {
    tree.files.insert(
        format!("{ROOT}/{name}.py").into(),
        format!("{HEADER}{source}").into_bytes(),
    );
}

pub(super) fn generate(reg: &Registry) -> Result<GeneratedTree, SchemaError> {
    let mut tree = GeneratedTree::empty(Language::Python.roots());
    emit(&mut tree, "enums", &enumerations(reg));
    emit(&mut tree, "values", &values()?);
    emit(&mut tree, "extension_types", &extensions::render(reg)?);
    let mut namespaces = std::collections::BTreeMap::<&str, String>::new();
    for spec in reg.relations() {
        let namespace = spec.key.namespace.as_str();
        let stem = format!("{}{}", pascal(namespace), pascal(spec.key.name));
        let mut declarations = String::new();
        let fields = spec
            .columns
            .iter()
            .map(|column| {
                Ok((
                    column.name().to_owned(),
                    types::optional(
                        types::logical(
                            &column.value_type(),
                            &format!("{stem}Field{}", pascal(column.name())),
                            &mut declarations,
                        )?,
                        column.nullable(),
                    ),
                ))
            })
            .collect::<Result<Vec<_>, SchemaError>>()?;
        declarations.push_str(&types::structure(&format!("{stem}Row"), &fields));
        namespaces
            .entry(namespace)
            .or_default()
            .push_str(&declarations);
    }
    for (namespace, declarations) in namespaces {
        let mut source = format!(
            "\"\"\"Typed rows in the {namespace} namespace.\"\"\"\n\nimport builtins as b\n"
        );
        if declarations.contains(": datetime") {
            source.push_str("from datetime import datetime\n");
        }
        source.push_str("\nimport attrs\n\n");
        if declarations.contains("e.") {
            source.push_str("from pse.contracts import enums as e\n");
        }
        if declarations.contains("v.") {
            source.push_str("from pse.contracts import values as v\n");
        }
        source.push_str(&declarations);
        emit(&mut tree, namespace, &source);
    }
    emit(
        &mut tree,
        "__init__",
        &format!(
            "\"\"\"Contracts generated from the sole registry declaration.\"\"\"\n\nfrom pse.contracts.extension_types import EXTENSION_NAMES, register_all\n\n__all__ = [\"EXTENSION_NAMES\", \"REGISTRY_FINGERPRINT\", \"register_all\"]\n\nREGISTRY_FINGERPRINT = {:?}\n",
            reg.fingerprint().to_prefixed()
        ),
    );
    Ok(tree)
}

fn enumerations(reg: &Registry) -> String {
    let mut source = String::from(
        "\"\"\"Declared string enumerations; ordinal codes are presentation only.\"\"\"\n\nfrom enum import StrEnum\n",
    );
    let mut mappings = Vec::new();
    for spec in reg.enums() {
        let name = pascal(spec.name);
        let _ = writeln!(
            source,
            "\n\nclass {name}(StrEnum):\n    \"\"\"The declared {} enumeration.\"\"\"\n",
            spec.name
        );
        for member in &spec.members {
            let variant = member.name.to_ascii_uppercase().replace(['-', '.'], "_");
            let variant = if variant.starts_with(|character: char| character.is_ascii_digit()) {
                format!("MEMBER_{variant}")
            } else {
                variant
            };
            let annotation = if variant == "PASS" {
                "  # noqa: S105 -- declared enumeration spelling"
            } else {
                ""
            };
            let _ = writeln!(source, "    {variant} = {:?}{annotation}", member.name);
        }
        if let Some(module) = spec.idaes_source {
            let members = spec
                .members
                .iter()
                .filter_map(|member| {
                    member
                        .idaes_name
                        .map(|idaes| format!("{:?}: {idaes:?}", member.name))
                })
                .collect::<Vec<_>>()
                .join(", ");
            mappings.push(format!("    {name:?}: ({module:?}, {{{members}}}),\n"));
        }
    }
    source.push_str("\n\nIDAES_NAMES: dict[str, tuple[str, dict[str, str]]] = {\n");
    source.push_str(&mappings.concat());
    source.push_str("}\n");
    source
}

fn values() -> Result<String, SchemaError> {
    let mut source = include_str!("values.py.template").to_owned();
    let mut declarations = String::new();
    for use_ in [
        ExtensionUse::DimensionVector,
        ExtensionUse::QuantityValue,
        ExtensionUse::Bound,
        ExtensionUse::SourceSpan,
    ] {
        types::storage(
            &use_.spec().storage(),
            &pascal(&use_.name()),
            &mut declarations,
        )?;
    }
    // This module owns the scalar helpers and extension classes; its projections use
    // local names instead of importing itself through the public package.
    source.push_str(&declarations.replace("v.", ""));
    Ok(source)
}
