// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Readable Rust source generated through syn, quote and prettyplease (ADR-0031).

mod alternative;
mod columnar;
mod enums;
mod manifest;
mod mathir;
mod mathir_sink;
pub mod physical;
mod relation;
pub(crate) mod types;

use std::collections::BTreeMap;
use std::path::PathBuf;

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::model::ExtensionUse;
use crate::{Registry, SchemaError};

use super::{GeneratedTree, Language};

const ROOT: &str = "crates/pse-relations/src/generated";
const HEADER: &str = "// SPDX-License-Identifier: MIT OR Apache-2.0\n// Copyright (c) 2026 Paul Heyse\n// @generated by pse-schema; do not edit\n\n";

pub(super) fn error(reason: String) -> SchemaError {
    SchemaError::Codegen {
        language: "rust",
        reason,
    }
}

fn emit(
    tree: &mut GeneratedTree,
    path: impl Into<PathBuf>,
    tokens: TokenStream,
) -> Result<(), SchemaError> {
    let file = syn::parse2::<syn::File>(tokens).map_err(|error_| error(error_.to_string()))?;
    tree.files.insert(
        path.into(),
        format!("{HEADER}{}", prettyplease::unparse(&file)).into_bytes(),
    );
    Ok(())
}

pub(super) fn generate(reg: &Registry) -> Result<GeneratedTree, SchemaError> {
    let mut tree = GeneratedTree::empty(Language::Rust.roots());
    let mut namespaces: BTreeMap<&str, Vec<TokenStream>> = BTreeMap::new();
    for spec in reg.relations() {
        let namespace = spec.key.namespace.as_str();
        let name = types::ident(spec.key.name);
        namespaces
            .entry(namespace)
            .or_default()
            .push(quote!(#[doc = "Generated relation contract."] pub mod #name;));
        emit(
            &mut tree,
            format!("{ROOT}/{namespace}/{}.rs", spec.key.name),
            relation::render(reg, spec)?,
        )?;
    }
    let mut modules = Vec::new();
    for (namespace, relations) in namespaces {
        let name = types::ident(namespace);
        modules.push(quote!(#[doc = "Generated namespace contracts."] pub mod #name;));
        emit(
            &mut tree,
            format!("{ROOT}/{namespace}/mod.rs"),
            quote!(#(#relations)*),
        )?;
    }
    let fingerprint = reg.fingerprint();
    let bytes = fingerprint.as_bytes();
    emit(
        &mut tree,
        format!("{ROOT}/mod.rs"),
        quote! {
            //! Typed contracts generated from the admitted registry.
            #![allow(clippy::doc_markdown, reason = "registry documentation is projected verbatim across Rust, Python and JSON contracts")]
            #![allow(clippy::too_many_lines, reason = "complete flat relation row codecs follow declared column inventory")]
            #(#modules)*
            /// Declared string enumerations.
            pub mod enums;
            /// Composite extension storage values.
            pub mod extension_values;
            /// Registry identity; validity is established by admission.
            pub const REGISTRY_FINGERPRINT: pse_ids::ContentHash = pse_ids::ContentHash::from_bytes([#(#bytes),*]);
            /// Resolves an exact declaration from the current registry.
            /// # Errors
            /// The registry could not assemble.
            pub fn relation_by_id(id: pse_ids::SemanticId) -> Result<Option<&'static pse_schema::model::RelationSpec>, crate::RelationError> {
                Ok(pse_schema::registry()?.relation_by_id(id))
            }
        },
    )?;
    emit(&mut tree, format!("{ROOT}/enums.rs"), enums::render(reg))?;
    emit(
        &mut tree,
        format!("{ROOT}/extension_values.rs"),
        extension_values()?,
    )?;
    emit(
        &mut tree,
        "crates/pse-authoring/src/generated/documents.rs",
        documents(reg)?,
    )?;
    emit(
        &mut tree,
        "crates/pse-authoring/src/generated/mod.rs",
        quote! {
            //! Authoring documents projected from registry document declarations.
            #![allow(clippy::doc_markdown, reason = "registry documentation is projected verbatim")]
            #![allow(clippy::too_many_lines, reason = "complete generated document dispatch preserves one declaration inventory")]
            /// Strict serde document types.
            pub mod documents;
        },
    )?;
    manifest_files(&mut tree, reg)?;
    mathir_files(&mut tree, reg)?;
    Ok(tree)
}

fn mathir_files(tree: &mut GeneratedTree, reg: &Registry) -> Result<(), SchemaError> {
    // The graph bridge is a consumer of the declared graph family. Standalone
    // manifest/document registries do not request or acquire that consumer.
    if reg.relation("compiled.math_expr_nodes").is_none() {
        return Ok(());
    }
    emit(
        tree,
        "crates/pse-compiler/src/generated/mathir_source.rs",
        mathir::source(reg)?,
    )?;
    emit(
        tree,
        "crates/pse-compiler/src/generated/mathir_sink.rs",
        mathir_sink::render(reg)?,
    )?;
    emit(
        tree,
        "crates/pse-compiler/src/generated/mod.rs",
        quote! {
            //! Mechanical declared relation bridges into the existing domain algorithms.
            #![allow(clippy::too_many_lines, reason = "generated callback inventory follows the complete mathematical relation families")]
            pub(crate) mod mathir_source;
            pub(crate) mod mathir_sink;
        },
    )?;
    Ok(())
}

fn manifest_files(tree: &mut GeneratedTree, reg: &Registry) -> Result<(), SchemaError> {
    if let Some(spec) = reg.manifest() {
        emit(
            tree,
            "crates/pse-catalog/src/generated/manifest.rs",
            manifest::render(spec)?,
        )?;
        emit(
            tree,
            "crates/pse-catalog/src/generated/mod.rs",
            quote! {
                //! Physical envelope types projected from the manifest declaration.
                #![allow(clippy::doc_markdown, reason = "registry documentation is projected verbatim")]
                /// Strict manifest wire types; admission remains in the catalog.
                pub mod manifest;
            },
        )?;
    }
    Ok(())
}

fn extension_values() -> Result<TokenStream, SchemaError> {
    let mut declarations = Vec::new();
    for use_ in [
        ExtensionUse::DimensionVector,
        ExtensionUse::QuantityValue,
        ExtensionUse::Bound,
        ExtensionUse::SourceSpan,
    ] {
        let name = types::pascal(&use_.name());
        let storage_name = format!("Extension{name}");
        let ty = types::storage(&use_.spec().storage(), &storage_name, &mut declarations)?;
        {
            let name = format_ident!("{}", name);
            declarations.push(
                quote!(#[doc = "The declared composite extension storage."] pub type #name = #ty;),
            );
        }
    }
    Ok(quote!(#(#declarations)*))
}

fn documents(reg: &Registry) -> Result<TokenStream, SchemaError> {
    let mut declarations = Vec::new();
    let mut dispatch = Vec::new();
    for spec in reg.documents() {
        let name = format_ident!("{}Document", types::pascal(spec.name));
        let mut fields = Vec::new();
        let mut batches = Vec::new();
        for section in &spec.sections {
            let relation = reg
                .relation(section.relation)
                .ok_or_else(|| error(format!("unknown document relation {}", section.relation)))?;
            let key = types::ident(section.key);
            let namespace = types::ident(relation.key.namespace.as_str());
            let relation = types::ident(relation.key.name);
            let row = quote!(pse_relations::generated::#namespace::#relation::Row);
            let (ty, default, values, capacity) = if section.repeated {
                (
                    quote!(Vec<#row>),
                    quote!(#[serde(default)]),
                    quote!(self.#key),
                    quote!(self.#key.len()),
                )
            } else {
                (row, quote!(), quote!(std::iter::once(self.#key)), quote!(1))
            };
            let doc = section.doc;
            fields.push(quote!(#[doc = #doc] #default pub #key: #ty,));
            batches.push(quote! {
                let mut builder = pse_relations::generated::#namespace::#relation::Builder::with_registry(registry, #capacity)?;
                for row in #values {
                    builder.push(row)?;
                }
                batches.entry(pse_relations::generated::#namespace::#relation::RELATION_ID)
                    .or_default().push(builder.finish()?);
            });
        }
        let doc = spec.doc;
        declarations.push(quote! {
            #[doc = #doc]
            #[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
            #[serde(deny_unknown_fields)]
            pub struct #name { #(#fields)* }
            impl #name {
                /// Projects strict document fields directly into generated Arrow columns.
                /// This establishes local field construction, not keys or foreign keys.
                /// # Errors
                /// An incompatible declaration or invalid scalar/nested field value.
                pub fn into_batches(self, registry: &pse_schema::Registry) -> Result<
                    std::collections::BTreeMap<pse_ids::SemanticId, Vec<pse_relations::columnar::FieldCheckedBatch>>,
                    pse_relations::RelationError,
                > {
                    let mut batches: std::collections::BTreeMap<pse_ids::SemanticId, Vec<pse_relations::columnar::FieldCheckedBatch>> = std::collections::BTreeMap::new();
                    #(#batches)*
                    Ok(batches)
                }
            }
        });
        let document_name = spec.name;
        dispatch.push(quote! {
            #document_name => {
                let document = <#name as serde::Deserialize>::deserialize(deserializer)
                    .map_err(|error| crate::AuthoringError::Contract { at: None, reason: error.to_string() })?;
                Ok(document.into_batches(registry)?)
            }
        });
    }
    Ok(quote! {
        #(#declarations)*
        /// Deserializes one declared document directly into generated column builders.
        /// # Errors
        /// Unknown document kinds, strict serde shape errors and invalid field values.
        pub fn batches_from_document<'de, D: serde::Deserializer<'de>>(
            name: &str, deserializer: D, registry: &pse_schema::Registry,
        ) -> Result<std::collections::BTreeMap<pse_ids::SemanticId, Vec<pse_relations::columnar::FieldCheckedBatch>>, crate::AuthoringError> {
            match name {
                #(#dispatch)*
                _ => Err(crate::AuthoringError::Contract { at: None, reason: format!("unknown document kind {name}") }),
            }
        }
    })
}
