// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Paul Heyse

//! Authoring JSON Schema projected from the same document and relation declarations.

use std::fmt::Write as _;

use arrow_schema::DataType;

use crate::model::{DocumentSection, ExtensionUse, FieldContract, SourceColumn};
use crate::{Registry, SchemaError};

pub(super) fn quote(value: &str) -> String {
    let mut out = String::from("\"");
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            character if character < '\u{20}' => {
                let _ = write!(out, "\\u{:04x}", u32::from(character));
            }
            character => out.push(character),
        }
    }
    out.push('"');
    out
}

pub(super) fn generate(reg: &Registry) -> Result<String, SchemaError> {
    let mut definitions = Vec::new();
    for relation in reg.relations() {
        let mut properties = Vec::new();
        let mut required = Vec::new();
        for column in &relation.columns {
            let ty = logical(reg, &column.value_type())?;
            let ty = if column.nullable() {
                format!("{{\"anyOf\":[{ty},{{\"type\":\"null\"}}]}}")
            } else {
                ty
            };
            properties.push(format!("{}:{ty}", quote(column.name())));
            // Nullable serde fields admit an absent value; all others are required.
            if !column.nullable() {
                required.push(quote(column.name()));
            }
        }
        definitions.push(format!(
            "{}:{}",
            quote(&relation.qualified_name()),
            object(&properties, &required)
        ));
    }
    let mut documents = Vec::new();
    for document in reg.documents() {
        let mut properties = Vec::new();
        for section in &document.sections {
            let definition = format!("source:{}:{}", document.name, section.key);
            definitions.push(format!(
                "{}:{}",
                quote(&definition),
                source_row(reg, section)?
            ));
            let reference = format!("{{\"$ref\":{}}}", quote(&format!("#/$defs/{definition}")));
            let value = if section.repeated {
                format!("{{\"type\":\"array\",\"items\":{reference}}}")
            } else {
                reference
            };
            properties.push(format!("{}:{value}", quote(section.key)));
        }
        let required = document
            .sections
            .iter()
            .filter(|section| !section.repeated)
            .map(|section| quote(section.key))
            .collect::<Vec<_>>();
        documents.push(object(&properties, &required));
    }
    Ok(format!(
        "{{\n  \"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\n  \"$comment\":\"@generated by pse-schema; do not edit\",\n  \"title\":\"Authoring source documents before parser and identity hydration\",\n  \"anyOf\":[{}],\n  \"$defs\":{{{}}}\n}}\n",
        documents.join(","),
        definitions.join(",")
    ))
}

fn source_row(reg: &Registry, section: &DocumentSection) -> Result<String, SchemaError> {
    let relation = reg
        .relation(section.relation)
        .ok_or_else(|| error(format!("unknown source relation {}", section.relation)))?;
    let mut properties = Vec::new();
    let mut required = Vec::new();
    for column in &relation.columns {
        let context = section.source_column(column);
        if matches!(
            context,
            SourceColumn::ParserSpan | SourceColumn::PackageIntegrity
        ) {
            continue;
        }
        let ty=logical(reg,&column.value_type())?.replace("^[0-9a-f]{32}$","^([0-9a-f]{32}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$");
        let ty = if column.nullable() {
            format!("{{\"anyOf\":[{ty},{{\"type\":\"null\"}}]}}")
        } else {
            ty
        };
        properties.push(format!("{}:{ty}", quote(column.name())));
        if section.identity_column == Some(column.name()) {
            properties.push(format!("\"id\":{ty}"));
        } else if !column.nullable() && context != SourceColumn::PackageContext {
            required.push(quote(column.name()));
        }
    }
    let mut object = object(&properties, &required);
    if let Some(identity) = section.identity_column {
        object.pop();
        // Named-policy identities are derived in package context; an editor cannot infer
        // a different file's policy. The loader enforces the conditional requirement.
        let needs_id = section.name_column.is_none();
        let required_id = if needs_id {
            format!(
                ",\"anyOf\":[{{\"required\":[\"id\"]}},{{\"required\":[{}]}}]",
                quote(identity)
            )
        } else {
            String::new()
        };
        let _ = write!(
            object,
            ",\"not\":{{\"required\":[\"id\",{}]}}{required_id}}}",
            quote(identity)
        );
    }
    let mut value: serde_json::Value =
        serde_json::from_str(&object).map_err(|cause| error(cause.to_string()))?;
    for (path, syntax) in section.expression_fields {
        let mut field = &mut value;
        for segment in path.split('.') {
            let name = segment.trim_end_matches("[]");
            field = nonnull(field)
                .get_mut("properties")
                .and_then(|properties| properties.get_mut(name))
                .ok_or_else(|| {
                    error(format!(
                        "declared source DSL path {path} absent from schema"
                    ))
                })?;
            let depth = (segment.len() - name.len()) / 2;
            for _ in 0..depth {
                field = nonnull(field).get_mut("items").ok_or_else(|| {
                    error(format!("declared source DSL path {path} is not a list"))
                })?;
            }
        }
        nonnull(field)["x-pse-dsl-syntax"] = serde_json::Value::String(syntax.as_str().to_owned());
    }
    // Feature unification can enable serde_json/preserve_order in a workspace build.
    // Fix object ordering explicitly in either graph; arrays retain declaration order.
    value.sort_all_objects();
    serde_json::to_string(&value).map_err(|cause| error(cause.to_string()))
}

fn nonnull(value: &mut serde_json::Value) -> &mut serde_json::Value {
    let nullable = value
        .get("anyOf")
        .and_then(serde_json::Value::as_array)
        .is_some_and(|branches| {
            branches.len() == 2
                && branches[1].get("type").and_then(serde_json::Value::as_str) == Some("null")
        });
    if nullable {
        &mut value["anyOf"][0]
    } else {
        value
    }
}

fn object(properties: &[String], required: &[String]) -> String {
    format!(
        "{{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{{{}}},\"required\":[{}]}}",
        properties.join(","),
        required.join(",")
    )
}

fn logical(reg: &Registry, ty: &FieldContract) -> Result<String, SchemaError> {
    let value = logical_value(reg, ty)?;
    let Some(collection) = crate::model::CollectionContract::from_field(ty.field())? else {
        return Ok(value);
    };
    let mut value: serde_json::Value =
        serde_json::from_str(&value).map_err(|cause| error(cause.to_string()))?;
    value["minItems"] = collection.minimum.into();
    if let Some(maximum) = collection.maximum {
        value["maxItems"] = maximum.into();
    }
    value["uniqueItems"] = collection.unique.into();
    value["x-pse-order"] =
        serde_json::to_value(collection.order).map_err(|cause| error(cause.to_string()))?;
    value.sort_all_objects();
    serde_json::to_string(&value).map_err(|cause| error(cause.to_string()))
}

fn logical_value(reg: &Registry, ty: &FieldContract) -> Result<String, SchemaError> {
    if let Some(range) = crate::model::IntegerRange::from_field(ty.field())? {
        return Ok(integer(
            i128::from(range.minimum),
            i128::from(range.maximum),
        ));
    }
    Ok(match (ty.extension(), ty.data_type()) {
        (Some(ExtensionUse::Enum(name)), _) => {
            let spec = reg
                .enum_spec(name)
                .ok_or_else(|| error(format!("unknown enum {name}")))?;
            format!(
                "{{\"type\":\"string\",\"enum\":[{}]}}",
                spec.members
                    .iter()
                    .map(|member| quote(member.name))
                    .collect::<Vec<_>>()
                    .join(",")
            )
        }
        (Some(ExtensionUse::ContentHash), _) => {
            "{\"type\":\"string\",\"pattern\":\"^blake3:[0-9a-f]{64}$\"}".to_owned()
        }
        (None, DataType::List(child)) => list(&logical_field(reg, &child)?, None),
        (None, DataType::FixedSizeList(child, width)) => {
            list(&logical_field(reg, &child)?, Some(width))
        }
        (None, DataType::Struct(children)) => {
            let mut properties = Vec::new();
            let mut required = Vec::new();
            for field in &children {
                let name = field.name();
                let ty = logical(reg, &FieldContract::from_field((**field).clone()))?;
                let ty = if field.is_nullable() {
                    format!("{{\"anyOf\":[{ty},{{\"type\":\"null\"}}]}}")
                } else {
                    required.push(quote(name));
                    ty
                };
                properties.push(format!("{}:{ty}", quote(name)));
            }
            alternative_shape(ty, object(&properties, &required))?
        }
        (None, DataType::FixedSizeBinary(_) | DataType::Dictionary(..)) => {
            return Err(error(format!(
                "no native language codec for {}; domain meaning requires an explicit declaration",
                ty.data_type()
            )));
        }
        _ => storage(reg, &ty.data_type())?,
    })
}

fn alternative_shape(ty: &FieldContract, shape: String) -> Result<String, SchemaError> {
    Ok(
        if let Some(alternative) = crate::model::TaggedAlternative::from_field(ty.field())? {
            let variants = alternative.arms.iter().map(|(tag, selected)| {
                    let mut properties = serde_json::Map::new();
                    properties.insert(alternative.discriminator.clone(), serde_json::json!({"const":tag}));
                    for arm in alternative.payloads() {
                        properties.insert(arm.to_owned(), serde_json::json!({"type":if Some(arm) == selected.as_deref() {"object"} else {"null"}}));
                    }
                    let required = std::iter::once(alternative.discriminator.as_str()).chain(selected.as_deref()).collect::<Vec<_>>();
                    serde_json::json!({"properties":properties,"required":required})
                }).collect::<Vec<_>>();
            let mut variants = serde_json::Value::Array(variants);
            variants.sort_all_objects();
            format!("{{\"allOf\":[{shape},{{\"oneOf\":{variants}}}]}}")
        } else {
            shape
        },
    )
}

fn logical_field(reg: &Registry, field: &arrow_schema::Field) -> Result<String, SchemaError> {
    let value = logical(reg, &FieldContract::from_field(field.clone()))?;
    Ok(if field.is_nullable() {
        format!("{{\"anyOf\":[{value},{{\"type\":\"null\"}}]}}")
    } else {
        value
    })
}

fn list(child: &str, width: Option<i32>) -> String {
    let length = width.map_or_else(String::new, |width| {
        format!(",\"minItems\":{width},\"maxItems\":{width}")
    });
    format!("{{\"type\":\"array\",\"items\":{child}{length}}}")
}

fn storage(reg: &Registry, ty: &DataType) -> Result<String, SchemaError> {
    Ok(match ty {
        DataType::Boolean => "{\"type\":\"boolean\"}".to_owned(),
        DataType::Utf8 => "{\"type\":\"string\"}".to_owned(),
        DataType::Float64 => "{\"type\":\"number\"}".to_owned(),
        DataType::Int16 => integer(-32768, 32767),
        DataType::Int32 => integer(i128::from(i32::MIN), i128::from(i32::MAX)),
        DataType::Int64 | DataType::Timestamp(..) => {
            integer(i128::from(i64::MIN), i128::from(i64::MAX))
        }
        DataType::UInt8 => integer(0, i128::from(u8::MAX)),
        DataType::UInt16 => integer(0, i128::from(u16::MAX)),
        DataType::UInt32 => integer(0, i128::from(u32::MAX)),
        DataType::UInt64 => integer(0, i128::from(u64::MAX)),
        DataType::FixedSizeBinary(16) => {
            "{\"type\":\"string\",\"pattern\":\"^[0-9a-f]{32}$\"}".to_owned()
        }
        DataType::FixedSizeBinary(32) => {
            "{\"type\":\"string\",\"pattern\":\"^blake3:[0-9a-f]{64}$\"}".to_owned()
        }
        DataType::List(child) => list(&storage(reg, child.data_type())?, None),
        DataType::FixedSizeList(child, width) => {
            list(&storage(reg, child.data_type())?, Some(*width))
        }
        DataType::Struct(children) => {
            let mut properties = Vec::new();
            let mut required = Vec::new();
            for child in children {
                let ty = if let Some(range) = crate::model::IntegerRange::from_field(child)? {
                    integer(i128::from(range.minimum), i128::from(range.maximum))
                } else if let Some(name) = super::enum_name(child) {
                    logical(reg, &FieldContract::enumeration(name))?
                } else {
                    storage(reg, child.data_type())?
                };
                let ty = if child.is_nullable() {
                    format!("{{\"anyOf\":[{ty},{{\"type\":\"null\"}}]}}")
                } else {
                    required.push(quote(child.name()));
                    ty
                };
                properties.push(format!("{}:{ty}", quote(child.name())));
            }
            object(&properties, &required)
        }
        other => return Err(error(format!("unsupported JSON storage {other}"))),
    })
}

fn integer(lower: i128, upper: i128) -> String {
    format!("{{\"type\":\"integer\",\"minimum\":{lower},\"maximum\":{upper}}}")
}
fn error(reason: String) -> SchemaError {
    SchemaError::Codegen {
        language: "jsonschema",
        reason,
    }
}
